const centros3 = [
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "PARQUE HAINAMOSA" },
      { name: "CLUB DE ALISTADO FARD" },
      { name: "MULTIUSO LOS FRAILES" },
      { name: "MULTIUSO LOS FRAILES III" },
      { name: "INSTITUTO  ITSC" },
      { name: "CODECO (CENTRO DESARROLLO COMUNITARIO)" },
      { name: "CRUZ ROJA LA CALETA" },
      { name: "MULTIUSO EL TAMARINDO" },
      { name: "HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "HOSPITAL ELVIRA ECHAVARRIA" },
      { name: "POLIDEPORTIVO DE GUERRA" },
      { name: "CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "HOSPITAL LOCAL DE BOCA CHICA" },
      { name: "CLUB LA UNION" },
      { name: "GAZEBO DEL PARQUE MONTE ADENTRO" },
      { name: "PARROQUIA SANTO THOMAS DE VILLA NUEVA" },
      { name: "MULTIUSO INVIVIENDA" },
      { name: "HOSPITAL EL ALMIRANTE" },
      { name: "MULTIUSO LOS FRAILES" },
      { name: "MULTIUSO LOS FRAILES II" },
    ],
  },
    {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "CLUB DE LOS BILLETEROS" },
      { name: "DOMICILIARIAS" },
      { name: "DOMICILIARIAS DIFERENTES SECTORES" },
      { name: "PARQUE DEL ESTE" },
      { name: "PLAY DE LA ZAFRA" },
      { name: "MULTIUSO HAMARAP" },
      { name: "COSALUP" },
      { name: "CPNA VIETNAM" },
      { name: "AYUNTAMIENTO SDE" },
      { name: "IGLESIA EL CAMINO" },
      { name: "PLAN SOCIAL DE LA PRESIDENCIA" },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "ESCUELA CELINA PELLIER" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "CLUB DEL ROSAL" },
      { name: "HOGAR DE ANCIANOS Y DISCAPACITADOS" },
      { name: "CLINICA ALTAGRACIA" },
      { name: "AREA II" },
      { name: "ARMADA DOMINICANA" },
      { name: "CENTRO MEDICO ALMED" },
      { name: "CENTRO MEDICO DIAGNOSTICO (CMEDI)" },
      { name: "CENTRO MEDICO HISPANICO" },
      { name: "CENTRO MEDICO INTEGRAL III" },
      { name: "CENTRO POLICLINICO NACIONAL" },
      { name: "CLINICA DR. LEGER MATOS" },
      { name: "HOSP. DR. DARIO CONTRERAS" },
      { name: "HOSPITAL MATERNO INFANTIL SAN LORENZO DE LOS MINA" },
      { name: "POLICLINICA ZONA E" },
    ],
  },
    {
    name: "SANTO DOMINGO NORTE (DAS-III)",
    centers: [
      { name: "BIBLIOTECA MULTIUSO GUARICANO CENTRO" },
      { name: "CLUD LOS MOSQUITOS" },
      { name: "MULTIUSO SABANA PERDIDA" },
      { name: "MULTIUSO LA VICTORIA /IGLESIA PARQUE LA VICTORIA" },
      { name: "HOSPITAL NEY ARIAS LORA" },
      { name: "HOSPITAL DR . REYNALDO ALMANZAR" },
      { name: "CLUD MULTIUSO EL CROM" },
      { name: "MULTIUSO SANTA CRUZ IGLESIA CATOLICA" },
      { name: "HOGAR DE DIA SABANA PERDIDA" },
      { name: "DISTRITO 10-01" },
      { name: "DISTRITO 10-02" },
      { name: "CLUB CAMPAÑA" },
      { name: "PUESTO LOS CASTILLOS" },
      { name: "LOS BOMBEROS DE LA VICTORIA" },
      { name: "CECARCI" },
    ],
  },
    {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "CENTRO DIAGNÓSTICO BARNEY MORGAN" },
      { name: "CLINICA RODRIGUEZ SANTOS" },
      { name: "COMIPOL" },
      { name: "HOSPITAL DOCTOR FRANCISCO MOSCOSO PUELLO" },
      { name: "CECANOT" },
      { name: "CLINICA CRUZ JIMINIAN" },
      { name: "DIGESETT" },
    ],
  },
    {
    name: "DISTRITO NACIONAL (DAS-V)",
    centers: [
      { name: "COROMINA  PEPIN" },
      { name: "CENTRO LASER" },
      { name: "PLASTIC CENTER" },
      { name: "PATOLOGIA FORENSE /LAB. NACIONAL" },
      { name: "CLUB NACO" },
      { name: "LOS PRADOS" },
      { name: "CLUB INDEPENDENCIA" },
      { name: "HONDURAS" },
      { name: "MOVEARTE" },
      { name: "PCMM" },
      { name: "CLUB MANGANAGUA" },
      { name: "CLUB MIRADOR" },
      { name: "CUSEP" },
      { name: "JUAN LAMBERT" },
      { name: "UNICARIBE" },
      { name: "COLEGIO SAN JUAN BAUTISTA" },
      { name: "SAN CARLOS" },
      { name: "CONAPE" },
      { name: "UNIBE" },
      { name: "DNI" },
      { name: "CENTRO OLIMPICO" },
      { name: "CCN" },
      { name: "CLINICA INDEPENDENCIA" },
      { name: "DISP. TEJADA Y FLORENTINO" },
      { name: "DNCD" },
      { name: "HOSPITAL DE POLICIA NACIONAL" },
      { name: "HOSPITAL ROBERT REID CABRAL" },
      { name: "INAVI" },
      { name: "MIDE" },
      { name: "SIRENA" },
      { name: "COOPNAMA" }
    ],
  },
    {
    name: "DISTRITO NACIONAL( DAS-VI)",
    centers: [
      { name: "CARREFOUR" },
      { name: "UNAP CARMEN RENATA" },
      { name: "UNPHU" },
      { name: "HOSPITAL SANTO SOCORRO" },
      { name: "ASILO SOL Y LUNA" },
      { name: "CEDIMAT" },
      { name: "PLAZA DE LA SALUD" }
    ],
  },
    {
    name: "SANTO DOMINGO OESTE (DAS VII)",
    centers: [
      { name: "ASODIFIMO" },
      { name: "MISSION ENMANUEL" },
      { name: "COOPERATIVA DE HERRERA" },
      { name: "CPN COSALUP" },
      { name: "LA HORA DE DIOS" },
      { name: "MULTIUSO SOCORRO MUTUO" },
      { name: "ESCUELA KILOMETRO 13/ESCUELA NUEVA" },
      { name: "MULTIUSO EL ABANICO" },
      { name: "CENTRO COMUNAL LAS PALMAS" },
      { name: "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CPN DIAZ PIÑEYRO" },
      { name: "CLUB DEPORTIVO COLIBRI-PALAVE" },
      { name: "IGLESIA BAUTISTA PASTOR DE OVEJAS" },
      { name: "IGLESIA SAN PEDRO NOLASCO" },
      { name: "ZONA F" },
      { name: "HOSPITAL MARCELINO VELEZ SANTANA" },
      { name: "CPNA DE LA MANO CON JESUS" },
      { name: "PARROQUIA ESPIRITU SANTO" },
      { name: "PRISMA SALUD DOMINICANA" },
      { name: "CPNA LAS CAOBAS" },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "MULTIUSO IVAN GUZMAN KLANG" },
      { name: "ESC. ROSARIO EVANG SOLANO" },
      { name: "COOPERATIVA DE MANOGUAYABO" },
      { name: "DISTRITO ESCOLAR 15-05" },
      { name: "FUNDACION PEDRO MARTINEZ" },
      { name: "OPERACIONES ESPECIALES" },
      { name: "CUERPO ESPECIALIZADO DE SEGURIDAD PORTUARIA, CESEP." },
      { name: "HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "WIND TELECOM" },
      { name: "LAB. REFERENCIA SEDE CENTRAL AV LUPERON" },
      { name: "CPNA DIAZ PIÑEYRO" },
    ],
  },
    {
    name: "SANTO DOMINGO OESTE (DAS VIII)",
    centers: [
      { name: "HOSPITAL DR. RODOLDOLFO DE LA CRUZ LORA" },
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ" },
      { name: "ESTANCIA DE DIA 24 DE ABRIL" },
      { name: "CUERPO DE BOMBEROS LOS ALCARRIZOS" },
      { name: "CENTRO CRISTIANO DE SERVICIO MEDICOS, ELIA SANTANA" },
      { name: "CAMPAMENTO 16 DE AGOSTO, MIDE" },
      { name: "HOSP. GENERAL DR. VINICIO CALVENTI" },
      { name: "HOSP. MUNICIPAL ALCARRIZOS II" },
    ],
  },
    {
    name: "SAMANA",
    centers: [
      { name: "POLIDEPORTIVO" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "CENTRO TECNOLOGICO DEL LIMON" },
      { name: "ARMADA DOMINICANA" },
      { name: "CRUCE DE HONDURAS (EDIFICIO BLANCO)" },
      { name: "ESCUELA VOCACIONAL" },
      { name: "ESCUELA LOS GRATINIS" },
      { name: "JUNTA DE VECINOS LOMA DE LA PINA" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CENTRO COMUNAL EL COCO" },
      { name: "JUNTA DE VECINOS PUNTA BALANDRA" },
      { name: "AYUNTAMIENTO LAS GALERAS" },
      { name: "SINDICATO DE PORTUARIA" },
      { name: "JUNTA DE VECINOS LOS CACAOS" },
      { name: "LOCAL COOPERATIVA VIEJA" },
      { name: "NANY, VALLE" },
      { name: "CENTRO COMUNAL LOS ROBALOS" },
      { name: "CENTRO COMUNAL RANCHO ESPAÑOL" },
      { name: "CENTRO COMUNAL LOS CORRALES" },
      { name: "CRUZ ROJA DOMINICANA" },
      { name: "FABRICA DE HIELO LA PASCUALA" },
      { name: "CRUCE DE TEZON" },
      { name: "JUNTA DE VECINO DANIEL WILLMORE" },
      { name: "IGLESIA CATÓLICA" },
      { name: "CENTRO COMUNAL" },
      { name: "CLUB DE MADRES LOS PUENTES" },
      { name: "CPN LA LOMETA" },
      { name: "CENTRO COMUNAL, BATEY HORMIGA" },
      { name: "MAJAGUA ADENTRO" },
      { name: "IGLESIA CATÓLICA LAS GARITAS" },
      { name: "JUNTA DE VECINOS LOMA DE LA PIÑA" },
      { name: "CENTRO TECNOLOGICO DEL LIMON" },
      { name: "ESCUELA PRIMARIA LOS GRATINIS" },
    ],
  },
      {
    name: "PUERTO PLATA",
    centers: [
      { name: "CASA A CASA DPS" },
      { name: "CENTRO MÉDICO DR. BOURNIGAL" },
      { name: "CENTRO MEDICO UTESA" },
      { name: "CENTRO MEDICO CABARETE" },
      { name: "CLINICA BRUGAL MEJIA LÓPEZ" },
      { name: "CLINICA GREGORIO HERNÁNDEZ" }, 
      { name: "DIRECCION PROVINCIAL DE SALUD PUERTO PLATA" },
      { name: "HOSPITAL GREGORIO LUPÈRON" }, 
      { name: "HOSPITAL CANTISANO ARIAS" }, 
      { name: "HOSPITAL DE VILLA ISABELA" }, 
      { name: "HOSPITAL DOCENTE UNIVERSITARIO RICARDO LIMARDO" }, 
      { name: "HOSPITAL MUNICIPAL DE IMBERT" }, 
      { name: "HOSPITAL PABLO MORROBEL JIMÉNEZ" },
    ],
  },
      {
    name: "LA ROMANA",
    centers: [
      { name: "CENTRO D. CALETA" },
      { name: "DISPENSARIO L.J.SUAREZ." },
      { name: "DPS LA ROMANA" },
      { name: "HOGAR DEL NIÑO" },
      { name: "HOSPITAL A.F.C." },
      { name: "HOSPITAL BUEN SAMARITANO" },
      { name: "IGLESIA UNIVERSAL DE CRISTO" },
      { name: "POLICIA NACIONAL" },
      { name: "Hospital Francisco A. Gonzalvo" },
      { name: "Domiciliar DPS" },
      { name: "Policia Nacional" },
      { name: "Unap Isla Saona" },
      { name: "Centro de Diagnostico Caleta" },
      { name: "Unap Paulina Jimenez" },
      { name: "unap cavaloto" },
      { name: "Gobernacion" },
      { name: "Hogar del Niño" },
      { name: "Hospital Buen Samaritano" },
      { name: "Unap Caleta" },
      { name: "Policlinica Los Mulos" },
      { name: "Unap Km10 de Cumayasa" },
      { name: "Unap Villa Hermosa 4" },
      { name: "Unap Km14 de Cumayasa" },
      { name: "Hospital Aristides Fiallo Cabral" },
      { name: "centro Comunal" },
      { name: "villa real" },
      { name: "Tomas Decir." },
      { name: "Cucama" },
      { name: "Hospital Guaymate ." },
      { name: "Iglesia universal de Cristo." },
      { name: "Iglesia Maranhta" },
      { name: "DPS -La Romana PFV." },
      { name: "Unap cavaloto" },
      { name: "Hosptal Francisco A. Gonzalvo" },
      { name: "Dispensario Luis J. Suarez" },
      { name: "Dps La Romana" },
      { name: "Clinica Los Mulos" },
      { name: "Fuerza Armada" },
      { name: "Unap Km14" },
      { name: "Unap Tomas desir" },
      { name: "Comunal" },
      { name: "Gobernacion" },
      { name: "Hospital Central Romana" },
      { name: "DPS -La Romana" },
      { name: "Clínica Canela I" },
      { name: "Dps-La Romana PFV" },
      { name: "Dps-La Romana DOMICILIARIO." },
      { name: "Hospital Materno Infantil Dr. Francisco A. Gonzalvo" },
      { name: "Villa Hermosa 1-2" },
      { name: "Dispensario Médico Dr. Luis J. Suarez" },
      { name: "Centro de Especialidades Médicas CEMER" },
      { name: "Unap Cucama" },
      { name: "DPS-LA ROMANA." },
      { name: "Hospital Municipal Guaymate" },
      { name: "Dispensario Padre Cavaloto" },
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "UNAP#9" },
      { name: "HOSPITAL PROVINCIA DE PEDERNALES" },
      { name: "UNAP #3 Y #4" },
      { name: "UNAP #5 Y#6" },
      { name: "UNAP#7Y #8" }
    ],
  },
  {
    name: "SANTIAGO (DISTRITO-I)",
    centers: [
      { name: "HOSP. REG. UNI. ARTURO GRULLON" },
      { name: "HOSP. ESTRELLA UREÑA" },
      { name: "CLUB SAMEJI:POLICIAS" },
      { name: "CLINICA SANTIAGO APOSTOL" },
      { name: "TECHADO LOS CIRUELITOS" },
      { name: "ENS. LIBETAD (GUG)" },
      { name: "CIENFUEGO BAJO TECHO" },
      { name: "CLUB MAMBUICHE" },
      { name: "PARQUE CENTRAL" },
      { name: "FORTALEZA SAN LUIS (MILITARES)" },
      { name: "DELIVERY ADULTOS EN CAMA" },
      { name: "TIPIQUITO LOS COCOS" },
      { name: "ZONA FRANCA PISANO" },
      { name: "MEDICA" },
      { name: "PM PLAZA CORAL" },
      { name: "CPN PEDRO GARCIA" },
      { name: "CPN ENS. ESPAILLAT" },
      { name: "CPN PALMAR ABAJO" },
      { name: "CPN LOS PEREZ" },
      { name: "CNP INGENIO ABAJO" },
      { name: "CPN EL LIMON" },
      { name: "CPN LA CUMBRE" },
      { name: "CPN JACAGUA ADENTRO" },
      { name: "CPN SANTA LUCIA" },
      { name: "CPN LLANOS DEL INGENIO" },
      { name: "CPN CJC" },
      { name: "CPN LA GLORIA" },
      { name: "CPN FUNDA AMBIENTE" },
      { name: "CPN LA CRUZ DE GURABO" },
      { name: "CPN MAMACHEN" },
      { name: "CPN ENS. BERMUDEZ" },
      { name: "CPN ANA CRUZ" },
      { name: "CPN RANCHITO PICHET" },
      { name: "CPN PALMARITO" },
      { name: "CPN LA DELGADA" },
      { name: "CPN LA CIENEGAS" },
      { name: "CPN CIENFUEGOS" },
      { name: "CPN VILLA TABACALERA" },
      { name: "CPN EL AGUACATE" },
      { name: "PARQUE DE VILLA GONZALEZ" },
      { name: "CPN JACAGUA ARRIBA" },
      { name: "CPN BANEGAS" },
      { name: "CPN ESTANCIA DEL YAQUE" },
      { name: "CLUB ROTARIO:NAVARRETE" },
      { name: "CENTRO ADP: NAVARRETE" }
    ],
  },
      {
    name: "SANTIAGO (II)",
    centers: [
      { name: "CONSULTORIO ADVENTISTA" },
      { name: "CPN BELLA VISTA" },
      { name: "CPN INOA" },
      { name: "CPN LA CANELA" },
      { name: "CPN LAS CHARCAS" },
      { name: "CPN LOS PLATANAL" },
      { name: "CPN PEDREGAL" },
      { name: "CPN MAMA TINGO" },
      { name: "CPN LA CUESTA" },
      { name: "HOSPITAL SAJOMA" },
      { name: "HOSP. JANICO" },
      { name: "LA JOYA/BARACOA" },
      { name: "CLUB LA OTRA BANDA" },
      { name: "UASD RECINTO SANTIAGO" },
      { name: "CPN YAGUITA DEL PASTOR" },
      { name: "CPN BUEN PASTOR" },
      { name: "HP HATO DEL YAQUE" },
      { name: "CLUB HATO DEL YAQUE" },
      { name: "HM SABANA IGLESIA" },
      { name: "CLUB LA ZANJA" },
      { name: "HM JANICO" },
      { name: "HM SAJOMA" },
      { name: "HOGAR DE ANCIANOS SAJOMA" },
      { name: "HP BELLA VISTA" },
    ],
  },
      {
    name: "SANTIAGO (III)",
    centers: [
      { name: "HEMMI" },
      { name: "CLUB HERMNOS PATIÑO" },
      { name: "CLUB VILLA OLGA" },
      { name: "DOMICILIO" },
      { name: "IGLESIA MONTE ADENTRO" },
      { name: "LICEO CARLOS DIAZ (CANCHA)" },
      { name: "LICEO EUGENIO DE JESUS MARCANO (TAMBORIL)" },
      { name: "UNIVERSIDAD NAPOLEON NUÑEZ MOLINA (licey)" },
    ],
  },
      {
    name: "LA VEGA",
    centers: [
      { name: "DEFENSA CIVIL" },
    ],
  },
      {
    name: "BAHORUCO",
    centers: [
      { name: "MULTIUSO TAMAYO" },
      { name: "LICEO SEC. PROF. JUAN BOSCH" },
      { name: "HOSPITAL JULIA SANTANA" },
      { name: "CPN CABEZA DE TORO" },
      { name: "CPN ALTAMIRA" },
      { name: "VUELTA GRANDE" },
      { name: "BATEY SANTANA" },
      { name: "SANTANA" },
      { name: "DPS BAHORUCO" },
      { name: "LICEO MANUEL DE JESUS GALVAN" },
      { name: "DESTACAMENTO PN NEIBA" },
      { name: "FORTALEZA CAMBRONAL" },
      { name: "ESCUELA VOCACIONAL FF.AA." },
      { name: "CPN APOLINAR PERDOMO" },
      { name: "CPN APOLINAR PERDOMO II" },
      { name: "LAS PETACAS" },
      { name: "CPN BATEY II" },
      { name: "CPN EL PALMAR" },
      { name: "HOSPITAL DR. ALFREDO GONZALEZ G R" },
      { name: "ESCUELA MARIE POUSEPIN" },
      { name: "HIGO DE LA CRUZ" },
      { name: "CPN LAS SABILAS" },
    ],
  },
      {
    name: "MONTECRISTI",
    centers: [
      { name: "CLUB CULTURAL HATILLO" },
      { name: "EL PARQUE VILLA VASQUEZ" },
      { name: "POLIDEPORTIVO CASTAÑUELAS" },
      { name: "POLIDEPORTIVO GUAYUBIN" },
      { name: "POLIDEPORTIVO LAS MATAS DE SANTA CRUZ" },
      { name: "POLIDEPORTIVO MANZANILLO" },
      { name: "RESTAURANTE LILO" },
      { name: "UNAP EL COPEY DE GUAYUBIN" },
    ],
  },
  {
    name: "SAN CRISTOBAL",
    centers: [
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOP. RAFAEL J. MAÑÓN" },
      { name: "COMEDOR ECONÓMICO" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "PARQUE RADHAMES" },
      { name: "CENTRO DIAGNOSTICO VILLA FUNDACIÓN" },
      { name: "CENTRO DIAGNOSTICO MADRE VIEJA SUR" },
      { name: "ESCUELA VILLA MERCEDES Ó IGLESIA CATÓLICA" },
      { name: "VILLA FEDERICO" },
      { name: "IGLESIA FRATERNAL LOS MOLINA" },
      { name: "GONZALES BINNET" },
      { name: "UNAPS PUEBLO" },
      { name: "UNAPS LAVA PIÉ" },
      { name: "HATILLO" },
      { name: "HATO DAMAS" },
      { name: "CANASTICA" },
      { name: "SAINAGUA(CRUCE DE LA PLENA)" },
      { name: "DPS" },
      { name: "HOSPITAL MUNICIPAL - BALSEQUILLO" },
      { name: "UNAP- GERÓNIMO PINALES" },
      { name: "UNAP- EL CARRIL" },
      { name: "UNAP- LA PARED" },
      { name: "UNAP MAMA TINGO" },
      { name: "ORDEN DE MALTA" },
      { name: "UNAP GERÓNIMO PINALES" },
      { name: "CENTRO MEDICO SAN AGUSTÍN" },
      { name: "UNAP DÑA. ANA" },
      { name: "MULTI-USO YAGUATE" },
      { name: "MULTI-USO DE BOCA DE NIGUA" },
      { name: "MULTI-USO SABANA PALENQUE" },
      { name: "HOSP MUNICIPAL DE CAMBITA" },
      { name: "HOSP. MUNIC DE LOS CACAOS" },
      { name: "ESCUELA PEDRO DOMÍNGUEZ" },
      { name: "HOSP. MUNICIPAL NTRA. SEÑORA DE LA ALTAGRACIA" },
      { name: "HOSP. NTRA. SEÑORA DE LA ALTAGRACIA (IDSS)" },
      { name: "UNAPS CUCHILLA" },
      { name: "UNAPS MEDINA" },
      { name: "UNAPS EL MAIZAL" },
      { name: "UNAPS LA REPRESA" },
      { name: "SABANA TORO (UNAP)" },
    ],
  },
      {
    name: "SAN JOSE DE OCOA",
    centers: [
      { name: "CENTRO DE SALUD HOSPITAL GUARIONEX ALCANTARA" },
      { name: "CENTRO DE SALUD UNAP ARROLLO CAÑA" },
      { name: "PUESTO MOVIL, PARQUE LA CENTRAL CIENAGA" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "CENTRO DE SALUD UNAP SABANA LARGA CENTRO" },
    ],
  },
      {
    name: "ESPAILLAT",
    centers: [
      { name: "HOSPITAL JOSE CONTRERAS" },
      { name: "HOSPITAL JAMAO AL NORTE" },
      { name: "HOSPITAL MANUEL DE LUNA" },
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CPN LAS FLORES" },
      { name: "CPN LA ISLETA" },
      { name: "CPN BOCA FERREA" },
      { name: "CPN ALGARROBO" },
      { name: "CPN LAS LAGUNAS" },
      { name: "CPN LA MANZANA" },
      { name: "CPN JUAN LOPEZ" },
      { name: "CPN LA GUAMA" },
      { name: "CPN GUAUCI" },
      { name: "CPN QUEBRADA HONDA" },
      { name: "CPN ZAFARRAYA" },
      { name: "CPN EL COROZO" },
      { name: "CPN NUEVO PUERTO RICO" },
      { name: "CPN LOS LÓPEZ" },
      { name: "CPN SANTA ROSA" },
      { name: "CPN LAS GUAZUMAS" },
      { name: "CPN TIERRA DURA" },
      { name: "CPN EL HIGUERITO" },
      { name: "CPN BONAGUA" },
      { name: "CPN MONTE DE LA JAGUA" },
      { name: "CPN ORTEGA" },
      { name: "CPN REPARADERO" },
      { name: "CDX CARLOS MARIA ROJAS BADIA" },
      { name: "CPN JOBA ARRIBA" },
      { name: "CPN LA YAGUA" },
      { name: "CPN VERAGUA" },
      { name: "CPN BATEY GINEBRA" },
      { name: "CPN VILLA PROGRESO" },
      { name: "CPN LOS BRAZOS" },
      { name: "CPN EL CAIMITO" },
      { name: "CPN PALMA HERRADA" },
      { name: "CPN SAL SI PUEDES" },
      { name: "CPN LOS PANCHOS" },
      { name: "CPN BARRIO VIEJO PUERTO RICO" },
      { name: "CPN BARRIO MANUEL RODRIGUEZ" },
      { name: "CPN LA ERMITA" },
      { name: "CPN SAN FRANCISCO ARRIBA" },
      { name: "CPN CANCA LA REINA" },
      { name: "CPN CEIBA DE MADERA" },
      { name: "CPN SAN VICTOR" },
      { name: "CPN CUERO DURO" },
      { name: "CPN PUESTO GRANDE" },
      { name: "CPN VILLA CAFETALERA" },
      { name: "CLUB BARRIO LA ESTELA" },
      { name: "CMD FILIAL MOCA" },
      { name: "CLUB BARRIO JOSE HORACIO" },
      { name: "CLUB RECREATIVO" },
      { name: "CLUB LA CANCHA" },
      { name: "PUESTO MOVIL DPS" },
    ],
  },
      {
    name: "DUARTE",
    centers: [
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "GRUPO MEDICO UNIDO SIGLO 21" },
      { name: "INEMED" },
      { name: "CENTRO MEDICO NACIONAL" },
      { name: "FORTALEZA DUARTE" },
      { name: "HOGAR GERIATRICO NIÑA VALERIO" },
      { name: "HOSPITAL DR. LEOPOLDO FEDERICO LAVANDIER" },
      { name: "POLICIA NACIONAL" },
    ],
  },
      {
    name: "DAJABON",
    centers: [
      { name: "POLI DEPORTIVO AMBROSIO ESTÉVEZ" },
      { name: "ADEPA" },
      { name: "CLUB CULTURAL" },
      { name: "CESFRONT" },
      { name: "CLUB CULTURAL EL PINO" },
      { name: "FORTALEZA DE BELLER, E.R.D" },
      { name: "FORTALEZA DE RESTAURACION" },
      { name: "HOSPITAL RAMON MATIAS MELLAS" },
    ],
  },
      {
    name: "PERAVIA",
    centers: [
      { name: "24 DE ABRIL" },
      { name: "ARROYO HONDO" },
      { name: "BOCA CANASTA 1" },
      { name: "BOCA CANASTA 2" },
      { name: "BUENAS NUEVAS" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "EL MANI" },
      { name: "ESCONDIDO I" },
      { name: "ESCONDIDO II" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "HONDURAS" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS CARRERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MATANZAS ABAJO" },
      { name: "MATANZAS ARRIBA" },
      { name: "MAXIMO GOMEZ" },
      { name: "PAYA ABAJO" },
      { name: "PAYA ARRIBA" },
      { name: "PIZARRET I" },
      { name: "PIZARRETE II" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "SALINAS" },
      { name: "SANTA ROSA 1" },
      { name: "SANTA ROSA 2" },
      { name: "SANTA ROSA 3" },
      { name: "SANTANA ARRIBA" },
      { name: "SAONA I" },
      { name: "SAONA II" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA SOMBBRERO 1" },
      { name: "VILLA SOMBRERO 2" },
      { name: "SANTA CRUZ" },
      { name: "PUEBLO NUEVO" },
      { name: "VILLA MEJAGA I" },
      { name: "VILLA MAJEGA II" },
      { name: "AYUNTAMIENTO" },
      { name: "DPS PERAVIA" },
      { name: "LA GOBERNACION PROVINCIAL" },
    ],
  },
      {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "UNAP ANAYUMA" },
      { name: "UNAP LOS CERRITOS" },
      { name: "UNAP BOCA DE YUMA" },
      { name: "HOSPITAL LAGUNA DE NISIBON" },
      { name: "HOSP. DOCTORA EVANGELINA RODRIGUEZ" },
      { name: "POLIDEPORTIVO" },
      { name: "MULTI-USO RS." },
    ],
  },
      {
    name: "AZUA",
    centers: [
      { name: "PARCELERO" },
      { name: "LAS LOMAS" },
      { name: "ANSONIA" },
      { name: "BARRERA" },
      { name: "HOSPITAL R. TAIWAN" },
      { name: "PRADO Y COLONIA (CPN)." },
      { name: "CUCHILLA" },
      { name: "BOMBITA" },
      { name: "SABANA YEGUA" },
      { name: "YAYA ABAJO" },
      { name: "YAYA ARRIBA" },
      { name: "VIAJAMA" },
      { name: "C/R MAGUEYAL" },
      { name: "C/R HATO NUEVO" },
      { name: "C/R VILLARPANDO" },
      { name: "C/R LAS CHARCAS" },
      { name: "C/R HATILLO" },
      { name: "C/ PARMAL DE OCOA" },
      { name: "C/R ESTEBANIA" },
      { name: "UNAP PUEBLO VIEJO" },
      { name: "C/ R EL ROSARIO" },
      { name: "UNAP EL HIGUERO" },
      { name: "UNAP LOS JOBOS -2" },
      { name: "UNAP LOS JOBOS -1" },
      { name: "UNAP CARISAL" },
      { name: "MAJAGUAL" },
      { name: "C/R TABARA ARRIBA" },
      { name: "C/R TABARA ABAJO" },
      { name: "C/R SAJANOA" },
      { name: "C/R LOS TOROS" },
      { name: "C/R AMIAMA GOMEZ" },
      { name: "HOSP. MUNICIPAL PLC" },
      { name: "MONTE BONITO" },
      { name: "C/R LA SIEMBRA" },
      { name: "C/R LAS LAGUNAS" },
      { name: "UNAP SANTA ANA" },
      { name: "UNAP VILLA OCOA" },
      { name: "UNAP CAÑITA -A" },
      { name: "UNAP LOS MONTES FRIOS" },
      { name: "PRADO Y COLONIA" },
      { name: "LOS JOVILLOS" },
      { name: "V. CORAZON DE JESUS" },
      { name: "CENTRO DIAGNSTICO" },
      { name: "PUESTO DE GOBERNACION" },
      { name: "LAS BARIAS" },
      { name: "LOS NEGROS" },
      { name: "MOD. SAN FCO KM-11" },
      { name: "PROYECTO-4" },
      { name: "PROYECTO-2-C" },
      { name: "GANADERO" },
      { name: "HOSPITAL M. GUAYABAL" },
    ],
  },
  {
    name: "ELIAS PIÑA",
    centers: [
      { name: "RINCONCITO" },
      { name: "PEDRO SANTANA" },
      { name: "CESFRONT" },
      { name: "BANICA" },
      { name: "HONDO VALLE" },
      { name: "JUAN SANTIAGO" },
      { name: "LA 25 CIA" },
      { name: "LA FORTALEZA ESTRELLETA" },
      { name: "LOS PUESTOS DE VACUNACIÓN DE EL LLANO" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CUARTEL DE LOS BOMBEROS" },
      { name: "ESCUELA FEDERICO AUGUSTO GONZALEZ" },
      { name: "ESCUELA LA GINA" },
      { name: "LICEO EMILIANO TEJERA" },
      { name: "POLIDEPORTIVO" },
      { name: "SALCEDO" },
      { name: "TENARES" },
      { name: "VILLA TAPIA" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "EJERCITO MONTE PLATA" },
      { name: "HOSPITAL MUNICIPAL DE YAMASÁ" },
      { name: "ADULTOS MAYORES CASA, CASA" },
      { name: "CPNA GREGORIO LUPERON" },
      { name: "LA COLORADA" },
      { name: "LOS JAVIELES" },
      { name: "SIERRA DE AGUA" },
      { name: "UNAP DON JUAN" },
    ],
  },  {
    name: "SANCHEZ RAMIREZ",
    centers: [
      { name: "DISTRITO 16-01" },
      { name: "BAJO TECHO" },
      { name: "COLEGIO MEDICO" },
      { name: "GRAN ARENA (PUEBLO NUEVO)" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "HOSPITAL INMACULADA CONCEPCIÓN" },
      { name: "CPN BARRIO LIBERTAD" },
      { name: "CPN QUITA SUEÑO (AYUTAMIENTO)" },
      { name: "CPN LA ALTAGRACIA" },
      { name: "CPN PEDRO FRANCISCO BONO" },
      { name: "HOSPITAL DR. RAMON BÁEZ" },
      { name: "CPN DUEY" },
      { name: "CPN EL LIMÓN" },
      { name: "CPN LA PLACETA" },
      { name: "CPN ZAMBRANA" },
      { name: "CPN PLATANAL" },
      { name: "CPN LA CRUZ" },
      { name: "DPS" },
      { name: "FORTALEZA PALO HINCADO" },
      { name: "DOMICILIARIO" },
      { name: "HOSPITAL LA MATA" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "CPN LA BIJA" },
      { name: "CPN LOS COROZOS" },
      { name: "CPN HERNANDO ALONZO" },
      { name: "BARRIO LINDO" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "BAJO TECHO" },
      { name: "CLUB JUAN PABLO DUARTE (CLUB 4 DE JULIO)" },
      { name: "CABALLERO" },
      { name: "COMEDERO ARRIBA" },
      { name: "EL LIMONCITO" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "BATERO" },
      { name: "LA CUEVA" },
      { name: "CPN PESCOZÓN" },
      { name: "PN CUARTEL GENERAL DE COTUÍ" },
      { name: "HOSPITAL SIGFREO ALBA DOMINGUEZ DE FANTINO" },
      { name: "HOSPITAL DE CEVICOS" },
    ],
  },  
  {
    name: "VALVERDE",
    centers: [
      { name: "CLUB DE LEONES" },
      { name: "HOSPITAL MATERNO INFANTIL J.F.P." },
      { name: "COLEGIO MEDICO" },
      { name: "4TA. BRIGADA DE INFANTERIA" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "HOSPITAL LAGUNA SALADA JULIO MORONTA" },
      { name: "UNAP CENTRO LAGUNA SALADA" },
      { name: "HOSPITAL LUIS L. BOGAERT" },
      { name: "UNAP CENTRO" },
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "SERVICIO EN LA DPS" },
      { name: "CENTRO DE VACUANCION SEGURO SOCIAL" },
      { name: "CENTRO DE VACUNACION EL FATIMA" },
      { name: "CENTRO DE VACUNACION EL POLIBON" },
      { name: "CENTRO DE VACUNACION LA LIRA" },
    ],
  },
  {
    name: "SAN PEDRO DE MACORIS",
    centers: [
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "COLEGIO MONTE DE SION" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "IGLESIA ASAMBLEA DE DIOS ADONAI" },
      { name: "IGLESIA PENTECOSTAL LUZ DEL FARO" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "CLUB DE LEONES" },
      { name: "UNAP EVANGELINA RODRIGUEZ" },
      { name: "CLINICA DR. DE LEON" },
      { name: "IGLESIA MARANATHA" },
      { name: "DEFENSA CIVIL" },
      { name: "CLUB DE PERIODISTA" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "MULTIUSO" },
      { name: "SALON AYUNTANIENTO" },
      { name: "CENTRO MADRE CARMEN" },
      { name: "IGLESIA CATOLICA" },
      { name: "IGLESIA ASAMBLEA DE DIOS" },
      { name: "IGLESIA DE DIOS" },
      { name: "BATEY PALOMA" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
