const centros = [
  {
    name: "AZUA",
    centers: [
      { name: "CENTRO DE SALUD FINCA 6" },
      { name: "CLINICA RURAL AMIAMA GOMEZ" },
      { name: "CLINICA RURAL ANZONIA" },
      { name: "CLINICA RURAL BARRERAS" },
      { name: "CLINICA RURAL EL CARRIZAL" },
      { name: "CLINICA RURAL EL ROSARIO" },
      { name: "CLINICA RURAL ESTEBANIA" },
      { name: "CLINICA RURAL HATILLO" },
      { name: "CLINICA RURAL HATO NUEVO" },
      { name: "CLINICA RURAL LA SIEMBRA" },
      { name: "CLINICA RURAL LAS BARIAS" },
      { name: "CLINICA RURAL LAS LAGUNAS" },
      { name: "CLINICA RURAL LOS NEGROS" },
      { name: "CLINICA RURAL LOS TOROS" },
      { name: "CLINICA RURAL MAGUEYAL" },
      { name: "CLINICA RURAL MONTE BONITO" },
      { name: "CLINICA RURAL PALMAR DE OCOA" },
      { name: "CLINICA RURAL PROYECTO 4" },
      { name: "CLINICA RURAL PROYECTO-2-C" },
      { name: "CLINICA RURAL PUEBLO VIEJO" },
      { name: "CLINICA RURAL SABANA YEGUA" },
      { name: "CLINICA RURAL SAJANOA" },
      { name: "CLINICA RURAL TABARA ABAJO" },
      { name: "CLINICA RURAL TABARA ARRIBA" },
      { name: "CLINICA RURAL VIAJAMA" },
      { name: "CLINICA RURAL VILLA ARPANDO" },
      { name: "DISTRITO ESCOLAR 03-01" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL TAIWAN" },
      { name: "LICEO GUAYACANAL" },
      { name: "LICEO JOSE FRANCISCO BOBADILLA" },
      { name: "LOS JOVILLOS" },
      { name: "CENTRO CLÍNICO Y DIAGNOSTICO DE ATENCION PRIMARIA" },
      { name: "GOBERNACIÓN" },
      { name: "SUPERMERCADO DIVERSO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA LA BOMBITA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA YAYAS #1" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAÑITA -A" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL BARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL HIGUERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GANADERO BARRIO LOS TECNICOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAYAS ARRIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -1" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -2" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOVILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS MONTES FRIOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PARCELEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUEBLO VIEJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA ANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CORAZON DE JESUS" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA OCOA" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE BAHORUCO NEYBA" },
      { name: "MULTIUSO JARAGUA" },
      { name: "MULTIUSO NEYBA" },
      { name: "MULTIUSO TAMAYO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA EL SALADO GALVAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTAMIRA" },
      { name: "UNIDAD DE ATENCION PRIMARIA APOLINAR PERDOMO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 2" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABEZA DE TORO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA UVILLA" },
      { name: "LOS BOMBEROS NEIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA MONSERRATE" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CLUB ENRIQUILLO" },
      { name: "COLEGIO MEDICO DOMINICANO" },
      { name: "ESCUELA LA LISTA" },
      { name: "IGLESIA RESURECCION Y VIDA (FLEMING)" },
      { name: "MULTIUSO DE POLO " },
      { name: "PARAISO UNIDAD DE ATENCION PRIMARIA 1 Y 2" },
      { name: "PLAZA COMUNAL VICENTE NOBLE" },
      { name: "POLO CENTRO COMUNAL" },
      { name: "UCATEBA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA DE QUITA CORAZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO BELO" },
      { name: "UNIDAD DE ATENCION PRIMARIA ARROYO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABRAL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA CANOA" },
      { name: "UNIDAD DE ATENCION PRIMARIA FONDO NEGRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA INVI-CEA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CIENAGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS SALINAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS BLANCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS COCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA PEÑON" },
      { name: "UNIDAD DE ATENCION PRIMARIA PESCADERIA" },
      { name: "DEFENSA CIVIL" },
      { name: "ENRIQUILLO HOSPITAL" },
      { name: "PALACIO DE JUSTICIA" },
      { name: "CENTRO DE PRIMER NIVEL PALO ALTO" },
      { name: "PARAISO III, IV" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAITOITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOMBITA " },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MONTAÑITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PEÑUELA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PLAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA RAQUETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "VICENTE NOBLE I, II V" },
      { name: "VICENTE NOBLE III, IV" },
    ],
  },
  {
    name: "DAJABÓN",
    centers: [
      { name: "CENTRO COMUNAL CRUZ DE CABRERA" },
      { name: "CENTRO COMUNAL LOS CEREZOS" },
      { name: "CENTRO COMUNAL MARIANO CESTERO" },
      { name: "CENTRO COMUNAL TRINITARIA" },
      { name: "CENTRO DE MADRE LOS MICHES" },
      { name: "CENTRO DE MADRE LUPERON" },
      { name: "POLI DEPORTIVO AMBRIOSO ESTEVEZ" },
    ],
  },
  {
    name: "DISTRITO NACIONAL",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL VILLA FRANCISCA" },
      { name: "CENTRO MEDICO HONDURAS" },
      { name: "CENTRO OLÍMPICO JUAN PABLO DUARTE (PABELLÓN DE COMBATE)" },
      { name: "CLUB LOS PRADOS" },
      { name: "CLUB MAURICIO BÁEZ" },
      { name: "CLUB NACO" },
      { name: "CLUB PLAZA INDEPENDENCIA" },
      { name: "CLUB RAFAEL BARIAS" },
      { name: "CLUB SAN CARLOS" },
      { name: "CENTRO DE PRIMER NIVEL HONDURAS" },
      { name: "DISPENSARIO PARROQUIAL SAN GABRIEL" },
      { name: "DISPENSARIO TEJADA Y FLORENTINO (UASD)" },
      { name: "FUNDACIÓN JUDEGU" },
      { name: "FUNSAZURZA" },
      { name: "HOSPITAL DE LA POLICIA NACIONAL" },
      { name: "HOSPITAL DOCENTE DR. FRANCISCO MOSCOSO PUELLO " },
      { name: "HOSPITAL DR. FÉLIX MARÍA GOICO" },
      { name: "IINSTITUTO DE AUXILIO Y VIVIENDA (INAVI)" },
      { name: "MINISTERIO DE DEFENSA (MIDE)" },
      { name: "PARROQUIA NUESTRA SEÑORA DEL SAGRADO CORAZON" },
      { name: "PUCMM - SANTO DOMINGO" },
      { name: "MINISTERIO DE TURISMO" },
      { name: "UNIBE" },
      { name: "UNIVERSIDAD DOMINICANA O&M" },
      { name: "PLAZA LAMA 27 DE FEBRERO" },
      { name: "AGRUCUDEGUA" },
      { name: "CENTRO DE DIAGNOSTICO DE ATENCION PRIMARIA BARNEY MORGAN " },
      { name: "CLUB DEPORTIVO LOS PIONEROS" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CLUB RENACER " },
      { name: "FUNDACION ESCOBA" },
      { name: "IGLESIA PERPETUO SOCORRO" },
      { name: "PLAZA SAMBIL" },
      { name: "CLUB GENERAL GREGORIO  LUPERON" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "FUNDACION HUELLAS DEL SIGLO" },
      {
        name:
          "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)",
      },
      { name: "CONSEJO NACIONAL DE LA PERSONA ENVEJECIENTE (CONAPE)" },
      { name: "CRUZ ROJA DOMINICANA" },
      { name: "DIRECCION GENERAL DE IMPUESTOS INTERNOS (DGII)" },
      { name: "PLAZA LAMA" },
      { name: "AGORA MALL AV. KENNEDY" },
      { name: "SUPERMERCADOS NACIONAL (CCN)" },
      { name: "COLEGIO MOVEARTE" },
      { name: "SENADO DE LA REPÚBLICA DOMINICANA" },
      { name: "UNIVERSIDAD OYM" },
      { name: "UNIVERSIDAD PCMM" },
      { name: "CENTRO DE PRIMER NIVELA CARMEN RENATA " },
      { name: "HOSPITAL JACINTO MAÑON" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "UNIVERSIDAD NACIONAL PEDRO HENRIQUEZ UREÑA (UNPHU)" },
      { name: "CENTRO MEDICO FUSADI" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "CATEDRAL SANTA ANA - JUAN XXIII" },
      { name: "CENTRO COMUNAL DE CASTILLO" },
      { name: "CENTRO DE VACUNACION SIGLO 21" },
      { name: "CENTRO MÉDICO DOCTOR OVALLE" },
      { name: "CLUB BLUE" },
      { name: "CLUB SALOME UREÑA" },
      { name: "ESCUELA GREGORIO LUPERÓN VISTA AL VALLE" },
      { name: "MULTIUSO ARENA  57" },
      { name: "MULTIUSO ARENOSO" },
      { name: "MULTIUSO BAJO TECHO VILLA RIVAS" },
      { name: "UASD" },
      { name: "CLUB JUAN ALBERTO ESPINOLA" },
      { name: "CLUB MAYORISTAS" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CASA CLUB DE GINANDIANA" },
      { name: "CENTRO CAMPESINO" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO (CTC) (MICHES)" },
      { name: "DEFENSA CIVIL" },
      { name: "HOSPITAL DOCTOR TEOFILO HERNADEZ" },
      { name: "IGLESIA BENJAMIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA MIRADOR SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA GUERRERO" },
    ],
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO DE COMBATE" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL LA GALLERA" },
      { name: "CENTRO DE PRIMER NIVEL LAS DELICIAS" },
      { name: "CENTRO DE PRIMER NIVEL MACASÍAS" },
      { name: "CENTRO DE PRIMER NIVEL PEDRO SANTANA" },
      { name: "CENTRO DE PRIMER NIVEL PINZON" },
      { name: "CENTRO DE PRIMER NIVEL POTROSO" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO DE LA GUARDIA" },
      { name: "CENTRO DE PRIMER NIVEL RINCONCITOS" },
      { name: "CENTRO DE PRIMER NIVEL SABANA HIGUERO" },
      { name: "CENTRO DE PRIMER NIVEL SABANA MULA" },
      { name: "CENTRO DE PRIMER NIVEL DE JUAN SANTIAGO" },
      { name: "CENTRO DE PRIMER NIVEL EL LLANO" },
      { name: "CENTRO DE PRIMER NIVEL GUANITO " },
      { name: "CENTRO DE PRIMER NIVEL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL LAS PALMAS " },
      { name: "CENTRO DE PRIMER NIVEL SABANA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL SABANA LARGA" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL DE HONDO VALLE " },
      { name: "HOSPITAL ROSA DUARTE" },
      { name: "POLIDEPORTIVO (HONDO VALLE)" },
      { name: "POLIDEPORTIVO  BANICA " },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CLUB JOSE HORACIO RODRIGUEZ" },
      { name: "CLUB RECREATIVO" },
      { name: "CENTRO DE PRIMER NIVEL ALGARROBO" },
      { name: "CENTRO DE PRIMER NIVEL BATEY GINEBRA" },
      { name: "CENTRO DE PRIMER NIVEL BONAGUA" },
      { name: "CENTRO DE PRIMER NIVEL CANCA LA REYNA" },
      { name: "CENTRO DE PRIMER NIVEL CEIBA DE MADERA" },
      { name: "CENTRO DE PRIMER NIVEL CUERO DURO" },
      { name: "CENTRO DE PRIMER NIVEL DE GUAUCI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAIMITO" },
      { name: "CENTRO DE PRIMER NIVEL EL COROZO" },
      { name: "CENTRO DE PRIMER NIVEL EL HIGUERITO" },
      { name: "CENTRO DE PRIMER NIVEL JOBA ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL JUAN LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA ERMITA" },
      { name: "CENTRO DE PRIMER NIVEL LA ISLETA" },
      { name: "CENTRO DE PRIMER NIVEL LA MANZANA" },
      { name: "CENTRO DE PRIMER NIVEL LA YAGUA" },
      { name: "CENTRO DE PRIMER NIVEL LAS FLORES" },
      { name: "CENTRO DE PRIMER NIVEL LAS GUAZUMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS LAGUNAS " },
      { name: "CENTRO DE PRIMER NIVEL LOS BRAZOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LOS PANCHOS" },
      { name: "CENTRO DE PRIMER NIVEL MONTE DE LA JAGUA " },
      { name: "CENTRO DE PRIMER NIVEL NUEVO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL PALMA HERRADA" },
      { name: "CENTRO DE PRIMER NIVEL QUEBRADA HONDA" },
      { name: "CENTRO DE PRIMER NIVEL REPARADERO" },
      { name: "CENTRO DE PRIMER NIVEL SAL SI PUEDES" },
      { name: "CENTRO DE PRIMER NIVEL SAN FRANCISCO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL SAN VICTOR" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA MOCA" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA DURA" },
      { name: "CENTRO DE PRIMER NIVEL VERAGUA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CAFETALERA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA PROGRESO" },
      { name: "CENTRO DE PRIMER NIVEL ZAFARRAYA" },
      { name: "HOSPITAL JOSÉ CONTRERAS" },
      { name: "SALON DE ACTIVIDADES BARRIO LA ESTELA" },
      { name: "CENTRO DE PRIMER NIVEL ORTEGA" },
      { name: "CENTRO DE PRIMER NIVEL PUESTO GRANDE" },
      { name: "HOSPITAL JAMAO AL NORTE" },
      { name: "HOSPITAL MANUEL DE LUNA" },
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUALEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUAYABO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CAÑITAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS HATILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MANCHADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUERTO RICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUNTA DE GARZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CANTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA NAVARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ORTEGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA JAVILLA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS GUAMAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAGUITAS" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO COMUNAL RANCHO ARRIBA" },
      { name: "POLIDEPORTIVO" },
      { name: "ESCUELA JAYABO AFUERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA TENARES" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA TAPIA" },
    ],
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL BATEY 8" },
      { name: "CENTRO DE PRIMER NIVEL BOCA DE CACHON" },
      { name: "CENTRO DE PRIMER NIVEL COLONIA MIXTA" },
      { name: "CENTRO DE PRIMER NIVEL PLACER BONITO" },
      { name: "CENTRO DIAGNÓSTICO." },
      { name: "CENTRO DE PRIMER NIVEL ANGOSTURA." },
      { name: "CENTRO DE PRIMER NIVEL BARTOLOMÉ" },
      { name: "CENTRO DE PRIMER NIVEL BATEY 8" },
      { name: "CENTRO DE PRIMER NIVEL CRISTÓBAL." },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABAL." },
      { name: "CENTRO DE PRIMER NIVEL EL LIMÓN." },
      { name: "CENTRO DE PRIMER NIVEL JIMANI CENTRO." },
      { name: "CENTRO DE PRIMER NIVEL LA DESCUBIERTA." },
      { name: "CENTRO DE PRIMER NIVEL LAS BAITOAS." },
      { name: "CENTRO DE PRIMER NIVEL LAS MERCEDES." },
      { name: "CENTRO DE PRIMER NIVEL LOS BOLOS." },
      { name: "CENTRO DE PRIMER NIVEL LOS PINOS DEL EDÉN." },
      { name: "CENTRO DE PRIMER NIVEL MELLA" },
      { name: "CENTRO DE PRIMER NIVEL POSTRER RÍO." },
      { name: "CENTRO DE PRIMER NIVEL PUESTO ESCONDIDO" },
      { name: "CENTRO DE PRIMER NIVEL SAN JOSÉ." },
      { name: "CENTRO DE PRIMER NIVEL TIERRA NUEVA." },
      { name: "CENTRO DE PRIMER NIVEL VENGAN A VER." },
      { name: "HOSPITAL GENERAL MELENCIANO" },
      { name: "HOSPITAL JOSE PEREZ" },
    ],
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "AEROPUERTO PUNTA CANA" },
      { name: "CENTRO COMUNAL LAS LAGUNAS DE NISIBON " },
      { name: "HOSPITAL DR. EVANGELINA RODRIGUEZ" },
      { name: "HOTEL LOPESAN COSTA BAVARO" },
      { name: "MULTIUSO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAYAHIBE" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOCA DE CHAVON" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOCA DE YUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA OTRA BANDA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PLATANITOS " },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
    ],
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "CENTRO DIAGNOSTICO CALETA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE LA ROMANA" },
      { name: "GOBERNACIÓN PROVINCIAL" },
      { name: "HOGAR DEL NIÑO " },
      { name: "HOSPITAL ARÍSTIDES FIALLO CABRAL" },
      { name: "HOSPITAL GUAYMATE" },
      { name: "HOSPITAL MATERNO INFANTIL DR. FRANCISCO A. GONZALVO" },
      { name: "HOSPITAL SAMARITANO" },
      { name: "IGLESIA SANTA ROSA DE LIMA" },
      { name: "POLICLINICO DUARTE" },
      {
        name: "UNIDAD DE ATENCION PRIMARIA ANTITUBERCULOSO DR. LUIS J. SUAREZ",
      },
      { name: "UNIDAD DE ATENCION PRIMARIA CALETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CENTRO COMUNAL" },
      {
        name: "UNIDAD DE ATENCION PRIMARIA CONSULTORIO RURAL KM. 14 CUMAYASA",
      },
      { name: "UNIDAD DE ATENCION PRIMARIA CUCAMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ESCUELA PAULINA JIMENEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA PADRE CAVALOTTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA HERMOSA 1 Y 2" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA REAL" },
      { name: "MULTIUSO SAN EDUARDO " },
    ],
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL BAYACANES" },
      { name: "CENTRO DE PRIMER NIVEL BUENA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL BURENDE" },
      { name: "CENTRO DE PRIMER NIVEL EL BALCON" },
      { name: "CENTRO DE PRIMER NIVEL EL CERCADO" },
      { name: "CENTRO DE PRIMER NIVEL EL MAMEY" },
      { name: "CENTRO DE PRIMER NIVEL GUACO" },
      { name: "CENTRO DE PRIMER NIVEL HATILLO" },
      { name: "CENTRO DE PRIMER NIVEL JUMUNUCO" },
      { name: "CENTRO DE PRIMER NIVEL LA CULATA" },
      { name: "CENTRO DE PRIMER NIVEL LA SABINA" },
      { name: "CENTRO DE PRIMER NIVEL LA TORRE" },
      { name: "CENTRO DE PRIMER NIVEL LIMONAL" },
      { name: "CENTRO DE PRIMER NIVEL OCTAVIA GAUTIER" },
      { name: "CENTRO DE PRIMER NIVEL PASO BAJITO" },
      { name: "CENTRO DE PRIMER NIVEL PIEDRA BLANCA" },
      { name: "CENTRO DE PRIMER NIVEL PONTON" },
      { name: "CENTRO DE PRIMER NIVEL RIO SECO" },
      { name: "CENTRO DE PRIMER NIVEL SAN MIGUEL" },
      { name: "CENTRO DE PRIMER NIVEL SANTO CERRO" },
      { name: "CENTRO DE PRIMER NIVEL TIREO" },
      { name: "CENTRO DE SALUD OBRA SOCIAL SALESIANA" },
      { name: "CENTRO MEDICO PADRE FANTINO" },
      { name: "CLÍNICA CEMEVE" },
      { name: "COOPERATIVA VEGA REAL" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "DEFENSA CIVIL" },
      { name: "HISPITAL JIMA ABAJO " },
      { name: "HOSPITAL JUAN ANT.CASTILLO" },
      { name: "HOSPITAL MORILO KING " },
      { name: "HOSPITAL OCTAVIA GAUTIER" },
      { name: "POLICLINICO LA VEGA" },
      { name: "AYUNTAMIENTO MUNICIPAL LA VEGA" },
      { name: "CENTRO DE PRIMER NIVEL CENTRO EL CARMEN" },
      { name: "CENTRO DE PRIMER NIVEL DON FAUSTO" },
      { name: "CENTRO DE PRIMER NIVEL EL PINO " },
      { name: "CENTRO DE PRIMER NIVEL EL TANQUE" },
      { name: "CENTRO DE PRIMER NIVEL GINA HUECA " },
      { name: "CENTRO DE PRIMER NIVEL LAS CARMELITAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS UVAS" },
      { name: "CENTRO DE PRIMER NIVEL LICEY" },
      { name: "CENTRO DE PRIMER NIVEL MARIA AUXILIADORA" },
      { name: "CENTRO DE PRIMER NIVEL MARTINEZ " },
      { name: "CENTRO DE PRIMER NIVEL NARANJAL " },
      { name: "CENTRO DE PRIMER NIVEL PINTO SABANETA" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL RIO VERDE" },
      { name: "CENTRO DE PRIMER NIVEL YAYAS" },
      { name: "CLUB DE ABOGADOS CLINICA LA CONCE PCION " },
    ],
  },
  {
    name: "MARIA TRINIDAD SÁNCHEZ",
    centers: [
      { name: "AYUNTAMIENTO DEL POZO" },
      { name: "AYUNTAMIENTO MUNICIPAL NAGUA" },
      { name: "CASA DE FORMACION SAGRADA FAMILIA" },
      { name: "CENTRO COMUNITARIO MATA BONITA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO AL MEDIO" },
      { name: "CENTRO DE PRIMER NIVEL LA FACTORIA" },
      { name: "CENTRO DE PRIMER NIVEL LOS YAYALES" },
      { name: "CENTRO DE PRIMER NIVEL ABREU" },
      { name: "CENTRO DE PRIMER NIVEL BAOBA DEL PIÑAL" },
      { name: "CENTRO DE PRIMER NIVEL BEJUCO ALAMBRE" },
      { name: "CENTRO DE PRIMER NIVEL BOBITA" },
      { name: "CENTRO DE PRIMER NIVEL COPEYITO" },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL EL PAPAYO" },
      { name: "CENTRO DE PRIMER NIVEL EL YAYAL" },
      { name: "CENTRO DE PRIMER NIVEL LA CAPILLA" },
      { name: "CENTRO DE PRIMER NIVEL LAS CEJAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CORCOBAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GARZAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GORDAS" },
      { name: "CENTRO DE PRIMER NIVEL LOMA ALTA" },
      { name: "CENTRO DE PRIMER NIVEL SAN RAFAEL" },
      { name: "HOSPITAL DR. ANTONIO YAPOR HEDED" },
      { name: "HOSPITAL DR. CARLOS A. ZAFRA" },
      { name: "PARROQUIA SANTISIMA TRINIDAD" },
      { name: "POLIDEPORTIVO NAGUA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
      { name: "UASD NUEVA" },
      { name: "UNIDAD DE ATENCION PRIMARIA MATANCITA" },
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CLINICA POLICLINICO BONAO" },
      { name: "CRUCE UASD BONAO" },
      { name: "HOSPITAL DOCTOR JOSE A COLUNMA (IDDS)" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "UNIDAD DE ATENCION PRIMARIA JAYACO" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAXIMO GOMEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN PEDRO Y SAN PABLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS QUEMADOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA NUESTRA SRA DE FATIMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SONADOR" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL VERDE" },
    ],
  },
  {
    name: "MONTE CRISTI",
    centers: [
      { name: "AYUNTAMIENTO CANA CHAPETÓN" },
      { name: "CENTRO COMUNAL LOMA DE CASTAÑUELAS" },
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "CLUB JUAN PABLO" },
      { name: "CLUB SAN PEDRO" },
      { name: "DOÑA ANTONIA (VER)" },
      { name: "IGLESIA SAN FERNÁNDO (KM 12)" },
      { name: "IGLESIA EVANGÉLICA MISIONERA AMPARO DEL CIELO (KM 13)" },
      { name: "IGLESIA KM. 14" },
      { name: "JOBO Y BOHÍO VIEJO" },
      { name: "LILO CAFÉ & RESTAURANT" },
      { name: "PARQUE VILLA VÁSQUEZ" },
      { name: "POLIDEPOIRTIVO DE GUAYUBIN" },
      { name: "POLIDEPORTIVO - CASTAÑUELAS" },
      { name: "POLIDEPORTIVO DE MANZANILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA CRUZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO DE LA PALOMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA CERRO GORDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA COPEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRAMADEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL AHOGADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL POCITO DE GUAYUBIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA HERMANAS MIRABAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CAPITALITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA GALLERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS FLORES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS BATEYES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CONUCOS MC" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ELISA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA SINDA" },
      { name: "LOS CONUCOS DE VILLA VASQUEZ" },
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA  5 Y 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA  9" },
      { name: "UNIDAD DE ATENCION PRIMARIA 3 Y 4" },
      { name: "UNIDAD DE ATENCION PRIMARIA 7 Y 8" },
      { name: "UNIDAD DE ATENCION PRIMARIA OVIEDO PEDERNALES" },
    ],
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "ARROYO HONDO" },
      { name: "CENTRO DE PRIMER NIVEL BOCA CANASTA" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CENTRO COMUNAL VILLA MAJEGA" },
      { name: "CENTRO DE SALUD MAXIMO GOMEZ" },
      { name: "CONSULTORIO MEDICO EL MANI" },
      { name: "CENTRO DE PRIMER NIVEL PAYA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA SOMBRERO" },
      { name: "CENTRO DE PRIMER NIVEL WILSON BELLO" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "ESCONDIDO I" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "GOBERNACION PROVINCIAL PERAVIA" },
      { name: "CENTRO DE PRIMER NIVEL DE ATENCIÓN HONDURAS" },
      { name: "HOSPITAL MUNICIPAL NIZAO" },
      { name: "HOSPITAL MUNICIPAL VILLA FUNDACION" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS CARRERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MATANZAS ARRIBA" },
      { name: "PIZARRETE I" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "SANTA ROSA 1" },
      { name: "SAONA I" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA MAJEGA I" },
      { name: "UNIDAD DE ATENCION PRIMARIA SALINAS" },
    ],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "AYUNTAMIENTO DE SOSUA" },
      { name: "CENTRO DE PRIMER NIVEL DOLORES DE LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL NAVAS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "HOSPITAL MUNICIPAL DE ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE GUANANICO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE LOS HIDALGOS" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "PLAY DEL SECTOR PADRE LAS CASAS" },
      { name: "HOSPITAL MUNICIPAL DE LUPERÓN" },
      { name: "LIGA DEL ATLÁNTICO" },
    ],
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "CENTRO COMUNAL (LOS CORRALES)" },
      { name: "CENTRO COMUNAL LOS COCOS" },
      { name: "CENTRO COMUNAL RANCHO ESPAÑOL" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO DEL LIMÓN" },
      { name: "CLUB DE MADRE LOS PUENTES" },
      { name: "CRUCE DE HONDURAS (EDIFICIO BLANCO)" },
      { name: "CRUCE DE TEZÓN" },
      { name: "FABRICA DE HIELO (PASCUALA)" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "IGLESIA CATÓLICA (RINCON)" },
      { name: "IGLESIA CATOLICA LAS GARITAS" },
      { name: "JUNTA DE VECINOS DANIEL WILMORE" },
      { name: "JUNTA DE VECINOS JUANA VICENTA" },
      { name: "LOS CACAOS" },
      { name: "LOS ROBALOS (CENTRO COMUNAN)" },
      { name: "PARQUE (LA GLORIETA)" },
      { name: "POLIDEPORTIVO MUNICIPAL LAS TERRENAS" },
      { name: "SINDICATO DE LA PORTUARIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MAJAGUA" },
      { name: "VILLA CLARA " },
    ],
  },
  {
    name: "SAN CRISTÓBAL",
    centers: [
      { name: "ASOCIACION DE INDUSTRIA" },
      { name: "CARCEL NAJAYO" },
      { name: "CENTRO DE DIAGNOSTICO CEDISA" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "COMEDOR ECONOMICO LAVA PIE" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO MAMEY" },
      { name: "CENTRO DE PRIMER NIVEL CONANI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAJUILITO" },
      { name: "CENTRO DE PRIMER NIVEL EL CARRIL" },
      { name: "CENTRO DE PRIMER NIVEL EL POMIER" },
      { name: "CENTRO DE PRIMER NIVEL ESTEBANIA BORINQUEN" },
      { name: "CENTRO DE PRIMER NIVEL GUANANITO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN BARON" },
      { name: "CENTRO DE PRIMER NIVEL KM 59" },
      { name: "CENTRO DE PRIMER NIVEL LA CANELA" },
      { name: "CENTRO DE PRIMER NIVEL LA PARED" },
      { name: "CENTRO DE PRIMER NIVEL LA PISCINA" },
      { name: "CENTRO DE PRIMER NIVEL LA PLENA" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOTAOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS MOLINAS" },
      { name: "CENTRO DE PRIMER NIVEL LOS PARCELEROS" },
      { name: "CENTRO DE PRIMER NIVEL LUCIOLO BAEZ" },
      { name: "CENTRO DE PRIMER NIVEL MAL PAEZ" },
      { name: "CENTRO DE PRIMER NIVEL MERCEDITO VIZCAINO CABRERA (DUVEAUX)" },
      { name: "CENTRO DE PRIMER NIVEL MODESTO OGANDO (LAS FLORES)" },
      { name: "CENTRO DE PRIMER NIVEL NAJAYO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL NORMAN RUIZ" },
      { name: "CENTRO DE PRIMER NIVEL PUEBLO NUEVO" },
      { name: "CENTRO DE PRIMER NIVEL PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL QUITA SUEÑO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "CENTRO DE PRIMER NIVEL SEMANA SANTA" },
      { name: "CENTRO DE PRIMER NIVEL V CENTENARIO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CENTRO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA FUNDACION" },
      { name: "CENTRO DE PRIMER NIVEL VILLEGAS" },
      { name: "CENTRO DE PRIMER NIVEL YAGUATE (RAMONA SANTANA)" },
      { name: "DISPENSARIO NTRA. SRA. DE LA PAZ" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN CRISTOBAL" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOSPITAL M. VILLA ALTAGRACIA" },
      { name: "HOSPITAL M. YAGUATE" },
      { name: "HOSPITAL MUNICIPAL HAINA" },
      { name: "HOSPITAL RAFAEL J. MAÑÓN" },
      { name: "HOSPITAL TOMASINA VALDEZ" },
      { name: "HOSPITAL CAMBITA GARABITO" },
      { name: "HOSPITAL CAMBITA PUEBLO" },
      { name: "MULTIUSO PALENQUE" },
      { name: "ONG ORDEN DE MALTA" },
      { name: "PARQUE RADHAMES" },
      { name: "POLICLINICA NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "POLIDEPORTIVO NIGUA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANETA " },
      { name: "VILLA MERCEDES" },
      { name: "DISPENSARIO LOS AMERICANOS" },
    ],
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO CAÑA" },
      { name: "CENTRO DE SALUD  LA CIENEGA" },
      { name: "CENTRO DE SALUD  LAS FLORES" },
      { name: "CENTRO DE SALUD  LOS MARTINEZ" },
      { name: "CENTRO DE SALUD  MAHOMA" },
      { name: "CENTRO DE SALUD  OJO DE AGUA" },
      { name: "CENTRO DE SALUD  SAN ANTONIO" },
      { name: "CENTRO DE SALUD  SAN LUIS " },
      { name: "CENTRO DE SALUD BANILEJO" },
      { name: "CENTRO DE SALUD EL PINAR" },
      { name: "CENTRO DE SALUD LA HORMA" },
      { name: "CENTRO DE SALUD LIMONAL" },
      { name: "CENTRO DE SALUD LOS COROZOS" },
      { name: "CENTRO DE SALUD NARANJAL" },
      { name: "CENTRO DE SALUD SABANA LARGA ABAJO" },
      { name: "CENTRO DE SALUD SAN RAFAEL" },
      { name: "HOSPITAL GUARIONEX ALCANTARA" },
      { name: "CENTRO DE PRIMER NIVEL NIZAO " },
    ],
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "AYUNTAMIENTO LAS MATAS" },
      { name: "CENTRO DE PRIMER NIVEL VALLEJUELO" },
      { name: "EL CASINO SJ" },
      { name: "HOSPITAL ALEJANDRO CABRAL" },
      { name: "IGLESIA ESPIRITU SANTOS" },
      { name: "PARQUE SÁNCHEZ" },
      { name: "SALÓN DE CONFERENCIA DIRECCION PROVINCIAL DE SALUD SAN JUAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOHECHIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BUENA VISTA DEL YAQUE" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAPULIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRUMBADERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL NARANJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JINOVA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JORGILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUAN HERRERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA ESTANCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA NAVAJA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CARTONES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS GRINGOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MATAYAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA POZO HONDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CARMEN" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ESPERANZA" },
    ],
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "CLINICA DOCTOR DE LEON" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DE PERIODISTAS" },
      { name: "DEFENSA CIVIL" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE SAN PEDRO DE MACORIS" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "IGLESIA ASAMBLEA DE DIOS JUAN DOLIÓ" },
      { name: "IGLESIA CATOLICA LOS CONUCOS" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "IGLESIA DE DIOS GUAYACANES" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "MONTE DE SION" },
      { name: "MULTIUSO - EXTENSION UASD" },
      { name: "AYUNTAMIENTO MUNICIPAL SAN PEDRO" },
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
    ],
  },
  {
    name: "SÁNCHEZ RAMIREZ",
    centers: [
      { name: "AYUNTAMIENTO DE QUITA SUEÑO" },
      { name: "BAJO TECHO" },
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER LA CUEVA" },
      { name: "CENTRO DE PRIMER NIVEL CABALLERO" },
      { name: "CENTRO DE PRIMER NIVEL CASTILLO" },
      { name: "CENTRO DE PRIMER NIVEL CHACUEY" },
      { name: "CENTRO DE PRIMER NIVEL COMEDERO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL CRUZ DE ANGELINA" },
      { name: "CENTRO DE PRIMER NIVEL DUEY" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONCITO" },
      { name: "CENTRO DE PRIMER NIVEL EL PESCOZON" },
      { name: "CENTRO DE PRIMER NIVEL HERNANDO ALONZO" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA" },
      { name: "CENTRO DE PRIMER NIVEL LA BIJA" },
      { name: "CENTRO DE PRIMER NIVEL LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL LAS CANAS" },
      { name: "CENTRO DE PRIMER NIVEL SABALLO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA PRIETA" },
      { name: "CENTRO DE PRIMER NIVEL ZAMBRANA" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "CLUB DE AMAS DE CASA PEDRO FRANCISCO BONO" },
      { name: "CLUB DEL COLEGIO MEDICO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA LA MATA" },
      { name: "DEFENZA CIVIL" },
      { name: "DISTRITO ESCOLAR 16-01" },
      { name: "GOBERNACION PROVINCIAL COTUI" },
      { name: "HOSPITAL DE VILLA LA MATA" },
      { name: "HOSPITAL DR. RAMON BAEZ" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "LOS COROZOS" },
      { name: "PARQUE DUARTE" },
      { name: "CENTRO DE DIAGNOSTICO LA MATA" },
      { name: "CENTRO DE PRIMER NIVEL PIÑA VIAJA" },
      { name: "CENTRO DE PRIMER NIVEL PLATANAL" },
      { name: "CLUB DE LEONES FANTINO " },
    ],
  },
  {
    name: "SANTIAGO",
    centers: [
      { name: "CENTRO DE LA CIUDAD (PARQUE)" },
      { name: "CENTRO DE PRIMER NIVEL YAGUITA DEL PASTOR" },
      { name: "CLÍNICA COROMINAS " },
      { name: "CLÍNICA UNIÓN MÉDICA DEL NORTE" },
      { name: "CLUB HATO DEL YAQUE" },
      { name: "CLUB VILLA OLGA" },
      { name: "CORAASAN" },
      { name: "CENTRO DE PRIMER NIVEL BELLA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL BN LA HERRADURA" },
      { name: "CENTRO DE PRIMER NIVEL BUEN PASTOR" },
      { name: "CENTRO DE PRIMER NIVEL EL RUBIO" },
      { name: "CENTRO DE PRIMER NIVEL LA CANELA " },
      { name: "CENTRO DE PRIMER NIVELLA OTRA BANDA " },
      { name: "CENTRO DE PRIMER NIVEL LOS GUANDULES" },
      { name: "CENTRO DE PRIMER NIVEL VILLA BAO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA TABACALERA" },
      { name: "ESCUELA COLORADO" },
      { name: "GRAN TEATRO DEL CIBAO" },
      { name: "HOMS" },
      { name: "HOSPITAL CABRAL Y BAEZ " },
      { name: "HOSPITAL IRENE FERNÁNDEZ JÁNICO" },
      { name: "HOSPITAL LUIS ESPAILLAT SABANA IGLESIA" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE" },
      { name: "LICEO EUGENIO DE JESUS MARCANO (TAMBORIL)" },
      { name: "PUCMM - SANTIAGO" },
      { name: "DIRECCIÓN REGIONAL DE SALUD" },
      { name: "UASD BARRANQUITA" },
      { name: "VILLA TABACALERA" },
      { name: "INTELLISYS" },
    ],
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [{ name: "AYUNTAMIENTO MUNICIPAL MONCIÓN" }],
  },
  {
    name: "SANTO DOMINGO",
    centers: [
      { name: "CODECOD (CENTRO DE DESAROLLO)" },
      { name: "GACEBO DEL PARQUE MONTE ADENTRO" },
      { name: "HOSPITAL MUNICIPIAL DE BOCA CHICA" },
      { name: "MULTIUSO PANTOJA" },
      { name: "ARMADA DOMINICANA" },
      { name: "AYUNTAMIENTO SANTO DOMINGO ESTE" },
      { name: "CLUB CALERO" },
      { name: "CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "CLUB EL ROSAL" },
      { name: "CLUB PLAN SOCIAL DE LOS BILLETEROS" },
      { name: "CENTRO DE PRIMER NIVEL DE ATENCIÓN VIETNAM" },
      { name: "CRUZ ROJA DOMINICANA FILIAR LA CALETA " },
      { name: "DIRECCION AREA DE SALUD II" },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "EL DIQUE" },
      { name: "ESCUELA PRIMARIA CELINA PELLIER" },
      { name: "ESTACION BOMBEROS CIVILES NO.2" },
      { name: "HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "HOSPITAL ELVIRA ECHAVARIA" },
      { name: "HOSPITAL MUNICIPAL RALMA" },
      { name: "INTITUTO TECNICO SUPERIOR COMUNITARIO SAN LUIS" },
      { name: "JUMBO MEGACENTRO" },
      { name: "JUMBO SAN ISIDRO" },
      { name: "MULTIUSO DE INVIVIENDA" },
      { name: "MULTIUSO TAMARINDO" },
      { name: "MULTIUSO URBANIZACION HAMARAP" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "PARRROQUIA SANTO TOMAS VILLA NUEVA" },
      { name: "POLIDEPORTIVO GUERRA" },
      { name: "FUERZA AEREA DOMINICANA" },
      { name: "COSALUP" },
      { name: "PARQUE DEL ESTE" },
      { name: "PLAN  DE ASISTENCIA SOCIAL DE LA PRESIDENCIA" },
      { name: "DISTRITO EDUCATIVO 10-01" },
      { name: "ESCUELA LEONCIO MANZUETA" },
      { name: "ESCUELA LEONCIO MANZUETA" },
      { name: "ESCUELA PARAISO VILLA MELLA" },
      { name: "ESCUELA SAN FELIPE" },
      { name: "HOGAR DE DÍA" },
      { name: "HOSPITAL NEY ARIAS LORA" },
      { name: "MAMA TINGO" },
      { name: "MULTIUSO LA VICTORIA" },
      { name: "MULTIUSO SABANA PERDIDA" },
      { name: "PARROQUIA SANTA CRUZ" },
      { name: "VESTIR DE HOY" },
      { name: "ESCUELA HARAS NACIONALES " },
      { name: "MULTIUSO DE GUARICANO " },
      { name: "CENTRO COMUNAL LAS PALMAS" },
      { name: "CENTRO DE PRIMER NIVEL COSALUD" },
      { name: "MULTIUSOS HAINAMOSA" },
      { name: "CENTRO DE SALUD LA HORA DE DIOS" },
      { name: "CLUB BANCO DE RESERVAS" },
      { name: "FUNDACION PEDRO MARTINEZ" },
      { name: "HOSPITAL DR MARCELINO VELEZ" },
      { name: "HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "IGLESIA SAN PEDRO NOLASCO" },
      { name: "MULTIUSO EL ABANICO" },
      {
        name:
          "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CENTRO DE PRIMER NIVEL DIAZ PIÑEYRO",
      },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "CENTRO DE PRIMER NIVEL COMUNAL EL CAFÉ/INFOTEP" },
      { name: "CENTRO DE PRIMER NIVELA DE LA MANO CON JESUS" },
      { name: "ESCUELA KILOMETRO 13/ ESCUELA NUEVA " },
      { name: "MULTIUSO SOCORRO MUTUO" },
      { name: "PARROQUIA ESPIRITU SANTO" },
      { name: "PARROQUIA SAGRADO CORAZON DE JESUS " },
      { name: "CENTRO DE PRIMER NIVELA ZONA F" },
      { name: "ESCUELA CONRADO MIESES " },
      { name: "ESCUELA REPUBLICA DE JAMAICA " },
      { name: "IGLESIA DE DIOS EN CRISTO LA SENDA. LAS MERCEDEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA GUAYIGA" },
      { name: "AYUTAMIENTO DE PEDRO BRAND" },
    ],
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "CLINICA DR. MONTESINOS" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "CLUB QUISQUELLA" },
      { name: "CLUB ROTARIO" },
      { name: "COLEGIO MEDICO" },
      { name: "HOSPITAL DE ESPERANZA DR. JOSÉ FAUSTO OVALLES" },
      { name: "PARROQUIA MARÍA AUXILIADORA MAO" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
