const centros3 = [
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "CRUZ ROFA FILIAL"},
      { name: "FUNDACIÓN CORREA VALDEZ"},
      { name: "CENTRO COMUNITARIO LO TANQUESITO"},
      { name: "MULTIUSO SECTOR LA CORPORANEA"},
      { name: "MULTIUSO LOS FRAILES"},
    ],
},
  {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "CLUB DE LOS BILLETEROS"},
      { name: "MIREDEC TURISMO"},
      { name: "MIREDEC TRANSPORTE PUBLICO"},
      { name: "MIREDEC DEPORTE, PERIODISTA"},
      { name: "CLUB EL ROSAL"},
      { name: "AREA II"},
      { name: "JUMBO"},
      { name: "PLAY LA ZAFRA"},
      { name: "ESTACION BOMBEROS CIVIL"},
      { name: "PARROQUIA SAN AGUSTIN"},
      { name: "MEGACENTRO"},
      { name: "IGLESIA METODISTA LIBRE"},
    ],
  },
  {
    name: "SANTO DOMINGO NORTE (DAS-III)",
    centers: [
      { name: "CLUB MULTIUSO EL CROM"},
      { name: "MULTIUSO LA VICTORIA /IGLESIA PARQUE LA VICTORIA"},
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "MULTIUSO SANTA CRUZ IGLESIA CATOLICA"},
      { name: "CLUB FATIMA OSCAR SANTANA"},
      { name: "CLUB MARIA AUXILIADORA"},
      { name: "SAMBIL"},
      { name: "FUNDACION ESCOBA"},
      { name: "LOS BOMBERITOS"},
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-V)",
    centers: [
      { name: "AGORA MALL"},
      { name: "CENTRO OLIMPICO"},
      { name: "HONDURAS"},
      { name: "HOTEL JARAGUA"},
      { name: "PLAZA LAMA"},
      { name: "SIRENA"},
    ]
  },
  {
    name: "DISTRITO NACIONAL( DAS-VI)",
    centers: [
      { name: "PLAZA DUARTE (CARREFOUR)"},
      { name: "FUSADI"},
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO"},
      { name: "HOSPITAL JACINTO MAÑON"},
    ],
},
  {
    name: "SANTO DOMINGO OESTE (DAS VII)",
    centers: [
      { name: "CPN COSALUP"},
      { name: "CPNA DIAZ PIÑEYRO"},
      { name: "MULTIUSO EL ABANICO"},
      { name: "CPNA LAS CAOBAS"},
      { name: "LABORATORIOS GASSÓ-GASSÓ"},
    ],
},
  {
    name: "SANTO DOMINGO OESTE (DAS VIII)",
    centers: [
      { name: "CENTRO MEDICO METROPOLITANO"},
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ"},
      { name: "HOSPITAL ALCARRIZOS II"},
      { name: "CUERPO DE BOMBEROS LOS ALCARRIZOS"},
      { name: "UNIDAD MOVIL"},
      { name: "MULTIUSO  PANTOJA"},
      { name: "CARMEN RENATA I"},
      { name: "CARMEN RENATA III"},
      { name: "HOSPITAL DR. RODOLFO DE LA CRUZ LORA"},
    ]
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "EL CASINO SJ"},
      { name: "CORBANO SUR 1"},
      { name: "CORBANO SUR 2"},
      { name: "CORBANO SUR 3"},
      { name: "CORBANO NORTE"},
      { name: "CODIA"},
      { name: "CLUD DIEGO DE VELAZQUEZ"},
      { name: "CPN VILLA LIBERACION"},
      { name: "P ARQUE SANCHEZ"},
      { name: "CPN QUIJADA QUIETA"},
      { name: "GUACHUPITA"},
      { name: "SABANETA"},
      { name: "LAS MAGUANA"},
      { name: "HATO NUEVO"},
      { name: "LA JAGUA"},
      { name: "CARD6N"},
      { name: "CPN HATO DEL PADRE"},
      { name: "SALON DE CONFERENCIA DPS SAN. JUAN."},
      { name: "CCPN SABANA ALTA"},
      { name: "CPN EL ROSARIO"},
      { name: "CPN HIGUERITO"},
      { name: "CPN GRUANITO"},
      { name: "CPN LOS BANCOS"},
      { name: "CPN LAS ZANJAS"},
      { name: "CPN EL BATEY"},
      { name: "CPN EL CACHEO"},
      { name: "CPN LAS CHARCAS DE GARABITO"},
      { name: "CPN MOGOLKIN"},
      { name: "CRY BAN-ANC A"},
      { name: "CPN LAS CHARCAS N'IARIA NOVA"},
      { name: "CPN PUNTA CANA"},
      { name: "CPN HATO DEL PADRE"},
      { name: "CPN CRISTO REY"},
      { name: "CPN PERPETUO SOCORRO"},
      { name: "CPN MIRADOR NORTE"},
      { name: "CPN PEDRO CORTO"},
      { name: "CLUD COME MORN"},
      { name: "CPN LOS TRANSFORMADORES I"},
      { name: "CPN LOS TRANSFORMADORES II"},
      { name: "AYUNTAMIENTO. L.M.F"},
      { name: "CPN LOS CARTONES"},
      { name: "HOSPITAL FEDERICO A. AYBAR"},
      { name: "HOGAR SANTA LUCIA"},
      { name: "CPN   VALLA CARMEN"},
      { name: "CPN LOS GRINGOS"},
      { name: "CPIS : LA ESTANCIA"},
      { name: "CPN ESPERANZA"},
      { name: "CPN EL HOYO"},
      { name: "CPN E1 NARANJO"},
      { name: "CPN  LOS COPYES"},
      { name: "CPN YABONICO"},
      { name: "CPN MATAYAYA"},
      { name: "CPN CARRERAS DE YEGUAS"},
      { name: "CPN POZO HONDO"},
      { name: "CPN LOS JOBOS"},
      { name: "DERTUMBADERO"},
      { name: "LOS BOMBEROS"},
      { name: "BATISTA"},
      { name: "EL ROVITO"},
      { name: "LA RANCHA"},
      { name: "LA NAVAJA"},
      { name: "LA COLONIA"},
      { name: "VAILECITO"},
      { name: "CPN JUAN HERRERA"},
      { name: "CPN JINOVA"},
      { name: "CPN BOHECHIO"},
      { name: "LOS MONTACITOS"},
      { name: "CPN ARROYO CANO"},
      { name: "CPN E1 COCO"},
      { name: "CPN LA GUAMA"},
      { name: "CPIS CAPULIN"},
      { name: "JORGILLO"},
      { name: "CPN VALLEJUELO"},
      { name: "RIO ARRIBA"},
      { name: "PALMA CANA"},
    ],
},
  {
    name: "SAMANA",
    centers: [
      { name: "POLIDEPORTIVO"},
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX"},
      { name: "CENTRO TECNOLOGICO DEL LIMON"},
      { name: "CRUCE DE TESON"},
      { name: "CRUCE DE HONDURAS (EDIFICIO BLANCO)"},
      { name: "POLIDEPORTIVO"},
      { name: "AYUNTAMIENTO LAS GALERAS"},
      { name: "SINDICATO DE PORTUARIA"},
      { name: "IGLESIA CATOLICA LAS GARITAS"},
      { name: "CENTRO COMUNAL EL COCO"},
    ],
},
  {
    name: "MARIA TRINIDAD SANCHEZ",
    centers: [
      { name: "CPN PAYITA"},
      { name: "POLIDEPORTIVO CABRERA"},
      { name: "CASA DE FORMACION SAGRADA FAMILIA"},
      { name: "CPN EL PAPAYO"},
      { name: "AYUNTAMIENTO DEL POZO"},
      { name: "DPS-MARIA TRINIDAD SANCHEZ (POBLACION PRIORIZADA)"},
      { name: "UASD NUEVA"},
      { name: "HOSP. DR.CARLOS A. ZAFRA"},
      { name: "CPN. MATANCITA"},
      { name: "CPN LOS YAYALES"},
      { name: "CPN ARROYO AL MEDIO"},
      { name: "CPN LAS GORDAS"},
      { name: "CENTRO COMUNITARIO MATA BONITA"},
      { name: "AYUNTAMIENTO DE NAGUA"},
      { name: "POLIDEPORTIVO RIO SAN JUAN"},
    ],
},
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "AEROPUERTO INTERNACIONAL GREGORIO LUPERON"},
    ],
},
  {
    name: "LA ROMANA",
    centers: [
      { name: "HOSPITAL FRANCISCO A. GONZALVO"},
      { name: "DPS -LA ROMANA PFV."},
      { name: "HOSPITAL ARISTIDES FIALLO CABRAL"},
    ],
},
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO"},
      { name: "UNAP#3 Y #4"},
      { name: "UNAP#5 Y #6"},
      { name: "UNAP#7 Y #8"},
      { name: "UNAP#9"},
    ],
},
  {
    name: "BARAHONA",
    centers: [
      { name: "HOTELES DE BARAHONA"},
      { name: "FARMACIAS DE BARAHONA."},
      { name: "COLEGIO MÉDICO"},
      { name: "DEFENSA CIVIL"},
    ],
},
  {
    name: "SANTIAGO (DISTRITO-I)",
    centers: [
      { name: "CLUB MADRES LA UNION CIENFIEGO"},
      { name: "CLUB MAMBUICHE"},
      { name: "CLUB NOEL"},
      { name: "ENS. LIBETAD (GUG)"},
      { name: "PARQUE CENTRAL"},
      { name: "TECHADO LOS CIENFUEGOS"},
      { name: "TECHADO LOS CIRUELITOS"},
      { name: "TIPIQUITO LOS COCOS"},
    ],
},
  {
    name: "SANTIAGO (II)",
    centers: [
      { name: "CLUB BARACOA"},
      { name: "HOSP. BELLA VISTA"},
      { name: "HOSP. HATO DEL YAQUE"},
    ],
},
  {
    name: "SANTIAGO (III)",
    centers: [
      { name: "HEMMI"},
      { name: "CPN PALO AMARILLO"},
      { name: "EL EMBRUJO"},
    ],
},
  {
    name: "LA VEGA",
    centers: [
      { name: "EL EMBRUJO"},
    ],
},
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO TAMAYO"},
      { name: "DPS BAHORUCO"},
      { name: "CENTRO COMUNAL"},
      { name: "MOVIL GALVAN"},
      { name: "MOVIL NEIBA 1"},
      { name: "MOVIL NEIBA 2"},
    ],
},
  {
    name: "MONTECRISTI",
    centers: [
      { name: "POLIDEPORTIVO MANZANILLO"},
      { name: "UNAP SANTA MARÍA"},
      { name: "UNAP COPEY DE MANZANILLO"},
      { name: "UNAP ALTOS DE LA PALOMA"},
      { name: "UNAP CARBONERA"},
      { name: "CLUB JUAN PABLO DUARTE"},
      { name: "RESTAURANTE LILO"},
      { name: "CLUB SAN PEDRO"},
      { name: "UNAP LAS FLORES"},
      { name: "UNAP LOS MAESTROS"},
      { name: "UNAP HERMANAS MIRABAL"},
      { name: "UNAP SANTA BARBARA"},
      { name: "UNAP LOS CONUCOS MC"},
      { name: "UNAP BATEY MADRE"},
      { name: "IGLESIA KM13"},
      { name: "IGLESIA KM 14"},
    ],
},
  {
    name: "SANTIAGO RODRIGUEZ",
    centers: [
      { name: "DPS"},
    ],
},
  {
    name: "SAN CRISTOBAL",
    centers: [
      { name: "DPS"},
      { name: "HOP. RAFAEL J. MAÑÓN"},
      { name: "NIGUA"},
      { name: "PALENQUE"},
    ],
},
  {
    name: "SAN JOSE DE OCOA",
    centers: [
      { name: ""},
      { name: "CENTRO DE DIAGNOSTICO BELLA VISTA"},
    ],
},
  {
    name:"ESPALLAT",
    centers: [
      { name: "CANCHA MUNICIPAL"},
      { name: "CPN BATEY GINEBRA"},
      { name: "CPN BOCA FERREA"},
      { name: "CPN BONAGUA"},
      { name: "CPN CANCA LA REYNA"},
      { name: "CPN CEIBA DE MADERA"},
      { name: "CPN CUERO DURO"},
      { name: "CPN DE GUAUCI"},
      { name: "CPN EL CAIMITO"},
      { name: "CPN EL COROZO"},
      { name: "CPN EL HIGUERITO"},
      { name: "CPN JUAN LOPEZ"},
      { name: "CPN LA ERMITA"},
      { name: "CPN LA GUAMA"},
      { name: "CPN LAS GUAZUMAS"},
      { name: "CPN LA ISLETA"},
      { name: "CPN LA MANZANA"},
      { name: "CPN LA YAGUA"},
      { name: "CPN LAS FLORES"},
      { name: "CPN LAS LAGUNAS"},
      { name: "CPN LOS LOPEZ"},
      { name: "CPN LOS PANCHOS"},
      { name: "CPN MANUEL RODRIGUEZ"},
      { name: "CPN MONTE DE LA JAGUA"},
      { name: "CPN NUEVO PUERTO RICO"},
      { name: "CPN ORTEGA"},
      { name: "CPN QUEBRADA HONDA"},
      { name: "CPN REPARADERO"},
      { name: "CPN SAL SI PUEDES"},
      { name: "CPN SAN VICTOR"},
      { name: "CPN SANTA ROSA"},
      { name: "CPN TIERRA DURA"},
      { name: "CPN VERAGUA"},
      { name: "CPN VIEJO PUERTO RICO"},
      { name: "CPN VILLA CAFETALERA"},
      { name: "CPN VILLA PROGRESO"},
      { name: "CPN ZAFARRAYA"},
      { name: "DISTRITO 06-01 JOSE CONTRERAS"},
      { name: "CPN  LOS  BRAZOS"},
      { name: "CPN LOS PUENTES"},
      { name: "HOSPITAL JOSÉ CONTRERAS"},
      { name: "ESCUELA LOS RONCONES"},
      { name: "SALON DON BOSCO KM1"},
      { name: "CPN PALMA  HERRADA"},
      { name: "CLUB RECREATIVO"},
      { name: "LA CANCHA MUNICIPAL"},
    ]
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CATEDRAL SANTA ANA - JUAN XXIII" },
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "BARRIO DAVID" },
      { name: "CENTRO MÉDICO DR. OVALLE" },
      { name: "CENTRO MÉDICO SIGLO 21." },
      { name: "LA GUAMA" },
      { name: "ENCAMADOS" },
      { name: "MULTIUSO " },
      { name: "MULTIUSO VILLA RIVAS" },
      { name: "CPN LA YAGUIZA" },
      { name: "ENCARGADOS LA YAGUIZA" },
    ],
},
  {
    name: "DAJABON",
    centers: [
      { name: "CASA DE LA CULTURA" },
      { name: "DPS-DAJABON" },
    ],
},
  {
    name: "PERAVIA",
    centers: [
      { name: "ROSA NOVA" },
      { name: "SANTANA ARRIBA" },
      { name: "BUENAS NUEVAS" },
      { name: "PIZARRET I" },
      { name: "PIZARRETE II" },
      { name: "LAS BARIAS" },
      { name: "EL CARRETON" },
      { name: "DON GREGORIO I" },
      { name: "VALDESIA" },
      { name: "RIO ARRIBA" },
      { name: "PAYA ARRIBA" },
      { name: "PAYA ABAJO" },
      { name: "MATA GORDA" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "ESCONDIDO I" },
      { name: "ESCONDIDO II" },
      { name: "EL LIMONAL" },
      { name: "VILLA GUERA" },
      { name: "VILLA DAVID" },
      { name: "SAONA I" },
      { name: "SAONA II" },
      { name: "EL MANI" },
      { name: "LOS YAGUARIZOS" },
      { name: "MAXIMO GOMEZ" },
      { name: "VILLA SOMBBRERO 1" },
      { name: "VILLA SOMBRERO 2" },
      { name: "HONDURAS" },
      { name: "LAS TABLAS" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "LAS CARRERAS" },
      { name: "SABANA BUEY" },
      { name: "QUIJA QUIETA" },
      { name: "MATANZAS ARRIBA" },
      { name: "MATANZAS ABAJO" },
      { name: "SALINAS" },
      { name: "LOS TUMBAOS" },
      { name: "ARROYO HONDO" },
      { name: "LAS CALDERAS" },
      { name: "EL LLANO" },
      { name: "SANTA ROSA 1" },
      { name: "SANTA ROSA 2" },
      { name: "SANTA ROSA 3" },
      { name: "BOCA CANASTA 1" },
      { name: "BOCA CANASTA 2" },
      { name: "24 DE ABRIL" },
      { name: "SANTA CRUZ" },
      { name: "PUEBLO NUEVO" },
      { name: "VILLA MEJAGA I" },
      { name: "VILLA MAJEGA II" },
    ],
},
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "HOTEL HYATT ZIVA" },
      { name: "HOTEL CATOLONIA" },
      { name: "HOTEL GRAND BAVARO PRINCESS" },
      { name: "HOTEL MELIA" },
      { name: "HOTEL RIU" },
      { name: "HOTEL BAHIA PRINCES" },
      { name: "HOTEL PALLADIUM" },
      { name: "HOTEL BAVARO" },
      { name: "HOTEL NIOKELODEON" },
      { name: "HOTEL LIVE AGUA" },
      { name: "HOTEL ROYALTON" },
      { name: "HOTEL HARO ROCK" },
      { name: "HOTEL ONYX" },
      { name: "HOTEL LOPESAN" },
      { name: "HOTEL MAJESTIC" },
      { name: "HOTEL IBEROESTAR" },
      { name: "HOTEL DREAMS MACAO" },
      { name: "HOTEL SECRET ROYAL" },
    ],
},
  {
    name: "AZUA",
    centers: [
      { name: "HOSPITAL R. TAIWAN" },
      { name: "PRADO Y COLONIA (CPN)." },
      { name: "CUCHILLA" },
      { name: "BOMBITA" },
      { name: "PARCELERO" },
      { name: "FINCA 6" },
      { name: "LOS JOVILLOS" },
      { name: "V. CORAZON DE JESUS" },
      { name: "ANSONIA" },
      { name: "LAS BARIAS" },
      { name: "BARRERA" },
      { name: "LOS NEGROS" },
      { name: "SABANA YEGUA" },
      { name: "MOD. SAN FCO KM-11" },
      { name: "PROYECTO-4" },
      { name: "PROYECTO-2-C" },
      { name: "GANADERO" },
      { name: "YAYA ABAJO" },
      { name: "YAYA ARRIBA" },
      { name: "VIAJAMA" },
      { name: "C/R MAGUEYAL" },
      { name: "C/R HATO NUEVO" },
      { name: "C/R VILLARPANDO" },
      { name: "C/R LAS CHARCAS" },
      { name: "C/R HATILLO" },
      { name: "C/ PARMAL DE OCOA" },
      { name: "C/R ESTEBANIA" },
      { name: "UNAP PUEBLO VIEJO" },
      { name: "C/ R EL ROSARIO" },
      { name: "LICEO GUAYACANAL" },
      { name: "UNAP EL HIGUERO" },
      { name: "UNAP LOS JOBOS -2" },
      { name: "UNAP LOS JOBOS -1" },
      { name: "MAJAGUAL" },
      { name: "C/R TABARA ARRIBA" },
      { name: "C/R TABARA ABAJO" },
      { name: "C/R SAJANOA" },
      { name: "C/R LOS TOROS" },
      { name: "C/R AMIAMA GOMEZ" },
      { name: "HOSP. MUNICIPAL PLC" },
      { name: "MONTE BONITO" },
      { name: "C/R LA SIEMBRA" },
      { name: "C/R LAS LAGUNAS" },
      { name: "UNAP SANTA ANA" },
      { name: "UNAP VILLA OCOA" },
      { name: "UNAP CAÑITA -A" },
      { name: "UNAP LOS MONTES FRIOS" },
      { name: "HOSPITAL M. GUAYABAL" },
      { name: "PUESTO DE GOBERNACION" },
    ],
},
  {
    name: "EL SEIBO",
    centers: [
    { name: "BOMBERO" }, 
  ],
},
  {
    name: "ELIAS PIÑA",
    centers: [
      { name: "CENTRO DE COMBATE" },
      { name: "CPN GUANITO" },
      { name: "CPN GUAYABO" },
      { name: "CPN HATO VIEJO" },
      { name: "CPN JUAN SANTIAGO" },
      { name: "CPN LA GALLERA" },
      { name: "CPN LAS DELICIAS" },
      { name: "CPN LAS PALMAS" },
      { name: "CPN MACASIAS" },
      { name: "CPN PEDRO SANTANA" },
      { name: "CPN PINZON" },
      { name: "CPN POTROSO" },
      { name: "CPN RANCHO DE LA GUARDIA" },
      { name: "CPN RINCONCITOS" },
      { name: "CPN ROSA LA PIEDRA" },
      { name: "CPN SABANA CRUZ" },
      { name: "CPN SABANA HIGUERO" },
      { name: "CPN SABANA LARGA" },
      { name: "CPN SABANA MULA" },
      { name: "CTC" },
      { name: "CTC" },
      { name: "CTC" },
      { name: "HOGAR DE ANCIANO SAN FRANSCISCO DE ASIS" },
      { name: "HOGAR DE ANCIANO SAN ISIDRO LABRADOR" },
      { name: "HOGAR DE ANCIANOS SANTA TERESA" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL ROSA DUARTE" },
      { name: "POLIDEPORTIVO" },
      { name: "POLIDEPORTIVO" },
    ],
},
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "14 BATALLON DE INFANTERIA" },
    ],
},
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "LICEO EMILIANO TEJERA" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "LICEO JULIAN JAVIER" },
      { name: "ESCUELA FEDERICO AUGUSTO GONZALEZ" },
    ],
},
  {
    name: "MONTE PLATA",
    centers: [
      { name: "HOSPITAL MUNICIPAL" },
      { name: "HOSPITAL MUNICIPAL" },
      { name: "GONZALO" },
    ],
},
  {
    name: "SANCHEZ RAMIREZ",
    centers: [
      { name: "CENTRO DIAGNOSTICO FANTINO"},
      { name: "CENTRO DIAGNOSTICO COTUI"},
      { name: "CPN CRUZ DE ANGELINA"},
      { name: "CPN LA LIBERTAD"},
      { name: "CPN COMENDADOR ARRIBA"},
      { name: "CPN QUITA SUEÑO"},
      { name: "CPN ZAMBRANA"},
      { name: "HOSPITAL DE CEVICOS"},
      { name: "HOSPITAL DE FANTINO"},
      { name: "HOSPITAL DR. RAMON BÁEZ"},
      { name: "HOSPITAL LA MATA"},
      { name: "LA ALTAGRACIA DE COTUI"},
      { name: "LA CUEVA"},
      { name: "DPS"},
    ],
},
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL MUNICIPAL EL VALLE"},
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO"},
      { name: "UNAP BARRIO LINDO"},
      { name: "UNAP GUALEY"},
      { name: "UNAP GUAYABO DULCE"},
      { name: "UNAP LA JAVILLA"},
      { name: "UNAP LAS CAÑITAS"},
      { name: "UNAP LAS GUAMAS"},
      { name: "UNAP LAS YAGUITAS"},
      { name: "UNAP LOS HATILLOS"},
      { name: "UNAP MANCHADO"},
      { name: "UNAP PUERTO RICO"},
      { name: "UNAP PUNTA DE GARZA"},
      { name: "UNAP VILLA CANTO"},
      { name: "UNAP VILLA NAVARRO"},
      { name: "UNAP VILLA ORTEGA"},
    ],
},
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "LAS LIRA"},
      { name: "SEGURO SOCIAL"},
      { name: "LOS AMAPOLAS"},
      { name: "UNIDAD MOVIL PARA MAÑANA"},
    ],
},
  {
    name: "SAN PEDRO DE MACORIS",
    centers: [
      { name: "HOSPITAL ALEJO MARTINEZ"},
      { name: "RED DE SALUD"},
      { name: "HOSPITAL  DR. ANGEL PONCE"},
    ],
},
{
  name: "VALVERDE",
  centers:[
    { name: "DPS VALVERDE" },
  ]
},
].sort((a, b) => (a.name < b.name ? -1 : 1));
