const centros = [
  {
    name: "AZUA",
    centers: [
      { name: "CENTRO COMUNAL DE TABARA ARRIBA" },
      { name: "CENTRO DE ATENCION A CLIENTES CLARO" },
      { name: "CENTRO DE DIAGNOSTICO AZUA" },
      { name: "CENTRO DE SALUD FINCA 6" },
      { name: "CLINICA RURAL AMIAMA GOMEZ" },
      { name: "CLINICA RURAL ANZONIA" },
      { name: "CLINICA RURAL BARRERAS" },
      { name: "CLINICA RURAL EL CARRIZAL" },
      { name: "CLINICA RURAL EL ROSARIO" },
      { name: "CLINICA RURAL ESTEBANIA" },
      { name: "CLINICA RURAL HATILLO" },
      { name: "CLINICA RURAL HATO NUEVO" },
      { name: "CLINICA RURAL LA SIEMBRA" },
      { name: "CLINICA RURAL LAS BARIAS" },
      { name: "CLINICA RURAL LAS CHARCAS" },
      { name: "CLINICA RURAL LAS LAGUNAS" },
      { name: "CLINICA RURAL LOS NEGROS" },
      { name: "CLINICA RURAL LOS TOROS" },
      { name: "CLINICA RURAL MAGUEYAL" },
      { name: "CLINICA RURAL MONTE BONITO" },
      { name: "CLINICA RURAL PALMAR DE OCOA" },
      { name: "CLINICA RURAL PROYECTO 4" },
      { name: "CLINICA RURAL PROYECTO-2-C" },
      { name: "CLINICA RURAL PUEBLO VIEJO" },
      { name: "CLINICA RURAL SABANA YEGUA" },
      { name: "CLINICA RURAL SAJANOA" },
      { name: "CLINICA RURAL TABARA ABAJO" },
      { name: "CLINICA RURAL TABARA ARRIBA" },
      { name: "CLINICA RURAL VIAJAMA" },
      { name: "CLINICA RURAL VILLA ARPANDO" },
      { name: "DISTRITO ESCOLAR 03-01" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL MUNICIPAL PERALTA" },
      { name: "HOSPITAL TAIWAN" },
      { name: "LICEO GUAYACANAL" },
      { name: "LICEO JOSE FRANCISCO BOBADILLA" },
      { name: "LOS JOVILLOS" },
      { name: "CENTRO CLÍNICO Y DIAGNOSTICO DE ATENCION PRIMARIA" },
      { name: "GOBERNACIÓN" },
      { name: "SUPERMERCADO DIVERSO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA LA BOMBITA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA YAYAS #1" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAÑITA -A" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL BARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL HIGUERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GANADERO BARRIO LOS TECNICOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAYAS ARRIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -1" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -2" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOVILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS MONTES FRIOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PARCELEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUEBLO VIEJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA ANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CORAZON DE JESUS" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA OCOA" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "CLUB LAS VIÑAS EN LOS RÍOS" },
      { name: "COLEGIO MEDICO NEIBA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE BAHORUCO NEYBA" },
      { name: "EL ESTERO DE NEYBA" },
      { name: "HOSPITAL SAN BARTOLOMÉ" },
      { name: "MULTIUSO JARAGUA" },
      { name: "MULTIUSO MUNICIPAL" },
      { name: "MULTIUSO NEYBA" },
      { name: "MULTIUSO TAMAYO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA CLAVELLINAS" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA EL SALADO GALVAN" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA GALVÁN" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA LOS RÍOS" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA VILLA JARAGUA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA TAMAYO" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTAMIRA" },
      { name: "UNIDAD DE ATENCION PRIMARIA APOLINAR PERDOMO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 2" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABEZA DE TORO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL PALMAR" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA UVILLA" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "AYUNTAMIENTO DE ENRIQUILLO" },
      { name: "AYUNTAMIENTO DE PARAISO" },
      { name: "AYUNTAMIENTO MUNICIPAL    " },
      { name: "CAPILLA SAN DIEGO" },
      { name: "CASA DE LA CULTURA, DANIEL FCO. URBÁEZ GÓMEZ  " },
      { name: "CATEDRAL NUESTRA SEÑORA DEL ROSARIO" },
      { name: "CENTRO COMUNAL DE CABRAL" },
      { name: "CENTRO COMUNITARIO" },
      { name: "CENTRO COMUNITARIO BARAHONA" },
      { name: "CENTRO TEGNOLOGICO BARAHONA" },
      { name: "CLUB DE CACHON" },
      { name: "CLUB DE LEONES DE CABRAL" },
      { name: "CLUB ENRIQUILLO" },
      { name: "CLUB GALLISTICO DON GENIN" },
      { name: "CLUB JUAN PABLO DUARTE " },
      { name: "COLEGIO MEDICO DOMINICANO" },
      { name: "EL AYUNTAMIENTO" },
      { name: "ESCUELA COPA" },
      { name: "ESCUELA LA LISTA" },
      { name: "ESCUELA MANUEL E. MATOS" },
      { name: "ESCUELA PRIMARIA DE ARROLLO DULCE" },
      { name: "ESCUELA PRIMARIA DE ARROLLO DULCE BARAHONA" },
      { name: "HOSPITAL MUNICIPAL ENRIQUILLO" },
      { name: "IGLESIA CATOLICA" },
      { name: "IGLESIA DE LA PASTORA LEA" },
      { name: "IGLESIA DE LA ROTONDA" },
      { name: "IGLESIA DEL NAZARENO" },
      { name: "IGLESIA PASTORA YOHANNA" },
      { name: "IGLESIA RESURECCION Y VIDA (FLEMING)" },
      { name: "IGLESIAS BUENAS NUEVAS" },
      { name: "INSTITUTO AGRARIO DOMINICANO (IAD)" },
      { name: "JUZGADO DE PAZ    " },
      { name: "LICEO ALTAGRACIA B. GONZALEZ" },
      { name: "LICEO DE LOS PATOS" },
      { name: "LICEO DR. FEDERICO HENRIQUEZ Y CARVAJAL" },
      { name: "PABELLON MULTIUSOS" },
      { name: "MULTIUSO DE CABRAL" },
      { name: "MULTIUSO DE POLO " },
      { name: "MULTIUSO PARAÍSO" },
      { name: "OFICINA DE CORREOS Y TELECOMUNICACIONES" },
      { name: "PABELLON DE BALONCESTO, VILLA OLIMPICA" },
      { name: "PABELLON DE ENTRENAMIENTO VILLA OLIMPICA" },
      { name: "PARAISO UNIDAD DE ATENCION PRIMARIA 1 Y 2" },
      { name: "PLAZA COMUNAL VICENTE NOBLE" },
      { name: "POLO CENTRO COMUNAL" },
      { name: "SALA CAPITULAR" },
      { name: "SALON PARROQUIAL, IGLESIA CATOLICA VIEJA      " },
      { name: "SINDICATO DE ESTIBADORES DE CARGA PESADA" },
      { name: "UCATEBA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA DE QUITA CORAZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO BELO" },
      { name: "UNIDAD DE ATENCION PRIMARIA ARROYO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABRAL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA CANOA" },
      { name: "UNIDAD DE ATENCION PRIMARIA FONDO NEGRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA INVI-CEA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CIENAGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA LISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS SALINAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS BLANCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS COCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PATOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA PEÑON" },
      { name: "UNIDAD DE ATENCION PRIMARIA PESCADERIA" },
      { name: "VILLA OLIMPICA" },
    ],
  },
  {
    name: "DAJABÓN",
    centers: [
      { name: "ASILO DE ANCIANOS DAJABÓN" },
      { name: "CANCHA CLUB CULTURAL LIBERACIÓN JUVENIL" },
      { name: "CASA DE LA CULTURA" },
      { name: "CENTRO COMUNAL CRUZ DE CABRERA" },
      { name: "CENTRO COMUNAL GUAYAJAYUCO" },
      { name: "CENTRO COMUNAL LAS ROSAS" },
      { name: "CENTRO COMUNAL LOS CEREZOS" },
      { name: "CENTRO COMUNAL MARIANO CESTERO" },
      { name: "CENTRO COMUNAL RIO LIMPIO" },
      { name: "CENTRO COMUNAL TRINITARIA" },
      { name: "CENTRO DIAGNÓSTICO BARRIO NORTE" },
      { name: "CENTRO DE MADRE CRISTO RESUCITADO" },
      { name: "CENTRO DE MADRE HERMANA MIRABAL " },
      { name: "CENTRO DE MADRE LA ALTAGRACIA" },
      { name: "CENTRO DE MADRE LA ESPERANZA" },
      { name: "CENTRO DE MADRE LOS MICHES" },
      { name: "CENTRO DE MADRE LUPERON" },
      { name: "CLUB RAFAEL SOCIAS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE DAJABON" },
      { name: "POLI DEPORTIVO AMBRIOSO ESTEVEZ" },
      { name: "POLI DEPORTIVO AMBROSIO ESTÉVEZ" },
      { name: "CENTRO DE MADRE CAPOTILLO" },
      { name: "CENTRO DE MADRE HIPOLITO BILLINI" },
      { name: "CENTRO MADRE EL CRUCE " },
    ],
  },
  {
    name: "DISTRITO NACIONAL",
    centers: [
      { name: "ALBERGUE OLÍMPICO DOMINICANO" },
      { name: "ASILO LA BENDICION DE DIOS" },
      { name: "CARREFOUR PLAZA DUARTE" },
      { name: "CENTRO DE EXCELENCIA REPÚBLICA DE COLOMBIA" },
      { name: "CENTRO DE PRIMER NIVEL LOS GIRASOLES" },
      { name: "CENTRO DE PRIMER NIVEL SAN CARLOS" },
      { name: "CENTRO DE PRIMER NIVEL SAN PEDRO APOSTOL" },
      { name: "CENTRO DE PRIMER NIVEL VALENTIN BUTTEN" },
      { name: "CENTRO DE PRIMER NIVEL VILLA FRANCISCA" },
      { name: "CENTRO DE SALUD DIVINA PROVIDENCIA" },
      { name: "CENTRO MEDICO FUSADI" },
      { name: "CENTRO MEDICO HONDURAS" },
      { name: "CENTRO OLÍMPICO JUAN PABLO DUARTE (PABELLÓN DE COMBATE)" },
      { name: "CLUB AGRUCUDEGUA" },
      { name: "CLUB LOS PRADOS" },
      { name: "CLUB LOS TRINITARIOS" },
      { name: "CLUB MARÍA AUXILIADORA" },
      { name: "CLUB MAURICIO BÁEZ" },
      { name: "CLUB NACO" },
      { name: "CLUB PLAZA INDEPENDENCIA" },
      { name: "CLUB RAFAEL BARIAS" },
      { name: "CLUB SAN CARLOS" },
      { name: "COLEGIO MÉDICO DOMINICANO" },
      { name: "COLEGIO MARILLAC" },
      { name: "COLEGIO SAN GABRIEL" },
      { name: "COMISION MILITAR Y POLICIAL (COMIPOL)" },
      { name: "CONAPE" },
      { name: "CONSULTORIO MÉDICO LA CIÉNAGA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO HONDO" },
      { name: "CENTRO DE PRIMER NIVEL BOCA CANASTA" },
      { name: "CENTRO DE PRIMER NIVEL CAÑAFISTOL" },
      { name: "CENTRO DE PRIMER NIVEL CATALINA" },
      { name: "CENTRO DE PRIMER NIVEL DON GREGORIO" },
      { name: "CENTRO DE PRIMER NIVEL EL CARRETON" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONAL" },
      { name: "CENTRO DE PRIMER NIVEL EL LLANO MATANZAS" },
      { name: "CENTRO DE PRIMER NIVEL ESCONDIDO" },
      { name: "CENTRO DE PRIMER NIVEL FUNDACION DE PERAVIA" },
      { name: "CENTRO DE PRIMER NIVEL HONDURAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS BARIAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CALDERAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CARRERAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS TABLAS" },
      { name: "CENTRO DE PRIMER NIVEL LOS TUMBAOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS YAGUARIZOS" },
      { name: "CENTRO DE PRIMER NIVEL MATA GORDA" },
      { name: "CENTRO DE PRIMER NIVEL MATANZAS" },
      { name: "CENTRO DE PRIMER NIVEL MAXIMO GOMEZ" },
      { name: "CENTRO DE PRIMER NIVEL PAYA" },
      { name: "CENTRO DE PRIMER NIVEL PIZARRETE" },
      { name: "CENTRO DE PRIMER NIVEL QUIJA QUIETA" },
      { name: "CENTRO DE PRIMER NIVEL RIO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL SABANA BUEY" },
      { name: "CENTRO DE PRIMER NIVEL SALINAS" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA" },
      { name: "CENTRO DE PRIMER NIVEL SANTANA" },
      { name: "CENTRO DE PRIMER NIVEL SAONA" },
      { name: "CENTRO DE PRIMER NIVEL VALDESIA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA DAVID" },
      { name: "CENTRO DE PRIMER NIVEL VILLA GUERA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA MAJEGA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA SOMBRERO" },
      { name: "CENTRO DE PRIMER NIVEL WILSON BELLO" },
      { name: "DIRECCION DE AREA DE SALUD IV (GAZCUE)" },
      { name: "DIRECCION GENERAL DE EPIDEMIOLOGIA (DIGEPI)" },
      { name: "DISPENSARIO PARROQUIAL SAN GABRIEL" },
      { name: "DISPENSARIO TEJADA Y FLORENTINO (UASD)" },
      { name: "ESCUELA MADRE MAZZARELLO" },
      { name: "ESCUELA PROFESOR JUAN BOSH" },
      { name: "ESCUELA REPÚBLICA DE ESPAÑA" },
      { name: "ESCUELA SANTO CURA" },
      { name: "FUNDACIÓN CRUZ JIMINIÁN" },
      { name: "FUNDACION ESCOBA" },
      { name: "FUNDACION HUELLAS DEL SIGLO" },
      { name: "FUNDACIÓN JUDEGU" },
      { name: "FUNSAZURZA" },
      { name: "HOSPITAL DE LA POLICIA NACIONAL" },
      { name: "HOSPITAL DOCENTE DR. FRANCISCO MOSCOSO PUELLO" },
      { name: "HOSPITAL DOCENTE DR. FRANCISCO MOSCOSO PUELLO " },
      { name: "HOSPITAL DR. FELIX MARIA GOICO" },
      { name: "HOSPITAL DR. FÉLIX MARÍA GOICO" },
      { name: "IGLESIA PERPETUO SOCORRO" },
      { name: "IINSTITUTO DE AUXILIO Y VIVIENDA (INAVI)" },
      { name: "INSTITUTO DE AUXILIOS Y VIVIENDAS (INAVI)" },
      { name: "INSTITUTO SAN JUAN BAUTISTA" },
      { name: "INTEC" },
      { name: "JUMBO AGORA" },
      { name: "LA SIRENA CHURCHILL" },
      { name: "MEDIA NARANJA CENTRO OLIMPICO" },
      { name: "MERCASID" },
      { name: "MINISTERIO DE DEFENSA (MIDE)" },
      { name: "PARROQUIA NUESTRA SEÑORA DEL SAGRADO CORAZON" },
      { name: "PLAZA CARMEN RENATA (LA ISABELA)" },
      { name: "PLAZA DE LA SALUD" },
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ" },
      { name: "PLAZA SAMBIL" },
      { name: "PUCMM - SANTO DOMINGO" },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "SOCIEDAD BENEFICA PRO-EMIGRANTES ESPAÑOLES" },
      { name: "SUPERMERCADO NACIONAL 27 DE FEBRERO" },
      { name: "MINISTERIO DE TURISMO" },
      { name: "UASD (DISPENSARIO TEJADA Y FLORENTINO)" },
      { name: "UNIBE" },
      { name: "UNIVERSIDAD DOMINICANA O&M" },
      { name: "UNPHU" },
      { name: "CANCHA VILLA FRANCISCA" },
      { name: "PLAZA LAMA 27 DE FEBRERO" },
      { name: "AGRUCUDEGUA" },
      { name: "CENTRO DE DIAGNOSTICO DE ATENCION PRIMARIA BARNEY MORGAN " },
      { name: "CLUB DEPORTIVO LOS PIONEROS" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CLUB RENACER " },
      {
        name:
          "CORPORACIÓN DEL ACUEDUCTO Y ALCANTARILLADO DE SANTO DOMINGO (CAASD)",
      },
      { name: "FUNDACION ESCOBA" },
      { name: "HIPERMERCADO OLE" },
      { name: "IGLESIA PERPETUO SOCORRO" },
      { name: "PLAZA SAMBIL" },
      { nam: "CLUB GENERAL GREGORIO  LUPERON" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "CENTRO DE PRIMER NIVEL VALENTIN BUTTEN" },
      { name: "FUNDACION HUELLAS DEL SIGLO" },
      { name: "HOSPITAL DR. FELIX MARIA GOICO" },
      {
        name:
          "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)",
      },
      { name: "CONSEJO NACIONAL DE LA PERSONA ENVEJECIENTE (CONAPE)" },
      { name: "CRUZ ROJA DOMINICANA" },
      { name: "DIRECCION GENERAL DE IMPUESTOS INTERNOS (DGII)" },
      { name: "INSTITUTO DE AUXILIOS Y VIVIENDAS" },
      { name: "PLAZA LAMA" },
      { name: "AGORA MALL AV. KENNEDY" },
      { name: "ALCALDIA DEL DISTRITO NACIONAL" },
      { name: "Club Villa Francisca" },
      { name: "SUPERMERCADOS NACIONAL (CCN)" },
      { name: "CLUB INDEPENDENCIA" },
      { name: "CLUB MIRADOR SUR" },
      { name: "COLEGIO DOMINICANO DE INGENIEROS,ARQUITECTOS Y AGRIMENSORES " },
      { name: "ESCUELA  TEJADA Y FLORENTINO" },
      { name: "COLEGIO MOVEARTE" },
      { name: "MULTICENTRO LA SIRENA" },
      { name: "O&M Medical School" },
      { name: "SENADO DE LA REPÚBLICA DOMINICANA" },
      { name: "UNICARIBE" },
      { name: "UNIVERSIDAD OYM" },
      { name: "UNIVERSIDAD PCMM" },
      { name: "CENTRO DE PRIMER NIVELA CARMEN RENATA " },
      { name: "ESCUELA PROFESOR JUAN BOSCH" },
      { name: "HOSPITAL JACINTO MAÑON" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "OBRAS PUBLICAS Y COMUNICACIONES" },
      { name: "PLAZA DUARTE (CARREFOUR)" },
      { name: "UNIVERSIDAD NACIONAL PEDRO HENRIQUEZ UREÑA (UNPHU)" },
      { name: "HOSPITAL GENERAL PLAZA DE LA SALUD" },
      { name: "CENTRO MEDICO FUSADI" },
      { name: "SUPERMERCADO NACIONAL (CCN), 27 DE FEBRERO" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CANCHA SAN MARTIN " },
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "CATEDRAL SANTA ANA - JUAN XXIII" },
      { name: "CENTRO COMUNAL DE CASTILLO" },
      { name: "CENTRO COMUNAL PABLO VI" },
      { name: "CENTRO DE VACUNACION SIGLO 21" },
      { name: "CENTRO MÉDICO DOCTOR OVALLE" },
      { name: "CIUDAD GANADERA" },
      { name: "CLUB 27 DE FEBRERO" },
      { name: "CLUB BLUE" },
      { name: "CLUB DE LOS PROFESORES" },
      { name: "CLUB HERMANAS MIRABAL" },
      { name: "CLUB MIGUEL GELABERT" },
      { name: "CLUB SALOME UREÑA" },
      { name: "COLEGIO SAN FRANCISCO" },
      { name: "EL AGUACATE" },
      { name: "ESCUELA GREGORIO LUPERÓN VISTA AL VALLE" },
      { name: "FUNDACION ADAMES" },
      { name: "GENIMO" },
      { name: "LA ENEA" },
      { name: "LA ISLETA DE CERREJÓN" },
      { name: "MULTIUSO ARENA  57" },
      { name: "MULTIUSO ARENOSO" },
      { name: "MULTIUSO BAJO TECHO ARENOSO" },
      { name: "MULTIUSO BAJO TECHO VILLA RIVAS" },
      { name: "NARANJO DULCE" },
      { name: "PALACIO DE JUSTICIA" },
      { name: "SAN FELIPE ARRIBA" },
      { name: "SEIBA DE LOS PÁJAROS" },
      { name: "UASD" },
      { name: "CLUB JUAN ALBERTO ESPINOLA" },
      { name: "CLUB MAYORISTAS" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CASA CLUB DE GINANDIANA" },
      { name: "CENTRO CAMPESINO" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO (CTC) (MICHES)" },
      { name: "DEFENSA CIVIL" },
      { name: "HOGAR DE ENVEJECIENTE" },
      { name: "HOSPITAL DOCTOR TEOFILO HERNADEZ" },
    ],
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO DE COMBATE" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL LA GALLERA" },
      { name: "CENTRO DE PRIMER NIVEL LAS DELICIAS" },
      { name: "CENTRO DE PRIMER NIVEL PINZON" },
      { name: "CENTRO DE PRIMER NIVEL POTROSO" },
      { name: "CENTRO DE PRIMER NIVEL RINCONCITOS" },
      { name: "CENTRO DE PRIMER NIVEL SABANA HIGUERO" },
      { name: "CENTRO DE PRIMER NIVEL SABANA MULA" },
      { name: "CENTRO DE PRIMER NIVEL DE JUAN SANTIAGO" },
      { name: "CENTRO DE PRIMER NIVEL EL LLANO" },
      { name: "CENTRO DE PRIMER NIVEL GUANITO " },
      { name: " CENTRO DE PRIMER NIVEL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL LAS PALMAS " },
      { name: "CENTRO DE PRIMER NIVEL PEDRO SANTANA " },
      { name: "CENTRO DE PRIMER NIVEL RANCHO DE LA GUARDIA " },
      { name: "CENTRO DE PRIMER NIVEL SABANA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL SABANA LARGA" },
      { name: "CENTRO TECNÓLOGICO CCOMUNITARIO (JUAN SANTIAGO)" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL DE HONDO VALLE " },
      { name: "HOSPITAL ROSA DUARTE" },
      { name: "POLIDEPORTIVO (HONDO VALLE)" },
      { name: "POLIDEPORTIVO  BANICA " },
      { name: "CENTRO DE PRIMER NIVEL EL VALLE" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CLUB RECREATIVO " },
      { name: "CENTRO DE PRIMER NIVEL ALGARROBO" },
      { name: "CENTRO DE PRIMER NIVEL BONAGUA" },
      { name: "CENTRO DE PRIMER NIVEL CEIBA DE MADERA" },
      { name: "CENTRO DE PRIMER NIVEL CUERO DURO" },
      { name: "CENTRO DE PRIMER NIVEL DE GUAUCI" },
      { name: "ESPAILLAT	CENTRO DE PRIMER NIVEL EL CAIMITO" },
      { name: "CENTRO DE PRIMER NIVEL EL COROZO" },
      { name: "CENTRO DE PRIMER NIVEL EL HIGUERITO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA ERMITA" },
      { name: "CENTRO DE PRIMER NIVEL LA ISLETA" },
      { name: "CENTRO DE PRIMER NIVEL LA MANZANA" },
      { name: "CENTRO DE PRIMER NIVEL LA YAGUA" },
      { name: "CENTRO DE PRIMER NIVEL LAS FLORES" },
      { name: "CENTRO DE PRIMER NIVEL LAS GUAZUMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS LAGUNAS " },
      { name: "CENTRO DE PRIMER NIVEL LOS BRAZOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LOS PANCHOS" },
      { name: "CENTRO DE PRIMER NIVEL MONTE DE LA JAGUA " },
      { name: "CENTRO DE PRIMER NIVEL NUEVO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL PALMA HERRADA" },
      { name: "CENTRO DE PRIMER NIVEL QUEBRADA HONDA" },
      { name: "CENTRO DE PRIMER NIVEL REPARADERO" },
      { name: "CENTRO DE PRIMER NIVEL SAL SI PUEDES" },
      { name: "CENTRO DE PRIMER NIVEL SAN VICTOR" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA MOCA" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA DURA" },
      { name: "CENTRO DE PRIMER NIVEL VERAGUA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA PROGRESO" },
      { name: "CENTRO DE PRIMER NIVEL ZAFARRAYA" },
      { name: "HOSPITAL JOSÉ CONTRERAS" },
      { name: "COLEGIO MÉDICO DOMINICANO" },
      { name: "CENTRO DE PRIMER NIVEL JOBA ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL ORTEGA" },
      { name: "CENTRO DE PRIMER NIVEL PUESTO GRANDE" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CAFETALERA" },
      { name: "HOSPITAL JAMAO AL NORTE" },
      { name: "HOSPITAL MANUEL DE LUNA" },
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUALEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUAYABO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CAÑITAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS GUAMAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS HATILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MANCHADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUERTO RICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUNTA DE GARZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CANTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA NAVARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ORTEGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA JAVILLA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAGUITAS" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO DIAGNÓSTICO." },
      { name: "CENTRO DE PRIMER NIVEL ANGOSTURA" },
      { name: "CENTRO DE PRIMER NIVEL BARTOLOMÉ" },
      { name: "CENTRO DE PRIMER NIVEL BATEY 8" },
      { name: "CENTRO DE PRIMER NIVEL BOCA DE CACHON" },
      { name: "CENTRO DE PRIMER NIVEL COLONIA MIXTA" },
      { name: "CENTRO DE PRIMER NIVEL CRISTÓBAL" },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABAL" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMÓN" },
      { name: "CENTRO DE PRIMER NIVEL JIMANI CENTRO" },
      { name: "CENTRO DE PRIMER NIVEL JIMANI VIEJO" },
      { name: "BARRIO JIMANI VIEJO." },
      { name: "CENTRO DE PRIMER NIVEL LA DESCUBIERTA" },
      { name: "CENTRO DE PRIMER NIVEL LAS BAITOAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS MERCEDES" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOLOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS PINOS DEL EDÉN" },
      { name: "CENTRO DE PRIMER NIVEL MELLA" },
      { name: "CENTRO DE PRIMER NIVEL PLACER BONITO" },
      { name: "CENTRO DE PRIMER NIVEL POSTRER RÍO" },
      { name: "CENTRO DE PRIMER NIVEL PUESTO ESCONDIDO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ISIDRO" },
      { name: "CENTRO DE PRIMER NIVEL SAN JOSÉ" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA NUEVA" },
      { name: "CENTRO DE PRIMER NIVEL VENGAN A VER" },
      { name: "HOSPITAL GENERAL MELENCIANO" },
      { name: "HOSPITAL JOSE PEREZ" },
      { name: "HOSPITAL JOSE PEREZ" },
      { name: "INDEPENDENCIA	HOSPITAL LA DESCUBIERTA" },
    ],
  },
  {
    name: "LA ALTAGRACIA",
    "centers": [
      { name: "LA ALTAGRACIA	AEROPUERTO PUNTA CANA" },
      { name: "HOSPITAL DR. EVANGELINA RODRIGUEZ" },
      { name: "HOTEL LOPESAN COSTA BAVARO" },
      { name: "MULTIUSO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAYAHIBE" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOCA DE YUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA OTRA BANDA " },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PLATANITOS " },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
    ]
  },
  {
    name: "LA ROMANA",
    "centers": [
      { name: "CENTRO DIAGNOSTICO CALETA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE LA ROMANA" },
      { name: "ECOLAB ZONA  FRANCA  2" },
      { name: "GOBERNACIÓN PROVINCIAL" },
      { name: "HOGAR DEL NIÑO " },
      { name: "HOSPITAL ARÍSTIDES FIALLO CABRAL" },
      { name: "HOSPITAL GUAYMATE" },
      { name: "HOSPITAL MATERNO INFANTIL DR. FRANCISCO A. GONZALVO" },
      { name: "HOSPITAL SAMARITANO" },
      { name: "IGLESIA MARANAHTA." },
      { name: "IGLESIA PENTECOSTAL MI VILLA NAZARET" },
      { name: "IGLESIA SANTA ROSA DE LIMA" },
      { name: "POLICLINICO DUARTE" },
      { name: "POLIDEPORTIVO LA ROMANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ANTITUBERCULOSO DR. LUIS J. SUAREZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA CALETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CUCAMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ESCUELA PAULINA JIMENEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA PIEDRA LINDA" },
      { name: "UNIDAD DE ATENCION PRIMARIA TOMAS DESIR LEBRON" },
      { name: "LA ROMANA   MULTIUSO SAN EDUARDO" },
    ]
  },
  {
    name: "LA VEGA",
    "centers": [
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL BAYACANES" },
      { name: "CENTRO DE PRIMER NIVEL BUENA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL BURENDE" },
      { name: "CENTRO DE PRIMER NIVEL EL BALCON" },
      { name: "CENTRO DE PRIMER NIVEL EL CERCADO" },
      { name: "CENTRO DE PRIMER NIVEL EL MAMEY" },
      { name: "CENTRO DE PRIMER NIVEL GUACO" },
      { name: "CENTRO DE PRIMER NIVEL HATILLO" },
      { name: "CENTRO DE PRIMER NIVEL JUMUNUCO" },
      { name: "CENTRO DE PRIMER NIVEL LA CULATA" },
      { name: "CENTRO DE PRIMER NIVEL LA SABINA" },
      { name: "CENTRO DE PRIMER NIVEL LA TORRE" },
      { name: "CENTRO DE PRIMER NIVEL LIMONAL" },
      { name: "CENTRO DE PRIMER NIVEL MANABAO" },
      { name: "CENTRO DE PRIMER NIVEL OCTAVIA GAUTIER" },
      { name: "CENTRO DE PRIMER NIVEL PASO BAJITO" },
      { name: "CENTRO DE PRIMER NIVEL PIEDRA BLANCA" },
      { name: "CENTRO DE PRIMER NIVEL PONTON" },
      { name: "CENTRO DE PRIMER NIVEL RIO SECO" },
      { name: "CENTRO DE PRIMER NIVEL SAN MIGUEL" },
      { name: "CENTRO DE PRIMER NIVEL SANTO CERRO" },
      { name: "CENTRO DE PRIMER NIVEL TIREO" },
      { name: "CENTRO DE SALUD OBRA SOCIAL SALESIANA" },
      { name: "CENTRO MEDICO PADRE FANTINO" },
      { name: "CLÍNICA BAEZ SOTO" },
      { name: "CLÍNICA CEMEVE" },
      { name: "COOPERATIVA VEGA REAL" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "HOSPITAL JUAN ANT.CASTILLO" },
      { name: "HOSPITAL MORILO KING " },
      { name: "POLICLINICO LA VEGA" },
      { name: "AYUNTAMIENTO MUNICIPAL LA VEGA" },
      { name: "CENTRO DE PRIMER NIVEL CENTRO EL CARMEN" },
      { name: "CENTRO DE PRIMER NIVEL DON FAUSTO" },
      { name: "CENTRO DE PRIMER NIVEL EL PINO " },
      { name: "CENTRO DE PRIMER NIVEL EL RANCHITO" },
      { name: "CENTRO DE PRIMER NIVEL EL TANQUE" },
      { name: "CENTRO DE PRIMER NIVEL GINA HUECA " },
      { name: "CENTRO DE PRIMER NIVEL GUAREY" },
      { name: "CENTRO DE PRIMER NIVEL LAS CARMELITAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS UVAS" },
      { name: "CENTRO DE PRIMER NIVEL LICEY" },
      { name: "CENTRO DE PRIMER NIVEL MARIA AUXILIADORA" },
      { name: "CENTRO DE PRIMER NIVEL MARTINEZ " },
      { name: "CENTRO DE PRIMER NIVEL NARANJAL " },
      { name: "CENTRO DE PRIMER NIVEL PINTO SABANETA" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL RIO VERDE" },
      { name: "CENTRO DE PRIMER NIVEL YAYAS" },
      { name: "CENTRO MEDICO JARABACOA" },
      { name: "CLUB DE ABOGADOS CLINICA LA CONCE PCION " },
    ]
  },
  {
    name: "MARIA TRINIDAD SÁNCHEZ",
    "centers": [
      { name: "AYUNTAMIENTO DEL POZO" },
      { name: "AYUNTAMIENTO MUNICIPAL NAGUA" },
      { name: "CASA DE FORMACION SAGRADA FAMILIA" },
      { name: "CENTRO COMUNITARIO MATA BONITA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO AL MEDIO" },
      { name: "CENTRO DE PRIMER NIVEL LOS YAYALES" },
      { name: "CENTRO DE PRIMER NIVEL ABREU" },
      { name: "CENTRO DE PRIMER NIVEL BOBITA" },
      { name: "CENTRO DE PRIMER NIVEL COPEYITO" },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL EL YAYAL" },
      { name: "CENTRO DE PRIMER NIVEL LA CAPILLA" },
      { name: "CENTRO DE PRIMER NIVEL LAS CEJAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CORCOBAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GARZAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GORDAS" },
      { name: "CENTRO DE PRIMER NIVEL LOMA ALTA" },
      { name: "HOSPITAL DR. ANTONIO YAPOR HEDED" },
      { name: "HOSPITAL DR. CARLOS A. ZAFRA" },
      { name: "PARROQUIA SANTISIMA TRINIDAD" },
      { name: "POLIDEPORTIVO CABRERA" },
      { name: "POLIDEPORTIVO NAGUA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA MATANCITA" },
    ]
  },
  {
    name: "MONSEÑOR NOUEL",
    "centers": [
      { name: "CLINICA POLICLINICO BONAO" },
      { name: "CLUB LOS AMAPOLOS" },
      { name: "FALCONDO" },
      { name: "HOSPITAL DOCTOR JOSE A COLUNMA (IDDS)" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL PIEDRA BLANCA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JAYACO" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAXIMO GOMEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANA DEL PUERTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN PEDRO Y SAN PABLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS ARROCES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS QUEMADOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA SONADOR" },
    ]
  },
  {
    name: "MONTE CRISTI",
    "centers": [
      { name: "CENTRO COMUNAL LOMA" },
      { name: "CLUB HATILLO PALMA" },
      { name: "CLUB JUAN PABLO" },
      { name: "GUAJACA" },
      { name: "IGLESIA EVANGÉLICA MISIONERA AMPARO DEL CIELO (KM 13)" },
      { name: "IGLESIA KM. 14" },
      { name: "LOS CONUCOS (VISITAR)" },
      { name: "POLIDEPOIRTIVO DE GUAYUBIN" },
      { name: "POLIDEPORTIVO" },
      { name: "POLIDEPORTIVO - CASTAÑUELA" },
      { name: "POLIDEPORTIVO - LAS MATAS DE SANTA CRUZ" },
      { name: "POLIDEPORTIVO DE MANZANILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA HATO DEL MEDIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO DE LA PALOMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CERRO GORDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA COPEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRAMADEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL AHOGADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL POCITO DE GUAYUBIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA HATILLO PALMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA HERMANAS MIRABAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CAPITALITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA GALLERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS FLORES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS MATAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CONUCOS MC" },
      { name: "UNIDAD DE ATENCION PRIMARIA MARTIN GARCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA PILOTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA CRUZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA SINDA" },
      { name: "VILLA ELISA AYUNTAMIENTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA COPEY DE MAZANILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA LO MAESTROS" },
    ]
  },
  {
    name: "MONTE PLATA",
    "centers": [
      { name: "CENTRO DE PRIMER NIVEL CHACARO" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOTADOS" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "SCUELA MERIÑO" },
      { name: "HOSPITAL MUNICIPAL DE YAMASA" },
      { name: "UNIDAD DE ATENCION PRIMARIA DON JUAN" },
      { name: "CENTRO COMUNAL MONTE PLATA" },
      { name: "CENTRO DE PRIMER NIVEL ANTON SÁNCHEZ" },
      { name: "CENTRO DE PRIMER NIVEL COPEY" },
      { name: "CENTRO DE PRIMER NIVEL GREGORIO LUPERÓN" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA" },
      { name: "CENTRO DE PRIMER NIVEL LA CUABA" },
      { name: "CENTRO DE PRIMER NIVEL LOS JAVIELES" },
      { name: "CENTRO DE PRIMER NIVEL LOS LIMONES" },
      { name: "CENTRO DE PRIMER NIVEL LOS SOSA" },
      { name: "CENTRO DE PRIMER NIVEL PUEBLO NUEVO" },
      { name: "CENTRO DE PRIMER NIVEL REFORMA DE DAJAO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA DE AGUA" },
    ]
  },
  {
    name: "PEDERNALES",
    "centers": [
      { name: "UNIDAD DE ATENCION PRIMARIA  5 Y 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA  9" },
      { name: "UNIDAD DE ATENCION PRIMARIA 3 Y 4" },
      { name: "UNIDAD DE ATENCION PRIMARIA 7 Y 8" },
    ]
  },
  {
    name: "PERAVIA",
    "centers": [
      { name: "CENTRO DE PRIMER NIVEL BOCA CANASTA" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CENTRO COMUNAL VILLA MAJEGA" },
      { name: "CENTRO DE PRIMER NIVEL NANCY ORTIZ - MATANZAS" },
      { name: "CENTRO DE PRIMER NIVEL WILSON BELLO" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "ESCONDIDO I" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MAXIMO GOMEZ" },
      { name: "PIZARRETE I" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "CENTRO DE ATENCION PRIMARIA LUIS ALFONZO MATOS" },
      { name: "SAONA I" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA SOMBRERO 1" },
    ]
  },
  {
    name: "PUERTO PLATA",
    "centers": [
      { name: "AYUNTAMIENTO DE SOSUA" },
      { name: "CENTRO DE PRIMER NIVEL DOLORES DE LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL NAVAS" },
      { name: "CENTRO DE PRIMER NIVEL SABANETA DE YASICA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "MUNICIPAL DE ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE GUANANICO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE LOS HIDALGOS" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "IGLESIA EL SHADDAI" },
      { name: "PLAY DEL SECTOR PADRE LAS CASAS" },
      { name: "HOSPITAL MUNICIPAL DE LUPERÓN" },
      { name: "HOTEL CASA VALERIA" },
      { name: "HOTEL SOSUA BY DE SEA" },
      { name: "HOTEL TERRA LINDA" },
      { name: "LIGA DEL ATLÁNTICO" },
    ]
  },
  {
    name: "SAMANÁ",
    "centers": [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CENTRO COMUNAL (LOS CORRALES)" },
      { name: "CENTRO COMUNAL (NARANJIITO)" },
      { name: "CENTRO COMUNAL LOS COCOS" },
      { name: "CENTRO COMUNAL RANCHO ESPAÑOL" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO DEL LIMÓN" },
      { name: "CLUB DE MADRE LOS PUENTES" },
      { name: "CRUCE DE TEZÓN" },
      { name: "ESCUELA PRIMARIA LOS GRATINIS" },
      { name: "FABRICA DE HIELO (PASCUALA)" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "IGLESIA CATÓLICA (RINCON)" },
      { name: "IGLESIA CATOLICA LAS GARITAS" },
      { name: "JUNTA DE VECINOS DANIEL WILMORE" },
      { name: "JUNTA DE VECINOS JUANA VICENTA" },
      { name: "JUNTA DISTRITAL LAS GALERAS" },
      { name: "LOS CACAOS" },
      { name: "LOS ROBALOS (CENTRO COMUNAN)" },
      { name: "SINDICATO DE LA PORTUARIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MAJAGUA" },
      { name: "VILLA CLARA " }
    ]
  },
  {
    name: "SAN CRISTÓBAL",
    "centers": [
      { name: "ASOCIACION DE INDUSTRIA" },
      { name: "CENTRO DIAGNOSTICO VILLA FUNDACION" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "COMEDOR ECONOMICO LAVA PIE" },
      { name: "CENTRO DE PRIMER NIVEL CONANI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAJUILITO" },
      { name: "CENTRO DE PRIMER NIVEL EL CARRIL" },
      { name: "CENTRO DE PRIMER NIVEL LA PARED" },
      { name: "CENTRO DE PRIMER NIVEL LA PISCINA" },
      { name: "CENTRO DE PRIMER NIVEL MODESTO OGANDO (LAS FLORES)" },
      { name: "CENTRO DE PRIMER NIVEL PUEBLO NUEVO" },
      { name: "CENTRO DE PRIMER NIVEL PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOSPITAL M. VILLA ALTAGRACIA" },
      { name: "HOSPITAL MUNICIPAL HAINA" },
      { name: "HOSPITAL RAFAEL J. MAÑÓN" },
      { name: "PARQUE RADHAMES" },
      { name: "POLICLINICA NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "POLIDEPORTIVO NIGUA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANETA " },
      { name: "DISPENSARIO LOS AMERICANOS" },
      { name: "UASD SAN CRISTOBAL" },
    ]
  },
  {
    name: "SAN JOSÉ DE OCOA",
    "centers": [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE SALUD  ARROYO CANA" },
      { name: "CENTRO DE SALUD  LA CIENEGA" },
      { name: "CENTRO DE SALUD  LAS FLORES" },
      { name: "CENTRO DE SALUD  LOS MARTINEZ" },
      { name: "CENTRO DE SALUD  PUEBLO A BAJO" },
      { name: "CENTRO DE SALUD  SAN ANTONIO" },
      { name: "CENTRO DE SALUD  SAN LUIS " },
      { name: "CENTRO DE SALUD EL PINAR" },
      { name: "CENTRO DE SALUD LIMONAL" },
      { name: "CENTRO DE SALUD NARANJAL" },
      { name: "CENTRO DE SALUD SABANA LARGA ABAJO" },
      { name: "CENTRO DE SALUD SAN RAFAEL" },
    ]
  },
  {
    name: "SAN JUAN",
    "centers": [
      { name: "CLUB COME MORO" },
      { name: "CODIA" },
      { name: "EL CASINO SJ" },
      { name: "PARQUE SÁNCHEZ" },
      { name: "SALÓN DE CONFERENCIA DIRECCION PROVINCIAL DE SALUD SAN JUAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOHECHIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BUENA VISTA DEL YAQUE" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRUMBADERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL NARANJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JINOVA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUAN HERRERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA ESTANCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA NAVAJA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CARTONES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS GRINGOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MATAYAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA POZO HONDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CARMEN" },
    ]
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    "centers": [
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "CLINICA DOCTOR DE LEON" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "CLUB DE PERIODISTAS" },
      { name: "DEFENSA CIVIL" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE SAN PEDRO DE MACORIS" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "IGLESIA ASAMBLEA DE DIOS JUAN DOLIÓ" },
      { name: "IGLESIA CATOLICA LOS CONUCOS" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "IGLESIA DE DIOS GUAYACANES" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "LOCAL DE LOS MUELLEROS" },
      { name: "MONTE DE SION" },
      { name: "MULTIUSO - EXTENSION UASD" },
      { name: "UCE" },
      { name: "AYUNTAMIENTO MUNICIPAL SAN PEDRO" },
      { name: "CANCHA CENTRO" },
      { name: "CENTRO DE BOMBEROS, GAUTIER" },
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
    ]
  },
  {
    name: "SÁNCHEZ RAMIREZ",
    "centers": [
      { name: "AYUNTAMIENTO DE QUITA SUEÑO" },
      { name: "BAJO TECHO" },
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER NIVEL CABALLERO" },
      { name: "CENTRO DE PRIMER NIVEL CASTILLO" },
      { name: "CENTRO DE PRIMER NIVEL CHACUEY" },
      { name: "CENTRO DE PRIMER NIVEL COMEDERO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL CRUZ DE ANGELINA" },
      { name: "CENTRO DE PRIMER NIVEL DUEY" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONCITO" },
      { name: "CENTRO DE PRIMER NIVEL EL PESCOZON" },
      { name: "CENTRO DE PRIMER NIVEL HERNANDO ALONZO" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA" },
      { name: "CENTRO DE PRIMER NIVEL LA BIJA" },
      { name: "CENTRO DE PRIMER NIVEL LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL LAS CANAS" },
      { name: "CENTRO DE PRIMER NIVEL SABALLO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA PRIETA" },
      { name: "CENTRO DE PRIMER NIVEL ZAMBRANA" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "CLUB DEL COLEGIO MEDICO" },
      { name: "DISTRITO ESCOLAR 16-01" },
      { name: "HOSPITAL DE VILLA LA MATA" },
      { name: "HOSPITAL DR. RAMON BAEZ" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "LOS COROZOS" },
      { name: "PARQUE DUARTE" },
      { name: "CENTRO DE PRIMER NIVEL PIÑA VIAJA" },
      { name: "CENTRO DE PRIMER NIVEL PLATANAL" },
      { name: "CLUB DE LEONES FANTINO " },
    ]
  },
  {
    name: "SANTIAGO",
    "centers": [
      { name: "CLINICA SANTIAGO APOSTOL	" },
      { name: "CLUB CREATIVO:NAVARRETE	" },
      { name: "CLUB HATO DEL YAQUE	" },
      { name: "CLUB MAMBUICHE" },
      { name: "CORAASAN	" },
      { name: "ENSANCHE LIBERTAD (GUG)" },
      { name: "ESCUELA COLORADO" },
      { name: "HOSPITAL IRENE FERNÁNDEZ JÁNICO	" },
      { name: "HOSPITAL LUIS ESPAILLAT SABANA IGLESIA	" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE	" },
      { name: "LICEO EUGENIO DE JESUS MARCANO (TAMBORIL)	" },
      { name: "OMSA CLUB NOEL LOS SALADOS" },
      { name: "PARQUE CENTRAL" },
      { name: "DIRECCIÓN REGIONAL DE SALUD	" },
      { name: "UNIVERSIDAD NAPOLEON NUNEZ MOLINA (LICEY)	" },
    ]
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    "centers": [
      { name: "AYUNTAMIENTO MUNICIPAL MONCIÓN" },
      { name: "ESCUELA ANA JOAQUIN HIDALGO" },
      { name: "LOS BOMBEROS" }
    ]
  },
  {
    name: "SANTO DOMINGO",
    "centers": [
      { name: "DAS-1	CLUB RECREATIVO CULTURAL UNION " },
      { name: "DAS-1	CODECOD (CENTRO DE DESAROLLO)" },
      { name: "DAS-1	GACEBO DEL PARQUE MONTE ADENTRO" },
      { name: "DAS-1	HOSPITAL MUNICIPIAL DE BOCA CHICA" },
      { name: "DAS-8	MULTIUSO PANTOJA" },
      { name: "DAS-2	ARMADA DOMINICANA" },
      { name: "DAS-2	AYUNTAMIENTO SANTO DOMINGO ESTE" },
      { name: "DAS-1	CENTRO DE SALUD LOS FRAILES III" },
      { name: "DAS-1	CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "DAS-2	CLUB EL ROSAL" },
      { name: "DAS-2	CLUB PLAN SOCIAL DE LOS BILLETEROS" },
      { name: "DAS-2	COMEDORES ECONÓMICO" },
      { name: "DAS-2	CENTRO DE PRIMER NIVEL DE ATENCIÓN VIETNAM" },
      { name: "DAS-1	CRUZ ROJA DOMINICANA FILIAR LA CALETA " },
      { name: "DAS-2	DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "DAS-2	EL DIQUE" },
      { name: "DAS-2	ESTACION BOMBEROS CIVILES NO.2" },
      { name: "DAS-1	HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "DAS-2	HOSPITAL DR DARIO CONTRERAS" },
      { name: "DAS-1	HOSPITAL ELVIRA ECHAVARIA" },
      { name: "DAS-2	HOSPITAL MUNICIPAL RALMA" },
      { name: "DAS-2	JUMBO MEGACENTRO" },
      { name: "DAS-2	JUMBO SAN ISIDRO" },
      { name: "DAS-1	MULTIUSO DE INVIVIENDA" },
      { name: "DAS-1	MULTIUSO TAMARINDO" },
      { name: "DAS-2	MULTIUSO URBANIZACION HAMARAP" },
      { name: "DAS-2	PARROQUIA SAN AGUSTIN" },
      { name: "DAS-1	PARRROQUIA SANTO TOMAS VILLA NUEVA" },
      { name: "DAS-1	POLIDEPORTIVO GUERRA" },
      { name: "DAS-1	ZONA FRANCA MEDTRONIC SAN ISIDRO" },
      { name: "DAS-1	FUERZA AEREA DOMINICANA" },
      { name: "DAS-2	COSALUP" },
      { name: "DAS-2	PARQUE DEL ESTE" },
      { name: "DAS-2	AREA II DE SALUD" },
      { name: "DAS-2	PLAN  DE ASISTENCIA SOCIAL DE LA PRESIDENCIA" },
      { name: "DAS-3	BIBLIOTECA MULTIUSO GUARICANO CENTRO" },
      { name: "DAS-3	CENTRO EDUCATIVO RAMONA NERIS SOSA" },
      { name: "DAS-3	ESCUELA LEONCIO MANZUETA" },
      { name: "DAS-3	ESCUELA PARAISO VILLA MELLA" },
      { name: "DAS-3	ESCUELA RAMON MATIAS MELLA" },
      { name: "DAS-3	ESCUELA SAN FELIPE" },
      { name: "DAS-3	HOGAR DE DÍA" },
      { name: "DAS-3	MULTIUSO LA VICTORIA /IGLESIA PARQUE LA VICTORIA" },
      { name: "DAS-3	MULTIUSO SABANA PERDIDA" },
      { name: "DAS-3	CENTRO MEDICO DR. ACEVEDO " },
      { name: "DAS-3	BRIGADA DE APOYO Y SERVICIO ERD" },
      { name: "DAS-3	CENTRO EDUCATIVO MILITAR SAN MIGUEL ARCANGEL" },
      { name: "DAS-3	ESCUELA HARAS NACIONALES " },
      { name: "DAS-3	ESCUELA LA PADRE GARCIA " },
      { name: "DAS-3	FUNDACION MUJERES SALOME UREÑA" },
      { name: "DAS-3	FUNDACION SIGLO XXI" },
      { name: "DAS-3	HOSPITAL MUNICIPAL HACIENDA ESTRELLA " },
      { name: "DAS-3	MULTIUSO DE GUARICANO " },
      { name: "DAS-3	CENTRO POLITECNICO MILITAR SAN MIGUEL ARCANGEL" },
      { name: "DAS-3	ESCUELA HACIENDA ESTRELLA " },
      { name: "DAS-3	FUNDACION EL ALMENDRO " },
      { name: "DAS-7	CENTRO COMUNAL LAS PALMAS" },
      { name: "DAS-1	MULTIUSOS HAINAMOSA" },
      { name: "DAS-7	CENTRO DE SALUD LA HORA DE DIOS" },
      { name: "DAS-7	FUNDACION PEDRO MARTINEZ" },
      { name: "DAS-7	HOSPITAL MARCELINO VELEZ SANTANA" },
      { name: "DAS-7	HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "DAS-1	INSTITUTO TÉCNICO SUPERIOR COMUNITARIO SAN LUIS ( ITSC)" },
      { name: "DAS-7	MULTIUSO EL ABANICO" },
      { name: "DAS-7	PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CENTRO DE PRIMER NIVEL DIAZ PIÑEYRO" },
      { name: "DAS-7	SANTO DOMINGO COUNTRY CLUB" },
      { name: "DAS-7	CENTRO DE PRIMER NIVEL COMUNAL EL CAFÉ/INFOTEP" },
      { name: "DAS-7	CENTRO DE PRIMER NIVELA DE LA MANO CON JESUS" },
      { name: "DAS-7	PARROQUIA ESPIRITU SANTO" },
      { name: "DAS-7	PARROQUIA SAGRADO CORAZON DE JESUS " },
      { name: "DAS-7	UNIVERSIDAD UFHEC" },
      { name: "DAS-7	COSALUP HERRERA" },
      { name: "DAS-7	CENTRO DE PRIMER NIVEL PALAVE" },
      { name: "DAS-7	LABORATORIO ETHICAL  PHARMACEUTICAL       " },
      { name: "DAS-7	ESCUELA REPUBLICA DE JAMAICA " },
      { name: "DAS-7	CEVECERIA BOHEMIA" },
      { name: "DAS-8	CENTRO DE PRIMER NIVEL LA GUAYIGA" },
      { name: "DAS-8	AYUTAMIENTO DE PEDRO BRAND" },
    ]
  },
  {
    name: "VALVERDE",
    "centers": [
      { name: "CLINICA MONTESINO" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "CLUB QUISQUELLA" },
      { name: "CLUB ROTARIO" },
      { name: "COLEGIO MEDICO" },
      { name: "PARROQUIA MARÍA AUXILIADORA MAO" },
      { name: "VALVERDE	UNIDAD DE ATENCION PRIMARIA CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAHORUCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO NORTE" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA CENTRO LAGUNA SALADA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CRUCE DE GUAYACANES" },
      { name: "UNIDAD DE ATENCION PRIMARIA D\ CLASE" },
      { name: "UNIDAD DE ATENCION PRIMARIA DAMAJAGUA" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL SAMAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA ENRIQUILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUALEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUATAPANAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUAYABO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA JAIBON" },
      { name: "UNIDAD DE ATENCION PRIMARIA JICOME" },
      { name: "UNIDAD DE ATENCION PRIMARIA JINAMAGAO" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA JAVILLA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MINA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CAÑITAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CUARENTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS GUAMAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS TRESCIENTAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAGUITAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS HATILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS QUEMADOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS RESTAURADORES" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAIZAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA MANCHADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUERTO RICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUNTA DE GARZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN ANTONIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CANTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA MUÑOZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA NAVARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ORTEGA" },
    ]
  }
];

centros.sort((a, b) => (a.name < b.name ? -1 : 1));
