const centros3 = [
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "PARQUE HAINAMOSA" },
      { name: "CLUB DE ALISTADO FARD" },
      { name: "MULTIUSO LOS FRAILES" },
      { name: "MULTIUSO LOS FRAILES III" },
      { name: "INSTITUTO  ITSC" },
      { name: "CODECO (CENTRO DESARROLLO COMUNITARIO)" },
      { name: "CRUZ ROJA LA CALETA" },
      { name: "MULTIUSO EL TAMARINDO" },
      { name: "HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "HOSPITAL ELVIRA ECHAVARRIA" },
      { name: "POLIDEPORTIVO DE GUERRA" },
      { name: "CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "HOSPITAL LOCAL DE BOCA CHICA" },
      { name: "CLUB LA UNION" },
      { name: "GAZEBO DEL PARQUE MONTE ADENTRO" },
      { name: "PARROQUIA SANTO THOMAS DE VILLA NUEVA" },
      { name: "MULTIUSO INVIVIENDA" },
      { name: "HOSPITAL EL ALMIRANTE" }
    ],
  },
    {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "CLUB DE LOS BILLETEROS" },
      { name: "DOMICILIARIAS" },
      { name: "DOMICILIARIAS DIFERENTES SECTORES" },
      { name: "PARQUE DEL ESTE" },
      { name: "PLAY DE LA ZAFRA" },
      { name: "MULTIUSO HAMARAP" },
      { name: "COSALUP" },
      { name: "CPNA VIETNAM" },
      { name: "AYUNTAMIENTO SDE" },
      { name: "IGLESIA EL CAMINO" },
      { name: "PLAN SOCIAL DE LA PRESIDENCIA" },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "ESCUELA CELINA PELLIER" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "CLUB DEL ROSAL" },
      { name: "HOGAR DE ANCIANOS Y DISCAPACITADOS" },
      { name: "CLINICA ALTAGRACIA" }
    ],
  },
    {
    name: "SANTO DOMINGO NORTE",
    centers: [
      { name: "BIBLIOTECA MULTIUSO GUARICANO CENTRO" },
      { name: "CLUD LOS MOSQUITOS" },
      { name: "MULTIUSO SABANA PERDIDA" },
      { name: "MULTIUSO LA VICTORIA /IGLESIA PARQUE LA VICTORIA" },
      { name: "HOSPITAL NEY ARIAS LORA" },
      { name: "HOSPITAL DR . REYNALDO ALMANZAR" },
      { name: "CLUD MULTIUSO EL CROM" },
      { name: "MULTIUSO SANTA CRUZ IGLESIA CATOLICA" },
      { name: "HOGAR DE DIA SABANA PERDIDA" },
      { name: "DISTRITO 10-01" },
      { name: "DISTRITO 10-02" },
      { name: "CLUB CAMPAÑA" },
      { name: "PUESTO LOS CASTILLOS" },
      { name: "LOS BOMBEROS DE LA VICTORIA" }
    ],
  },
    {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "CENTRO DIAGNÓSTICO BARNEY MORGAN" },
      { name: "CLINICA RODRIGUEZ SANTOS" },
      { name: "COMIPOL" },
      { name: "HOSPITAL DOCTOR FRANCISCO MOSCOSO PUELLO" },
      { name: "CECANOT" },
      { name: "CLINICA CRUZ JIMINIAN" }
    ],
  },
    {
    name: "DISTRITO NACIONAL (DAS-V)",
    centers: [
      { name: "COROMINA  PEPIN" },
      { name: "CENTRO LASER" },
      { name: "PLASTIC CENTER" },
      { name: "PATOLOGIA FORENSE /LAB. NACIONAL" },
      { name: "PLAZA LAMA" },
      { name: "HOSPITAL DE LA POLICIA NACIONAL" },
      { name: "CLUB NACO" },
      { name: "LOS PRADOS" },
      { name: "CLUB INDEPENDENCIA" },
      { name: "HONDURAS" },
      { name: "MOVEARTE" },
      { name: "PCMM" },
      { name: "CLUB MANGANAGUA" },
      { name: "CLUB MIRADOR" },
      { name: "CUSEP" },
      { name: "JUAN LAMBERT" },
      { name: "UNICARIBE" },
      { name: "COLEGIO SAN JUAN BAUTISTA" },
      { name: "SAN CARLOS" },
      { name: "CONAPE" },
      { name: "UNIBE" },
      { name: "DNI" },
      { name: "CENTRO OLIMPICO" },
      { name: "AGORA MALL" },
      { name: "CCN" },
      { name: "CLINICA INDEPENDENCIA" },
      { name: "DISP. TEJADA Y FLORENTINO" },
      { name: "DNCD" },
      { name: "HOSPITAL DE POLICIA NACIONAL" },
      { name: "HOSPITAL ROBERT REID CABRAL" },
      { name: "INAVI" },
      { name: "MIDE" },
      { name: "PLAZA LAMA" },
      { name: "SIRENA" }
    ],
  },
    {
    name: "DISTRITO NACIONAL( DAS-VI)",
    centers: [
      { name: "CARREFOUR" },
      { name: "UNAP CARMEN RENATA" },
      { name: "UNPHU" },
      { name: "HOSPITAL SANTO SOCORRO" },
      { name: "CEDIMAT" },
      { name: "PLAZA DE LA SALUD" }
    ],
  },
    {
    name: "SANTO DOMINGO OESTE (DAS VII)",
    centers: [
      { name: "ASODIFIMO" },
      { name: "MISSION ENMANUEL" },
      { name: "COOPERATIVA DE HERRERA" },
      { name: "CPN COSALUP" },
      { name: "LA HORA DE DIOS" },
      { name: "MULTIUSO SOCORRO MUTUO" },
      { name: "ESCUELA KILOMETRO 13/ESCUELA NUEVA" },
      { name: "MULTIUSO EL ABANICO" },
      { name: "CENTRO COMUNAL LAS PALMAS" },
      { name: "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CPN DIAZ PIÑEYRO" },
      { name: "CLUB DEPORTIVO COLIBRI-PALAVE" },
      { name: "IGLESIA BAUTISTA PASTOR DE OVEJAS" },
      { name: "IGLESIA SAN PEDRO NOLASCO" },
      { name: "ZONA F" },
      { name: "HOSPITAL MARCELINO VELEZ SANTANA" },
      { name: "CPNA DE LA MANO CON JESUS" },
      { name: "PARROQUIA ESPIRITU SANTO" },
      { name: "PRISMA SALUD DOMINICANA" },
      { name: "CPNA LAS CAOBAS" },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "MULTIUSO IVAN GUZMAN KLANG" },
      { name: "ESC. ROSARIO EVANG SOLANO" },
      { name: "COOPERATIVA DE MANOGUAYABO" },
      { name: "DISTRITO ESCOLAR 15-05" },
      { name: "FUNDACION PEDRO MARTINEZ" },
      { name: "OPERACIONES ESPECIALES" },
      { name: "CUERPO ESPECIALIZADO DE SEGURIDAD PORTUARIA, CESEP." },
      { name: "HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "WIND TELECOM" },
      { name: "LAB. REFERENCIA SEDE CENTRAL AV LUPERON" }
    ],
  },
    {
    name: "SAN JUAN",
    centers: [
      { name: "CODIA" },
      { name: "CASINO SAN JUAN" },
      { name: "SALÓN DE CONFERENCIA DE PS SAN JUAN" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "UNAP JUAN HERRERA" },
      { name: "RÍO ARRIBA." },
      { name: "PARQUE SANCHEZ" }
    ],
  },
    {
    name: "MARIA TRINIDAD SANCHEZ",
    centers: [
      { name: "HOSPITAL DR. CARLOS  A. ZAFRA" },
      { name: "HOSPITAL DR.ANTONIO YAPOR HEDED" },
      { name: "HOSPITAL DR. LUIS R. BONILLA" },
      { name: "CPN. MATANCITA" },
      { name: "CPN LOS YAYALES" },
      { name: "CPN LAS GARZAS" },
      { name: "CPN LAS CEJAS" },
      { name: "UASD NUEVA" },
      { name: "CPN.URB. SUR. SAN JOSE DE VILLA" },
      { name: "DPS-MARIA TRINIDAD SANCHEZ (SEGUNDA DOSIS)" },
      { name: "FORTALEZA OLEGARIO TENARES(PERSONAL DEL  EJERCITO)" },
      { name: "UNAP. NAGUA (POLICIA NACIONAL)" },
      { name: "AYUNTAMIENTO  MUNICIPAL  NAGUA" },
      { name: "CPN EL YAYAL" },
      { name: "CPN EL GUAYABO" },
      { name: "CPN LA CORCOBA" },
      { name: "ARROYO AL MEDIO" },
      { name: "CPN.LAS GORDAS" },
      { name: "CPN.MATA BONITA" },
      { name: "LOS RICONES DE BOBA (CPN LAS GORDAS)" },
      { name: "HOSPITAL MUNICIPAL EL FACTOR" },
      { name: "CASA DE FORMACION   SAGRADA FAMILIA" },
      { name: "AYUNTAMIENTO DISTRITO MUNICIPAL EL POZO" },
      { name: "CPN LOS LIMONES" },
      { name: "CPN LA FACTORIA" },
      { name: "CPN.EL PAPAYO" },
      { name: "HOSPITAL DR. VIRGILO GARCIA" },
      { name: "CPN URBANA CABRERA" },
      { name: "CPN. ABREU" },
      { name: "CPN. LOMA ALTA" },
      { name: "CPN. PAYITA" },
      { name: "CPN BAOBA DEL PIÑAL" },
      { name: "CPN. SAN RAFAEL" },
      { name: "CPN COPEYITO" },
      { name: "CPN LA CAPILLA" },
      { name: "CPN LA ENTRADA" },
      { name: "CPN BEJUCO ALAMBRE" },
      { name: "HOSPITAL DR. DESIDERIO ACOSTA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" }
    ],
  },
    {
    name: "SAMANA",
    centers: [
      { name: "POLIDEPORTIVO" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "CENTRO TECNOLOGICO DEL LIMON" },
      { name: "ARMADA DOMINICANA" },
      { name: "CRUCE DE HONDURAS (EDIFICIO BLANCO)" },
      { name: "ESCUELA VOCACIONAL" },
      { name: "ESCUELA LOS GRATINIS" },
      { name: "JUNTA DE VECINOS LOMA DE LA PINA" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "POLIDEPORTIVO" },
      { name: "CENTRO COMUNAL EL COCO" },
      { name: "JUNTA DE VECINOS PUNTA BALANDRA" },
      { name: "AYUNTAMIENTO LAS GALERAS" },
      { name: "SINDICATO DE PORTUARIA" },
      { name: "JUNTA DE VECINOS LOS CACAOS" },
      { name: "LOCAL COOPERATIVA VIEJA" },
      { name: "NANY, VALLE" }
    ],
  },
      {
    name: "PUERTO PLATA",
    centers: [
      { name: "CASA A CASA DPS" },
      { name: "CENTRO MÉDICO DR. BOURNIGAL" },
      { name: "CENTRO MEDICO UTESA" },
      { name: "CLINICA BRUGAL MEJIA LÓPEZ" },
      { name: "CLINICA GREGORIO HERNÁNDEZ" },
      { name: "DIRECCION PROVINCIAL DE SALUD PUERTO PLATA" },
      { name: "ESCUELA PADRE BOIL" },
      { name: "HOSPITAL CANTISANO ARIAS" },
      { name: "HOSPITAL DE VILLA ISABELA (PERSONAL DE SALUD)" },
      { name: "HOSPITAL DOCENTE UNIVERSITARIO RICARDO LIMARDO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL PABLO MORROBEL JIMÉNEZ" }
    ],
  },
      {
    name: "LA ROMANA",
    centers: [
      { name: "CENTRO D. CALETA" },
      { name: "DISPENSARIO L.J.SUAREZ." },
      { name: "DPS LA ROMANA" },
      { name: "HOGAR DEL NIÑO" },
      { name: "HOSPITAL A.F.C." },
      { name: "HOSPITAL BUEN SAMARITANO" },
      { name: "IGLESIA UNIVERSAL DE CRISTO" },
      { name: "POLICIA NACIONAL" },
      { name: "POLICLINICA LOS MULOS" },
      { name: "UNAP CAVALOTO" },
      { name: "UNAP KM14 CUMAYASA" },
      { name: "UNAP LA ROMANA" }
    ],
  },
      {
    name: "PEDERNALES",
    centers: [
      { name: "UNAP#9" },
      { name: "HOSPITAL PROVINCIA DE PEDERNALES" },
      { name: "UNAP #3 Y #4" },
      { name: "UNAP #5 Y#6" },
      { name: "UNAP#7Y #8" }
    ],
  },
      {
    name: "BARAHONA",
    centers: [
      { name: "UCATEBA" },
      { name: "VICENTE NOBLE" },
      { name: "5TA. BRIGADA DE INF. ERD." },
      { name: "ALTO VELO" },
      { name: "BOMBITA" },
      { name: "CABRAL CENTRO" },
      { name: "ENRIQUILLO (CLUB ESTACION 1)" },
      { name: "ENRIQUILLO (CLUB ESTACION 2)" },
      { name: "FONDO NEGRO" },
      { name: "LA CIENEGA" },
      { name: "LA CIENEGA, LICEO LEA MANUELA MORETA" },
      { name: "LICEO FEDERICO ENRRIQUEZ Y CABRAL" },
      { name: "MARIA MONTES" },
      { name: "PALO ALTO (LICEO CRUCE DE PALO)" },
      { name: "PARAISO ESCUELA MENCIA" },
      { name: "POLO" },
      { name: "QUITA CORAZA" },
      { name: "REGIONAL SUR BH POLICIA NACIONAL" },
      { name: "SALINAS" }
    ],
  },
      {
    name: "SANTIAGO (DISTRITO-I)",
    centers: [
      { name: "HOSP. REG. UNI. ARTURO GRULLON" },
      { name: "HOSP. ESTRELLA UREÑA" },
      { name: "CLUB SAMEJI:POLICIAS" },
      { name: "CLINICA SANTIAGO APOSTOL" },
      { name: "TECHADO LOS CIRUELITOS" },
      { name: "ENS. LIBETAD (GUG)" },
      { name: "CIENFUEGO BAJO TECHO" },
      { name: "CLUB MAMBUICHE" },
      { name: "PARQUE CENTRAL" },
      { name: "FORTALEZA SAN LUIS (MILITARES)" },
      { name: "DELIVERY ADULTOS EN CAMA" },
      { name: "TIPIQUITO LOS COCOS" },
      { name: "ZONA FRANCA PISANO" },
      { name: "MEDICA" },
      { name: "PM PLAZA CORAL" },
      { name: "CPN PEDRO GARCIA" },
      { name: "CPN ENS. ESPAILLAT" },
      { name: "CPN PALMAR ABAJO" },
      { name: "CPN LOS PEREZ" },
      { name: "CNP INGENIO ABAJO" },
      { name: "CPN EL LIMON" },
      { name: "CPN LA CUMBRE" },
      { name: "CPN JACAGUA ADENTRO" },
      { name: "CPN SANTA LUCIA" },
      { name: "CPN LLANOS DEL INGENIO" },
      { name: "CPN CJC" },
      { name: "CPN LA GLORIA" },
      { name: "CPN FUNDA AMBIENTE" },
      { name: "CPN LA CRUZ DE GURABO" },
      { name: "CPN MAMACHEN" },
      { name: "CPN ENS. BERMUDEZ" },
      { name: "CPN ANA CRUZ" },
      { name: "CPN RANCHITO PICHET" },
      { name: "CPN PALMARITO" },
      { name: "CPN LA DELGADA" },
      { name: "CPN LA CIENEGAS" },
      { name: "CPN CIENFUEGOS" },
      { name: "CPN VILLA TABACALERA" },
      { name: "CPN VILLA NUEVA (PARQUE)" },
      { name: "CPN EL AGUACATE" },
      { name: "PARQUE DE VILLA GONZALEZ" },
      { name: "CPN JACAGUA ARRIBA" },
      { name: "CPN BANEGAS" },
      { name: "CENTRO TECNOLOGICO" },
      { name: "CPN ESTANCIA DEL YAQUE" },
      { name: "CLUB ROTARIO:NAVARRETE" },
      { name: "CENTRO ADP: NAVARRETE" }
    ],
  },
      {
    name: "SANTIAGO (II)",
    centers: [
      { name: "CONSULTORIO ADVENTISTA" },
      { name: "CPN BELLA VISTA" },
      { name: "CPN INOA" },
      { name: "CPN LA CANELA" },
      { name: "CPN LAS CHARCAS" },
      { name: "CPN LOS PLATANAL" },
      { name: "CPN PEDREGAL" },
      { name: "CPN MAMA TINGO" },
      { name: "CPN LA CUESTA" },
      { name: "HOSPITAL SAJOMA" },
      { name: "HOSP. JANICO" },
      { name: "HOSP. JANICO" },
      { name: "LA JOYA / BARACOA" }
    ],
  },
      {
    name: "SANTIAGO (III)",
    centers: [
      { name: "CENTRO MEDICO CIBAO" },
      { name: "CLINICA BONILLA" },
      { name: "CLINICA COROMINAS" },
      { name: "CLINICA UNION MEDICA" },
      { name: "DOMICILIO" },
      { name: "DOMICILIO" },
      { name: "DOMICILIO" },
      { name: "FORTALEZA FERNANDO VALERIO" },
      { name: "HEMMI" },
      { name: "HOMS" },
      { name: "HOSPITAL DE LICEY" },
      { name: "MATERNO INFALTIL" },
      { name: "UASD" }
    ],
  },
      {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO DIAGNOSTICO" },
      { name: "CENTRO MEDICO JARABACOA" },
      { name: "CENTRO MEDICO PADRE FANTINO" },
      { name: "CLINICA BAEZ SOTO" },
      { name: "CLUB DE LOS ABOGADOS" },
      { name: "CPN BACUI" },
      { name: "CPN BELARMINIO" },
      { name: "CPN BURENDE" },
      { name: "CPN HATILLO" },
      { name: "CPN JUMUNUCU" },
      { name: "CPN LAS UVAS" },
      { name: "CPN LICEY" },
      { name: "CPN MANABAO" },
      { name: "CPN PASO BAJITO" },
      { name: "DISTRITO 06-02" },
      { name: "HOSP. ARMIDA GARCIA" },
      { name: "HOSP. JIMA ABAJO" },
      { name: "HOSP. JUAN ANT. CASTILLO" },
      { name: "HOSP. MORILLO KING" },
      { name: "HOSP. OCTAVIA GAUTIER" },
      { name: "OBRA SOCIAL SALESIANA" },
      { name: "PISCINA OLIMPICA" },
      { name: "POLICLINICO LA VEGA" },
    ],
  },
      {
    name: "BAHORUCO",
    centers: [
      { name: "ESCUELA MARIA PAUSEPIN DE JARAGUA" },
      { name: "ESCUELA ULPINA GONZALEZ DE GALVAN" },
      { name: "LICEO JUAN PABLO DUARTE DE TAMAYO" },
      { name: "LICEO MANUEL DE JESUS GALVAN DE NEYBA" }
    ],
  },
      {
    name: "MONTECRISTI",
    centers: [
      { name: "UNAP EL CENTRO" },
      { name: "UNAP LA GALLERA" },
      { name: "UNAP BARRIO SUR" },
      { name: "UNAP LOS CONUCOS DE VV" },
      { name: "ESCUELA DEL MANANTIAL" },
      { name: "POLIDEPORTIVO MANZANILLO" },
      { name: "UNAP SANTA MARÍA" },
      { name: "UNAP COPEY DE MANZANILLO" },
      { name: "UNAP ALTOS DE LA PALOMA" },
      { name: "UNAP CARBONERA" },
      { name: "CLUB JUAN PABLO DUARTE" },
      { name: "UNAP LOS BOMBEROS" },
      { name: "UNAP LOMA DE CASTAÑUELAS" },
      { name: "UNAP LA CAPITALITA" },
      { name: "UNAP EL AHOGADO" },
      { name: "UNAP EL VIGIADOR" },
      { name: "CASA DE PROMOCION" },
      { name: "RESTAURANTE LILO" },
      { name: "CLUB SAN PEDRO" },
      { name: "UNAP LAS FLORES" },
      { name: "UNAP LOS MAESTROS" },
      { name: "UNAP HERMANAS MIRABAL" },
      { name: "UNAP SANTA BARBARA" },
      { name: "UNAP LOS CONUCOS MC" },
      { name: "UNAP BATEY MADRE" },
      { name: "IGLESIA KM 11" },
      { name: "IGLESIA KM13" },
      { name: "IGLESIA KM 14" },
      { name: "POLIDEPORTIVO DE GUAYUBIN" },
      { name: "UNAP EL POCITO" },
      { name: "UNAP MARTIN GARCIA" },
      { name: "UNAP CERRO GORDO" },
      { name: "UNAP CANA CHAPETON" },
      { name: "UNAP PILOTO" },
      { name: "UNAP VILLA SINDA" },
      { name: "UNAP HATO DEL MEDIO" },
      { name: "UNAP VILLA ELISA" },
      { name: "UNAP LA GUAJACA" },
      { name: "UNAP DOÑA ANTONIA" },
      { name: "UNAP HATILLO PALMA" },
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "OLFANATO ENMANUEL" },
      { name: "UNAP DERRAMADERO" },
      { name: "UNAP EL PAPAYO" },
      { name: "UNAP COPEY GUAYUBIN" },
      { name: "HOSPITAL MUNICIPAL CASTAÑUELAS" },
      { name: "HOSPITAL MUNICIPAL LAS MATAS DE SANTA CRUZ" },
      { name: "HOSPITAL MUNICIPAL GUAYUBIN" },
      { name: "HOSPITAL MUNICIPAL PEPILLO SALCEDO" },
      { name: "HOSPITAL MUNICIPAL VILLA VASQUEZ" }
    ],
  },
      {
    name: "SANTIAGO RODRIGUEZ",
    centers: [
      { name: "POLIDEPORTIVO LOS TOMINES" },
      { name: "ESC. ANA JOAQUINA HIDALGO" },
      { name: "CANCHA GERMAN CASTRO" },
      { name: "UNAP ASIENTO FRIO" },
      { name: "ESCUELA VALLECITO" },
      { name: "HOSPITAL MUNICIPAL MONCION" },
      { name: "UNAP CEPILLO" },
      { name: "UNAP AMAMONCITO" },
      { name: "LOS BOMBEROS" },
      { name: "EL DAJAO" },
      { name: "ESC. DR. CARLOS GONZALES" },
      { name: "OFICINA DE AGRICULTURA" }
    ],
  },
      {
    name: "SAN CRISTOBAL",
    centers: [
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOP. RAFAEL J. MAÑÓN" },
      { name: "COMEDOR ECONÓMICO" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "PARQUE RADHAMES" },
      { name: "CENTRO DIAGNOSTICO VILLA FUNDACIÓN" },
      { name: "CENTRO DIAGNOSTICO MADRE VIEJA SUR" },
      { name: "ESCUELA VILLA MERCEDES Ó IGLESIA CATÓLICA" },
      { name: "VILLA FEDERICO" },
      { name: "IGLESIA FRATERNAL LOS MOLINA" },
      { name: "GONZALES BINNET" },
      { name: "UNAPS PUEBLO" },
      { name: "UNAPS LAVA PIÉ" },
      { name: "HATILLO" },
      { name: "HATO DAMAS" },
      { name: "CANASTICA" },
      { name: "SAINAGUA(CRUCE DE LA PLENA)" },
      { name: "SABANA TORO (UNAP)" },
      { name: "DPS" },
      { name: "HOSPITAL MUNICIPAL - BALSEQUILLO" },
      { name: "UNAP- GERÓNIMO PINALES" },
      { name: "UNAP- EL CARRIL" },
      { name: "UNAP- LA PARED" },
      { name: "UNAP MAMA TINGO" },
      { name: "ORDEN DE MALTA" },
      { name: "UNAP GERÓNIMO PINALES" },
      { name: "CENTRO MEDICO SAN AGUSTÍN" },
      { name: "UNAP DÑA. ANA" },
      { name: "MULTI-USO YAGUATE" },
      { name: "MULTI-USO DE BOCA DE NIGUA" },
      { name: "MULTI-USO SABANA PALENQUE" },
      { name: "HOSP MUNICIPAL DE CAMBITA" },
      { name: "HOSP. MUNIC DE LOS CACAOS" },
      { name: "ESCUELA PEDRO DOMÍNGUEZ" },
      { name: "HOSP. MUNICIPAL NTRA. SEÑORA DE LA ALTAGRACIA" },
      { name: "HOSP. NTRA. SEÑORA DE LA ALTAGRACIA (IDSS)" },
      { name: "UNAPS CUCHILLA" },
      { name: "UNAPS MEDINA" },
      { name: "UNAPS EL MAIZAL" },
      { name: "UNAPS LA REPRESA" }
    ],
  },
      {
    name: "SAN JOSE DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNOSTICO BELLA VISTA" }
    ],
  },
      {
    name: "ESPAILLAT",
    centers: [
      { name: "CENTRO MEDICO GUADALUPE" },
      { name: "DPS ESPAILLAT" },
      { name: "ESCUELA VOCACIONAL" },
      { name: "HOSPITAL TORIBIO BENCOSME" }
    ],
  },
      {
    name: "DUARTE",
    centers: [
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "CENTRO MEDICO NACIONAL" },
      { name: "GRUPO MEDICO UNIDO      SIGLO 21" },
      { name: "HOSPITAL  DR. LEOPOLDO FEDERICO LAVANDIER" },
      { name: "INEMED" },
      { name: "GRUPO MEDICO UNIDO SIGLO 21" },
      { name: "POLICIA NACIONAL" }
    ],
  },
      {
    name: "DAJABON",
    centers: [
      { name: "CAMPAMENTO DE CESFRONT" },
      { name: "FORTALEZA BELLER, E.R.D." },
      { name: "POLIDEPORTIVO AMBROSIO ESTEVEZ DE DAJABON" }
    ],
  },
      {
    name: "PERAVIA",
    centers: [
      { name: "24 DE ABRIL" },
      { name: "ARROYO HONDO" },
      { name: "BOCA CANASTA 1" },
      { name: "BOCA CANASTA 2" },
      { name: "BUENAS NUEVAS" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "EL MANI" },
      { name: "ESCONDIDO I" },
      { name: "ESCONDIDO II" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "HONDURAS" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS CARRERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MATANZAS ABAJO" },
      { name: "MATANZAS ARRIBA" },
      { name: "MAXIMO GOMEZ" },
      { name: "PAYA ABAJO" },
      { name: "PAYA ARRIBA" },
      { name: "PIZARRET I" },
      { name: "PIZARRETE II" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "SALINAS" },
      { name: "SANTA ROSA 1" },
      { name: "SANTA ROSA 2" },
      { name: "SANTA ROSA 3" },
      { name: "SANTANA ARRIBA" },
      { name: "SAONA I" },
      { name: "SAONA II" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA SOMBBRERO 1" },
      { name: "VILLA SOMBRERO 2" },
      { name: "SANTA CRUZ" },
      { name: "PUEBLO NUEVO" },
      { name: "VILLA MEJAGA I" }
    ],
  },
      {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "UNAP ANAYUMA" },
      { name: "UNAP LOS CERRITOS" },
      { name: "UNAP BOCA DE YUMA" },
      { name: "HOSPITAL LAGUNA DE NISIBON" },
      { name: "HOSP. DOCTORA EVANGELINA RODRIGUEZ" },
      { name: "POLIDEPORTIVO" },
      { name: "MULTI-USO RS." },
      { name: "VILLA MAJEGA II" }
    ],
  },
      {
    name: "AZUA",
    centers: [
      { name: "AZUA" },
      { name: "CPN LAS YAYASS 1" },
      { name: "CPN PRADO Y COLONIA" },
      { name: "ESTEBANIA" },
      { name: "HOSPITAL MUNICIPAL P LC" },
      { name: "HOSPITAL REGIONAL TAIWAN" },
      { name: "LAS CHARCAS" },
      { name: "LAS CHARCAS" },
      { name: "LAS CHARCAS" },
      { name: "LAS CHARCAS" },
      { name: "LICEO ROMAN B. CASTRO" },
      { name: "PALMAR DE OCOA" },
      { name: "PALMAR DE OCOA" },
      { name: "PUESTO LICEO B DE CASTRO" },
      { name: "SABANA YEGUA KM-11" },
      { name: "SABANA YEGUA KM-11" },
      { name: "TABARA ARRIBA" },
      { name: "UNAP CUCHILLA" },
      { name: "UNAP CUCHILLA" },
      { name: "UNAP LOS TOROS" },
      { name: "UNAP SAJANOA" },
      { name: "UNAP LOS FRIOS" }
    ],
  },
      {
    name: "EL SEIBO",
    centers: [
      { name: "POLICIA NACIONAL FORTALEZA PEDRO SANTANA." },
      { name: "CTC" },
      { name: "DEFENSA CIVIL" },
      { name: "CENTRO CAMPESINO" },
      { name: "CLUB DE DOMINO" },
      { name: "IGLESIA BENJAMIN" },
      { name: "CENTRO COMUNAL V.G" }
    ],
  },
      {
    name: "ELIAS PIÑA",
    centers: [
      { name: "RINCONCITO" },
      { name: "PEDRO SANTANA" },
      { name: "CESFRONT" },
      { name: "FUERZA ARMADA" }
    ],
  },
      {
    name: "INDEPENDENCIA",
    centers: [
      { name: "14 BATALLON DE INFANTERIA" },
      { name: "CENTRO DIAGNÓSTICO JIMANI" },
      { name: "CESFRON" },
      { name: "CIA. 19 FORTALEZA EL RODEO ERD." },
      { name: "CPN ANGOSTURA" },
      { name: "CPN BARTOLOMÉ" },
      { name: "CPN BATEY 8" },
      { name: "CPN BOCA DE CACHON" },
      { name: "CPN COLONIA MIXTA" },
      { name: "CPN CRISTÓBAL" },
      { name: "CPN EL GUAYABAL" },
      { name: "CPN JIMANI CENTRO" },
      { name: "CPN JIMANI PUEBLO" },
      { name: "CPN JIMANI VIEJO." },
      { name: "CPN LA DESCUBIERTA" },
      { name: "CPN LAS BAITOAS" },
      { name: "CPN LAS MERCEDES" },
      { name: "CPN LOS BOLOS" },
      { name: "CPN LOS PINOS DEL EDÉN" },
      { name: "CPN MELLA" },
      { name: "CPN PLACER BONITO" },
      { name: "CPN POSTRER RÍO" },
      { name: "CPN PUESTO ESCONDIDO" },
      { name: "CPN SAN ISIDRO" },
      { name: "CPN SAN JOSE" },
      { name: "CPN TIERRA NUEVA" },
      { name: "CPN VENGAN A VER" },
      { name: "CPN. EL LIMÓN" },
      { name: "DEFENSA CIVIL DE JIMANI" },
      { name: "DPS INDEPENDENCIA" },
      { name: "HOSP. GENERAL MELENCIANO" },
      { name: "HOSP.MUNI.DUVERGE JOSE PEREZ" },
      { name: "HOSPITAL MUNICIPAL DESCUBIERTA" },
      { name: "LICEO ENRRIQUILLO" },
      { name: "MULTIUSOS HÉCTOR PÉREZ N." }
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "BRIGADA MOVIL" },
      { name: "HOSPITAL DR. ROMÁN BRACHE" },
      { name: "HOSPITAL VILLA TAPIA" },
      { name: "LICEO EMILIANO TEJERA" },
      { name: "PROVINCIAL DE INDEPENDENCIA" },
      { name: "SALCEDO" },
      { name: "TENARES" }
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "CPN 5TA COMANDANCIA POLICIA NACIONAL" },
      { name: "EJERCITO MONTE PLATA" },
      { name: "HOSPITAL MUNICIPAL DE YAMASÁ" },
      { name: "PERSONAL DE SALUD, HOSP. PEDRO HEREDIA" },
      { name: "PERSONAL DE SALUD, HOSPITAL  SANTO CRISTO DE LOS MILAGROS" }
    ],
  },  {
    name: "SANCHEZ RAMIREZ",
    centers: [
      { name: "DISTRITO 16-01" },
      { name: "BAJO TECHO" },
      { name: "COLEGIO MEDICO" },
      { name: "GRAN ARENA (PUEBLO NUEVO)" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "HOSPITAL INMACULADA CONCEPCIÓN" },
      { name: "CPN BARRIO LIBERTAD" },
      { name: "CPN QUITA SUEÑO (AYUTAMIENTO)" },
      { name: "CPN LA ALTAGRACIA" },
      { name: "CPN PEDRO FRANCISCO BONO" },
      { name: "HOSPITAL DR. RAMON BÁEZ" },
      { name: "CPN DUEY" },
      { name: "CPN EL LIMÓN" },
      { name: "CPN LA PLACETA" },
      { name: "CPN ZAMBRANA" },
      { name: "CPN PLATANAL" },
      { name: "CPN LA CRUZ" },
      { name: "DPS" },
      { name: "FORTALEZA PALO HINCADO" },
      { name: "DOMICILIARIO" },
      { name: "HOSPITAL LA MATA" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "CPN LA BIJA" },
      { name: "CPN LOS COROZOS" },
      { name: "CPN HERNANDO ALONZO" },
      { name: "BARRIO LINDO" },
      { name: "CENTRO DIAGNOSTICO" },
      { name: "BAJO TECHO" },
      { name: "CLUB JUAN PABLO DUARTE (CLUB 4 DE JULIO)" },
      { name: "CABALLERO" },
      { name: "COMEDERO ARRIBA" },
      { name: "EL LIMONCITO" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "BATERO" },
      { name: "LA CUEVA" },
      { name: "CPN PESCOZÓN" },
      { name: "PN CUARTEL GENERAL DE COTUÍ" }
    ],
  },  
  {
    name: "VALVERDE",
    centers: [
      { name: "CLUB DE LEONES" },
      { name: "COLEGIO MEDICO" },
      { name: "HOSPITAL LUIS L. BOGAERT" },
      { name: "CLUB DEL CERRO" },
      { name: "UNAP CENTRO" }
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNAP BARRIO LINDO" },
      { name: "UNAP GUALEY" },
      { name: "UNAP GUAYABO DULCE" },
      { name: "UNAP LA JAVILLA" },
      { name: "UNAP LAS CAÑITAS" },
      { name: "UNAP LAS GUAMAS" },
      { name: "UNAP LAS YAGUITAS" },
      { name: "UNAP LOS HATILLOS" },
      { name: "UNAP MANCHADO" },
      { name: "UNAP PUERTO RICO" },
      { name: "UNAP PUNTA DE GARZA" },
      { name: "UNAP VILLA CANTO" },
      { name: "UNAP VILLA NAVARRO" },
      { name: "UNAP VILLA ORTEGA" },
      { name: "DPTO. POLICIA NACIONAL HATO MAYOR" }
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "LAS LIRAS DISTRITO 16-04" },
      { name: "UNAP SABANA DEL PUERTO" },
      { name: "UNAP  JUMA" },
      { name: "UNAP LOS QUEMADOS" },
      { name: "UNAP NUESTRA SRA DE FATIMA" },
      { name: "CLINICA  POLICLINICO BONAO" },
      { name: "HOSP. DR. JOSE A COLUMNA (IDSS)" },
      { name: "UNAP SAN PEDRO SAN PABLO" },
      { name: "UNAP  JAYACO CLUB JUAN BEATO" },
      { name: "UNAP LOS ARROCES" },
      { name: "IGLESIA SANTA ROSA" },
      { name: "PARROQUIA SAN ISIDRO LABRADOR" },
      { name: "UNAP  MAXIMO GOMEZ" },
      { name: "HOSPITAL M. PIEDRA BLANCA" },
      { name: "UNAP EL VERDE" },
      { name: "CENTRO PSICOLOGICO BONAO" },
      { name: "UNAD UNIVERSIDAD ADVENTISTA D" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "UNAP SONADOR" }
    ],
  },
  {
    name: "SAN PEDRO DE MACORIS",
    centers: [
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "COLEGIO MONTE DE SION" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "IGLESIA ASAMBLEA DE DIOS ADONAI" },
      { name: "IGLESIA PENTECOSTAL LUZ DEL FARO" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "CLUB DE LEONES" },
      { name: "UNAP EVANGELINA RODRIGUEZ" },
      { name: "CLINICA DR. DE LEON" },
      { name: "IGLESIA MARANATHA" },
      { name: "DEFENSA CIVIL" },
      { name: "CLUB DE PERIODISTA" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "MULTIUSO" },
      { name: "SALON AYUNTANIENTO" },
      { name: "MULTIUSO" },
      { name: "CENTRO MADRE CARMEN" },
      { name: "BATEY PALOMA" },
      { name: "IGLESIA CATOLICA" },
      { name: "IGLESIA ASAMBLEA DE DIOS" },
      { name: "IGLESIA DE DIOS" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
