const centros1 = [
  {
    name: "SANTO DOMINGO ESTE(DAS-I)",
    centers: [
      { name: "CRUZ ROJA LA CALETA" },
      { name: "POLIDEPORTIVO DE GUERRA" },
    ],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "CLUB DE LOS BILLETEROS" },
      { name: "MIREDEC TURISMO" },
      { name: "MIREDEC TRANSPORTE PUBLICO" },
      { name: "MIREDEC DEPORTE, PERIODISTA" },
      { name: "CLUB EL ROSAL" },
      { name: "AREA II" },
      { name: "ESTACION BOMBEROS CIVIL" },
      { name: "MEGACENTRO" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "JUMBO" },
      { name: "PLAY LA ZAFRA" },
    ],
  },
    {
    name: "SANTO DOMINGO NORTE (DAS-III)",
    centers: [
      { name: "LOS BOMBEROS DE SABANA PERDIDA" },
      { name: "MULTIUSO LA VICTORIA /IGLESIA PARQUE LA VICTORIA" },
      { name: "MULTIUSO SABANA PERDIDA" },
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "CLUB FATIMA OSCAR SANTANA" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "SAMBIL" },
      { name: "FUNDACION ESCOBA" },
      { name: "FUNSAZURSA" },
      { name: "LOS BOMBERITOS" },
    ],
  },
  {
    name: "DISTRITO NACIONAL(DAS-V)",
    centers: [
      { name: "CENTRO OLÍMPICO" },
      { name: "PLAZA LAMA SEÑOR" },
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-VI)",
    centers: [
      { name: "PLAZA DUARTE (CARREFOUR)" },
      { name: "FUSADI" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "HOSPITAL JACINTO MAÑON" },
   ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS VII)",
    centers: [
      { name: "CPN COSALUP" },
      { name: "CPNA DIAZ PIÑEYRO" },
      { name: "MULTIUSO EL ABANICO" },
      { name: "CPNA LAS CAOBAS" },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS VIII)",
    centers: [
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ" },
      { name: "HOSPITAL MUNICIPAL  ALCARRIZOS II" },
      { name: "CUERPO DE BOMBEROS LOS ALCARRIZOS" },
    ],
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "EL CASINO SJ" },
      { name: "HOSPITAL ALEJANDRO CABRAL" },
      { name: "CODIA" },
      { name: "PARQUE SÁNCHEZ" },
      { name: "SALÓN DE CONFERENCIA DPS SAN JUAN" },
      { name: "CPN SABANETA" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "LOS CARTONES" },
      { name: "VILLA CARMEN" },
      { name: "LOS GRINGOS" },
      { name: "LA ESTANCIA" },
      { name: "EL HOYO" },
      { name: "EL NARANJO" },
      { name: "YABONICO" },
      { name: "MATAYAYA" },
      { name: "POZO HONDO" },
      { name: "LOS JOBOS" },
      { name: "VILLA ESPERANZA" },
      { name: "BOHECHIO" },
      { name: "ARROYO CANO" },
      { name: "LA GUAMA" },
      { name: "DERRUMBADERO" },
      { name: "LA RANCHA" },
      { name: "VALLECITO" },
      { name: "EL JOVITO" },
      { name: "LA NAVAJA" },
      { name: "BATISTA" },
      { name: "JUAN HERRERA" },
      { name: "JINOVA" },
      { name: "VALLEJUELO" },
      { name: "CAPULIN" },
      { name: "JORGILLO" },
    ],
  },
  {
    name: "MARIA TRINIDAD SANCHEZ",
    centers: [
      { name: "DPS-MARIA TRINIDAD SANCHEZ" },
      { name: "CASA DE FORMACION  SAGRADA FAMILIA" },
      { name: "HOSPITAL DR. VIRGILO GARCIA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
    ],
  },
  {
    name: "SAMANA",
    centers: [
      { name: "POLIDEPORTIVO" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "CENTRO TECNOLOGICO DEL LIMON" },
      { name: "POLIDEPORTIVO" },
    ],
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "HOSPITAL FRANCISCO A. GONZALVO" },
      { name: "DPS -LA ROMANA PFV." },
      { name: "HOSPITAL ARISTIDES FIALLO CABRAL" },
    ]
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO" },
      { name: "JUANCHO OVIEDO" },
      { name: "OVIEDO PEDERNALES" },
      { name: "UNAP#3 Y #4" },
      { name: "UNAP#5 Y #6" },
      { name: "UNAP#7 Y #8" },
      { name: "UNAP#9" },
    ]
  },
  {
    name: "SANTIAGO (I)",
    centers: [
      { name: "CLUB MADRES LA UNION CIENFIEGO" },
      { name: "CLUB MAMBUICHE" },
      { name: "CLUB NOEL" },
      { name: "ENS. LIBETAD (GUG)" },
      { name: "PARQUE CENTRAL" },
      { name: "TECHADO LOS CIENFUEGOS" },
    ]
  },
  {
    name: "SANTIAGO (II)",
    centers: [
      { name: "CLUB BARACOA" },
      { name: "HOSP. BELLA VISTA" },
      { name: "HOSP. HATO DEL YAQUE" },
    ]
  },
  {
    name: "SANTIAGO (III)",
    centers: [
      { name: "HEMMI" },
      { name: "CPN PALO AMARILLO" },
      { name: "EL EMBRUJO" },
    ]
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO TAMAYO" },
      { name: "DPS BAHORUCO" },
      { name: "CENTRO COMUNAL" },
      { name: "MOVIL GALVAN" },
      { name: "MOVIL NEIBA 1" },
      { name: "MOVIL NEIBA 2" },
    ]
  },
  {
    name: "MONTECRISTI",
    centers: [
      { name: "POLIDEPORTIVO MANZANILLO" },
      { name: "UNAP SANTA MARÍA" },
      { name: "UNAP COPEY DE MANZANILLO" },
      { name: "UNAP ALTOS DE LA PALOMA" },
      { name: "UNAP CARBONERA" },
      { name: "CLUB JUAN PABLO DUARTE" },
      { name: "RESTAURANTE LILO" },
      { name: "CLUB SAN PEDRO" },
      { name: "UNAP LAS FLORES" },
      { name: "UNAP LOS MAESTROS" },
      { name: "UNAP HERMANAS MIRABAL" },
      { name: "UNAP SANTA BARBARA" },
      { name: "UNAP LOS CONUCOS MC" },
      { name: "UNAP BATEY MADRE" },
      { name: "IGLESIA KM13" },
      { name: "IGLESIA KM 14" },
    ]
  },
  {
    name: "SANTIAGO RODRIGUEZ",
    centers: [
      { name: "DPS" },
    ]
  },
  {
    name: "SAN CRISTOBAL",
    centers: [
      { name: "DPS" },
      { name: "HOP. RAFAEL J. MAÑÓN" },
      { name: "NIGUA" },
      { name: "PALENQUE" },
    ]
  },
  {
    name: "SAN JOSE DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNOSTICO BELLA VISTA" },
    ]
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CAPILLA LA ALTAGRACIA" },
    ]
  },
  {
    name: "DAJABON",
    centers: [
      { name: "DPS" },
    ]
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "ROSA NOVA" },
      { name: "SANTANA ARRIBA" },
      { name: "BUENAS NUEVAS" },
      { name: "PIZARRET I" },
      { name: "PIZARRETE II" },
      { name: "LAS BARIAS" },
      { name: "EL CARRETON" },
      { name: "DON GREGORIO I" },
      { name: "VALDESIA" },
      { name: "RIO ARRIBA" },
      { name: "PAYA ARRIBA" },
      { name: "PAYA ABAJO" },
      { name: "MATA GORDA" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "ESCONDIDO I" },
      { name: "ESCONDIDO II" },
      { name: "EL LIMONAL" },
      { name: "VILLA GUERA" },
      { name: "VILLA DAVID" },
      { name: "SAONA I" },
      { name: "SAONA II" },
      { name: "EL MANI" },
      { name: "LOS YAGUARIZOS" },
      { name: "MAXIMO GOMEZ" },
      { name: "VILLA SOMBBRERO 1" },
      { name: "VILLA SOMBRERO 2" },
      { name: "HONDURAS" },
      { name: "LAS TABLAS" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "LAS CARRERAS" },
      { name: "SABANA BUEY" },
      { name: "QUIJA QUIETA" },
      { name: "MATANZAS ARRIBA" },
      { name: "MATANZAS ABAJO" },
      { name: "SALINAS" },
      { name: "LOS TUMBAOS" },
      { name: "ARROYO HONDO" },
      { name: "LAS CALDERAS" },
      { name: "EL LLANO" },
      { name: "SANTA ROSA 1" },
      { name: "SANTA ROSA 2" },
      { name: "SANTA ROSA 3" },
      { name: "BOCA CANASTA 1" },
      { name: "BOCA CANASTA 2" },
      { name: "24 DE ABRIL" },
      { name: "SANTA CRUZ" },
      { name: "PUEBLO NUEVO" },
      { name: "VILLA MEJAGA I" },
      { name: "VILLA MAJEGA II" },
    ]
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "HOTEL HYATT ZIVA" },
      { name: "HOTEL CATOLONIA" },
      { name: "HOTEL GRAND BAVARO PRINCESS" },
      { name: "HOTEL MELIA" },
      { name: "HOTEL RIU" },
      { name: "HOTEL BAHIA PRINCESS" },
      { name: "HOTEL PALLADIUM" },
      { name: "HOTEL BAVARO" },
      { name: "HOTEL NIOKELODEON" },
      { name: "HOTEL LIVE AGUA" },
      { name: "HOTEL ROYALTON" },
      { name: "HOTEL HARO ROCK" },
      { name: "HOTEL ONYX" },
      { name: "HOTEL LOPESAN" },
      { name: "HOTEL MAJESTIC" },
      { name: "HOTEL IBEROESTAR" },
      { name: "HOTEL DREAMS MACAO" },
      { name: "HOTEL SECRET ROYAL,PARA SU" },
    ]
  },
  {
    name: "AZUA",
    centers: [
      { name: "HOSPITAL R. TAIWAN" },
      { name: "PRADO Y COLONIA (CPN)." },
      { name: "CUCHILLA" },
      { name: "BOMBITA" },
      { name: "PARCELERO" },
      { name: "FINCA 6" },
      { name: "LOS JOVILLOS" },
      { name: "V. CORAZON DE JESUS" },
      { name: "ANSONIA" },
      { name: "LAS BARIAS" },
      { name: "BARRERA" },
      { name: "LOS NEGROS" },
      { name: "SABANA YEGUA" },
      { name: "MOD. SAN FCO KM-11" },
      { name: "PROYECTO-4" },
      { name: "PROYECTO-2-C" },
      { name: "GANADERO" },
      { name: "YAYA ABAJO" },
      { name: "YAYA ARRIBA" },
      { name: "VIAJAMA" },
      { name: "C/R MAGUEYAL" },
      { name: "C/R HATO NUEVO" },
      { name: "C/R VILLARPANDO" },
      { name: "C/R LAS CHARCAS" },
      { name: "C/R HATILLO" },
      { name: "C/ PARMAL DE OCOA" },
      { name: "C/R ESTEBANIA" },
      { name: "UNAP PUEBLO VIEJO" },
      { name: "C/ R EL ROSARIO" },
      { name: "LICEO GUAYACANAL" },
      { name: "UNAP EL HIGUERO" },
      { name: "UNAP LOS JOBOS -2" },
      { name: "UNAP LOS JOBOS -1" },
      { name: "MAJAGUAL" },
      { name: "C/R TABARA ARRIBA" },
      { name: "C/R TABARA ABAJO" },
      { name: "C/R SAJANOA" },
      { name: "C/R LOS TOROS" },
      { name: "C/R AMIAMA GOMEZ" },
      { name: "HOSP. MUNICIPAL PLC" },
      { name: "MONTE BONITO" },
      { name: "C/R LA SIEMBRA" },
      { name: "C/R LAS LAGUNAS" },
      { name: "UNAP SANTA ANA" },
      { name: "UNAP VILLA OCOA" },
      { name: "UNAP CAÑITA -A" },
      { name: "UNAP LOS MONTES FRIOS" },
      { name: "HOSPITAL M. GUAYABAL" },
      { name: "PUESTO DE GOBERNACION" },
    ],
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "ESTACION DE BOMBERO LA VEGA" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "ESTACION DE BOMBERO" }
    ],
  },
  {
    name: "ELIAS PIÑA",
    centers: [
      { name: "CENTRO DE COMBATE" },
      { name: "CPN GUANITO" },
      { name: "CPN GUAYABO" },
      { name: "CPN HATO VIEJO" },
      { name: "CPN JUAN SANTIAGO" },
      { name: "CPN LA GALLERA" },
      { name: "CPN LAS DELICIAS" },
      { name: "CPN LAS PALMAS" },
      { name: "CPN MACASIAS" },
      { name: "CPN PEDRO SANTANA" },
      { name: "CPN PINZON" },
      { name: "CPN POTROSO" },
      { name: "CPN RANCHO DE LA GUARDIA" },
      { name: "CPN RINCONCITOS" },
      { name: "CPN ROSA LA PIEDRA" },
      { name: "CPN SABANA CRUZ" },
      { name: "CPN SABANA HIGUERO" },
      { name: "CPN SABANA LARGA" },
      { name: "CPN SABANA MULA" },
      { name: "CTC" },
      { name: "HOGAR DE ANCIANO SAN FRANSCISCO DE ASIS" },
      { name: "HOGAR DE ANCIANO SAN ISIDRO LABRADOR" },
      { name: "HOGAR DE ANCIANOS SANTA TERESA" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL ROSA DUARTE" },
      { name: "POLIDEPORTIVO" },
    ],
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CLINICA EL LIMON" },
      { name: "HOSP.MUNI.DUVERGE JOSE PEREZ" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CUERPO DE BOMBEROS" },
      { name: "LICEO JULIAN JAVIER" },
      { name: "ESCUELA FEDERICO AUGUSTO GONZALEZ" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "HOSPITAL SABANA" },
      { name: "UNAP GONZALO" },
      { name: "AYUNTAMIENTO  DE LOS BOTADOS" },
    ],
  },
  {
    name: "SANCHEZ RAMIREZ",
    centers: [
      { name: "DPS" },
      { name: "COLEGIO MEDICO" },
      { name: "CPN LA MATA" },
      { name: "CPN LA CRUZ" },
      { name: "CPN LA ESTANCIA" },
      { name: "CPN PIÑA VIEJA" },
      { name: "CPN PESCOZÓN" },
      { name: "HOSPITAL DE CEVICOS" },
      { name: "HOSPITAL DE FANTINO" },
      { name: "HOSPITAL DR. RAMON BÁEZ" },
      { name: "HOGAR DE ANCIANOS COTUI" },
      { name: "HOSPITAL INMACULADA CONCEPCIÓN" },
    ],
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "DPS VALVERDE" }
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNAP BARRIO LINDO" },
      { name: "UNAP GUALEY" },
      { name: "UNAP GUAYABO DULCE" },
      { name: "UNAP LA JAVILLA" },
      { name: "UNAP LAS CAÑITAS" },
      { name: "UNAP LAS GUAMAS" },
      { name: "UNAP LAS YAGUITAS" },
      { name: "UNAP LOS HATILLOS" },
      { name: "UNAP MANCHADO" },
      { name: "UNAP PUERTO RICO" },
      { name: "UNAP PUNTA DE GARZA" },
      { name: "UNAP VILLA CANTO" },
      { name: "UNAP VILLA NAVARRO" },
      { name: "UNAP VILLA ORTEGA" },
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "LAS LIRA" },
      { name: "SEGURO SOCIAL" },
      { name: "LOS AMAPOLAS" },
    ],
  },
  {
    name: "SAN PEDRO DE MACORIS",
    centers: [
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "COLEGIO JUAN PABLO DUARTE" },
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "HOSPITAL REGIONAL DR. ANTONIO MUSA" },
      { name: "CEDISA DE LEON" },
      { name: "MEDSORB DOMINICANA" },
      { name: "HOSPITAL PEDRO  MARIA SANTANA" },
      { name: "MONTE DE SION" },
      { name: "GREMIO DE LOS MUELLEROS" },
      { name: "CLINICA DR. DE LEON" },
      { name: "UCE" },
      { name: "DEFENSA CIVIL" },
      { name: "CLUB DE PERIODISTA" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "MULTIUSO" },
      { name: "HOSPITAL ALEJO MARTINEZ" },
      { name: "MULTIUSO" },
      { name: "HOSPITAL SAGRADO CORAZON DE JESUS" },
      { name: "IGLESIA CATOLICA, LOS CONUCOS" },
      { name: "IGLESIA ASAMBLEA DE DIOS, JUAN DOLIO" },
      { name: "IGLESIA DE DIOS, GUAYACANES" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "UNAP PORVENIR" },
      { name: "CLUB DE LEONES" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "CENTRO COMUNAL PUNTA PESCADORA" },
      { name: "CENTRO COMUNAL PUNTA DE GARZA" },
      { name: "CONDOMINIO TORRE MARBELLA" },
      { name: "PODER  JUDICIAL DE SAN PEDRO DE MACORIS" },
      { name: "IGLESIA MARANATHA" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CENTRO COMUNAL GAUTIER" },
      { name: "CENTRO COMUNAL EL PUERTO" },
      { name: "RED DE SALUD" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
