const centros2 = [
  {
    name: "LA ROMANA",
    centers: [
      { name: "SEDE 911" },
      { name: "CENTRO DE ESPECIALIDADES MÉDICAS CEMER" },
      { name: "CENTRO MÉDICO CENTRAL ROMANA" },
      { name: "CENTRO MÉDICO CORAL" },
      { name: "CENTRO MÉDICO DR. ROSARIO" },
      { name: "CENTRO MÉDICO ORIENTAL" },
      { name: "CLÍNICA CANELA I" },
      { name: "CLÍNICA CANELA II" },
      { name: "CLÍNICA DR. CANELO" },
      { name: "CLÍNICA LOS MULOS" },
      { name: "COLEGIO MÉDICO DOMINICANO (CMD)" },
      { name: "CONSULTORIO ODONTÓLOGICO DRA. MARGHERITA" },
      { name: "DISPENSARIO MEDICO DR. LUIS J. SUAREZ" },
      { name: "DISPENSARIO PADRE CAVALOTO" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD LA ROMANA" },
      { name: "GERENCIA DE ÁREA" },
      { name: "HOSPITAL DR. ARISTIDES FIALLO CABRAL" },
      { name: "HOSPITAL EL BUEN SAMARITANO" },
      { name: "HOSPITAL MATERNO INFANTIL DR. FRANCISCO A. GONZALVO" },
      { name: "HOSPITAL MUNICIPAL GUAYMATE" },
      { name: "CENTRO MÉDICO RELAX DENTAL" },
      { name: "SERVICIO MÉDICO DIAGNÓSTICO MANZANO" },
      { name: "UNAP CUCAMA" },
      { name: "UNAP LOS BOMBEROS" },
      { name: "UNAP LOS COCOS" },
      { name: "UNAP VILLA HERMOSA 1-2" },
      { name: "UNAP VILLA REAL" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CENTRO DE ATENCIÓN LA CIENEGA (UNAP)" },
      { name: "CENTRO OLÍMPICO" },
      { name: "CENTRO REGIONAL MAGNOLIA" },
      { name: "HOSPITAL MUNICIPAL DR. JAIME SÁNCHEZ" },
      { name: "HOSPITAL DE REHABILITACIÓN (ASOCIACIÓN DOMINICANA DE REHABILITACIÓN)" },
      { name: "INSTITUTO DERMATÓLOGICO HUMBERTO BOGAERT UNIDAD BARAHONA" },
      { name: "HOSPITAL JAIME SANCHEZ" },
      { name: "HOSPITAL MINICIPAL DE POLO" },
      { name: "HOSPITAL MUNICIPAL DE CABRAL" },
      { name: "HOSPITAL MUNICIPAL DE ENRIQUILLO" },
      { name: "HOSPITAL MUNICIPAL DE PARAISO" },
      { name: "HOSPITAL MUNICIPAL DE SALINAS" },
      { name: "HOSPITAL MUNICIPAL DE VICENTE NOBLE" },
      { name: "HOSPITAL REGIONAL JAIME MOTA", },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BARAHONAL" },
      { name: "SERVICIO NACIONAL DE SALUD" }
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "CENTRO MINUCIPAL LOS RIOS" },
      { name: "CENTRO MUNICIPAL TAMAYO" },
      { name: "HOSPITAL GIL ROLDÁN" },
      { name: "HOSPITAL JULIA SANTANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BAHORUCO" },
      { name: "HOSPITAL SAN BARTOLOMÉ" }
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD PEDERNALES " },
      { name: "HOSPITAL DR. ELIO FIALLO" }
    ],
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "CLÍNICA ESPECIALIZADA INTERNACIONAL LAS TERRENAS" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX EN SÁNCHEZ" },
      { name: "HOSPITAL LIC. PABLO PAULINO, LAS TERRENAS" },
      { name: "HOSPITAL NATIVIDAD ALCALÁ EL LIMÓN" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD SAMANÁ" },
      { name: "HOSPITAL PROVINCIAL DR. LEOPOLDO POU, SANTA BARBARA" }
    ]
  },
  { 
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO MÉDICO DE ESPECIALIDADES VILLA TAPIA (CEMEVIT)" },
      { name: "CENTRO DIAGNOSTICO VILLA TAPIA" },
      { name: "CENTRO MÉDICO DR. RAFAEL GRULLÓN" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL DR. ROMÁN BRACHE" },
      { name: "HOSPITAL DR. ROMAN BAUTISTA BRACHE" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD HERMANAS MIRABAL" },
      { name: "HOSPITAL MUNICIPAL VILLA TAPIA" },
    ] 
  },
  {
    name: "INDEPENDENCIA", 
    centers: [
      { name: "CENTRO DE ATENCION PRIMARIA (UNAP)" },
      { name: "CENTRO DIAGNÓSTICO JIMANÍ" },
      { name: "CPN EL LIMON" },
      { name: "CPN JIMANÍ" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD INDEPENDENCIA" },
      { name: "HOSPITAL PROVINCIAL GENERAL MELENCIANO" },
      { name: "HOSPITAL DR. JOSÉ PÉREZ" },
      { name: "HOSPITAL LA DESCUBIERTA" },
      { name: "HOSPITAL LOS PINOS DEL EDEN" },
      { name: "HOSPITAL MUNICIPAL DE JIMANÍ" },
      { name: "HOSPITAL MUNICIPAL DUVERGÉ" },
    ]
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CENTRO MÉDICO DE LEÓN" },
      { name: "CENTRO MÉDICO ESPECIALIZADO MACORIS" },
      { name: "CENTRO MÉDICO UCE SAN PEDRO DE MACORÍS" },
      { name: "CLÍNICA DR. FRANKLIN PEÑA" },
      { name: "HOSPITAL DR. JAIME OLIVER PINO" },
      { name: "HOSPITAL PEDRO MARÍA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN PEDRO DE MACORÍS" }, 
      { name: "HOSPITAL REGIONAL DR. ANTONIO MUSA" },
    ]
  },
  { 
    name: "HATO MAYOR",
    centers: [
      { name: "ASILO DE ANCIANOS ROMERLIA SALAS DE BARCELÓ" }, 
      { name: "SEDE 9-1-1" },
      { name: "CENTRO DE REHABILITACIÓN DE HATO MAYOR" },
      { name: "DIRECCION PROVINCIAL DE SALUD HATO MAYOR" },
      { name: "HATO MAYOR DEL REY" },
      { name: "HOSPITAL ELUPINA CORDERO" },
      { name: "HOSPITAL LEOPOLDO MARTÍNEZ" },
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "LABORATORIO ALBUERME" },
      { name: "LABORATORIO ODONTOLÓGICOS LOCALES" },
      { name: "LABORATORIO PATRIA RIVAS" },
      { name: "LABORATORIO PUELLO" },
      { name: "LABORATORIO VASQUEZ" },
      { name: "LOCAL LA LOGIA" },
      { name: "HOSPITAL MUNICIPAL SRTA. ELUPINA CORDERO SABANA DE LA MAR" },
    ]
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "ASILO NUESTRA SEÑORA DE LA PROVIDENCIA" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA EL SEIBO (UNAP)" }, 
      { name: "CENTRO MÉDICO DEL ESTE" },
      { name: "CLÍNICA DR. CHAN" },
      { name: "CONSULTORIO FRAY LUIS OREGUI" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD EL SEIBO" },
      { name: "HOSPITAL DR. TEÓFILO HERNÁNDEZ" },
      { name: "HOSPITAL PÚBLICO DE MICHES" },
      { name: "SEDE 9-1-1" },
    ]
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "CENTRO MÉDICO DR. BALTAZAR Y ASOCIADOS, SRL" },
      { name: "CENTRO MÉDICO PUNTA CANA" },
      { name: "CENTRO MEDICO QUIRÚRGICO" },
      { name: "CLÍNICA DOCTOR GIL" },
      { name: "CENTRO MÉDICO DE ORTOPEDIA Y ESPECIALIDADES DR. QUEVEDO" },
      { name: "CLÍNICA DOCTOR VIRGILIO CEDANO" },
      { name: "CLÍNICA DR. PEROZO SRL" },
      { name: "GRUPO MÉDICO LIBERTAD" },
      { name: "HOSPITAL GENERAL Y DE ESPECIALIDADES NUESTRA SEÑORA DE LA ALTAGRACIA (HGENSA)" },
      { name: "HOSPITAL DRA. EVANGELINA RODRIGUEZ" },
      { name: "HOSPITAL IMG BAVARO" },
      { name: "HOSPITAL LAGUNAS DE NISIBON" },
      { name: "HOSPITAL MATERNO INFANTIL" },
      { name: "HOSPITAL NUESTRA SRA. DE LA ALTAGRACIA" },
      { name: "HOSPITEN" },
      { name: "MEDICALL BAVARO" },
      { name: "SERVICIO REGIONAL DE SALUD (SRS)" },
      { name: "SERVIMED LABORATORO" },
      { name: "UNAP ZONA URBANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD LA ALTAGRACIA" },
      { name: "UNAP ZONAS RURALES" },
    ]
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "ASOCIACIÓN AYUDA MUTUA" },
      { name: "AYUNTAMIENTO PROVINCIAL" },
      { name: "CENTRO TECNOLÓGICO" },
      { name: "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN JUAN" },
      { name: "HOSPITAL DR. FEDERICO AYBAR" },
      { name: "HOSPITAL MUNICIPAL DE BOHECHIO" },
      { name: "HOSPITAL MUNICIPAL DE VALLEJUELO" },
      { name: "HOSPITAL MUNICIPAL EL CERCADO" },
      { name: "HOSPITAL MUNICIPAL JUAN HERRERA" },
      { name: "HOSPITAL MUNICIPAL MATAS DE FARFAN" },
      { name: "HOSPITAL REGIONAL DOCENTE DR. ALEJANDRO CABRAL" },
      { name: "IGLESIA ESPÍRITU SANTOS" },
      { name: "POLIDEPORTIVO DE SAN JUAN" },
      { name: "SEDE  9-1-1" },
    ]
  },
  { 
    name: "AZUA",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD AZUA" },
      { name: "HOSPITAL MUNICIPAL DE PERALTA" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL MUNICIPAL NUESTRA SEÑORA DEL CARMEN" },
      { name: "HOSPITAL PADRES LAS CASA" },
      { name: "HOSPITAL TAIWAN" },
    ]
  },
  { 
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO MÉDICO DRA CABRERA" },
      { name: "HOSPITAL BANICA" },
      { name: "HOSPITAL MUNICIPAL HONDO VALLE" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD EL ELÍAS PIÑA" },
      { name: "HOSPITAL ROSA DUARTE" },
    ]
  },
  { 
    name: "VALVERDE",
    centers: [
      { name: "ASILO DE ANCIANOS DE MAO" },
      { name: "CASA CLUB COLEGIO MEDICO MAO" },
      { name: "CENTRO MÉDICO CEMENOR, S,R,L" },
      { name: "CLÍNICA INMANOR" },
      { name: "CLÍNICA DR. MONTESINOS" }, 
      { name: "CLINICA PERPETUO SOCORRO" },
      { name: "CLUB DE LEONES MAO" },
      { name: "COLEGIO MÉDICO DOMINICANO (CMD)" }, 
      { name: "HOSPITAL DR. JOSÉ FAUSTO OVALLES" },
      { name: "HOSPITAL MATERNO INFALTIL JOSE FRANCISCO PEÑA GOME" },
      { name: "HOSPITAL MUNICIPAL LAGUNA SALADA" },
      { name: "HOSPITAL REGIONAL  ING. LUIS L. BOGAERT" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD VALVERDE" },
      { name: "SEDE 911" },
    ]
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [
      { name: "CLÍNICA GRAN PODER DE DIOS" },
      { name: "HOSPITAL DE MONCIÓN" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SANTIAGO RODRÍGUEZ" },
      { name: "HOSPITAL MUNICIPAL VILLA LOS ALMACIGOS" },
      { name: "HOSPITAL PROVINCIAL GENERAL SANTIAGO RODRÍGUEZ" },
    ]
  },
  {
    name: "MONTECRISTI",
    centers: [
      { name: "AYUNTAMIENTO CANA CHAPETON" },
      { name: "CENTRO INTEGRAL ODONTOLÓGICO Y ORTODONCIA" },
      { name: "CLÍNICA GRUPO MÉDICO CARLO CARLOS J.FINLAY" },
      { name: "CLÍNICA DENTAL DR. LUIS PIMETEL" },
      { name: "CLÍNICA DENTAL DR. MATIRDE GONZALEZ" },
      { name: "CLÍNICA DRA. SUERO" },
      { name: "CLÍNICA ODONTOLOGICA NERSON ISIDOR" },
      { name: "CLÍNICA SAN ANTONIO" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MONTECRISTI" },
      { name: "HATILLO PALMA E EL CLUB" },
      { name: "HOSPITAL DE LAS MATAS DE SANTA CRUZ" },
      { name: "HOSPITAL JULIO ALVAREZ ACOSTA" },
      { name: "HOSPITAL MUNICIPAL DE CASTAÑUELA" },
      { name: "HOSPITAL MUNICIPAL GUAYUBIN " },
      { name: "HOSPITAL MUNICIPAL PEPILLO SALCEDO" },
      { name: "HOSPITAL MUNICIPAL VILLA VASQUES" },
      { name: "HOSPITAL PÚBLICO PADRE FANTINO " },
      { name: "LABORATORIO DENTAL ROMULO LORENZO" },
      { name: "MANZANILLO EN EL MULTIUSO" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SAN FERNANDO (UNAP)" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SANTA MARIA (UNAP)" },
      { name: "AYUNTAMIENTO VILLA ELISA" },
    ]
  },
  { 
    name: "DAJABON",
    centers: [
      { name: "CLÍNICA ROSA BENITA" },
      { name: "HOGAR DE ANCIANOS EN VILLA ALEGRE" },
      { name: "HOSPITAL MUNICIPAL DE PARTIDO" },
      { name: "HOSPITAL MUNICIPAL RESTAURACIÓN" },
      { name: "HOSPITAL RAMON ADRIANO VILLALOBOS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DAJABON" },
      { name: "HOSPITAL RAMON MATÍAS MELLA" },
    ]
  },
  { 
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CENTRO DE CIRUGÍA Y ESPECILIDADES MEDICAS MAIMON" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS MONSEÑOR NOUEL" },
      { name: "CENTRO MÉDICO ZONA PROSPERIDAD" },
      { name: "CLINICA CAROLINA DE JESUS" },
      { name: "CLINICA SAN ANTONIO DE PADUA" },
      { name: "CONSULTORIO NUESTRA SRA. DE FATIMA" },
      { name: "DIRECCION PROVINCIAL DE SALUD MONSEÑOR NOUEL" },
      { name: "EPIDEMIOLOGO PROVINCIAL DE SALUD" },
      { name: "HOGAR DE ANCIANOS SAN ANTONIO" },
      { name: "HOSPITAL DR. PEDRO EMILIO DE MARCHENA" },
      { name: "HOSPITAL DR. JOSE A. COLUMNA" },
      { name: "HOSPITAL MARCHENA NUEVO" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL DE PIEDRA BLANCA" },
      { name: "CENTRO MEDICO PLAN DIENTE SANO" },
    ]
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO MEDICO CEMEVE" },
      { name: "CENTRO DIAGNOSTICO Y DE ATENCION PRIMARIA LA VEGA" },
      { name: "CENTRO MEDICO PADRE FANTINO, S.R.L. " },
      { name: "CLINICA 5TO. CENTENARIO" },
      { name: "CLINICA BAEZ SOTO SRL" },
      { name: "CLINICA LA CONCEPCION" },
      { name: "DIRECCIOB PROVINCIAL DE SALUD LA VEGA" },
      { name: "HOSPITAL DRA. ARMIDA GARCIA" },
      { name: "HOSPITAL JIMA ABAJO" },
      { name: "HOSPITAL JUAN ANTONIO CASTILLO (CUTUPU)" },
      { name: "HOSPITAL PROFESOR JUAN BOSCH" },
      { name: "HOSPITAL REGIONAL UNIVERSITARIO DR. LUIS ML. MORILLO KING" },
      { name: "POLICLINICO LA VEGA, S.A" },
      { name: "REGIONAL DE SALUD 8" },
    ]
  },
  { 
    name: "SÁNCHEZ RAMÍREZ",
    centers: [
      { name: "CENTRO MEDICO AMK DENTAL" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS" },
      { name: "CENTRO DE EUDIRIS SOTO" },
      { name: "CENTRO DENTAL DRA. ELVIRA THEN" },
      { name: "CENTRO DIAGNOSTICO COTUI" },
      { name: "CENTRO DIAGNOSTICO DE FANTINO" },
      { name: "CENTRO DIAGNOSTICO VILLA LA MATA" },
      { name: "CENTRO MEDICO NUÑEZ HERNANDEZ" },
      { name: "CENTRO ODONTOLOGICO DISLA NUÑEZ" },
      { name: "CLINICA CECIESMED" },
      { name: "CLINICA DR. JACOBO" },
      { name: "CLINICA DR. PAREDES" },
      { name: "CLINICA GUADALUPE" },
      { name: "CLINICA LAS MERCEDES" },
      { name: "CLINICA NUESTRA SRA. DEL PILAR" },
      { name: "CONSULTORIO INMACULADA CONCEPCION" },
      { name: "CONSULTORIO UTECO" },
      { name: "CPN SANCHEZ RAMIREZ" },
      { name: "DIRECCION DE AREA DE SALUD SÁNCHEZ RAMÍREZ" },
      { name: "DIRECCION PROVINCIA DE SALUD SANCHEZ RAMIREZ" },
      { name: "HOGAR DE ANCIANOS CLUB DE LEONES INMACULADA CONCEPCIÓN" },
      { name: "HOGAR DE DIA VILLA LA MATA" },
      { name: "HOSPITAL CEVICO" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "HOSPITAL MUNICIPAL FANTINO (SIGFREDO ALBA)" },
      { name: "HOSPITAL RAMÓN BÁEZ" },
      { name: "HOSPITAL SIGIFREDO ALBA DOMINGUEZ" },
      { name: "HOSPITAL VILLA LA MATA" },
      { name: "DIRECCION PROVINCIAL DE SALUD " },
      { name: "CENTRO MEDICO ODNONTOCLINIC" },
      { name: "CENTRO MEDICO ORAL IMPLANT RD" },
      { name: "SEDE  9-1-1 SÁNCHEZ RAMÍREZ" },
    ]
  }
].sort((a, b) => (a.name < b.name ? -1 : 1));
