const centros = [
  {
    name: "SANTO DOMINGO ESTE",
    centers: [
      { name: "AREA II SALUD" },
      { name: "CENTRO DE PRIMER NIVEL DE ATENCIÓN VIETNAM" },
      { name: "CENTRO DE PRIMER NIVEL EL DIQUE" },
      { name: "CLUB EL ROSAL" },
      { name: "CLUB PLAN SOCIAL DE LOS BILLETEROS" },
      { name: "CUERPO DE BOMBERO" },
      { name: "MULTIUSO DE INVIVIENDA" },
      { name: "MULTIUSO TAMARINDO" },
      { name: "PARQUE DE HAINAMOSA " },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "PARRROQUIA SANTO TOMAS VILLA NUEVA" },
      { name: "PLAN SOCIAL DE LA PRESIDENCIA " },
      { name: "PLAY LA ZAFRA" },
      { name: "SUPERMERCADO BRAVO" },
      { name: "COSALUP" },
      { name: "FUNDACIÓN CORREA VALDEZ" },
      { name: "IGLESIA METODISTA LIBRE" },
      { name: "MULTICENTRO LA SIRENA" },
      { name: "PARQUE DEL ESTE" },
    ],
  },
  {
    name: "SANTO DOMINGO NORTE",
    centers: [
      { name: "MULTIUSO SANTA CRUZ IGLESIA CATOLICA" },
      { name: "ESCUELA OTILIA PELAES " },
      { name: "IGLESIA PENTECOSTAL MISION INTERNACIONAL " },
      { name: "MULTIUSO EL CROM" },
      { name: "PAROQUIA SAN LUIS BELTRAN " },
    ],
  },
  {
    name: "DISTRITO NACIONAL",
    centers: [
      { name: "AGORA MALL" },
      { name: "AGRUCUDEGUA" },
      { name: "CENTRO CUESTA NACIONAL (CCN)" },
      { name: "CENTRO DE PRIMER NIVEL SAN CARLOS" },
      { name: "CENTRO OLÍMPICO" },
      { name: "CLUB INDEPENDENCIA" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CLUB LOS PRADOS" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "CLUB NACO" },
      { name: "FUNDACION ESCOBA" },
      { name: "FUNSAZURZA" },
      { name: "HONDURAS" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "MERCASID" },
      { name: "MULTICENTRO LA SIRENA" },
      { name: "PLAZA DUARTE (CARREFOUR)" },
      { name: "PLAZA LAMA" },
      { name: "UNIVERSIDAD NACIONAL PEDRO HENRIQUEZ UREÑA (UNPHU)" },
      { name: "HOSPITAL JACINTO MAÑON " },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL COSALUD" },
      { name: "CENTRO DE PRIMER NIVEL LAS CAOBAS" },
      { name: "CUERPO DE BOMBEROS LOS ALCARRIZOS" },
      { name: "HOSPITAL DOCTOR RODOLFO DE LA CRUZ LORA" },
      { name: "HOSPITAL MUNICIPAL ALCARRIZOS II" },
      { name: "MULTIUSO EL ABANICO" },
      { name: "MULTIUSO PANTOJA" },
      { name: "MULTIUSO SOCORRO MUTUO" },
      { name: "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CPN DIAZ PIÑEYRO" },
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ" },
      { name: "COLINAS DEL NORTE" },
      { name: "CUERPO DE BOMBEROS VILLA LINDA" },
      { name: "FENATRADO" },
      { name: "SUPERMERCADO OLE" },
      { name: "MULTICENTRO LA SIRENA" },
    ],
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CLUB COME MORO" },
      { name: "CLUB DIEGO DE VELAZQUEZ" },
      { name: "CODIA" },
      { name: "EL CASINO SAN JUAN" },
      { name: "HOSPITAL ALEJANDRO CABRAL" },
      { name: "PARQUE SÁNCHEZ" },
      { name: "SALÓN DE CONFERENCIA DPS SAN JUAN" },
      { name: "UNAP ARROYO CANO" },
      { name: "UNAP BATISTA" },
      { name: "UNAP BOHECHIO" },
      { name: "UNAP BUENA VISTA DEL YAQUE" },
      { name: "UNAP CAPULIN" },
      { name: "UNAP DERRUMBADERO" },
      { name: "UNAP EL JOVITO" },
      { name: "UNAP EL NARANJO" },
      { name: "UNAP JINOVA" },
      { name: "UNAP JORGILLO" },
      { name: "UNAP JUAN HERRERA" },
      { name: "UNAP LA ESTANCIA" },
      { name: "UNAP LA NAVAJA" },
      { name: "UNAP LA RANCHA" },
      { name: "UNAP LOS CARTONES" },
      { name: "UNAP LOS GRINGOS" },
      { name: "UNAP MATAYAYA" },
      { name: "UNAP POZO HONDO" },
      { name: "UNAP VALLECITO" },
      { name: "UNAP VALLEJUELO" },
      { name: "UNAP VILLA CARMEN" },
      { name: "UNAP VILLA ESPERANZA" },
      { name: "UNAP YABONICO" },
      { name: "CORBANO SUR 1" },
      { name: "UNAP EL ROSARIO" },
      { name: "UNAP HATO NUEVO" },
    ],
  },
  {
    name: "MARIA TRINIDAD SANCHEZ",
    centers: [
      { name: "AYUNTAMIENTO DEL POZO" },
      { name: "DPS-MARÍA TRINIDAD SANCHEZ" },
      { name: "HOSPITAL DR. ANTONIO YAPOR HEDED" },
      { name: "POLIDEPORTIVO CABRERA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
    ],
  },
  {
    name: "SAMANA",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO DEL LIMÓN" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "POLIDEPORTIVO" },
      { name: "SINDICATO DE LA PORTUARIA" },
      { name: "UNAP" },
      { name: "UNAP LA MAJAGUA" },
    ],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "AYUNTAMIENTO DE CABARETE" },
      { name: "AYUNTAMIENTO DE SOSUA" },
      { name: "CENTRO DE PRIMER NIVEL DOLORES DE LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL NAVAS" },
      { name: "CENTRO DE PRIMER NIVEL SABANETA DE YASICA" },
      { name: "CENTRO DE PRIMER NIVEL YASICA" },
      { name: "CLUB DE YASICA ARRIBA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "HOSPITAL MUNICIPAL DE ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE GUANANICO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE LOS HIDALGOS" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "HOTEL BLUE RAY" },
      { name: "IGLESIA EL SHADDAI" },
      { name: "LIGA DE ATLANTICO" },
      { name: "PLAY DE LA FORTALEZA DEL EJERCITO" },
      { name: "PLAY DE PADRE LAS CASAS" },
      { name: "POLIDEPORTIVO PUERTO PLATA" },
    ],
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "ASOMIRO" },
      { name: "CENTRO DIAGNOSTICO CALETA" },
      { name: "DPS LA ROMANA" },
      { name: "HOGAR DEL NIÑO " },
      { name: "HOSPITAL ARÍSTIDES FIALLO CABRAL" },
      { name: "HOSPITAL GUAYMATE" },
      { name: "HOSPITAL SAMARITANO" },
      { name: "IGLESIA MARANAHTA." },
      { name: "IGLESIA SANTA ROSA DE LIMA" },
      { name: "POLIDEPORTIVO LA ROMANA" },
      { name: "SICHOEM" },
      { name: "UNAP CALETA" },
      { name: "CENTRO COMUNAL " },
      { name: "CLINICA LOS MULOS " },
      { name: "H. F. A. GONZALVO " },
      { name: "HIPER MERCADO ROMANA " },
      { name: "IGL. UNIVERSAL DE CRISTO " },
      { name: "IGLESIA APOSTOLICA EL MAESTRO " },
      { name: "KM14 DE CUMAYASA " },
      { name: "LUIS J. SUAREZ " },
      { name: "MULTIUSO SAN EDUARDO " },
      { name: "NIÑOS DE CRISTO " },
      { name: "ORENSE VILLA HERMOSA " },
      { name: "PADRE CAVALOTO " },
      { name: "PAULINA JIMENEZ " },
      { name: "PLAZA LAMA " },
      { name: "POLICLINICA DUARTE " },
      { name: "UNAP CUCAMA " },
      { name: "UNAP HIGUERAL " },
      { name: "UNAP TOMAS DESIR " },
      { name: "UNAP VILLA REAL " },
      { name: "VILLA HERMOSA 4 " },
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "DPS PEDERNALES" },
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO" },
      { name: "UNAP OVIEDO PEDERNALES" },
      { name: "UNAP#3 Y #4" },
      { name: "UNAP#5 Y #6" },
      { name: "UNAP#7 Y #8" },
      { name: "UNAP#9" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CLUB ENRIQUILLO" },
      { name: "HOSPITAL MUNICIPAL ENRIQUILLO" },
      { name: "PARAISO UNAP 1 Y 2" },
      { name: "PARAISO UNAP 3 Y 4" },
      { name: "PLAZA COMUNAL VICENTE NOBLE" },
      { name: "POLO CENTRO COMUNAL" },
      { name: "UNAP ARROYO DULCE" },
      { name: "UNAP BAHORUCO" },
      { name: "UNAP LA CIENAGA" },
      { name: "UNAP LOS BLANCOS" },
      { name: "UNAP LOS COCOS" },
      { name: "UNAP LOS PATOS" },
    ],
  },
  {
    name: "SANTIAGO",
    centers: [
      { name: "CENTRO INTEGRAL BELLA VISTA" },
      { name: "CLUB BARACOA" },
      { name: "CLUB HATO DEL YAQUE" },
      { name: "PARQUE CENTRAL" },
      { name: "TECHADO CIENFUEGO" },
      { name: "TECHADO LOS CIRUELITOS " },
      { name: "TIPIQUITO LOS COCOS " },
      { name: "CLUB EMBRUJO III" },
      { name: "CLUB HERMANOS PATIÑO" },
      { name: "CLUB MAMBUICHE" },
      { name: "ENSANCHE LIBETAD (GUG)" },
      { name: "OFTALMOLASER " },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "DPS BAHORUCO NEYBA" },
      { name: "MULTIUSO JARAGUA" },
      { name: "MULTIUSO NEYBA" },
      { name: "MULTIUSO TAMAYO" },
      { name: "UASD NEYBA" },
      { name: "UNAP APOLINAR PERDOMO" },
      { name: "UNAP CABEZA DE TORO" },
      { name: "UNAP LAS PIEDRAS" },
      { name: "UNAP LAS SABILAS" },
      { name: "UNAP UVILLA" },
      { name: "AYUNTAMIENTO LOS RÍOS" },
      { name: "AYUNTAMIENTO MONSERRATE" },
      { name: "CUERPO DE BOMBEROS" },
    ],
  },
  {
    name: "MONTECRISTI",
    centers: [
      { name: "AYUNTAMIENTO DE CANA CHAPETON" },
      { name: "CENTRO COMUNAL LOMA DE CASTAÑUELAS" },
      { name: "CENTRO DE PRIMER NIVEL SANTA BARBARA" },
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "CLUB DEPORTIVO Y CULTURAL SAN PEDRO" },
      { name: "CLUB JUAN PABLO DUARTE" },
      { name: "IGLESIA KM. 14" },
      { name: "POLIDEPOIRTIVO DE GUAYUBIN" },
      { name: "POLIDEPORTIVO DE CASTAÑUELAS" },
      { name: "POLIDEPORTIVO DE LAS MATAS" },
      { name: "POLIDEPORTIVO DE MANZANILLO" },
      { name: "RESTAURANTE LILO" },
      { name: "UNAP ALTO DE LA PALOMA" },
      { name: "UNAP BARRIO SUR" },
      { name: "UNAP BATEY MADRE" },
      { name: "UNAP CERRO GORDO" },
      { name: "UNAP COPEY DE GUAYUBIN" },
      { name: "UNAP COPEY PEPILLO SALCEDO" },
      { name: "UNAP DERRAMADEROS" },
      { name: "UNAP EL AHOGADO" },
      { name: "UNAP EL CENTRO" },
      { name: "UNAP EL POCITO DE GUAYUBIN" },
      { name: "UNAP EL VIGIADOR" },
      { name: "UNAP HATILLO PALMA" },
      { name: "UNAP HERMANAS MIRABAL" },
      { name: "UNAP LA CAPITALITA" },
      { name: "UNAP LA GALLERA" },
      { name: "UNAP LAS FLORES" },
      { name: "UNAP LAS MATAS" },
      { name: "UNAP LOS CONUCOS (VV)" },
      { name: "UNAP LOS CONUCOS MC" },
      { name: "UNAP MARTIN GARCIA" },
      { name: "UNAP PILOTO" },
      { name: "UNAP SANTA CRUZ" },
      { name: "UNAP SANTA MARIA" },
      { name: "UNAP VILLA ELISA" },
      { name: "UNAP VILLA SINDA" },
      { name: "IGLESIA KM 13" },
    ],
  },
  {
    name: "SANTIAGO RODRIGUEZ",
    centers: [
      { name: "HOSPITAL MUNICIPAL" },
      { name: "LOS BOMBEROS" },
      { name: "DPS SANTIAGO RODRIGUEZ" },
      { name: "COLA REAL" },
      { name: "CLUB LA CEIBA" },
    ],
  },
  {
    name: "SAN CRISTOBAL",
    centers: [
      { name: "COLEGIO SAN RAFAEL" },
      { name: "DPS SAN CRISTOBAL" },
      { name: "HOSPITAL J. MAÑON" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOSPITAL M. HAINA" },
      { name: "CENTRO DIAGNOTICO MVN" },
      { name: "DISPENSARIO MEDICO SAN AGUSTIN" },
    ],
  },
  {
    name: "SAN JOSE DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "PARQUE CENTRAL OCOA  " },
      { name: "PARQUE CENTRAL FRANCISCO CAAMAÑO" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "CANCHA MUNICIPAL" },
      { name: "CENTRO DE PRIMER NIVEL ALGARROBO" },
      { name: "CENTRO DE PRIMER NIVEL BATEY GINEBRA" },
      { name: "CENTRO DE PRIMER NIVEL BOCA FERREA" },
      { name: "CENTRO DE PRIMER NIVEL BONAGUA" },
      { name: "CENTRO DE PRIMER NIVEL CANCA LA REYNA" },
      { name: "CENTRO DE PRIMER NIVEL CUERO DURO" },
      { name: "CENTRO DE PRIMER NIVEL DE GUAUCI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAIMITO" },
      { name: "CENTRO DE PRIMER NIVEL EL COROZO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA CEIBA DE MADERA" },
      { name: "CENTRO DE PRIMER NIVEL LA ERMITA" },
      { name: "CENTRO DE PRIMER NIVEL LA GUAMA" },
      { name: "CENTRO DE PRIMER NIVEL LA ISLETA" },
      { name: "CENTRO DE PRIMER NIVEL LA MANZANA" },
      { name: "CENTRO DE PRIMER NIVEL LA YAGUA" },
      { name: "CENTRO DE PRIMER NIVEL LAS FLORES" },
      { name: "CENTRO DE PRIMER NIVEL LAS GUAZUMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS LAGUNAS" },
      { name: "CENTRO DE PRIMER NIVEL LOS BRAZOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LOS PANCHOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS PUENTES" },
      { name: "CENTRO DE PRIMER NIVEL MANUEL RODRIGUEZ" },
      { name: "CENTRO DE PRIMER NIVEL MONTE DE LA JAGUA" },
      { name: "CENTRO DE PRIMER NIVEL NUEVO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL ORTEGA" },
      { name: "CENTRO DE PRIMER NIVEL PALMA HERRADA" },
      { name: "CENTRO DE PRIMER NIVEL QUEBRADA HONDA" },
      { name: "CENTRO DE PRIMER NIVEL REPARADERO" },
      { name: "CENTRO DE PRIMER NIVEL SAL SI PUEDES" },
      { name: "CENTRO DE PRIMER NIVEL SAN VICTOR" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA DURA" },
      { name: "CENTRO DE PRIMER NIVEL VERAGUA" },
      { name: "CENTRO DE PRIMER NIVEL VIEJO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CAFETALERA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA PROGRESO" },
      { name: "CENTRO DE PRIMER NIVEL ZAFARRAYA" },
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CLUB LIBERTAD GASPAR HERNANDEZ" },
      { name: "CLUB MUNICIPAL JAMAO AL NORTE" },
      { name: "CLUB RECREATIVO " },
      { name: "DISTRITO 06-01 JOSE CONTRERAS" },
      { name: "ESCUELA LOS RINCONES" },
      { name: "HOSPITAL JOSÉ CONTRERAS" },
      { name: "SALON DON BOSCO KM1" },
      { name: "CENTRO DE PRIMER NIVEL JOSE HORASIO" },
      { name: "LOGIA PERSEVERANCIA" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "ARENA 57 DE PIMENTEL" },
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "CASA CURIAL" },
      { name: "CATEDRAL SANTA ANA - JUAN XXIII" },
      { name: "CENTRO COMUNAL DE CASTILLO" },
      { name: "CENTRO MÉDICO DOCTOR OVALLE" },
      { name: "CENTRO MÉDICO SIGLO 21" },
      { name: "CLUB ANACAONA" },
      { name: "CLUB BLUE LANC" },
      { name: "CLUB HERMANAS MIRABAL" },
      { name: "CLUB MIGUEL GELABERT" },
      { name: "MULTIUSO ARENOSO" },
      { name: "MULTIUSOS VILLA RIVAS" },
      { name: "BOMBA DE YAIBA" },
      { name: "UNAP ARENOSO" },
      { name: "UNAP CASTILLO" },
      { name: "UNAP ENCAMADOS VILLA RIVAS" },
      { name: "UNAP GENIMO" },
      { name: "UNAP LAS GUARANAS" },
      { name: "UNAP PIMENTEL" },
      { name: "UNAP SAN FRANCISCO DE MACORIS" },
    ],
  },
  {
    name: "DAJABON",
    centers: [
      { name: "DPS DAJABON" },
      { name: "POLI DEPORTIVO AMBRIOSO ESTEVEZ" },
      { name: "ADEPA" },
    ],
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "24 DE ABRIL" },
      { name: "ARROYO HONDO" },
      { name: "BOCA CANASTA 1" },
      { name: "BOCA CANASTA 2" },
      { name: "BUENAS NUEVAS" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "EL MANI" },
      { name: "ESCONDIDO I" },
      { name: "ESCONDIDO II" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "HONDURAS" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS CARRERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MATANZAS ABAJO" },
      { name: "MATANZAS ARRIBA" },
      { name: "MAXIMO GOMEZ" },
      { name: "PAYA ABAJO" },
      { name: "PAYA ARRIBA" },
      { name: "PIZARRETE I" },
      { name: "PIZARRETE II" },
      { name: "PUEBLO NUEVO" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "SALINAS" },
      { name: "SANTA CRUZ" },
      { name: "SANTA ROSA 1" },
      { name: "SANTA ROSA 2" },
      { name: "SANTA ROSA 3" },
      { name: "SANTANA ARRIBA" },
      { name: "SAONA I" },
      { name: "SAONA II" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA MAJEGA I" },
      { name: "VILLA MAJEGA II" },
      { name: "VILLA SOMBRERO 1" },
      { name: "VILLA SOMBRERO 2" },
    ],
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "HOTEL LOPESAN" },
      { name: "HOTEL NOW ONIX RS. " },
      { name: "HOTEL RIU RS. PLAYA BAVARO" },
      { name: "HOTEL SECRET PUNTA CANA RS. " },
      { name: "MULTIUSO" },
      { name: "PLAYA JARABILLO P. C. 6- HOTEL SECRET ROYAL AV. ALEMANIA" },
      { name: "UASD LA ALTAGRACIA" },
    ],
  },
  {
    name: "AZUA",
    centers: [
      { name: "ASODEMA" },
      { name: "CENTRO DE PRIMER NIVEL GANADERO" },
      { name: "CENTRO DE PRIMER NIVEL LA BOMBITA" },
      { name: "CENTRO DE PRIMER NIVEL MAGUEYAL" },
      { name: "CENTRO DE SALUD FINCA 6" },
      { name: "CLINICA RURAL AMIAMA GOMEZ" },
      { name: "CLINICA RURAL ANSONIA" },
      { name: "CLINICA RURAL BARRERAS" },
      { name: "CLINICA RURAL EL CARRIZAL" },
      { name: "CLINICA RURAL EL ROSARIO" },
      { name: "CLINICA RURAL ESTEBANIA" },
      { name: "CLINICA RURAL HATILLO" },
      { name: "CLINICA RURAL HATO NUEVO" },
      { name: "CLINICA RURAL LAS BARIAS" },
      { name: "CLINICA RURAL LAS LAGUNAS" },
      { name: "CLINICA RURAL LOS NEGROS" },
      { name: "CLINICA RURAL LOS TOROS" },
      { name: "CLINICA RURAL MONTE BONITO" },
      { name: "CLINICA RURAL PALMAR DE OCOA" },
      { name: "CLINICA RURAL PROYECTO-2-C" },
      { name: "CLINICA RURAL PROYECTO-4 YSURA" },
      { name: "CLINICA RURAL SABANA YEGUA" },
      { name: "CLINICA RURAL SAJANOA" },
      { name: "CLINICA RURAL TABARA ABAJO" },
      { name: "CLINICA RURAL TABARA ARRIBA" },
      { name: "CLINICA RURAL VIAJAMA" },
      { name: "CLINICA RURAL VILLARPANDO" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL TAIWAN" },
      { name: "LOS JOVILLOS" },
      { name: "MOD. SAN FCO KM-11" },
      { name: "PRADO Y COLONIA (CPN)." },
      { name: "PUESTO DE GOBERNACION" },
      { name: "UNAP CAÑITA -A" },
      { name: "UNAP EL HIGUERO" },
      { name: "UNAP LA CUCHILLA" },
      { name: "UNAP LAS YAYAS ARRIBA" },
      { name: "UNAP LOS JOBOS -1" },
      { name: "UNAP LOS JOBOS -2" },
      { name: "UNAP LOS MONTES FRIOS" },
      { name: "UNAP LOS PARCELEROS" },
      { name: "UNAP MAJAGUAL" },
      { name: "UNAP PUEBLO VIEJO" },
      { name: "UNAP SANTA ANA" },
      { name: "UNAP VILLA CORAZON DE JESUS" },
      { name: "UNAP VILLA OCOA" },
      { name: "YAYA ABAJO" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "BOMBERO" },
      { name: "CTC" },
    ],
  },
  {
    name: "ELIAS PIÑA",
    centers: [
      { name: "CENTRO DE COMBATE" },
      { name: "CENTRO DE PRIMER NIVEL GUANITO" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN SANTIAGO" },
      { name: "CENTRO DE PRIMER NIVEL LAS PALMAS" },
      { name: "CENTRO DE PRIMER NIVEL PEDRO SANTANA" },
      { name: "CENTRO DE PRIMER NIVEL PINZON" },
      { name: "CENTRO DE PRIMER NIVEL POTROSO" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO DE LA GUARDIA" },
      { name: "CENTRO DE PRIMER NIVEL RINCONCITOS" },
      { name: "CENTRO DE PRIMER NIVEL ROSA LA PIEDRA" },
      { name: "CENTRO DE PRIMER NIVEL SABANA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL SABANA HIGUERO" },
      { name: "CENTRO DE PRIMER NIVEL SABANA LARGA" },
      { name: "CENTRO DE PRIMER NIVEL SABANA MULA" },
      { name: "HOGAR DE ANCIANO SAN FRANSCISCO DE ASIS " },
      { name: "HOGAR DE ANCIANO SAN ISIDRO LABRADOR " },
      { name: "HOGAR DE ANCIANOS SANTA TERESA " },
      { name: "HOSPITAL DE HONDO VALLE." },
      { name: "HOSPITAL ROSA DUARTE" },
      { name: "POLIDEPORTIVO" },
      { name: "CTC" },
    ],
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL DESCUBIERTA" },
      { name: "HOSPITAL DE JIMANI" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CUERPO DE BOMBEROS" },
      { name: "ESCUELA FEDERICO AUGUSTO GONZALES" },
      { name: "POLIDEPORTIVO" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "BANCO DE RESERVAS" },
      { name: "CENTRO DE PRIMER NIVEL 5 CASAS" },
      { name: "CENTRO DE PRIMER NIVEL ANTON SÁNCHEZ" },
      { name: "CENTRO DE PRIMER NIVEL ANTONCI" },
      { name: "CENTRO DE PRIMER NIVEL CHACARO" },
      { name: "CENTRO DE PRIMER NIVEL GUANICO" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL LA COLORADA" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOTADOS" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD " },
      { name: "LA FISCALÍA " },
      { name: "HOGAR DE ANCIANOS NUESTRA SEÑORA DE FÁTIMA" },
      { name: "HOGAR DE DÍA HERMANA CARMEN CUADRADO " },
      { name: "HOSPITAL DR. ÀNGEL CONTRERAS  M EJÌA " },
      { name: "SINDICATO DE CHOFERES DE BAYAGUANA " },
      { name: "UNAP CACIQUE" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "ESCUELA MERIÑO" },
      { name: "HOSPITAL DOCTOR PEDRO HEREDIA ROJAS" },
      { name: "HOSPITAL MUNICIPAL DE YAMASA" },
      { name: "HOSPITAL SANTO CRISTO" },
      { name: "UNAP DON JUAN" },
    ],
  },
  {
    name: "SANCHEZ RAMIREZ",
    centers: [
      { name: " CENTRO DE PRIMER NIVEL PLATANAL" },
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE DIAGNOSTICO FANTINO" },
      { name: "CENTRO DE PRIMER NIVEL CABALLERO" },
      { name: "CENTRO DE PRIMER NIVEL CASTILLO" },
      { name: "CENTRO DE PRIMER NIVEL CHACUEY" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONCITO" },
      { name: "CENTRO DE PRIMER NIVEL LAS AOBAS" },
      { name: "CENTRO DE PRIMER NIVEL LA BIJA" },
      { name: "CENTRO DE PRIMER NIVEL SABALLO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA PRIETA" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "CLUB DE AMAS DE CASA PEDRO FRANCISCO BONO" },
      { name: "CLUB JUAN PABLO DUARTE (CLUB 4 DE JULIO)" },
      { name: "DPS SANCHEZ RAMIREZ" },
      { name: "PARQUE DUARTE" },
      { name: "CENTRO DE PRIMER NIVEL PUEBLO NUEVO" },
      { name: "CENTRO DE PRIMER NIVEL LOS CASTELLANOS" },
      { name: "CENTRO DE PRIMER NIVEL LA SOLEDAD " },
    ],
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "CLINICA DR. MONTESINOS" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "COLEGIO MEDICO" },
      { name: "UNAP CENTRO" },
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNAP BARRIO LINDO" },
      { name: "UNAP GUALEY" },
      { name: "UNAP GUAYABO DULCE" },
      { name: "UNAP LA JAVILLA" },
      { name: "UNAP LAS CAÑITAS" },
      { name: "UNAP LAS GUAMAS" },
      { name: "UNAP LAS YAGUITAS" },
      { name: "UNAP LOS HATILLOS" },
      { name: "UNAP MANCHADO" },
      { name: "UNAP PUERTO RICO" },
      { name: "UNAP PUNTA DE GARZA" },
      { name: "UNAP VILLA CANTO" },
      { name: "UNAP VILLA NAVARRO" },
      { name: "UNAP VILLA ORTEGA" },
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CLINICA POLICLINICO BONAO" },
      { name: "CRUCE UASD BONAO" },
      { name: "HOSPITAL DOCTOR JOSE A COLUNMA (IDDS)" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL PIEDRA BLANCA" },
      { name: "IGLESIA SAN PEDRO SAN PABLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAXIMO GOMEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA NUESTRA SRA DE FATIMA" },
      { name: "UNAP LAS LIRAS " },
      { name: "UNAP ARROYO TORO " },
      { name: "UNAP DOS RÍOS " },
      { name: "UNAP CARIBE " },
    ],
  },
  {
    name: "SAN PEDRO DE MACORIS",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "CEDISA DE LEON" },
      { name: "CLINICA DOCTOR DE LEON" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "DEFENSA CIVIL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "GREMIO DE LOS MUELLEROS" },
      { name: "IGLESIA ASAMBLEA DE DIOS JUAN DOLIÓ" },
      { name: "IGLESIA CATOLICA LOS CONUCOS" },
      { name: "IGLESIA DE DIOS GUAYACANES" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "MONTE DE SION" },
      { name: "MULTIUSO" },
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
    ],
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL JUMUNUCO" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "DEFENSA CIVIL" },
      { name: "HOSPITAL OCTAVIA GAUTIER" },
      { name: "OFICINA UCAVE LA VEGA" },
      { name: "CENTRO DIAGNOSTICO CONSTANZA" },
    ],
  },
];

centros.sort((a, b) => (a.name < b.name ? -1 : 1));
