const centros4 = [
  {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "HOSPITAL CECANOT" },
      { name: "CLÍNICA CRUZ JIMINIÁN" },
      { name: "DIRECCIÁN ÁREA DE SALID IV" },
      { name: "CLÍNICA RODRÍGUEZ SANTOS" },
      { name: "HOSPITAL DR.FRANCISCO E MOSCOSO PUELLO" },
      { name: "HOSPITAL FÉLIZ MARÍA GOICO" },
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-V)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD V" },
      { name: "HOGAR DE ANCIANOS SAN FRANCISCO DE ASIS" },
      { name: "CENTRO MÉDICO DEL CARIBE" },
      { name: "CENTRO MÉDICO DR. RICHARDSON CRUZ" },
      { name: "CENTRO MÉDICO ELOHIM" },
      { name: "CENTRO MÉDICO GAZCUE" },
      { name: "CENTRO MÉDICO MODERNO" },
      { name: "CENTRO MÉDICO REAL" },
      { name: "CENTRO MÉDICO UCE" },
      { name: "CLÍNICA ABREU" },
      { name: "CLÍNICA DOMINICO CUBANA" },
      { name: "CLÍNICA INDEPENDENCIA" },
      { name: "COLEGIO MÉDICO DOMINICANO" },
      { name: "DISPENSARIO MÉDICO TEJADA Y FLORENTINO" },
      { name: "GINECOLOGÍA Y OBSTETRICIA" },
      { name: "HOSPITAL GENERAL DE LA POLICÍA" },
      { name: "HOSPITAL INFANTIL DR.ROBERT REID CABRAL" },
      { name: "PUCMM" }
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-VI)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD VI" },
      { name: "CEDIMAT" },
      { name: "CENTRO MÉDICO VISTA DEL JARDIN" },
      { name: "DIRECCIÓN GENERAL DE EPIDEMIOLOGÍA,(DIGEPI)" },
      { name: "HOSPITAL GENERAL PLAZA DE LA SALUD" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "HOSPITAL MUNICIPAL JACINTO IGNACIO MAÑÓN" },
      { name: "HOSPITAL SALVADOR B. GAUTIER" },
      { name: "HOSPITAL INSTITUTO DE DIABETES (INDEN)" },
      { name: "UNIVERSIDAD PEDRO HENRIQUEZ UREÑA (UNPHU)" },
    ],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD II" },
      { name: "CENTRO MÉDICO ALMED" },
      { name: "CENTRO MÉDICO HISPÁNICO" },
      { name: "CENTRO MÉDICO INTEGRAL - I" },
      { name: "CENTRO MÉDICO INTEGRAL - III" },
      { name: "CENTRO MÉDICO UNIVERSAL" },
      { name: "CENTRO ORIENTAL DE DIABETES Y ENDOCRINOLOGÍA" },
      { name: "CENTRO POLICLÍNICO NACIONAL" },
      { name: "CENTRO PRIMER NIVEL (CPN), EL DIQUE" },
      { name: "CENTRO PRIMER NIVEL (CPN), ISABELITA" },
      { name: "CENTRO PRIMER NIVEL (CPN), LOS MAMEYES" },
      { name: "CENTRO PRIMER NIVEL (CPN), VILLA DUARTE" },
      { name: "CLÍNICA DRES. LEGER MATOS" },
      { name: "CLÍNICA SANTO DOMINGO ORIENTAL" },
      { name: "CENTRO SOTO GONZÁLEZ" },
      { name: "INSTITUTP SOCIAL COLECTIVO DE SALUD POPULAR (COPSALUD)" },
      { name: "CPN - VIERTNAM" },
      { name: "HOSPITAL DOCTOR DARIO CONTRERAS" },
      { name: "HOSPITAL MATERNO INFANTIL SAN LORENZO DE LOS MINA" },
      { name: "CENTRO MÉDICO MUNICIPAL DE RALMA" },
      { name: "HOSPITAL UNIVERSITARIO DOCTOR VÁSQUEZ" },
      { name: "INTEGRAL - I" },
      { name: "POLICLÍNICA ZONE - E" },
    ],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "HOSPITAL DR. RAMÓN DE LARA, FARD" },
      { name: "DIRECCIÓN ÁREA DE SALUD I" },
      { name: "HOSPITAL MUNICIPAL ELVIRA ECHAVARRÍA DE GUERRA" },
    ],
  },
  {
    name: "SANTO DOMINGO NORTE (DAS-III)",
    centers: [
      { name: "CLÍNICA DR.UREÑA ARIAS" },
      { name: "HOSPITAL HACIENDA ESTRELLA" },
      { name: "HOSPITAL PEDIÁTRICO DR.HUGO MENDOZA" },
      { name: "DIRECCIÓN ÁREA DE SALUD III" },
      { name: "HOSPITAL NEY ARIAS LORA" },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS-VII)",
    centers: [
      { name: "DR.MARCELINO VELEZ SANTANA" },
      { name: "HOSPITAL MUNICIPAL ENGOMBE" },
      { name: "SUB CENTRO DR.INOCENCIO DIAZ PIÑEYRO" },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS-VIII)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD VIII" },
      { name: "HOSPITAL DR.ELIAS SANTANA" },
      { name: "HOSPITAL MUNICIPAL LOS ALCARRIZOS II" },
      { name: "HOSPITAL DR.RODOLFO DE LA CRUZ LORA" },
      { name: "HOSPITAL GENERAL DR.VINICIO CALVENTI" },
      { name: "SUB CENTRO ALCARRIZO I" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "CENTRO MÉDICO DR.MATEO ROSARIO" },
      { name: "HOSPITAL MUNICIPAL DE DR. PEDRO HEREDIA ROJAS" },
      { name: "HOSPITAL MUNICIPAL DE YAMASA" },
      { name: "HOSPITAL PROVINCIAL DE MONTE PLATE DR.ANGEL CONTRERAS" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MONTE PLATA" },
      { name: "HOSPITAL SANTO CRISTO DE LOS MILAGROS" },
    ],
  },
  {
    name: "SAN CRISTÓBAL",
    centers: [
      { name: "AMEDOSA-CLÍNICA SAN CRISTÓBAL" },
      { name: "CASA ACOGIDA DE ENVEJECIENTES NUESTRA SEÑORA DE LA ALTAGRACIA" },
      { name: "DIRECCÓN PROVINCIAL DE SALUD SAN CRISTÓBAL" },
      { name: "CPN CAMBITA GARABITO CRUCE" },
      { name: "HOSPITAL MUNICIPAL CAMBITA GARABITO" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "LEPROCOMIO NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "HOSPITAL MUNICIPAL DE HAINA BALSEQUILLO" },
      { name: "HOSPITAL MUNICIPAL BAJOS DE HAINA" },
      { name: "HOSPITAL MUNICIPAL MARÍA PANIAGUA (BOBITA) DE NIGUA" },
      { name: "HOSPITAL MUNICIPAL DE PALENQUE" },
      { name: "HOSPITAL MUNICIPAL DE YAGUATE" },
      { name: "HOSPITAL MUNICIPAL VILLA ALTAGRACIA" },
      { name: "HOSPITAL NUESTRA SEÑORA DE LA ALTAGRACIA" },
      { name: "CENTRO DE SALUD HOSPITAL DR.RAFAEL J. MAÑÓN" },
    ],
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD PERAVIA" },
      { name: "CENTRO GRUPO MÉDICO BANÍ" },
      { name: "CLÍNICA INSTITUTO REGIONAL MATERNO INFANTIL Y ESPECIALIDADES MÉDICAS (IRMIE)" },
      { name: "CENTRO MÉDICO DR.PAULINO DE NIZAO" },
      { name: "CENTRO MÉDICO REGIONAL AGUASVIVAS" },
      { name: "HOSPITAL MUNICIPAL VILLA FUNDACIÓN" },
      { name: "CLÍNICA PERAVIA" },
      { name: "DISPENSARIO MÉDICO BASE NAVAL" },
      { name: "HOSPITAL NUESTRA SEÑORA DE REGLA" },
    ],
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE SALUD LAS FLORES" },
      { name: "CENTRO DE SALUD PUEBLO ABAJO" },
      { name: "CENTRO DE DIAGNÓSTICO Y ATENCIÓN PRIMARIA DE SAN LUIS" },
      { name: "CPN SAN RAFAEL" },
      { name: "CENTRO MÉDICO EL MANIEL" },
      { name: "CENTRO MÉDICO VELÁZQUEZ" },
      { name: "CLÍNICA ARIAS" },
      { name: "HOSPITAL MUNICIAL DR.GUARIONEZ ALCÁNTARA" },
      { name: "HOSPITAL SAN JOSÉ DE OCOA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN JOSÉ DE OCOA" },
      { name: "CPN NIZAO" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - I)",
    centers: [
      { name: "SEDE 9-1-1" },
      { name: "HOSPITAL PRESIDENTE ESTRELLA UREÑA" },
      { name: "CLÍNICA ARTURO LOGROÑO" },
      { name: "CENTRO MÉDICO SANTIAGO APOSTOL" },
      { name: "HOSPITAL PERIFÉRICO DE CIENFUEGOS" },
      { name: "HOSPITAL MUNICIAL DE NAVARRETE" },
      { name: "HOSPITAL MUNICIAL DE VILLA GONZÁLEZ DR.NATIER DÍAS" },
      { name: "HOSPITAL DR.SALVADOR B, GAUTIER, (INSTITUTO DOMINICANO DE SEGUROS SOCIALES)" },
      { name: "HOSPITAL ENSANCHE LIBERTAD" },
      { name: "HOSPITAL INFANTIL DR.ARTURO GRULLÓN" },
      { name: "HOSPITAL REGIONAL DE SALUD" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - I)" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - II)",
    centers: [
      { name: "CPN BELLA VISTA" },
      { name: "CPN LA OTRA BANDA" },
      { name: "CPN VILLA LIBERACIÓN" },
      { name: "CENTRO DIAGNÓSTICO LOS GUANDULES" },
      { name: "CENTRO DE SALUD MADRE FRANCES STREITEL" },
      { name: "CLÍNICA DR.GUZMÁN" },
      { name: "CLÍNICA JIMÉNEZ" },
      { name: "CLÍNICA PROFAMILIA ROSA CISNEROS" },
      { name: "CLÍNICA TOLENTINO ABREU" },
      { name: "CPN BARRIO NUEVO HERRADURA" },
      { name: "CPN BUEN PASTOR" },
      { name: "CPN LA JOYA" },
      { name: "CPN LAS CHARCAS" },
      { name: "CPN MAMA TINGO" },
      { name: "CPN VILLA BAO" },
      { name: "CPN VILLA TABACALERA" },
      { name: "CPN YAGUISTA DE PASTOR" },
      { name: "DEFENSA CIVIL" },
      { name: "HOGAR DE ANCIANOS SAN JOSÉ DE SAJOMA" },
      { name: "HOSPITAL INTEGRAL BELLA VISTA" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE" },
      { name: "HOSPITAL MUNICIPAL DE SABANA IGLESIA" },
      { name: "HOSPITAL MUNICIAL DE SAN JOSÉ DE LAS MATAS" },
      { name: "IGLESIA ADVENTISTA DEL SÉPTIMO DÍA" },
      { name: "PROFAMILIA Y CENTRO DIAGNÓSTICO FAMILIAR DR.TERRERO" },
      { name: "PUESTO FIJO DE LA DAS II" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - II)" },
      { name: "HOSPITAL MUNICIAL YRENE FERNÁNDEZ DE JANICO" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - III)",
    centers: [
      { name: "ACERO ESTRELLA" },
      { name: "CENTRO CENCACE" },
      { name: "CENTRO DE ESPECIALIDADES DR.PAULINO REYES" },
      { name: "HOGAR GERIÁTRICO CANITAS DORADAS" },
      { name: "CENTRO GERIÁTRICO DOMINICANO" },
      { name: "CENTRO GERIÁTRICO DRA.MOREU" },
      { name: "CENTRO MATERNO INFANTIL Y ESPECIALIDADES" },
      { name: "CENTRO MÉDICO CIBAO - UTESA" },
      { name: "CENTRO UROLÓGICO DEL CIBAO" },
      { name: "CLÍNICA DOCTOR EDUARDO MARTÍNEZ" },
      { name: "CLÍNICA COROMINAS, S.A." },
      { name: "CLÍNICA DR.BONILLA" },
      { name: "CLÍNICA GENARO VALDEZ UTESA" },
      { name: "CLÍNICA UNIÓN MÉDICA DEL NORTE" },
      { name: "CONSULTORIO AEROPUERTO INTERNACIONAL SANTIAGO" },
      { name: "DISPENSARIO MÉDICO UNIVERSIDAD PUCMM" },
      { name: "DISPENSARIO MÉDICO UAPA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - III)" },
      { name: "FUNDACIÓN SOLIDARIA DEL DIVINO NIÑO DE JESUS INC." },
      { name: "HOSPITAL DE ESPECIALIDADES MÉDICAS MATERNO INFANTIL (HEMMI)" },
      { name: "HOGAR DE ANCIANOS ELISEO ÁLVAREZ" },
      { name: "HOGAR DE ANCIANOS LAS TRES HERMANAS" },
      { name: "CENTRO MÉDICO PREVENTIVO SALUD Y VIDA (CENSAVID)" },
      { name: "HOSPITAL MUNICIPAL BAITOA" },
      { name: "HOSPITAL MUNICIPAL DE TAMBORIL DR.JORGE ARMANDO 'ICO'" },
      { name: "HOSPITAL JORGE BLANCO" },
      { name: "HOSPITAL JOSÉ MARÍA CABRAL Y BÁEZ" },
      { name: "HOSPITAL JUAN 23 MONTE ADENTRO" },
      { name: "HOSPITAL METROPOLITANO DE SANTIAGO (HOMS)" },
      { name: "HOSPITAL MUNICIPAL LICEY AL MEDIO" },
      { name: "HOSPITAL OFTALMOLÓGICO" },
      { name: "INSTITUTO DERMATOLÓGICO Y CIRUJÍA DEL PIEL DR.HUMBERTO BOGAERT DÍAZ" },
      { name: "INSTITUTO ONCOLÓGICO REGIONAL DEL CIBAO" },
      { name: "CENTRO MÉDICO LOS VETERANOS" },
      { name: "CENTRO MÉDICO NEOCLINIC" },
      { name: "HOSPITAL SEMMA" },
      { name: "HOSPITAL SAN VICENTE DE PAUL" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "HOGAR PARA ANCIANOS DESVALIDOS LA SANTÍSIMA TRINIDAD" },
      { name: "CENTRO DE DIAGNÓSTICO AVANZADO LOS LÓPEZ (CDA)" },
      { name: "CPN CEIBA DE MADERA" },
      { name: "CPN JUAN LOPEZ" },
      { name: "CLÍNICA ALTAGRACIA" },
      { name: "CENTRO MÉDICO GUADALUPE" },
      { name: "COLEGIO MÉDICO DOMINICANO FILIAL MOCA (CMD)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD ESPAILLAT" },
      { name: "HOSPITAL DR.TORIBIO BENCOSME" },
      { name: "CENTRO MÉDICO HOSPIMED" },
      { name: "HOSPITAL CARLOS MARÍA ROJAS BADÍA" },
      { name: "HOSPITAL MUNICIPAL JAMAO AL NORTE" },
      { name: "HOSPITAL MUNICIPAL JOSÉ CONTRERAS" },
      { name: "HOSPITAL MUNICIPAL MANUEL DE LUNA" },
      { name: "HOSPITAL MUNICIPAL DR. RAFAEL GUTIERREZ SÁNCHEZ" },
      { name: "HOSPITAL DR.ROTIBIO BENCOSME (HOSTOBEN)" },
      { name: "INSTITUTO DE ESPECIALIDADES MÉDICAS GREGORIO HERNÁNDEZ" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL Y ESPECIALIDADES DR.MÉNDEZ" },
    ],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "HOGAR DE ANCIANOS SAN ANTONIO MARÍA CLARET" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA DE SALUD (CAPS) BASE AÉREA PUERTO PLATA" },
      { name: "CENTRO MÉDICO BOURNIGAL" },
      { name: "CENTRO MÉDICO CABARETE" },
      { name: "CENTRO MÉDICO DE ESPECIALIDADES UTESA" },
      { name: "CENTRO SANITARIO DR.FRANCISCO GONZÁLEZ HARDY" },
      { name: "CLÍNICA BRUGAL" },
      { name: "HOSPITAL DR. RAFAEL CANTISANO ARIAS" },
      { name: "HOSPITAL GREGORIO LUPERÓN" },
      { name: "HOSPITAL MUNICIPAL ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "HOSPITAL PABLO MORROBEL JIMÉNEZ" },
      { name: "HOSPITAL PROVINCIAL DOCENTE RICARDO LIMARDO" },
      { name: "PADRE LAS CASAS (CASA CLUB)" },
      { name: "POLICLÍNICAS DE VILLA LIBERACIÓN Y CHARAMICO" },
      { name: "DIRECCIÓN PROVINCIAL SALUD PUERTO PLATA" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CENTRO DE CIRUGÍA PLÁSTICA AVANZADA DEL CIBAO (CIPLACI)" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL DEL NORDESTE" },
      { name: "CENTRO MÉDICO NACIONAL SAN FRANCISCO" },
      { name: "CENTRO MÉDICO SIGLO 21" },
      { name: "CPN VENTURA GRULLÓN" },
      { name: "HOSPITAL SAN VICENTE DE PAUL" },
      { name: "INSTITUTO DE ESPECIALIDADES MÉDICAS DEL NORDESTE, INEMED" },
      { name: "CPN LOMA DE LA JOYA" },
      { name: "CENTRO DE AISLAMIENTO Y CUIDADOS INTENSIVOS GUIZA" },
      { name: "CPN PROVINCIA DUARTE" },
      { name: "HOGAR DE ANCIANOS AMÉRICA ESPERANZA, SAN FCO DE MACORIS" },
      { name: "HOSPITAL FEDERICO LEOPOLDO LAVANDIER" },
      { name: "HOSPITAL MUNICIPAL DE CASTILLO" },
      { name: "HOSPITAL MUNICIPAL DR.FELIPE J. ACHÉCAR" },
      { name: "HOSPITAL MUNICIPAL DR.MARIO FDEZ MENA, CENOVI" },
      { name: "HOSPITAL PÚBLICO ALICIA DE LEGENDRE" },
      { name: "HOSPITAL PÚBLICO ETANAILDA BRITO, LAS GUARANAS" },
      { name: "DISPENSARIO RECINTO UASD" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD DUARTE" },
      { name: "UNIVERSIDAD NORDESTANA" },
    ],
  },
  {
    name: "MARÍA TRINIDAD SÁNCHEZ",
    centers: [
      { name: "CENTRO MÉDICO DR.PÉREZ" },
      { name: "CENTRO MÉDICO ESPAILLAT UBIERA" },
      { name: "CENTRO DE ESPECIALIDADES MÉDICAS COSTA NORTE" },
      { name: "CENTRO DE ESPECIALIDADES MÉDICAS NAGUA (CEMNA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MARÍA TRINIDAD SÁNCHEZ" },
      { name: "HOGAR ASILO DE ANCIANOS LOS DISCÍPULOS Y MISIONEROS DEL AMOR Y LA PAZ" },
      { name: "HOSPITAL MUNICIPAL DESIDERIO ACOSTA" },
      { name: "HOSPITAL DR.CARLOS A ZAFRA" },
      { name: "HOSPITAL DR.LUIS RAMÓN BONILLA" },
      { name: "HOSPITAL MATERNO INFANTIL MATANCITAS" },
      { name: "HOSPITAL MUNICIPAL EL FACTOR" },
      { name: "HOSPITAL MUNICIPAL DR.VIRGILIO A. GARCÍA" },
      { name: "HOSPITAL ANTONIO YAPOR HEDED" },
      { name: "POLICLÍNICO LA UNIÓN" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "CENTRO MINUCIPAL LOS RIOS" },
      { name: "CENTRO MUNICIPAL TAMAYO" },
      { name: "HOSPITAL GIL ROLDÁN" },
      { name: "HOSPITAL JULIA SANTANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BAHORUCO" },
      { name: "HOSPITAL SAN BARTOLOMÉ" }
    ],
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "CLÍNICA ESPECIALIZADA INTERNACIONAL LAS TERRENAS" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX EN SÁNCHEZ" },
      { name: "HOSPITAL LIC. PABLO PAULINO, LAS TERRENAS" },
      { name: "HOSPITAL NATIVIDAD ALCALÁ EL LIMÓN" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD SAMANÁ" },
      { name: "HOSPITAL PROVINCIAL DR. LEOPOLDO POU, SANTA BARBARA" }
    ]
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO MÉDICO DE ESPECIALIDADES VILLA TAPIA (CEMEVIT)" },
      { name: "CENTRO DIAGNOSTICO VILLA TAPIA" },
      { name: "CENTRO MÉDICO DR. RAFAEL GRULLÓN" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL DR. ROMÁN BRACHE" },
      { name: "HOSPITAL DR. ROMAN BAUTISTA BRACHE" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD HERMANAS MIRABAL" },
      { name: "HOSPITAL MUNICIPAL VILLA TAPIA" },
    ]
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DE ATENCION PRIMARIA (UNAP)" },
      { name: "CENTRO DIAGNÓSTICO JIMANÍ" },
      { name: "CPN EL LIMON" },
      { name: "CPN JIMANÍ" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD INDEPENDENCIA" },
      { name: "HOSPITAL PROVINCIAL GENERAL MELENCIANO" },
      { name: "HOSPITAL DR. JOSÉ PÉREZ" },
      { name: "HOSPITAL LA DESCUBIERTA" },
      { name: "HOSPITAL LOS PINOS DEL EDEN" },
      { name: "HOSPITAL MUNICIPAL DE JIMANÍ" },
      { name: "HOSPITAL MUNICIPAL DUVERGÉ" },
    ]
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CENTRO MÉDICO DE LEÓN" },
      { name: "CENTRO MÉDICO ESPECIALIZADO MACORIS" },
      { name: "CENTRO MÉDICO UCE SAN PEDRO DE MACORÍS" },
      { name: "CLÍNICA DR. FRANKLIN PEÑA" },
      { name: "HOSPITAL DR. JAIME OLIVER PINO" },
      { name: "HOSPITAL PEDRO MARÍA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN PEDRO DE MACORÍS" },
      { name: "HOSPITAL REGIONAL DR. ANTONIO MUSA" },
    ]
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "ASILO DE ANCIANOS ROMERLIA SALAS DE BARCELÓ" },
      { name: "SEDE 9-1-1" },
      { name: "CENTRO DE REHABILITACIÓN DE HATO MAYOR" },
      { name: "DIRECCION PROVINCIAL DE SALUD HATO MAYOR" },
      { name: "HATO MAYOR DEL REY" },
      { name: "HOSPITAL ELUPINA CORDERO" },
      { name: "HOSPITAL LEOPOLDO MARTÍNEZ" },
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "LABORATORIO ALBUERME" },
      { name: "LABORATORIO ODONTOLÓGICOS LOCALES" },
      { name: "LABORATORIO PATRIA RIVAS" },
      { name: "LABORATORIO PUELLO" },
      { name: "LABORATORIO VASQUEZ" },
      { name: "LOCAL LA LOGIA" },
      { name: "HOSPITAL MUNICIPAL SRTA. ELUPINA CORDERO SABANA DE LA MAR" },
    ]
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "CENTRO MÉDICO DR. BALTAZAR Y ASOCIADOS, SRL" },
      { name: "CENTRO MÉDICO PUNTA CANA" },
      { name: "CENTRO MEDICO QUIRÚRGICO" },
      { name: "CLÍNICA DOCTOR GIL" },
      { name: "CENTRO MÉDICO DE ORTOPEDIA Y ESPECIALIDADES DR. QUEVEDO" },
      { name: "CLÍNICA DOCTOR VIRGILIO CEDANO" },
      { name: "CLÍNICA DR. PEROZO SRL" },
      { name: "GRUPO MÉDICO LIBERTAD" },
      { name: "HOSPITAL GENERAL Y DE ESPECIALIDADES NUESTRA SEÑORA DE LA ALTAGRACIA (HGENSA)" },
      { name: "HOSPITAL DRA. EVANGELINA RODRIGUEZ" },
      { name: "HOSPITAL IMG BAVARO" },
      { name: "HOSPITAL LAGUNAS DE NISIBON" },
      { name: "HOSPITAL MATERNO INFANTIL" },
      { name: "HOSPITAL NUESTRA SRA. DE LA ALTAGRACIA" },
      { name: "HOSPITEN" },
      { name: "MEDICALL BAVARO" },
      { name: "SERVICIO REGIONAL DE SALUD (SRS)" },
      { name: "SERVIMED LABORATORO" },
      { name: "UNAP ZONA URBANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD LA ALTAGRACIA" },
      { name: "UNAP ZONAS RURALES" },
    ]
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "ASOCIACIÓN AYUDA MUTUA" },
      { name: "AYUNTAMIENTO PROVINCIAL" },
      { name: "CENTRO TECNOLÓGICO" },
      { name: "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN JUAN" },
      { name: "HOSPITAL DR. FEDERICO AYBAR" },
      { name: "HOSPITAL MUNICIPAL DE BOHECHIO" },
      { name: "HOSPITAL MUNICIPAL DE VALLEJUELO" },
      { name: "HOSPITAL MUNICIPAL EL CERCADO" },
      { name: "HOSPITAL MUNICIPAL JUAN HERRERA" },
      { name: "HOSPITAL MUNICIPAL MATAS DE FARFAN" },
      { name: "HOSPITAL REGIONAL DOCENTE DR. ALEJANDRO CABRAL" },
      { name: "IGLESIA ESPÍRITU SANTOS" },
      { name: "POLIDEPORTIVO DE SAN JUAN" },
      { name: "SEDE  9-1-1" },
    ]
  },
  {
    name: "AZUA",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD AZUA" },
      { name: "HOSPITAL MUNICIPAL DE PERALTA" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL MUNICIPAL NUESTRA SEÑORA DEL CARMEN" },
      { name: "HOSPITAL PADRES LAS CASA" },
      { name: "HOSPITAL TAIWAN" },
    ]
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO MÉDICO DRA CABRERA" },
      { name: "HOSPITAL BANICA" },
      { name: "HOSPITAL MUNICIPAL HONDO VALLE" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD EL ELÍAS PIÑA" },
      { name: "HOSPITAL ROSA DUARTE" },
    ]
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "ASILO DE ANCIANOS DE MAO" },
      { name: "CASA CLUB COLEGIO MEDICO MAO" },
      { name: "CENTRO MÉDICO CEMENOR, S,R,L" },
      { name: "CLÍNICA INMANOR" },
      { name: "CLÍNICA DR. MONTESINOS" },
      { name: "CLINICA PERPETUO SOCORRO" },
      { name: "CLUB DE LEONES MAO" },
      { name: "COLEGIO MÉDICO DOMINICANO (CMD)" },
      { name: "HOSPITAL DR. JOSÉ FAUSTO OVALLES" },
      { name: "HOSPITAL MATERNO INFALTIL JOSE FRANCISCO PEÑA GOME" },
      { name: "HOSPITAL MUNICIPAL LAGUNA SALADA" },
      { name: "HOSPITAL REGIONAL  ING. LUIS L. BOGAERT" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD VALVERDE" },
      { name: "SEDE 911" },
    ]
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [
      { name: "CLÍNICA GRAN PODER DE DIOS" },
      { name: "HOSPITAL DE MONCIÓN" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SANTIAGO RODRÍGUEZ" },
      { name: "HOSPITAL MUNICIPAL VILLA LOS ALMACIGOS" },
      { name: "HOSPITAL PROVINCIAL GENERAL SANTIAGO RODRÍGUEZ" },
    ]
  },
  {
    name: "MONTECRISTI",
    centers: [
      { name: "AYUNTAMIENTO CANA CHAPETON" },
      { name: "CENTRO INTEGRAL ODONTOLÓGICO Y ORTODONCIA" },
      { name: "CLÍNICA GRUPO MÉDICO CARLO CARLOS J.FINLAY" },
      { name: "CLÍNICA DENTAL DR. LUIS PIMETEL" },
      { name: "CLÍNICA DENTAL DR. MATIRDE GONZALEZ" },
      { name: "CLÍNICA DRA. SUERO" },
      { name: "CLÍNICA ODONTOLOGICA NERSON ISIDOR" },
      { name: "CLÍNICA SAN ANTONIO" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MONTECRISTI" },
      { name: "HATILLO PALMA E EL CLUB" },
      { name: "HOSPITAL DE LAS MATAS DE SANTA CRUZ" },
      { name: "HOSPITAL JULIO ALVAREZ ACOSTA" },
      { name: "HOSPITAL MUNICIPAL DE CASTAÑUELA" },
      { name: "HOSPITAL MUNICIPAL GUAYUBIN " },
      { name: "HOSPITAL MUNICIPAL PEPILLO SALCEDO" },
      { name: "HOSPITAL MUNICIPAL VILLA VASQUES" },
      { name: "HOSPITAL PÚBLICO PADRE FANTINO " },
      { name: "LABORATORIO DENTAL ROMULO LORENZO" },
      { name: "MANZANILLO EN EL MULTIUSO" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SAN FERNANDO (UNAP)" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SANTA MARIA (UNAP)" },
      { name: "AYUNTAMIENTO VILLA ELISA" },
    ]
  },
  {
    name: "DAJABON",
    centers: [
      { name: "CLÍNICA ROSA BENITA" },
      { name: "HOGAR DE ANCIANOS EN VILLA ALEGRE" },
      { name: "HOSPITAL MUNICIPAL DE PARTIDO" },
      { name: "HOSPITAL MUNICIPAL RESTAURACIÓN" },
      { name: "HOSPITAL RAMON ADRIANO VILLALOBOS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DAJABON" },
      { name: "HOSPITAL RAMON MATÍAS MELLA" },
    ]
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CENTRO DE CIRUGÍA Y ESPECILIDADES MEDICAS MAIMON" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS MONSEÑOR NOUEL" },
      { name: "CENTRO MÉDICO ZONA PROSPERIDAD" },
      { name: "CLINICA CAROLINA DE JESUS" },
      { name: "CLINICA SAN ANTONIO DE PADUA" },
      { name: "CONSULTORIO NUESTRA SRA. DE FATIMA" },
      { name: "DIRECCION PROVINCIAL DE SALUD MONSEÑOR NOUEL" },
      { name: "EPIDEMIOLOGO PROVINCIAL DE SALUD" },
      { name: "HOGAR DE ANCIANOS SAN ANTONIO" },
      { name: "HOSPITAL DR. PEDRO EMILIO DE MARCHENA" },
      { name: "HOSPITAL DR. JOSE A. COLUMNA" },
      { name: "HOSPITAL MARCHENA NUEVO" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL DE PIEDRA BLANCA" },
      { name: "CENTRO MEDICO PLAN DIENTE SANO" },
    ]
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO MEDICO CEMEVE" },
      { name: "CENTRO DIAGNOSTICO Y DE ATENCION PRIMARIA LA VEGA" },
      { name: "CENTRO MEDICO PADRE FANTINO, S.R.L. " },
      { name: "CLINICA 5TO. CENTENARIO" },
      { name: "CLINICA BAEZ SOTO SRL" },
      { name: "CLINICA LA CONCEPCION" },
      { name: "DIRECCIOB PROVINCIAL DE SALUD LA VEGA" },
      { name: "HOSPITAL DRA. ARMIDA GARCIA" },
      { name: "HOSPITAL JIMA ABAJO" },
      { name: "HOSPITAL JUAN ANTONIO CASTILLO (CUTUPU)" },
      { name: "HOSPITAL PROFESOR JUAN BOSCH" },
      { name: "HOSPITAL REGIONAL UNIVERSITARIO DR. LUIS ML. MORILLO KING" },
      { name: "POLICLINICO LA VEGA, S.A" },
      { name: "REGIONAL DE SALUD 8" },
    ]
  },
  {
    name: "SÁNCHEZ RAMÍREZ",
    centers: [
      { name: "CENTRO MEDICO AMK DENTAL" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS" },
      { name: "CENTRO DE EUDIRIS SOTO" },
      { name: "CENTRO DENTAL DRA. ELVIRA THEN" },
      { name: "CENTRO DIAGNOSTICO COTUI" },
      { name: "CENTRO DIAGNOSTICO DE FANTINO" },
      { name: "CENTRO DIAGNOSTICO VILLA LA MATA" },
      { name: "CENTRO MEDICO NUÑEZ HERNANDEZ" },
      { name: "CENTRO ODONTOLOGICO DISLA NUÑEZ" },
      { name: "CLINICA CECIESMED" },
      { name: "CLINICA DR. JACOBO" },
      { name: "CLINICA DR. PAREDES" },
      { name: "CLINICA GUADALUPE" },
      { name: "CLINICA LAS MERCEDES" },
      { name: "CLINICA NUESTRA SRA. DEL PILAR" },
      { name: "CONSULTORIO INMACULADA CONCEPCION" },
      { name: "CONSULTORIO UTECO" },
      { name: "CPN SANCHEZ RAMIREZ" },
      { name: "DIRECCION DE AREA DE SALUD SÁNCHEZ RAMÍREZ" },
      { name: "DIRECCION PROVINCIA DE SALUD SANCHEZ RAMIREZ" },
      { name: "HOGAR DE ANCIANOS CLUB DE LEONES INMACULADA CONCEPCIÓN" },
      { name: "HOGAR DE DIA VILLA LA MATA" },
      { name: "HOSPITAL CEVICO" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "HOSPITAL MUNICIPAL FANTINO (SIGFREDO ALBA)" },
      { name: "HOSPITAL RAMÓN BÁEZ" },
      { name: "HOSPITAL SIGIFREDO ALBA DOMINGUEZ" },
      { name: "HOSPITAL VILLA LA MATA" },
      { name: "DIRECCION PROVINCIAL DE SALUD " },
      { name: "CENTRO MEDICO ODNONTOCLINIC" },
      { name: "CENTRO MEDICO ORAL IMPLANT RD" },
      { name: "SEDE  9-1-1 SÁNCHEZ RAMÍREZ" },
    ]
  },
  {
    name: "San Francisco De Macoris",
    centers: [
      { name: "Grupo Medico Unido Siglo 21" },
      { name: "Centro Medico Materno Infantil del Nordeste" },
      { name: "Centro Medico Nacional" },
      { name: "Centro Medico de Especialidades Medicas (INEMED)" },
      { name: "Fortaleza Duarte" },
      { name: "Policia Nacional" },
      { name: "Hospital Regional San Vicente de Paul" },
      { name: "CIPLACI" },
      { name: "Policia Nacional" },
      { name: "Centro del Jaya " },
      { name: "Capilla La Altagracia" },
      { name: "Ruta CPN 1A" },
      { name: "Ruta CPN 1B" },
      { name: "Ruta CPN 1C" },
      { name: "Ruta CPN 2A" },
      { name: "Ruta CPN 2B" },
      { name: "Ruta CPN 3" },
      { name: "Ruta CPN 4" },
      { name: "Ruta CPN 5" },
      { name: "Ruta CPN 6" },
      { name: "Ruta CPN 7" },
      { name: "Ruta CPN 8" },
      { name: "UCNE (Intrnos de Medicina)" },
      { name: "Hogar Geriatrico Niña  Valerio " },
      { name: "Casa Senatorial " },
      { name: "Club de Mayorista" },
      { name: "UASD (Internos de Medicina)" },
      { name: "Centro Medico Dr. Ovalle " },
      { name: "Centro Medico Dr. Nuñez " },
      { name: "Clinica Dra. Flabia Sanchez (SAREI)" },
      { name: "Clinica Dr. Sarante " },
      { name: "Dr. Reynoso " },
      { name: "Dr. Goris Abreu " },
      { name: "Cardio Renal " },
      { name: "Cruz Roja  Dominicana " },
      { name: "Centro Israel Garcia" },
      { name: "CEDINEFROT " },
      { name: "Incardio " },
      { name: "Fundacion de Cardiologia " },
      { name: "Rehabilitacion " },
      { name: "Yun Peralta " },
      { name: "Oncologico " },
      { name: "Serenidad " },
      { name: "Casa Senatorial" },
      { name: "Club de Mayorista" },
      { name: "Club de los Profesores" },
      { name: "Centro Comunal Pablo VI" },
      { name: "Club 27 de Febrero " },
      { name: "Capilla La Altagracia" },
      { name: "Cancha San Martin" },
      { name: "Ciudad Ganadera" },
      { name: "Centro Medico Dr. Ovalle " },
      { name: "Grupo Medico Unido Siglo 21" },
      { name: "Casa Senatorial " },
      { name: "Club de Mayorista" },
      { name: "Club 27 de Febrero " },
      { name: "Grupo Medico Unido Siglo 21" },
      { name: "Centro Medico Dr. Ovalle " },
      { name: "Centro Comunal Pablo VI" },
      { name: "Cancha San Martin " },
      { name: "Club de los Profesores" },
      { name: "Capilla La Altagracia " },
      { name: "Ciudad Ganadera " },
      { name: "Getsemani " },
      { name: "UASD (Internos de Medicina)" },
      { name: "Casa Senatorial" },
      { name: "Club de Mayorista" },
      { name: "Club Olegario Tenares (Vista al Valle)" },
      { name: "Ciudad Ganadera" },
      { name: "Cancha San Martin" },
      { name: "Profamilia " },
      { name: "UCNE (Intrnos de Medicina)" },
      { name: "Club Cristo Rey" },
      { name: "Grupo Medico Unido Siglo 21" },
      { name: "Centro Comunal Pablo VI" },
      { name: "DPS Duarte" },
      { name: "Capilla La Altagracia" },
      { name: "Casa Senatorial" },
      { name: "Club de Mayorista" },
      { name: "Centro Comunal San Juan Bautista" },
      { name: "UCNE (Intrnos de Medicina)" },
      { name: "Club Cristo Rey " },
      { name: "Grupo Medico Unido Siglo 21" },
      { name: "Centro Medico Dr. Ovalle " },
      { name: "Capilla La Altagracia " },
      { name: "DPS Duarte" },
      { name: "Los Espinolas " },
      { name: "Hermanas Mirabal " },
      { name: "Santa Ana " },
      { name: "Fortaleza Duarte  (911)" },
      { name: "Regional de Salud " },
      { name: "UASD (Internos de Medicina)" }
    ]
  },
  {
    name: "Aguayo",
    centers: [
      { name: "Centro Comunal de Aguayo" }
    ],
  },
  {
    name: "Arenoso",
    centers: [
      { name: "Hospital Municipal Arenoso" },
      { name: "Multiuso Bajo Techo Arenoso" },
      { name: "Bajo Techo de Arenoso " },
      { name: "Multiuso Bajo Techo Arenoso" }
    ],
  },
  {
    name: "Castillo",
    centers: [
      { name: "Hospital Municipal Castillo" },
      { name: "Centro Comunal de Castillo" }
    ],
  },
  {
    name: "Cenovi",
    centers: [
      { name: "Hospital Dr.  Mario Fernandez Mena" },
      { name: "Centro Comunal  Salome Ureña (Cenovi)" }
    ],
  },
  {
    name: "Hostos",
    centers: [
      { name: "Centro Comunal de Hostos " }
    ],
  },
  {
    name: "Hoyo de Jaya",
    centers: [
      { name: "Casa Curial (Hoyo de Jaya)" }
    ],
  },
  {
    name: "La Peña",
    centers: [
      { name: "Club Miguel Gelaber" }
    ],
  },
  {
    name: "Las Guaranas",
    centers: [
      { name: "Hospital Municipal Ethailda Brito" },
      { name: "Club Blue" }
    ],
  },
  {
    name: "Pimentel",
    centers: [
      { name: "Hospital Municipal Felipe J. Achecar" },
      { name: "Arena 57 " }
    ],
  },
  {
    name: "Villa Rivas",
    centers: [
      { name: "Hospital Municipal Alicia Legendre" },
      { name: "Multiuso Bajo Techo Villa Rivas" },
      { name: "Bajo Techo Villa Riva" },
      { name: "Villa rivas ( Guaraguao)" }
    ],
  },
  {
    name: "Santa Barbara",
    centers: [
      { name: "Polideportivo" },
      { name: "Centro Tecnologico del Limon" },
      { name: "Centro Comunal Los Robalos" },
      { name: "Cruce de Honduras (Edificio blanco)" },
      { name: "Centro Comunal Rancho Español" },
      { name: "FABRICA DE HIELO LA PASCUALA" },
      { name: "CRUCE DE TEZON" },
      { name: "AYUNTAMIENTO LAS GALERAS" },
      { name: "JUNTA DE VECINO DANIEL WILLMORE" },
      { name: "Iglesia Catolica " },
      { name: "Sindicato de portuaria " },
      { name: "Junta de vecinos Los Cacaos" },
      { name: "Local Cooperativa vieja " }
    ],
  },
  {
    name: "Las Terrenas",
    centers: [
      { name: "Centro Comunal" },
      { name: "Iglesia Catolica" },
      { name: "CLUB DE MADRES LOS PUENTES" },
      { name: "Polideportivo " }
    ],
  },
  {
    name: "Sanchez",
    centers: [
      { name: "CPN La Lometa" },
      { name: "Centro Comunal, Batey Hormiga" },
      { name: "MAJAGUA ADENTRO" },
      { name: "Iglesia Catolica Las Garitas" },
      { name: "Centro Comunal Los Corrales" },
      { name: "Cruz Roja Dominicana" },
      { name: "Ayuntamiento Municipal" },
      { name: "Hospital Dr. Alberto Gautreaux" }
    ],
  },
  {
    name: "Salcedo",
    centers: [
      { name: "HOSPITAL DR. PASACASIO TORIBIO PIANTINI" },
      { name: "CENTRO MEDICO MATERNO INFANTIL" },
      { name: "CENTRO MEDICO Dr.GRULLON" },
      { name: "HOSPITAL Dr.ROMAN BRACHEZ" },
      { name: "CASA DE LOS JOVENES DE AYER" },
      { name: "LOCAL DEL COLEGIO MEDICO PROVINCIAL" },
      { name: "UNAP  ANA MERCEDES RODRIGUEZ" },
      { name: "CASA DE LA TERCERA EDAD" }
    ],
  },
  {
    name: "Tenares",
    centers: [
      { name: "HOSPITAL ANGEL CONCEPCION LAJARA" },
      { name: "CENTRO MEDICO SAN RAFAEL" },
      { name: "UNIVERSAL DE SALUD" },
      { name: "CENTRO MEDICO DR. GUZMAN" },
      { name: "CENTRO DIAGNOSTICO TENARES" },
      { name: "POLIDEPORTIVO TENARES" },
      { name: "CENTRO COMUNITARIO PASO HONDO ADULTOS DE 70 AÑOS" },
      { name: "CENTRO COMUNITARIO LA JAGUITA TENARES ADULTOS DE 70 AÑOS Y MAS" },
      { name: "UNAP EULALIA PEÑA PERSONAL" }
    ],
  },
  {
    name: "Villa Tapia",
    centers: [
      { name: "HOSPITAL MUNICIPAL VILLA TAPIA" },
      { name: "CENTRO DIAGNOSTICO " },
      { name: "CENTRO MEDICO DE ESPECIALIDADES DE VILLA TAPIA (CEMEVIT)" },
      { name: "HOGAR PADRE NOEL VILLA TAPIA" },
      { name: "PUESTO MOVIL HOGAR DE ANCIANO PADRE NOEL" }
    ],
  },
  {
    name: "Tamayo",
    centers: [
      { name: "HOSPITAL MUNICIPAL JULIA SANTANA" },
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "TECHADO DE TAMAYO" },
      { name: "MONSERRATE " }
    ],
  },
  {
    name: "Neyba",
    centers: [
      { name: "HOSP. SAN BARTOLOME" },
      { name: "MULTIUSO NEYBA" },
      { name: "HOGAR ALEGRIA" },
      { name: "COLEGIO MEDICO (NEYBA)" },
      { name: "DPS BAHORUCO" },
      { name: "EL MANGUITO" }
    ],
  },
  {
    name: "Los Rios",
    centers: [
      { name: "CLUB LAS VIÑAS" },
      { name: "HOSP. MUNICIPAL LOS RIOS" }
    ],
  },
  {
    name: "Galvan",
    centers: [
      { name: "ESC. LAS TEJAS" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "ESC. ADELCIDA PEÑA MENDEZ" }
    ],
  },
  {
    name: "Villa Jaragua",
    centers: [
      { name: "TECHADO DE JARAGUA" },
      { name: "ESC. FE Y ALEGRIA" },
      { name: "HOGAR DIA VILLA JARAGUA" }
    ],
  },
  {
    name: "Las Clavellinas",
    centers: [
      { name: "ESC. MAXIMO GOMEZ" }
    ],
  },
  {
    name: "Santa Cruz",
    centers: [
      { name: "Iglesia Resureccion y vida" },
      { name: "Iglesia Buenas Nuevas" },
      { name: "Iglesia de Dios Pentecostal M.I" },
      { name: "Colegio Medico Dominicano" },
      { name: "CMD Filiar Barahona" }
    ],
  },
  {
    name: "Distrito Municipal de Villa Central",
    centers: [
      { name: "Club Juan Pablo Duarte" }
    ],
  },
  {
    name: "Vicente Noble",
    centers: [
      { name: "Club Cultural Vicente Noble" }
    ],
  },
  {
    name: "Cabral",
    centers: [
      { name: "Polideportivo/Multiusos Cabral" },
      { name: "Club Comunitario Las Viñas" }
    ],
  },
  {
    name: "Polo",
    centers: [
      { name: "Club Municipal de Polo" }
    ],
  },
  {
    name: "El Cachón",
    centers: [
      { name: "Club el Cachon" }
    ],
  },
  {
    name: "Enriquillo",
    centers: [
      { name: "Ayuntamiento de Enriquillo" }
    ],
  },
  {
    name: "Paraiso",
    centers: [
      { name: "Ayuntamiento de Paraiso" }
    ],
  },
  {
    name: "La Cienaga",
    centers: [
      { name: "Centro Comunitario de La Cienaga" }
    ],
  },
  {
    name: "Provincia de Barahona",
    centers: [
      { name: "Todas las unidades de Atencion Primaria  de la Provincia de Barahona, que son 40." }
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CENTRO DE ATENCIÓN LA CIENEGA (UNAP)" },
      { name: "CENTRO OLÍMPICO" },
      { name: "CENTRO REGIONAL MAGNOLIA" },
      { name: "HOSPITAL MUNICIPAL DR. JAIME SÁNCHEZ" },
      { name: "HOSPITAL DE REHABILITACIÓN (ASOCIACIÓN DOMINICANA DE REHABILITACIÓN)" },
      { name: "INSTITUTO DERMATÓLOGICO HUMBERTO BOGAERT UNIDAD BARAHONA" },
      { name: "HOSPITAL JAIME SANCHEZ" },
      { name: "HOSPITAL MINICIPAL DE POLO" },
      { name: "HOSPITAL MUNICIPAL DE CABRAL" },
      { name: "HOSPITAL MUNICIPAL DE ENRIQUILLO" },
      { name: "HOSPITAL MUNICIPAL DE PARAISO" },
      { name: "HOSPITAL MUNICIPAL DE SALINAS" },
      { name: "HOSPITAL MUNICIPAL DE VICENTE NOBLE" },
      { name: "HOSPITAL REGIONAL JAIME MOTA", },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BARAHONAL" },
      { name: "SERVICIO NACIONAL DE SALUD" }
    ],
  },
  {
    name: "Jimani",
    centers: [
      { name: "Centro Diagnostico Jimani" },
      { name: "Defensa Civil Jimani" },
      { name: "CPN Jimani Viejo" },
      { name: "CPN Jimani Pueblo" },
      { name: "CPN El Limon" },
      { name: "CPN Boca De Cachon" },
      { name: "CPN Tierra Nueva" }
    ],
  },
  {
    name: "Duverge",
    centers: [
      { name: "CPN Las Baitoas" },
      { name: "CPN Vengan a Ver" },
      { name: "CPN Puesto Escondido" },
      { name: "CPN San Jose" },
      { name: "CPN Las Mercedes" },
      { name: "CPN San Isidro" },
      { name: "Hosp.  Munic. DR. Jose Perez" },
      { name: "CPN Placer Bonito" }
    ],
  },
  {
    name: "Mella",
    centers: [
      { name: "CPN Colonia Mixta" },
      { name: "CPN Mella " }
    ],
  },
  {
    name: "Angostura",
    centers: [
      { name: "CPN Angostura" }
    ],
  },
  {
    name: "Cristobal",
    centers: [
      { name: "CPN Cristobal" },
      { name: "CPN Batey -8" }
    ],
  },
  {
    name: "La Descubierta",
    centers: [
      { name: "CPN Bartolome" },
      { name: "CPN Los Pinos Del Eden" },
      { name: "Hosp. Munic. La Descubierta" },
      { name: "CPN La Descubierta" }
    ],
  },
  {
    name: "Postrer Rio",
    centers: [
      { name: "CPN Postrer Rio" },
      { name: "CPN El Guayabal" },
      { name: "CPN Los Bolos" }
    ],
  },
  {
    name: "SAN PEDRO",
    centers: [
      { name: "Salon de la cultura ayuntamiento municipal" },
      { name: "Gobernacion provincial" },
      { name: "UCE" },
      { name: "Local de los bomberos" },
      { name: "Local de los Muelleros" },
      { name: "Capilla Sagrado Corazon de Jesus" },
      { name: "Iglesia Circulo de Oracion" },
      { name: "Club de Leones" },
      { name: "Defensa Civil" },
      { name: "Club de Periodista" },
      { name: "Iglesia Enmanuel tercera" },
      { name: "Parroquia Nuestra Señora de los Angeles" },
      { name: "Centro Comunal Barrio Lindo" },
    ],
  },
  {
    name: "Los Llanos",
    centers: [
      { name: "Club 26 de febrero" },
    ],
  },
  {
    name: "Quisqueya",
    centers: [
      { name: "Multiuso" },
    ],
  },
  {
    name: "Ramon Santana",
    centers: [
      { name: "Salon Ayuntaniento" },
    ],
  },
  {
    name: "Consuelo",
    centers: [
      { name: "Multiuso" },
    ],
  },
  {
    name: "Guayacanes",
    centers: [
      { name: "Iglesia de Dios" },
      { name: "Multiusu Honduras" },
      { name: "Iglesia Catolica" },
      { name: "Iglesia Asamblea De Dios" },
      { name: "Multiusu, Punta Pescadora" },
    ],
  },
  {
    name: "La Romana",
    centers: [
      { name: "Hospital Francisco A. Gonzalvo" },
      { name: "Domiciliar DPS" },
      { name: "Dispensario Luis J. Suarez" },
      { name: "Policia Nacional" },
      { name: "Unap Isla Saona" },
      { name: "Centro de Diagnostico Caleta" },
      { name: "Unap Paulina Jimenez" },
      { name: "Fuerza Armada" },
      { name: "Gobernacion" },
      { name: "Hogar del Niño" },
      { name: "Hospital Buen Samaritano" },
      { name: "Unap Caleta" },
      { name: "Hospital Aristides Fiallo Cabral" },
      { name: "Hospital Francisco A. Gonzalvo" },
      { name: "Unap Tomas desir" },
      { name: "Hospital Central Romana" },
      { name: "Hospital Materno Infantil Dr. Francisco A. Gonzalvo" },
      { name: "Centro Medico Coral" },
      { name: "Clínica Canela I" },
      { name: "Dispensario Médico Dr. Luis J. Suarez" },
      { name: "Centro de Especialidades Médicas CEMER" },
      { name: "Clínica Canela II" },
      { name: "Gerencia de Área" },
      { name: "Unap Los Bomberos" },
      { name: "Dispensario  Padre Cavaloto" },
      { name: "Centro Médico Dr. Rosario" },
      { name: "911 -CRUE" },
      { name: "DPS -La Romana" },
      { name: "Servicio Médico Diagnostico Manzano" },
      { name: "CESAC" },
      { name: "Multiuso Calasanz San Eduardo" },
      { name: "CEMER" },
      { name: "Colegio Medico Filial la Romana" },
      { name: "Centro Medico Oriental" },
      { name: "911 La Romana" },
      { name: "Iglesia Sanata Rosa de Lima" },
      { name: "Iglesia San Pablo" },
      { name: "Iglesia San Antonio de Padua" },
      { name: "Asamblea de Dios Camino de Vida" },
      { name: "Asamblea de Dios Casa Sobre la Roca" },
      { name: "Asamblea de Dios Emanuel Dios Con Nosotros" },
      { name: "Asamblea de Dios 5ta" },
      { name: "Asamblea de Dios Nueva Vida Central" },
      { name: "Asamblea de Dios la Rosa Salon Maranatha" },
      { name: "Centro Diagnostico Caleta" },
      { name: "Policlinica Duarte" },
    ],
  },
  {
    name: "Villa Hermosa",
    centers: [
      { name: "Policlinica Los Mulos" },
      { name: "Unap Km10 de Cumayasa" },
      { name: "Unap Villa Hermosa 4" },
      { name: "Unap Km14 de Cumayasa" },
      { name: "Villa  Hermosa 1-2" },
      { name: "Unap Cucama" },
      { name: "Km 10" },
    ],
  },
  {
    name: "Guaymte",
    centers: [
      { name: "Hospital Municipal Guaymate" },
      { name: "Guaymate" },
    ],
  },
  {
    name: "HIGUEY",
    centers: [
      { name: "MULTIUSO #1" },
      { name: "MULTIUSO #2" },
      { name: "MULTIUSO #3" },
      { name: "MULTIUSO #4" },
      { name: "MULTIUSO #5" },
      { name: "CLINICA DR. CEDANO" },
      { name: "CLINICA DR. QUEVEDO" },
      { name: "POLIDEPORTIVO" },
      { name: "HOGAR DE ANCIANOS" },
      { name: "HOSP. LAGUNAS DE NISIBON" },
      { name: "UNAP LA OTRA BANDA" },
      { name: "UNAP SAN FRANCISCO" },
      { name: "UNAP MAMÁ TINGÓ" },
      { name: "GRUPO MEDICO LIBERTAD" },
      { name: "GRUPO MEDICO QUIRULGICO" },
      { name: "HOSPITEN" },
      { name: "SERVICIO NACIONAL DE SALUD" },
      { name: "UNAP HATO DE MANA" },
      { name: "UNAP EL BONAO" },
      { name: "CENTRO MEDICO PUNTA CANA" },
    ],
  },
  {
    name: "SAN RAFAEL DEL YUMA",
    centers: [
      { name: "HOSP. DRA EVANGELINA RODRIGUEZ" },
      { name: "UNAP BAYAHIBE" },
      { name: "UNAP LOS NEGROS" },
    ],
  },
  {
    name: "Hato Mayor del Rey",
    centers: [
      { name: "Unap Guayabo Dulce" },
      { name: "Unap Jalonga" },
      { name: "Unap Los Hatillos" },
      { name: "Unap Villa Canto" },
      { name: "Unap Villa Ortega" },
      { name: "Unap La China" },
      { name: "Unap Villa Navarro" },
      { name: "Unap Ondina" },
      { name: "Unap Barrio Lindo" },
      { name: "Unap Gualey" },
      { name: "Unap La Javilla" },
      { name: "Unap Punta de Garza" },
      { name: "Unap Puerto Rico" },
      { name: "Unap Las Guamas" },
      { name: "Unap KM15" },
      { name: "Unap Yerba Buena" },
      { name: "Unap La Sierra" },
      { name: "Unap Morquecho" },
      { name: "Unap Pringamosa" },
      { name: "El mamón" },
    ],
  },
  {
    name: "Sabana de la Mar",
    centers: [
      { name: "Hospital Elupina Cordero" },
      { name: "Unap Magua" },
      { name: "Unap Las yaguita" },
      { name: "Unap Las Cañitas" },
      { name: "Escuela Caño Hondo" },
    ],
  },
  {
    name: "El Valle",
    centers: [
      { name: "Hospital El Valle" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "CENTRO MEDICO DR. CHAIN" },
      { name: "CENTRO MEDICO DEL ESTE" },
      { name: "DPS" },
      { name: "911" },
      { name: "ASILO DE HIGUERRA" },
      { name: "COLEGIO EL ROSARIO" },
      { name: "CENTRO CAMPESINO" },
      { name: "CTC" },
      { name: "POLITECNICO FEZ Y ALEGRIA" },
      { name: "POLITECNICO SEGIO A BERA" },
      { name: "DEFENSA CIVIL" },
      { name: "ESCUELA VILLA GUERRERO" },
      { name: "CASA CLUB GINANDIANA" },
      { name: "ESTANCIA DE ENVEGECIENTE" },
      { name: "DISCAPACITADO" },
      { name: "CENTRO COMUNAL V.G." },
      { name: "VICENTILLO" },
      { name: "BOMBERO" },
      { name: "CENTRO COM.VILA G." },
      { name: "PEDRO SANCHEZ" },
      { name: "LA HIGUERRA" },
      { name: "IGLESIA BEJAMIN" },
      { name: "EL CERCADO" },
      { name: "EL CUEY" },
      { name: "CLUB DOMINO" },
      { name: "HOSPITAL TEOFILO HDEZ" },
    ],
  },
  {
    name: "MICHES",
    centers: [
      { name: "HOSPITAL , MUN.MICHES" },
      { name: "DISTRITO EDUCATIVO" },
      { name: "CTC" },
      { name: "EL ASFALTO" },
      { name: "BOCA DEL RIO" },
      { name: "LOS FRANCESES" },
      { name: "CENTRO PARROQUIAL" },
    ],
  },
  {
    name: "Pedernales",
    centers: [
      { name: "Hospital Dr. Elio Fiallo" },
      { name: "CPN 3-4" },
      { name: "CPN 5-6" },
      { name: "CPN 7-8" },
      { name: "UNAP 9" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
