const centros = [
  {
    name: "AZUA",
    centers: [
      { name: "CENTRO DE SALUD FINCA 6" },
      { name: "CLINICA RURAL AMIAMA GOMEZ" },
      { name: "CLINICA RURAL ANZONIA" },
      { name: "CLINICA RURAL BARRERAS" },
      { name: "CLINICA RURAL EL CARRIZAL" },
      { name: "CLINICA RURAL EL ROSARIO" },
      { name: "CLINICA RURAL ESTEBANIA" },
      { name: "CLINICA RURAL HATILLO" },
      { name: "CLINICA RURAL HATO NUEVO" },
      { name: "CLINICA RURAL LA SIEMBRA" },
      { name: "CLINICA RURAL LAS BARIAS" },
      { name: "CLINICA RURAL LAS CHARCAS" },
      { name: "CLINICA RURAL LAS LAGUNAS" },
      { name: "CLINICA RURAL LOS NEGROS" },
      { name: "CLINICA RURAL LOS TOROS" },
      { name: "CLINICA RURAL MAGUEYAL" },
      { name: "CLINICA RURAL MONTE BONITO" },
      { name: "CLINICA RURAL PALMAR DE OCOA" },
      { name: "CLINICA RURAL PROYECTO 4" },
      { name: "CLINICA RURAL PROYECTO-2-C" },
      { name: "CLINICA RURAL PUEBLO VIEJO" },
      { name: "CLINICA RURAL SABANA YEGUA" },
      { name: "CLINICA RURAL SAJANOA" },
      { name: "CLINICA RURAL TABARA ABAJO" },
      { name: "CLINICA RURAL TABARA ARRIBA" },
      { name: "CLINICA RURAL VIAJAMA" },
      { name: "CLINICA RURAL VILLA ARPANDO" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL TAIWAN" },
      { name: "LICEO GUAYACANAL" },
      { name: "LICEO JOSE FRANCISCO BOBADILLA" },
      { name: "CENTRO CLÍNICO Y DIAGNOSTICO DE ATENCION PRIMARIA" },
      { name: "GOBERNACIÓN" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA LA BOMBITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAÑITA -A" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL BARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL HIGUERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GANADERO BARRIO LOS TECNICOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAYAS ARRIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -1" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -2" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOVILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS MONTES FRIOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PARCELEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUEBLO VIEJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA ANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CORAZON DE JESUS" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA OCOA" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE BAHORUCO NEYBA" },
      { name: "MULTIUSO JARAGUA" },
      { name: "MULTIUSO NEYBA" },
      { name: "MULTIUSO TAMAYO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA EL SALADO GALVAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTAMIRA" },
      { name: "UNIDAD DE ATENCION PRIMARIA APOLINAR PERDOMO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 2" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABEZA DE TORO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL PALMAR" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA UVILLA" },
      { name: "LOS BOMBEROS NEIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA MONSERRATE" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CLUB DE CACHON" },
      { name: "CLUB ENRIQUILLO" },
      { name: "COLEGIO MEDICO DOMINICANO" },
      { name: "IGLESIA RESURECCION Y VIDA (FLEMING)" },
      { name: "PARAISO UNIDAD DE ATENCION PRIMARIA 1 Y 2" },
      { name: "PLAZA COMUNAL VICENTE NOBLE" },
      { name: "POLO CENTRO COMUNAL" },
      { name: "UCATEBA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA DE QUITA CORAZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CABRAL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA CANOA" },
      { name: "UNIDAD DE ATENCION PRIMARIA FONDO NEGRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA INVI-CEA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA LISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS SALINAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS BLANCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PATOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA PEÑON" },
      { name: "UNIDAD DE ATENCION PRIMARIA PESCADERIA" },
      { name: "DEFENSA CIVIL" },
      { name: "ENRIQUILLO HOSPITAL" },
      { name: "PALACIO DE JUSTICIA" },
      { name: "CENTRO DE PRIMER NIVEL PALO ALTO" },
      { name: "PARAISO III, IV" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAITOITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOMBITA " },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MONTAÑITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PEÑUELA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PLAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA RAQUETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS ARROYOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "VICENTE NOBLE I, II V" },
      { name: "VICENTE NOBLE III, IV" },
      { name: "DIRECCION PROVINCIAL DE SALUD BAHORUCO" },
      { name: "SECTOR CASANDRA" },
      { name: "HOTELES ZONA BARAHONA" },
    ],
  },
  {
    name: "DAJABÓN",
    centers: [
      { name: "UNIDAD DE TENCION PRIMARIA BARRIO NORTE" },
      { name: "CASA DE LA CULTURA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE DAJABON" },
      { name: "POLI DEPORTIVO AMBRIOSO ESTEVEZ" },
    ],
  },
  {
    name: "DISTRITO NACIONAL",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL SAN PEDRO APOSTOL" },
      { name: "CLUB MAURICIO BÁEZ" },
      { name: "CLUB RAFAEL BARIAS" },
      { name: "COLEGIO SAN GABRIEL" },
      { name: "FUNDACIÓN JUDEGU" },
      { name: "FUNSAZURZA" },
      { name: "CENTRO DE DIAGNOSTICO DE ATENCION PRIMARIA BARNEY MORGAN " },
      { name: "CLUB DEPORTIVO LOS PIONEROS" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CLUB RENACER " },
      { name: "FUNDACION ESCOBA" },
      { name: "IGLESIA PERPETUO SOCORRO" },
      { name: "PLAZA SAMBIL" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "FUNDACION HUELLAS DEL SIGLO" },
      { name: "HOSPITAL DR. FELIX MARIA GOICO" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "PLAZA DUARTE (CARREFOUR)" },
      { name: "UNIVERSIDAD NACIONAL PEDRO HENRIQUEZ UREÑA (UNPHU)" },
      { name: "CENTRO MEDICO FUSADI" },
      {
        name:
          "CENTRO DE DIAGNÓSTICO MEDICINA AVANZADA Y TELEMEDICINA (CEDIMAT)",
      },
      { name: "HOSPITAL DR. IGNACIO JACINTO MAÑÓN" },
      { name: "HOSPITAL GENERAL PLAZA DE LA SALUD" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CAPILLA LA ALTAGRACIA" },
      { name: "CATEDRAL SANTA ANA - JUAN XXIII" },
      { name: "CENTRO DE VACUNACION SIGLO 21" },
      { name: "CENTRO MÉDICO DOCTOR OVALLE" },
      { name: "CLUB BLUE" },
      { name: "CLUB SALOME UREÑA" },
      { name: "ESCUELA GREGORIO LUPERÓN VISTA AL VALLE" },
      { name: "MULTIUSO ARENA  57" },
      { name: "MULTIUSO ARENOSO" },
      { name: "MULTIUSO BAJO TECHO VILLA RIVAS" },
      { name: "UASD" },
      { name: "CLUB JUAN ALBERTO ESPINOLA" },
      { name: "CLUB MAYORISTAS" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CASA CLUB DE GINANDIANA" },
      { name: "CENTRO CAMPESINO" },
      { name: "CENTRO TECNOLOGICO COMUNITARIO" },
      { name: "DEFENSA CIVIL" },
      { name: "HOSPITAL DOCTOR TEOFILO HERNADEZ" },
      { name: "CUERPO DE BOMBEROS EL SEIBO" },
      { name: "IGLESIA BENJAMIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA MIRADOR SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA GUERRERO" },
      { name: "CLUB DE DOMINO" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS QUINIENTAS" },
    ],
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL PEDRO SANTANA" },
      { name: "CENTRO DE PRIMER NIVEL DE JUAN SANTIAGO" },
      { name: "CENTRO DE PRIMER NIVEL EL LLANO" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL DE HONDO VALLE " },
      { name: "POLIDEPORTIVO  COMENDADOR" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CENTRO DE PRIMER NIVEL ALGARROBO" },
      { name: "CENTRO DE PRIMER NIVEL BATEY GINEBRA" },
      { name: "CENTRO DE PRIMER NIVEL BONAGUA" },
      { name: "CENTRO DE PRIMER NIVEL CEIBA DE MADERA" },
      { name: "CENTRO DE PRIMER NIVEL CUERO DURO" },
      { name: "CENTRO DE PRIMER NIVEL EL CAIMITO" },
      { name: "CENTRO DE PRIMER NIVEL EL COROZO" },
      { name: "CENTRO DE PRIMER NIVEL EL HIGUERITO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA ERMITA" },
      { name: "CENTRO DE PRIMER NIVEL LA ISLETA" },
      { name: "CENTRO DE PRIMER NIVEL LA MANZANA" },
      { name: "CENTRO DE PRIMER NIVEL LA YAGUA" },
      { name: "CENTRO DE PRIMER NIVEL LAS FLORES" },
      { name: "CENTRO DE PRIMER NIVEL LAS GUAZUMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS LAGUNAS " },
      { name: "CENTRO DE PRIMER NIVEL LOS BRAZOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LOS PANCHOS" },
      { name: "CENTRO DE PRIMER NIVEL MONTE DE LA JAGUA " },
      { name: "CENTRO DE PRIMER NIVEL NUEVO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL PALMA HERRADA" },
      { name: "CENTRO DE PRIMER NIVEL QUEBRADA HONDA" },
      { name: "CENTRO DE PRIMER NIVEL REPARADERO" },
      { name: "CENTRO DE PRIMER NIVEL SAL SI PUEDES" },
      { name: "CENTRO DE PRIMER NIVEL SAN FRANCISCO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL SAN VICTOR" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA MOCA" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA DURA" },
      { name: "CENTRO DE PRIMER NIVEL VERAGUA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA PROGRESO" },
      { name: "CENTRO DE PRIMER NIVEL ZAFARRAYA" },
      { name: "HOSPITAL JOSÉ CONTRERAS" },
      { name: "COLEGIO MÉDICO DOMINICANO" },
      { name: "CENTRO DE PRIMER NIVEL JOBA ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL ORTEGA" },
      { name: "CENTRO DE PRIMER NIVEL PUESTO GRANDE" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CAFETALERA" },
      { name: "HOSPITAL JAMAO AL NORTE" },
      { name: "HOSPITAL MANUEL DE LUNA" },
      { name: "CDX CARLOS MARIA ROJAS BADIA" },
      { name: "CLUB JOSE HORACIO RODRIGUEZ" },
      { name: "CLUB BARRIO LA ESTELA" },
      { name: "CLUB RECREATIVO MOCA" },
      { name: "CENTRO DE PRIMER NIVEL MANUEL RODRIGUEZ" },
      { name: "CENTRO DE PRIMER NIVEL BARRIO VIEJO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL BOCA FERREA" },
      { name: "CENTRO DE PRIMER NIVEL CANCA LA REINA" },
      { name: "CENTRO DE PRIMER NIVEL LA GUAMA" },
      { name: "LOGIA PERSEVERANCIA" },
      { name: "CENTRO DE PRIMER NIVEL GUAUCI" },
    ],
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL EL VALLE" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL MAMON" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUALEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUAYABO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA JALONGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA KM 15" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CHINAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS GUAMAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS HATILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MANCHADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUERTO RICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUNTA DE GARZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CANTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA NAVARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ORTEGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA YERBA BUENA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA JAVILLA" },
    ],
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "UNIDAD DE ATENCION PRIMARIA TENARES" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA TAPIA" },
      { name: "CASA CLUB COLEGIO MEDICO" },
      { name: "POLIDEPORTIVO BAJO TECHO" },
      { name: "AYUNTAMIENTO DE SALCEDO" },
    ],
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL BATEY 8" },
      { name: "CENTRO DE PRIMER NIVEL BOCA DE CACHON" },
      { name: "CENTRO DE PRIMER NIVEL COLONIA MIXTA" },
      { name: "CENTRO DE PRIMER NIVEL PLACER BONITO" },
      { name: "CENTRO DE PRIMER NIVEL SAN JOSE" },
      { name: "CENTRO DIAGNÓSTICO." },
      { name: "CENTRO DE PRIMER NIVEL ANGOSTURA." },
      { name: "CENTRO DE PRIMER NIVEL BARTOLOMÉ" },
      { name: "CENTRO DE PRIMER NIVEL CRISTÓBAL." },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABAL." },
      { name: "CENTRO DE PRIMER NIVEL EL LIMÓN." },
      { name: "CENTRO DE PRIMER NIVEL JIMANI CENTRO." },
      { name: "CENTRO DE PRIMER NIVEL JIMANI VIEJO. BARRIO JIMANI VIEJO." },
      { name: "CENTRO DE PRIMER NIVEL LA DESCUBIERTA." },
      { name: "CENTRO DE PRIMER NIVEL LAS BAITOAS." },
      { name: "CENTRO DE PRIMER NIVEL LAS MERCEDES." },
      { name: "CENTRO DE PRIMER NIVEL LOS BOLOS." },
      { name: "CENTRO DE PRIMER NIVEL LOS PINOS DEL EDÉN." },
      { name: "CENTRO DE PRIMER NIVEL MELLA" },
      { name: "CENTRO DE PRIMER NIVEL POSTRER RÍO." },
      { name: "CENTRO DE PRIMER NIVEL PUESTO ESCONDIDO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ISIDRO." },
      { name: "CENTRO DE PRIMER NIVEL TIERRA NUEVA." },
      { name: "CENTRO DE PRIMER NIVEL VENGAN A VER." },
      { name: "HOSPITAL GENERAL MELENCIANO" },
      { name: "HOSPITAL JOSE PEREZ" },
      { name: "HOSPITAL LA DESCUBIERTA" },
    ],
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "AEROPUERTO PUNTA CANA" },
      { name: "HOSPITAL DR. EVANGELINA RODRIGUEZ" },
      { name: "HOTEL LOPESAN COSTA BAVARO" },
      { name: "MULTIUSO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAYAHIBE" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOCA DE CHAVON" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOCA DE YUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL SALADO - HIGUEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA HATO DE MANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA OTRA BANDA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PLATANITOS " },
      { name: "UNIDAD DE ATENCION PRIMARIA MAMATINGO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
    ],
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "DIRECCION PROVINCIAL DE SALUD DE LA ROMANA" },
      { name: "GOBERNACIÓN PROVINCIAL" },
      { name: "HOSPITAL ARÍSTIDES FIALLO CABRAL" },
      { name: "HOSPITAL MATERNO INFANTIL DR. FRANCISCO A. GONZALVO" },
      { name: "MULTIUSO SAN EDUARDO " },
    ],
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CAFETALERA BELARMINIO RAMIREZ E. HIJOS. (CAFE MONTE ALTO)" },
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER NIVEL BAYACANES" },
      { name: "CENTRO DE PRIMER NIVEL BUENA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL BURENDE" },
      { name: "CENTRO DE PRIMER NIVEL EL BALCON" },
      { name: "CENTRO DE PRIMER NIVEL EL CERCADO" },
      { name: "CENTRO DE PRIMER NIVEL EL MAMEY" },
      { name: "CENTRO DE PRIMER NIVEL HATILLO" },
      { name: "CENTRO DE PRIMER NIVEL JUMUNUCO" },
      { name: "CENTRO DE PRIMER NIVEL LA CULATA" },
      { name: "CENTRO DE PRIMER NIVEL LA SABINA" },
      { name: "CENTRO DE PRIMER NIVEL LA TORRE" },
      { name: "CENTRO DE PRIMER NIVEL LIMONAL" },
      { name: "CENTRO DE PRIMER NIVEL OCTAVIA GAUTIER" },
      { name: "CENTRO DE PRIMER NIVEL PASO BAJITO" },
      { name: "CENTRO DE PRIMER NIVEL PIEDRA BLANCA" },
      { name: "CENTRO DE PRIMER NIVEL RIO SECO" },
      { name: "CENTRO DE PRIMER NIVEL SAN MIGUEL" },
      { name: "CENTRO DE PRIMER NIVEL SANTO CERRO" },
      { name: "CENTRO DE PRIMER NIVEL TIREO" },
      { name: "CENTRO DE SALUD OBRA SOCIAL SALESIANA" },
      { name: "CENTRO MEDICO PADRE FANTINO" },
      { name: "CLÍNICA BAEZ SOTO" },
      { name: "CLÍNICA CEMEVE" },
      { name: "COOPERATIVA VEGA REAL" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "DEFENSA CIVIL" },
      { name: "HISPITAL JIMA ABAJO " },
      { name: "HOSPITAL JUAN ANT.CASTILLO" },
      { name: "HOSPITAL MORILO KING " },
      { name: "HOSPITAL OCTAVIA GAUTIER" },
      { name: "POLICLINICO LA VEGA" },
      { name: "AYUNTAMIENTO MUNICIPAL LA VEGA" },
      { name: "CENTRO DE PRIMER NIVEL CENTRO EL CARMEN" },
      { name: "CENTRO DE PRIMER NIVEL EL PINO " },
      { name: "CENTRO DE PRIMER NIVEL EL RANCHITO" },
      { name: "CENTRO DE PRIMER NIVEL EL TANQUE" },
      { name: "CENTRO DE PRIMER NIVEL LAS CARMELITAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS UVAS" },
      { name: "CENTRO DE PRIMER NIVEL LICEY" },
      { name: "CENTRO DE PRIMER NIVEL MARIA AUXILIADORA" },
      { name: "CENTRO DE PRIMER NIVEL PINTO SABANETA" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL RIO VERDE" },
      { name: "CENTRO DE PRIMER NIVEL YAYAS" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL BACUI" },
      { name: "CENTRO DE PRIMER NIVEL CABUYAS" },
      { name: "CLINICA LA CONCEPCION" },
    ],
  },
  {
    name: "MARIA TRINIDAD SÁNCHEZ",
    centers: [
      { name: "AYUNTAMIENTO DEL POZO" },
      { name: "AYUNTAMIENTO MUNICIPAL NAGUA" },
      { name: "CASA DE FORMACION SAGRADA FAMILIA" },
      { name: "CENTRO COMUNITARIO LOS YAYALES" },
      { name: "CENTRO COMUNITARIO MATA BONITA" },
      { name: "CENTRO COMUNITARIO PAYITA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO AL MEDIO" },
      { name: "CENTRO DE PRIMER NIVEL LA FACTORIA" },
      { name: "CENTRO DE PRIMER NIVEL ABREU" },
      { name: "CENTRO DE PRIMER NIVEL BAOBA DEL PIÑAL" },
      { name: "CENTRO DE PRIMER NIVEL BEJUCO ALAMBRE" },
      { name: "CENTRO DE PRIMER NIVEL BOBITA" },
      { name: "CENTRO DE PRIMER NIVEL COPEYITO" },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL EL PAPAYO" },
      { name: "CENTRO DE PRIMER NIVEL EL YAYAL" },
      { name: "CENTRO DE PRIMER NIVEL LA CAPILLA" },
      { name: "CENTRO DE PRIMER NIVEL LAS CEJAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CORCOBAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GARZAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GORDAS" },
      { name: "CENTRO DE PRIMER NIVEL LOMA ALTA" },
      { name: "CENTRO DE PRIMER NIVEL SAN RAFAEL" },
      { name: "HOSPITAL DR. ANTONIO YAPOR HEDED" },
      { name: "HOSPITAL DR. CARLOS A. ZAFRA" },
      { name: "PARROQUIA SANTISIMA TRINIDAD" },
      { name: "POLIDEPORTIVO NAGUA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
      { name: "UASD NUEVA" },
      { name: "CENTRO DE PRIMER NIVEL MATANCITAS" },
      { name: "HOSPITAL VIRGILIO GARCIA" },
    ],
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CLINICA POLICLINICO BONAO" },
      { name: "CLUB LOS AMAPOLOS" },
      { name: "CRUCE UASD BONAO" },
      { name: "DISTRITO MUNICIPAL JUMA BEJUCAL" },
      { name: "HOSPITAL DR. JOSE A. COLUMNA" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL PIEDRA BLANCA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JAYACO" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAXIMO GOMEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANA DEL PUERTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN PEDRO Y SAN PABLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS ARROCES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS QUEMADOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA NUESTRA SRA DE FATIMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SONADOR" },
    ],
  },
  {
    name: "MONTE CRISTI",
    centers: [
      { name: "CARBONERA (VISITAR)" },
      { name: "CENTRO COMUNAL LOMA" },
      { name: "CLUB JUAN PABLO" },
      { name: "DOÑA ANTONIA (VER)" },
      { name: "GUAJACA" },
      { name: "IGLESIA EVANGÉLICA MISIONERA AMPARO DEL CIELO (KM 13)" },
      { name: "IGLESIA KM. 14" },
      { name: "LILO CAFÉ & RESTAURANT" },
      { name: "POLIDEPOIRTIVO DE GUAYUBIN" },
      { name: "POLIDEPORTIVO - CASTAÑUELAS" },
      { name: "POLIDEPORTIVO - LAS MATAS DE SANTA CRUZ" },
      { name: "POLIDEPORTIVO - PEPILLO SALCEDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA COPEY - PEPILLO SALCEDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA HATILLO PALMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA HATO DEL MEDIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PAPAYO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA CRUZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO DE LA PALOMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL VIJIADOR" },
      { name: "UNIDAD DE ATENCION PRIMARIA HERMANAS MIRABAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA GALLERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS FLORES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS MATAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MARTIN GARCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA PILOTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA MARIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ELISA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA SINDA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LO MAESTROS" },
      { name: "UNIDAD DE TENCION PRIMARIA COPEY DE GUAYUBIN" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL GREGORIO LUPERÓN" },
      { name: "CENTRO DE PRIMER NIVEL REFORMA DE DAJAO" },
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA  5 Y 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA  9" },
      { name: "UNIDAD DE ATENCION PRIMARIA 3 Y 4" },
      { name: "UNIDAD DE ATENCION PRIMARIA 7 Y 8" },
    ],
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "ARROYO HONDO" },
      { name: "AYUNTAMIENTO MUNIICIPAL DE BANI" },
      { name: "CENTRO DE PRIMER NIVEL BOCA CANASTA" },
      { name: "CAÑAFISTOL ABAJO" },
      { name: "CAÑAFISTOL ARRIBA" },
      { name: "CENTRO COMUNAL VILLA MAJEGA" },
      { name: "CLINICA RURAL PIZARRETE - CENTRO DE PRIMER NIVEL" },
      { name: "CONSULTORIO MEDICO EL MANI" },
      { name: "CENTRO DE PRIMER NIVEL NANCY ORTIZ - MATANZAS" },
      { name: "CENTRO DE PRIMER NIVEL PAYA" },
      { name: "CENTRO DE PRIMER NIVEL WILSON BELLO" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "ESCONDIDO I" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "FUNDACION DE PERAVIA II" },
      { name: "GOBERNACION PROVINCIAL PERAVIA" },
      { name: "CENTRO DE PRIMER NIVEL DE ATENCIÓN HONDURAS" },
      { name: "HOSPITAL MUNICIPAL NIZAO" },
      { name: "HOSPITAL MUNICIPAL VILLA FUNDACION" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS CARRERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "MAXIMO GOMEZ" },
      { name: "QUIJA QUIETA" },
      { name: "RIO ARRIBA" },
      { name: "ROSA NOVA" },
      { name: "SABANA BUEY" },
      { name: "SANTA ROSA 1" },
      { name: "SAONA I" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTANA" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA MAJEGA I" },
      { name: "VILLA SOMBRERO 1" },
      { name: "UNIDAD DE ATENCION PRIMARIA SALINAS" },
    ],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "AYUNTAMIENTO DE CABARETE" },
      { name: "AYUNTAMIENTO DE SOSUA" },
      { name: "CENTRO DE PRIMER NIVEL DOLORES DE LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL SAN MARCOS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "HOSPITAL MUNICIPAL DE ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE GUANANICO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE LOS HIDALGOS" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "LIFESTYLE HOTEL" },
      { name: "OCEAN WORLD" },
      { name: "HOSPITAL MUNICIPAL DE LUPERÓN" },
      { name: "LIGA DEL ATLÁNTICO" },
    ],
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CENTRO COMUNAL" },
      { name: "CENTRO COMUNAL LOS COCOS" },
      { name: "CENTRO COMUNAL RANCHO ESPAÑOL" },
      { name: "CENTRO COMUNAL, BATEY HORMIGA " },
      { name: "CENTRO TECNOLOGICO COMUNITARIO DEL LIMÓN" },
      { name: "CLUB DE MADRE LOS PUENTES" },
      { name: "CRUCE DE HONDURAS (EDIFICIO BLANCO)" },
      { name: "CRUCE DE TEZÓN" },
      { name: "FABRICA DE HIELO (PASCUALA)" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "IGLESIA CATÓLICA (RINCON)" },
      { name: "IGLESIA CATOLICA LAS GARITAS" },
      { name: "JUNTA DE VECINOS DANIEL WILMORE" },
      { name: "JUNTA DE VECINOS JUANA VICENTA" },
      { name: "LOS CACAOS" },
      { name: "LOS ROBALOS (CENTRO COMUNAN)" },
      { name: "SINDICATO DE LA PORTUARIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MAJAGUA" },
    ],
  },
  {
    name: "SAN CRISTÓBAL",
    centers: [
      { name: "ASOCIACION DE INDUSTRIA" },
      { name: "CENTRO DE DIAGNOSTICO CEDISA" },
      { name: "CENTRO DE DIAGNOSTICO MADRE VIEJA NORTE" },
      { name: "CENTRO DIAGNOSTICO EL CARRIL" },
      { name: "CENTRO DIAGNOSTICO VILLA FUNDACION" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "COMEDOR ECONOMICO LAVA PIE" },
      { name: "CENTRO DE PRIMER NIVEL ESTEBANIA BORINQUEN" },
      { name: "CENTRO DE PRIMER NIVEL GERONIMO PINALES (KM. 18)" },
      { name: "CENTRO DE PRIMER NIVEL JUAN BARON" },
      { name: "CENTRO DE PRIMER NIVEL LA CANELA" },
      { name: "CENTRO DE PRIMER NIVEL LA PISCINA" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOTAOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS MOLINAS" },
      { name: "CENTRO DE PRIMER NIVEL LOS PARCELEROS" },
      { name: "CENTRO DE PRIMER NIVEL LUCIOLO BAEZ" },
      { name: "CENTRO DE PRIMER NIVEL MODESTO OGANDO (LAS FLORES)" },
      { name: "CENTRO DE PRIMER NIVEL PAJARITO (VILLA ALTAGRACIA)" },
      { name: "CENTRO DE PRIMER NIVEL PUEBLO NUEVO" },
      { name: "CENTRO DE PRIMER NIVEL PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL QUITA SUEÑO" },
      { name: "CENTRO DE PRIMER NIVEL SEMANA SANTA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CENTRO" },
      { name: "CENTRO DE PRIMER NIVEL YAGUATE (RAMONA SANTANA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN CRISTOBAL" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOSPITAL M. CAMBITA GARABITO" },
      { name: "HOSPITAL M. VILLA ALTAGRACIA" },
      { name: "HOSPITAL M. YAGUATE" },
      { name: "HOSPITAL MUNICIPAL HAINA" },
      { name: "HOSPITAL RAFAEL J. MAÑÓN" },
      { name: "HOSPITAL TOMASINA VALDEZ" },
      { name: "HOSPITAL CAMBITA PUEBLO" },
      { name: "MULTIUSO PALENQUE" },
      { name: "ONG ORDEN DE MALTA" },
      { name: "PARQUE RADHAMES" },
      { name: "POLICLINICA NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "POLIDEPORTIVO NIGUA" },
      { name: "DISPENSARIO LOS AMERICANOS" },
      { name: "UASD SAN CRISTOBAL" },
      { name: "COMEDOR ECONOMICO" },
    ],
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE SALUD  ARROYO CANA" },
      { name: "CENTRO DE SALUD  PUEBLO A BAJO" },
      { name: "CENTRO DE SALUD  SAN ANTONIO" },
      { name: "CENTRO DE SALUD SAN RAFAEL" },
      { name: "HOSPITAL GUARIONEX ALCANTARA" },
    ],
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "CLUB COME MORO" },
      { name: "CENTRO DE PRIMER NIVEL VALLEJUELO" },
      { name: "EL CASINO SJ" },
      { name: "SALÓN DE CONFERENCIA DIRECCION PROVINCIAL DE SALUD SAN JUAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOHECHIO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BUENA VISTA DEL YAQUE" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAPULIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRUMBADERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL NARANJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JINOVA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JORGILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUAN HERRERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA ESTANCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA NAVAJA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CARTONES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS GRINGOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MATAYAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA POZO HONDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CARMEN" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ESPERANZA" },
      { name: "EL JOVITO" },
      { name: "LA RANCHA" },
      { name: "VALLECITO" },
    ],
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "CLINICA DOCTOR DE LEON" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "CLUB DE LEONES" },
      { name: "DEFENSA CIVIL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "IGLESIA ASAMBLEA DE DIOS JUAN DOLIÓ" },
      { name: "IGLESIA CATOLICA LOS CONUCOS" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "LOCAL DE LOS MUELLEROS" },
      { name: "MONTE DE SION" },
      { name: "MULTIUSO - EXTENSION UASD" },
      { name: "UCE" },
      { name: "AYUNTAMIENTO MUNICIPAL SAN PEDRO" },
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" },
      { name: "AGIO CARIBBEAN TOBACCO" },
      { name: "CLUB LOS PINOS" },
      { name: "DPS SAN PEDRO DE MACORIS" },
      { name: "IGLESIA DE DIOS GUAYACANES" },
    ],
  },
  {
    name: "SÁNCHEZ RAMIREZ",
    centers: [
      { name: "BAJO TECHO" },
      { name: "AYUNTAMIENTO DE QUITA SUEÑO" },
      { name: "CENTRO DE DIAGNOSTICO FANTINO" },
      { name: "CENTRO DE PRIMER LA CUEVA" },
      { name: "CENTRO DE PRIMER NIVEL ARENOSO" },
      { name: "CENTRO DE PRIMER NIVEL BATERO" },
      { name: "CENTRO DE PRIMER NIVEL CABALLERO" },
      { name: "CENTRO DE PRIMER NIVEL CHACUEY" },
      { name: "CENTRO DE PRIMER NIVEL COMEDERO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL CRUZ DE ANGELINA" },
      { name: "CENTRO DE PRIMER NIVEL DOS PALMAS" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONCITO" },
      { name: "CENTRO DE PRIMER NIVEL HERNANDO ALONZO" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA" },
      { name: "CENTRO DE PRIMER NIVEL LA BIJA" },
      { name: "CENTRO DE PRIMER NIVEL LA PLACETA" },
      { name: "CENTRO DE PRIMER NIVEL SABALLO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA PRIETA" },
      { name: "CENTRO DE PRIMER NIVEL ZAMBRANA" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "CLUB DE AMAS DE CASA PEDRO FRANCISCO BONO" },
      { name: "CLUB DEL COLEGIO MEDICO" },
      { name: "CENTRO DE PRIMER NIVEL VILLA LA MATA" },
      { name: "DISTRITO ESCOLAR 16-01" },
      { name: "HOSPITAL DE VILLA LA MATA" },
      { name: "HOSPITAL DR. RAMON BAEZ" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "HOSPITAL SIGIFREDO ALBA DOMINGUEZ" },
      { name: "LOS COROZOS" },
      { name: "PARQUE DUARTE" },
      { name: "CENTRO DE DIAGNOSTICO LA MATA" },
      { name: "CENTRO DE PRIMER NIVEL PIÑA VIAJA" },
      { name: "CENTRO DE PRIMER NIVEL PLATANAL" },
    ],
  },
  {
    name: "SANTIAGO",
    centers: [
      { name: "CIENFUEGOS (BAJO TECHO)" },
      { name: "CLUB CREATIVO:NAVARRETE" },
      { name: "CLUB HATO DEL YAQUE" },
      { name: "CLUB MAMBUICHE" },
      { name: "ENSANCHE LIBERTAD (GUG)" },
      { name: "HOSPITAL IRENE FERNÁNDEZ JÁNICO" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE" },
      { name: "HOSPITAL REGIONAL UNIVERSITARIO ARTURO GRULLON" },
      { name: "IGLESIA ADVENTISTA" },
      { name: "MEDICA" },
      { name: "PARQUE CENTRAL" },
      { name: "DIRECCIÓN REGIONAL DE SALUD" },
      { name: "UNIVERSIDAD NAPOLEON NUNEZ MOLINA (LICEY)" },
      { name: "SUPER MERCADO NACIONAL " },
      { name: "SUPER MERCADO LA SIRENA " },
      { name: "CLUB VILLA OLGA " },
      { name: "LICEO EUGENIO DE JESUS MARCANO (TAMBORIL)" },
      { name: "COLINAS MALL" },
      { name: "INTELLISYS CERROS DE GURABO" },
      { name: "PARQUE DE VILLA GONZALEZ" },
      { name: "PARQUE ZONA FRANCA DELIO CLASE" },
      { name: "ZONA FRANCA EMIMAR" },
      { name: "ZONA FRANCA PISANO" },
      { name: "CENTRO DE PRIMER NIVEL BUEN PASTOR" },
      { name: "CENTRO DE PRIMER NIVEL BELLA VISTA" },
      { name: "CLUB ASOCIACIÓN DE CRONISTAS DEPORTIVOS DE SANTIAGO (ACDS)" },
      { name: "CENTRO DE PRIMER NIVEL VILLA BAO" },
      { name: "CENTRO DE PRIMER NIVEL LA HERRADURA" },
      { name: "CENTRO DE PRIMER NIVEL PLATANAL" },
      { name: "CENTRO DE PRIMER NIVEL BELLA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA LIBERACION" },
      { name: "CENTRO DE PRIMER NIVEL YAGUITA DEL PASTOR" },
      { name: "CIUDAD SANTA MARIA LA OTRA BANDA" },
      { name: "HOSPITAL SABANA IGLESIA" },
      { name: "HOSPITAL SAJOMA" },
      { name: "SUPER MERCADO LA FUENTE FUN" },
      { name: "UASD BARRANQUITA" },
      { name: "CABRAL Y BAEZ" },
      { name: "CLÍNICA UNIÓN MÉDICA" },
      { name: "CLUB CANCA" },
      { name: "COROMINAS" },
      { name: "GRAN TEATRO DEL CIBAO" },
      { name: "PARQUE INDUSTRIAL MATANZA" },
      { name: "PLAZA LAMA" },
      { name: "UNIVERSIDAD PUCMM" },
      { name: "UNIVERSIDAD UTESA" },
    ],
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL MONCIÓN" },
      { name: "CENTRO DE MADRES, LA CEIBA" },
      { name: "CLUB SAN JOSE" },
      { name: "ESCUELA ANA JOAQUIN HIDALGO" },
      { name: "PARQUE OLEGARIA RODIGUEZ" },
    ],
  },
  {
    name: "SANTO DOMINGO",
    centers: [
      { name: "CESAC" },
      { name: "CLUB RECREATIVO CULTURAL UNION " },
      { name: "CODECOD (CENTRO DE DESAROLLO)" },
      { name: "GACEBO DEL PARQUE MONTE ADENTRO" },
      { name: "HOSPITAL MUNICIPIAL DE BOCA CHICA" },
      { name: "MULTIUSO PANTOJA" },
      { name: "AYUNTAMIENTO SANTO DOMINGO ESTE" },
      { name: "CLUB CALERO" },
      { name: "CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "CLUB EL ROSAL" },
      { name: "CENTRO DE PRIMER NIVEL DE ATENCIÓN VIETNAM" },
      { name: "CRUZ ROJA DOMINICANA FILIAR LA CALETA " },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "EL DIQUE" },
      { name: "ESTACION BOMBEROS CIVILES NO.2" },
      { name: "HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "HOSPITAL ELVIRA ECHAVARIA" },
      { name: "JUMBO MEGACENTRO" },
      { name: "MULTIUSO DE INVIVIENDA" },
      { name: "MULTIUSO TAMARINDO" },
      { name: "MULTIUSO URBANIZACION HAMARAP" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "POLIDEPORTIVO GUERRA" },
      { name: "COSALUP" },
      { name: "PARQUE DEL ESTE" },
      { name: "SANIDAD AÉREA FARD" },
      { name: "TONKA FOOTWEAR SAN ISIDRO" },
      { name: "VELAS HISPANIOLA" },
      { name: "ESCUELA CELIA PELIER (PARROQUIA SAN JUAN DE AVILA)" },
      { name: "BIBLIOTECA MULTIUSO GUARICANO CENTRO" },
      { name: "CLUB MULTIUSOS EL CROM " },
      { name: "DISTRITO EDUCATIVO 10-01" },
      { name: "HOGAR DE DÍA" },
      { name: "HOSPITAL NEY ARIAS LORA" },
      { name: "MULTIUSO LA VICTORIA" },
      { name: "MULTIUSO SABANA PERDIDA" },
      { name: "PARROQUIA SANTA CRUZ" },
      { name: "VESTIR DE HOY" },
      { name: "BRIGADA DE APOYO Y SERVICIO ERD" },
      { name: "ESCUELA BASICA HACIENDA ESTRELLA " },
      { name: "MULTICENTO LA SIRENA (UNIDAD DE VACUNACIÓN OMSA)" },
      { name: "ESCUELA ERCILIA PEPÍN" },
      { name: "SALUDOM RED DE ATENCIÓN PRIMARIA (SALUDOM)" },
      { name: "IGLESIA LOS MORMONES LA PIÑA" },
      { name: "PLAZA PEÑA GOMEZ" },
      { name: "CUERPO DE BOMBEROS LOS ALCARRIZOS" },
      { name: "HOSPITAL DR. RODOLFO DE LA CRUZ LORA" },
      { name: "CENTRO DE PRIMER NIVEL EL PEDREGAL" },
      { name: "HOSPITAL DR ELIAS SANTANA" },
      { name: "IGLESIA DE DIOS EN CRISTO LA SENDA" },
      { name: "HIPERMERCADO OLE KM17" },
      { name: "TIENDA GARRIDO" },
      { name: "CENTRO COMUNAL LAS PALMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CAOBAS" },
      { name: "MULTIUSOS HAINAMOSA" },
      { name: "CENTRO DE SALUD LA HORA DE DIOS" },
      { name: "CLUB BANCO DE RESERVAS" },
      { name: "FUNDACION PEDRO MARTINEZ" },
      { name: "HOSPITAL MARCELINO VELEZ SANTANA" },
      { name: "HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "INSTITUTO TÉCNICO SUPERIOR COMUNITARIO SAN LUIS ( ITSC)" },
      { name: "MULTIUSO EL ABANICO" },
      {
        name:
          "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CENTRO DE PRIMER NIVEL DIAZ PIÑEYRO",
      },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "CENTRO DE PRIMER NIVEL COMUNAL EL CAFÉ/INFOTEP" },
      { name: "CENTRO DE PRIMER NIVELA DE LA MANO CON JESUS" },
      { name: "ESCUELA KILOMETRO 13/ ESCUELA NUEVA " },
      { name: "MULTIUSO SOCORRO MUTUO" },
      { name: "PARROQUIA ESPIRITU SANTO" },
      { name: "PARROQUIA SAGRADO CORAZON DE JESUS " },
      { name: "COSALUP HERRERA" },
      { name: "CENTRO DE PRIMER NIVELA ZONA F" },
      { name: "CENTRO DE PRIMER NIVEL PALAVE" },
      { name: "ESCUELA SALOME UREÑA" },
      { name: "ESCUELA CONRADO MIESES " },
      { name: "ESCUELA REPUBLICA DE JAMAICA " },
      { name: "AYUTAMIENTO DE PEDRO BRAND" },
      { name: "MULTIUSO PALMAREJO" },
    ],
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "CLINICA MONTESINO" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "CLUB QUISQUELLA" },
      { name: "CLUB ROTARIO" },
      { name: "COLEGIO MEDICO" },
      { name: "PARROQUIA MARÍA AUXILIADORA MAO" },
      { name: "UNIDAD DE ATENCION PRIMARIA CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
