const centros = [
  {
    name: "AZUA",
    centers: [
      { name: "CENTRO DE SALUD FINCA 6" },
      { name: "CLINICA RURAL AMIAMA GOMEZ" },
      { name: "CLINICA RURAL ANZONIA" },
      { name: "CLINICA RURAL BARRERAS" },
      { name: "CLINICA RURAL EL CARRIZAL" },
      { name: "CLINICA RURAL EL ROSARIO" },
      { name: "CLINICA RURAL ESTEBANIA" },
      { name: "CLINICA RURAL HATILLO" },
      { name: "CLINICA RURAL HATO NUEVO" },
      { name: "CLINICA RURAL LA SIEMBRA" },
      { name: "CLINICA RURAL LAS BARIAS" },
      { name: "CLINICA RURAL LAS LAGUNAS" },
      { name: "CLINICA RURAL LOS NEGROS" },
      { name: "CLINICA RURAL LOS TOROS" },
      { name: "CLINICA RURAL MAGUEYAL" },
      { name: "CLINICA RURAL MONTE BONITO" },
      { name: "CLINICA RURAL PALMAR DE OCOA" },
      { name: "CLINICA RURAL PROYECTO 4" },
      { name: "CLINICA RURAL PROYECTO-2-C" },
      { name: "CLINICA RURAL PUEBLO VIEJO" },
      { name: "CLINICA RURAL SABANA YEGUA" },
      { name: "CLINICA RURAL SAJANOA" },
      { name: "CLINICA RURAL TABARA ABAJO" },
      { name: "CLINICA RURAL TABARA ARRIBA" },
      { name: "CLINICA RURAL VIAJAMA" },
      { name: "CLINICA RURAL VILLA ARPANDO" },
      { name: "DISTRITO ESCOLAR 03-01" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL MUNICIPAL PERALTA" },
      { name: "HOSPITAL TAIWAN" },
      { name: "LICEO GUAYACANAL" },
      { name: "LICEO JOSE FRANCISCO BOBADILLA" },
      { name: "LOS JOVILLOS" },
      { name: "CENTRO CLÍNICO Y DIAGNOSTICO DE ATENCION PRIMARIA" },
      { name: "GOBERNACIÓN" },
      { name: "SUPERMERCADO DIVERSO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA LA BOMBITA" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA YAYAS #1" },
      { name: "UNIDAD DE ATENCION PRIMARIA CAÑITA -A" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL BARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL HIGUERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GANADERO BARRIO LOS TECNICOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAYAS ARRIBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -1" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOBOS -2" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS JOVILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS MONTES FRIOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS PARCELEROS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUEBLO VIEJO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN FRANCISCO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SANTA ANA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CORAZON DE JESUS" }
    ]
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "MULTIUSO JARAGUA" },
      { name: "MULTIUSO TAMAYO" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA CLAVELLINAS" },
      { name: "UNIDAD DE ATENCIÓN PRIMARIA EL SALADO GALVAN" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 2" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATEY 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL PALMAR" },
      { name: "UNIDAD DE ATENCION PRIMARIA UVILLA" },
      { name: "ESCUELA MARIE POUSEPIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA MONSERRATE" }
    ]
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CLUB DE CACHON" },
      { name: "CLUB ENRIQUILLO" },
      { name: "COLEGIO MEDICO DOMINICANO" },
      { name: "PLAZA COMUNAL VICENTE NOBLE" },
      { name: "POLO CENTRO COMUNAL" },
      { name: "UCATEBA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO BELO" },
      { name: "UNIDAD DE ATENCION PRIMARIA INVI-CEA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CIENAGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS SALINAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS BLANCOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA PEÑON" },
      { name: "UNIDAD DE ATENCION PRIMARIA PESCADERIA" },
      { name: "DEFENSA CIVIL" },
      { name: "PALACIO DE JUSTICIA" },
      { name: "PARAISO III, IV" },
      { name: "UNIDAD DE ATENCION PRIMARIA BAITOITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BOMBITA " },
      { name: "UNIDAD DE ATENCION PRIMARIA LA MONTAÑITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PEÑUELA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA PLAYA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA RAQUETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS ARROYOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAJAGUAL" },
      { name: "VICENTE NOBLE I, II V" }
    ]
  },
  {
    name: "DAJABÓN",
    centers: [
      { name: "DIRECCION PROVINCIAL DE SALUD DE DAJABON" },
      { name: "POLI DEPORTIVO AMBRIOSO ESTEVEZ" }
    ]
  },
  {
    name: "DISTRITO NACIONAL",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL SAN PEDRO APOSTOL" },
      { name: "CENTRO MEDICO HONDURAS" },
      { name: "CLUB LOS PRADOS" },
      { name: "CLUB MAURICIO BÁEZ" },
      { name: "CLUB NACO" },
      { name: "CLUB PLAZA INDEPENDENCIA" },
      { name: "CLUB RAFAEL BARIAS" },
      { name: "DISPENSARIO PARROQUIAL SAN GABRIEL" },
      { name: "DISPENSARIO TEJADA Y FLORENTINO (UASD)" },
      { name: "FUNDACIÓN JUDEGU" },
      { name: "FUNSAZURZA" },
      { name: "HOSPITAL DE LA POLICIA NACIONAL" },
      { name: "HOSPITAL DOCENTE DR. FRANCISCO MOSCOSO PUELLO " },
      { name: "IINSTITUTO DE AUXILIO Y VIVIENDA (INAVI)" },
      { name: "JUMBO AGORA" },
      { name: "MINISTERIO DE DEFENSA (MIDE)" },
      { name: "SUPERMERCADO NACIONAL 27 DE FEBRERO" },
      { name: "MINISTERIO DE TURISMO" },
      { name: "UNIVERSIDAD DOMINICANA O&M" },
      { name: "UNPHU" },
      { name: "CANCHA VILLA FRANCISCA" },
      { name: "PLAZA LAMA 27 DE FEBRERO" },
      { name: "AGRUCUDEGUA" },
      { name: "CENTRO DE DIAGNOSTICO DE ATENCION PRIMARIA BARNEY MORGAN " },
      { name: "CLUB DEPORTIVO LOS PIONEROS" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CLUB RENACER " },
      { name: "FUNDACION ESCOBA" },
      { name: "IGLESIA PERPETUO SOCORRO" },
      { name: "PLAZA SAMBIL" },
      { name: "CLUB GENERAL GREGORIO  LUPERON" },
      { name: "CLUB MARIA AUXILIADORA" },
      { name: "FUNDACION HUELLAS DEL SIGLO" },
      {
        name: "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)"
      },
      { name: "CONSEJO NACIONAL DE LA PERSONA ENVEJECIENTE (CONAPE)" },
      { name: "CRUZ ROJA DOMINICANA" },
      { name: "AGORA MALL AV. KENNEDY" },
      { name: "CLUB MIRADOR SUR" },
      { name: "MULTICENTRO LA SIRENA" },
      { name: "HOSPITAL JACINTO MAÑON" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "HOSPITAL GENERAL PLAZA DE LA SALUD" },
      { name: "CENTRO MEDICO FUSADI" }
    ]
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CENTRO DE VACUNACION SIGLO 21" },
      { name: "CLUB SALOME UREÑA" },
      { name: "EL AGUACATE" },
      { name: "GENIMO" },
      { name: "MULTIUSO ARENA  57" },
      { name: "MULTIUSO ARENOSO" },
      { name: "MULTIUSO BAJO TECHO VILLA RIVAS" },
      { name: "SEIBA DE LOS PÁJAROS" },
      { name: "UASD" },
      { name: "CLUB JUAN ALBERTO ESPINOLA" },
      { name: "CLUB MAYORISTAS" }
    ]
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "CASA CLUB DE GINANDIANA" },
      { name: "CENTRO CAMPESINO" },
      { name: "DEFENSA CIVIL" },
      { name: "CUERPO DE BOMBEROS EL SEIBO" },
      { name: "IGLESIA BENJAMIN" },
      { name: "UNIDAD DE ATENCION PRIMARIA MIRADOR SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA GUERRERO" }
    ]
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL DE JUAN SANTIAGO" },
      { name: "CENTRO DE PRIMER NIVEL EL LLANO" },
      { name: "CENTRO DE PRIMER NIVEL PEDRO SANTANA " },
      { name: "CENTRO TECNÓLOGICO CCOMUNITARIO (COMENDADOR)" },
      { name: "HOSPITAL DE BANICA" },
      { name: "HOSPITAL DE HONDO VALLE " }
    ]
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "CENTRO DE PRIMER NIVEL ALGARROBO" },
      { name: "CENTRO DE PRIMER NIVEL BATEY GINEBRA" },
      { name: "CENTRO DE PRIMER NIVEL BONAGUA" },
      { name: "CENTRO DE PRIMER NIVEL CEIBA DE MADERA" },
      { name: "CENTRO DE PRIMER NIVEL CUERO DURO" },
      { name: "CENTRO DE PRIMER NIVEL DE GUAUCI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAIMITO" },
      { name: "CENTRO DE PRIMER NIVEL EL COROZO" },
      { name: "CENTRO DE PRIMER NIVEL EL HIGUERITO" },
      { name: "CENTRO DE PRIMER NIVEL JUAN LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LA ERMITA" },
      { name: "CENTRO DE PRIMER NIVEL LA ISLETA" },
      { name: "CENTRO DE PRIMER NIVEL LA MANZANA" },
      { name: "CENTRO DE PRIMER NIVEL LA YAGUA" },
      { name: "CENTRO DE PRIMER NIVEL LAS FLORES" },
      { name: "CENTRO DE PRIMER NIVEL LAS GUAZUMAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS LAGUNAS " },
      { name: "CENTRO DE PRIMER NIVEL LOS BRAZOS" },
      { name: "CENTRO DE PRIMER NIVEL LOS LOPEZ" },
      { name: "CENTRO DE PRIMER NIVEL LOS PANCHOS" },
      { name: "CENTRO DE PRIMER NIVEL MONTE DE LA JAGUA " },
      { name: "CENTRO DE PRIMER NIVEL NUEVO PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL PALMA HERRADA" },
      { name: "CENTRO DE PRIMER NIVEL QUEBRADA HONDA" },
      { name: "CENTRO DE PRIMER NIVEL REPARADERO" },
      { name: "CENTRO DE PRIMER NIVEL SAL SI PUEDES" },
      { name: "CENTRO DE PRIMER NIVEL SAN FRANCISCO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL SAN VICTOR" },
      { name: "CENTRO DE PRIMER NIVEL SANTA ROSA MOCA" },
      { name: "CENTRO DE PRIMER NIVEL TIERRA DURA" },
      { name: "CENTRO DE PRIMER NIVEL VERAGUA" },
      { name: "CENTRO DE PRIMER NIVEL VILLA PROGRESO" },
      { name: "CENTRO DE PRIMER NIVEL ZAFARRAYA" },
      { name: "HOSPITAL JOSÉ CONTRERAS" },
      { name: "COLEGIO MÉDICO DOMINICANO" },
      { name: "CENTRO DE PRIMER NIVEL JOBA ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL ORTEGA" },
      { name: "CENTRO DE PRIMER NIVEL PUESTO GRANDE" },
      { name: "CENTRO DE PRIMER NIVEL VILLA CAFETALERA" },
      { name: "HOSPITAL JAMAO AL NORTE" },
      { name: "HOSPITAL MANUEL DE LUNA" }
    ]
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "HOSPITAL EL VALLE" },
      { name: "HOSPITAL SEÑORA ELUPINA CORDERO" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO LINDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUALEY" },
      { name: "UNIDAD DE ATENCION PRIMARIA GUAYABO DULCE" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS CAÑITAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS GUAMAS" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS HATILLOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA MANCHADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUERTO RICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA PUNTA DE GARZA" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA CANTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA NAVARRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA ORTEGA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA JAVILLA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LAS YAGUITAS" }
    ]
  },
 {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO COMUNAL RANCHO ARRIBA" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "POLIDEPORTIVO" },
      { name: "UNIDAD DE ATENCION PRIMARIA TENARES" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA TAPIA" }
    ]
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DIAGNÓSTICO." },
      { name: "CENTRO DE PRIMER NIVEL ANGOSTURA." },
      { name: "CENTRO DE PRIMER NIVEL BARTOLOMÉ" },
      { name: "CENTRO DE PRIMER NIVEL BATEY 8" },
      { name: "CENTRO DE PRIMER NIVEL BOCA DE CACHON." },
      { name: "CENTRO DE PRIMER NIVEL COLONIA MIXTA." },
      { name: "CENTRO DE PRIMER NIVEL CRISTÓBAL." },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABAL." },
      { name: "CENTRO DE PRIMER NIVEL EL LIMÓN." },
      { name: "CENTRO DE PRIMER NIVEL JIMANI CENTRO." },
      { name: "CENTRO DE PRIMER NIVEL JIMANI VIEJO. BARRIO JIMANI VIEJO." },
      { name: "CENTRO DE PRIMER NIVEL LA DESCUBIERTA." },
      { name: "CENTRO DE PRIMER NIVEL LAS BAITOAS." },
      { name: "CENTRO DE PRIMER NIVEL LAS MERCEDES." },
      { name: "CENTRO DE PRIMER NIVEL LOS BOLOS." },
      { name: "CENTRO DE PRIMER NIVEL LOS PINOS DEL EDÉN." },
      { name: "CENTRO DE PRIMER NIVEL MELLA" },
      { name: "CENTRO DE PRIMER NIVEL PLACER BONITO." },
      { name: "CENTRO DE PRIMER NIVEL POSTRER RÍO." },
      { name: "CENTRO DE PRIMER NIVEL PUESTO ESCONDIDO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ISIDRO." },
      { name: "CENTRO DE PRIMER NIVEL SAN JOSÉ." },
      { name: "CENTRO DE PRIMER NIVEL TIERRA NUEVA." },
      { name: "CENTRO DE PRIMER NIVEL VENGAN A VER." },
      { name: "HOSPITAL GENERAL MELENCIANO" },
      { name: "HOSPITAL JOSE PEREZ" },
      { name: "HOSPITAL LA DESCUBIERTA" }
    ]
  },
  {
    name: "LA ALTAGRACIA",
    centers: [{ name: "AEROPUERTO PUNTA CANA" }]
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "CENTRO DIAGNOSTICO CALETA" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE LA ROMANA" },
      { name: "GOBERNACIÓN PROVINCIAL" },
      { name: "HOGAR DEL NIÑO " },
      { name: "HOSPITAL ARÍSTIDES FIALLO CABRAL" },
      { name: "HOSPITAL GUAYMATE" },
      { name: "HOSPITAL SAMARITANO" },
      { name: "IGLESIA MARANAHTA." },
      { name: "IGLESIA PENTECOSTAL MI VILLA NAZARET" },
      { name: "IGLESIA SANTA ROSA DE LIMA" },
      { name: "POLICLINICO DUARTE" },
      { name: "POLIDEPORTIVO LA ROMANA" },
      {
        name: "UNIDAD DE ATENCION PRIMARIA ANTITUBERCULOSO DR. LUIS J. SUAREZ"
      },
      { name: "UNIDAD DE ATENCION PRIMARIA CALETA" },
      { name: "UNIDAD DE ATENCION PRIMARIA CUCAMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA ESCUELA PAULINA JIMENEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA PIEDRA LINDA" },
      { name: "UNIDAD DE ATENCION PRIMARIA TOMAS DESIR LEBRON" },
      { name: "MULTIUSO SAN EDUARDO " }
    ]
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER NIVEL BAYACANES" },
      { name: "CENTRO DE PRIMER NIVEL BURENDE" },
      { name: "CENTRO DE PRIMER NIVEL EL MAMEY" },
      { name: "CENTRO DE PRIMER NIVEL GUACO" },
      { name: "CENTRO DE PRIMER NIVEL LA TORRE" },
      { name: "CENTRO DE PRIMER NIVEL PONTON" },
      { name: "CENTRO DE PRIMER NIVEL RIO SECO" },
      { name: "CENTRO DE PRIMER NIVEL SAN MIGUEL" },
      { name: "CENTRO DE PRIMER NIVEL SANTO CERRO" },
      { name: "CENTRO MEDICO PADRE FANTINO" },
      { name: "CLÍNICA BAEZ SOTO" },
      { name: "CLÍNICA CEMEVE" },
      { name: "COOPERATIVA VEGA REAL" },
      { name: "CUERPO DE BOMBEROS" },
      { name: "HOSPITAL JUAN ANT.CASTILLO" },
      { name: "HOSPITAL MORILO KING " },
      { name: "POLICLINICO LA VEGA" },
      { name: "CENTRO DE PRIMER NIVEL CENTRO EL CARMEN" },
      { name: "CENTRO DE PRIMER NIVEL DON FAUSTO" },
      { name: "CENTRO DE PRIMER NIVEL EL PINO " },
      { name: "CENTRO DE PRIMER NIVEL EL RANCHITO" },
      { name: "CENTRO DE PRIMER NIVEL EL TANQUE" },
      { name: "CENTRO DE PRIMER NIVEL GINA HUECA " },
      { name: "CENTRO DE PRIMER NIVEL GUAREY" },
      { name: "CENTRO DE PRIMER NIVEL LAS UVAS" },
      { name: "CENTRO DE PRIMER NIVEL LICEY" },
      { name: "CENTRO DE PRIMER NIVEL MARIA AUXILIADORA" },
      { name: "CENTRO DE PRIMER NIVEL MARTINEZ " },
      { name: "CENTRO DE PRIMER NIVEL NARANJAL " },
      { name: "CENTRO DE PRIMER NIVEL PINTO SABANETA" },
      { name: "CENTRO DE PRIMER NIVEL RANCHO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL RIO VERDE" },
      { name: "CENTRO DE PRIMER NIVEL YAYAS" },
      { name: "CENTRO MEDICO JARABACOA" },
      { name: "CLUB DE ABOGADOS CLINICA LA CONCE PCION " }
    ]
  },
  {
    name: "MARIA TRINIDAD SÁNCHEZ",
    centers: [
      { name: "AYUNTAMIENTO DEL POZO" },
      { name: "AYUNTAMIENTO MUNICIPAL NAGUA" },
      { name: "CASA DE FORMACION SAGRADA FAMILIA" },
      { name: "CENTRO COMUNITARIO MATA BONITA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO AL MEDIO" },
      { name: "CENTRO DE PRIMER NIVEL LA FACTORIA" },
      { name: "CENTRO DE PRIMER NIVEL LOS YAYALES" },
      { name: "CENTRO DE PRIMER NIVEL ABREU" },
      { name: "CENTRO DE PRIMER NIVEL BAOBA DEL PIÑAL" },
      { name: "CENTRO DE PRIMER NIVEL BEJUCO ALAMBRE" },
      { name: "CENTRO DE PRIMER NIVEL BOBITA" },
      { name: "CENTRO DE PRIMER NIVEL COPEYITO" },
      { name: "CENTRO DE PRIMER NIVEL EL GUAYABO" },
      { name: "CENTRO DE PRIMER NIVEL EL PAPAYO" },
      { name: "CENTRO DE PRIMER NIVEL EL YAYAL" },
      { name: "CENTRO DE PRIMER NIVEL LA CAPILLA" },
      { name: "CENTRO DE PRIMER NIVEL LAS CEJAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS CORCOBAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GARZAS" },
      { name: "CENTRO DE PRIMER NIVEL LAS GORDAS" },
      { name: "CENTRO DE PRIMER NIVEL LOMA ALTA" },
      { name: "CENTRO DE PRIMER NIVEL SAN RAFAEL" },
      { name: "HOSPITAL DR. ANTONIO YAPOR HEDED" },
      { name: "HOSPITAL DR. CARLOS A. ZAFRA" },
      { name: "PARROQUIA SANTISIMA TRINIDAD" },
      { name: "POLIDEPORTIVO NAGUA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
      { name: "UASD NUEVA" }
    ]
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CLINICA POLICLINICO BONAO" },
      { name: "CRUCE UASD BONAO" },
      { name: "HOSPITAL DR. JOSE A. COLUMNA" },
      { name: "UNIDAD DE ATENCION PRIMARIA JAYACO" },
      { name: "UNIDAD DE ATENCION PRIMARIA MAXIMO GOMEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANA DEL PUERTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN PEDRO Y SAN PABLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA JUMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS ARROCES" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS QUEMADOS" },
      { name: "UNIDAD DE ATENCION PRIMARIA NUESTRA SRA DE FATIMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA RINCON DE YUBOA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SONADOR" },
      { name: "UNIDAD DE ATENCION PRIMARIA SAN ISIDRO" }
    ]
  },
  {
    name: "MONTE CRISTI",
    centers: [
      { name: "CENTRO COMUNAL LOMA" },
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "CLUB JUAN PABLO" },
      { name: "DOÑA ANTONIA (VER)" },
      { name: "IGLESIA EVANGÉLICA MISIONERA AMPARO DEL CIELO (KM 13)" },
      { name: "IGLESIA KM. 14" },
      { name: "LILO CAFÉ & RESTAURANT" },
      { name: "PLEY SANTA MARÍA" },
      { name: "POLIDEPOIRTIVO DE GUAYUBIN" },
      { name: "POLIDEPORTIVO DE MANZANILLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA ALTO DE LA PALOMA" },
      { name: "UNIDAD DE ATENCION PRIMARIA BARRIO SUR" },
      { name: "UNIDAD DE ATENCION PRIMARIA CERRO GORDO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL AHOGADO" },
      { name: "UNIDAD DE ATENCION PRIMARIA EL CENTRO" },
      { name: "UNIDAD DE ATENCION PRIMARIA HERMANAS MIRABAL" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA CAPITALITA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LA GALLERA" },
      { name: "UNIDAD DE ATENCION PRIMARIA LOS CONUCOS (VV)" },
      { name: "UNIDAD DE ATENCION PRIMARIA MARTIN GARCIA" },
      { name: "UNIDAD DE ATENCION PRIMARIA PILOTO" },
      { name: "UNIDAD DE ATENCION PRIMARIA VILLA SINDA" },
      { name: "COMEDOR ECONOMICO" },
      { name: "UNIDAD DE ATENCION PRIMARIA LO MAESTROS" }
    ]
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL ANTONCI" },
      { name: "CENTRO DE PRIMER NIVEL HATO VIEJO" },
      { name: "CENTRO DE PRIMER NIVEL LA COLORADA" },
      { name: "CENTRO DE PRIMER NIVEL LOS BOTADOS" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "HOSPITAL MUNICIPAL DE YAMASA" },
      { name: "UNIDAD DE ATENCION PRIMARIA DON JUAN" },
      { name: "CENTRO COMUNAL MONTE PLATA" },
      { name: "CENTRO DE PRIMER NIVEL LA CUABA" },
      { name: "CENTRO DE PRIMER NIVEL LOS LIMONES" },
      { name: "HOSPITAL PROVINCIAL DR. ÁNGEL CONTRERAS" }
    ]
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL PROVINCIAL DR ELIO FIALLO" },
      { name: "UNIDAD DE ATENCION PRIMARIA  5 Y 6" },
      { name: "UNIDAD DE ATENCION PRIMARIA  9" },
      { name: "UNIDAD DE ATENCION PRIMARIA 3 Y 4" },
      { name: "UNIDAD DE ATENCION PRIMARIA 7 Y 8" },
      { name: "UNIDAD DE ATENCION PRIMARIA OVIEDO PEDERNALES" }
    ]
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL BOCA CANASTA" },
      { name: "CENTRO COMUNAL VILLA MAJEGA" },
      { name: "CLINICA RURAL PIZARRETE - CENTRO DE PRIMER NIVEL" },
      { name: "CENTRO DE PRIMER NIVEL NANCY ORTIZ - MATANZAS" },
      { name: "CENTRO DE PRIMER NIVEL PAYA" },
      { name: "CENTRO DE PRIMER NIVEL WILSON BELLO" },
      { name: "DON GREGORIO I" },
      { name: "EL CARRETON" },
      { name: "EL LIMONAL" },
      { name: "EL LLANO" },
      { name: "ESCONDIDO I" },
      { name: "FUNDACION DE PERAVIA I" },
      { name: "LAS BARIAS" },
      { name: "LAS CALDERAS" },
      { name: "LAS TABLAS" },
      { name: "LOS TUMBAOS" },
      { name: "LOS YAGUARIZOS" },
      { name: "MATA GORDA" },
      { name: "PIZARRETE II" },
      { name: "RIO ARRIBA" },
      { name: "SABANA BUEY" },
      { name: "SAONA I" },
      { name: "VALDESIA" },
      { name: "VILLA DAVID" },
      { name: "VILLA GUERA" },
      { name: "VILLA SOMBRERO 1" }
    ]
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "CENTRO DE PRIMER NIVEL DOLORES DE LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL NAVAS" },
      { name: "CENTRO DE PRIMER NIVEL SAN MARCOS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "HOSPITAL MUNICIPAL DE ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE GUANANICO" },
      { name: "HOSPITAL MUNICIPAL DE IMBERT" },
      { name: "HOSPITAL MUNICIPAL DE LOS HIDALGOS" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "HOSPITAL MUNICIPAL DE LUPERÓN" }
    ]
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "CENTRO COMUNAL (LOS CORRALES)" },
      { name: "CENTRO COMUNAL RANCHO ESPAÑOL" },
      { name: "CRUCE DE TEZÓN" },
      { name: "ESCUELA PRIMARIA LOS GRATINIS" },
      { name: "HOSPITAL DR. ALBERTO GAUTREAUX" },
      { name: "IGLESIA CATÓLICA (RINCON)" },
      { name: "IGLESIA CATOLICA LAS GARITAS" },
      { name: "JUNTA DE VECINOS JUANA VICENTA" },
      { name: "JUNTA DISTRITAL LAS GALERAS" },
      { name: "POLIDEPORTIVO SAMANA CENTRO" },
      { name: "VILLA CLARA " }
    ]
  },
  {
    name: "SAN CRISTÓBAL",
    centers: [
      { name: "ASOCIACION DE INDUSTRIA" },
      { name: "CARCEL NAJAYO" },
      { name: "CENTRO DIAGNOSTICO VILLA FUNDACION" },
      { name: "COLEGIO SAN RAFAEL" },
      { name: "COMEDOR ECONOMICO LAVA PIE" },
      { name: "CENTRO DE PRIMER NIVEL CONANI" },
      { name: "CENTRO DE PRIMER NIVEL EL CAJUILITO" },
      { name: "CENTRO DE PRIMER NIVEL EL CARRIL" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA (SAN CRISTÓBAL)" },
      { name: "CENTRO DE PRIMER NIVEL LA PARED" },
      { name: "CENTRO DE PRIMER NIVEL LA PISCINA" },
      { name: "CENTRO DE PRIMER NIVEL MODESTO OGANDO (LAS FLORES)" },
      { name: "CENTRO DE PRIMER NIVEL PUERTO RICO" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANTONIO" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "HOSPITAL MUNICIPAL HAINA" },
      { name: "HOSPITAL RAFAEL J. MAÑÓN" },
      { name: "PARQUE RADHAMES" },
      { name: "POLICLINICA NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "POLIDEPORTIVO NIGUA" },
      { name: "UNIDAD DE ATENCION PRIMARIA SABANETA " },
      { name: "DISPENSARIO LOS AMERICANOS" }
    ]
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE PRIMER NIVEL ARROYO CAÑA" },
      { name: "CENTRO DE PRIMER NIVEL SAN ANOTNIO" },
      { name: "CENTRO DE SALUD  LA CIENEGA" },
      { name: "CENTRO DE SALUD  LAS FLORES" },
      { name: "CENTRO DE SALUD  LOS MARTINEZ" },
      { name: "CENTRO DE SALUD  LOS RACHITOS" },
      { name: "CENTRO DE SALUD  PUEBLO A BAJO" },
      { name: "CENTRO DE SALUD  SAN LUIS " },
      { name: "CENTRO DE SALUD EL PINAR" },
      { name: "CENTRO DE SALUD LIMONAL" },
      { name: "CENTRO DE SALUD NARANJAL" },
      { name: "CENTRO DE SALUD SABANA LARGA ABAJO" },
      { name: "CENTRO DE SALUD SAN RAFAEL" },
      { name: "HOSPITAL GUARIONEX ALCANTARA" },
      { name: "CENTRO DE PRIMER NIVEL NIZAO " }
    ]
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "CLUB COME MORO" },
      { name: "CODIA" },
      { name: "EL CASINO SJ" },
      { name: "PARQUE SÁNCHEZ" },
      { name: "UNIDAD DE ATENCION PRIMARIA BATISTA" },
      { name: "UNIDAD DE ATENCION PRIMARIA DERRUMBADERO" }
    ]
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "CENTRO COMUNAL PUNTA PESCADORA" },
      { name: "CLINICA DOCTOR DE LEON" },
      { name: "CLUB 26 DE FEBRERO" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DE PERIODISTAS" },
      { name: "DEFENSA CIVIL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "IGLESIA ASAMBLEA DE DIOS JUAN DOLIÓ" },
      { name: "IGLESIA CATOLICA LOS CONUCOS" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "IGLESIA DE DIOS GUAYACANES" },
      { name: "IGLESIAS ASAMBLEAS DE DIOS ADONAI" },
      { name: "LOCAL DE LOS BOMBEROS" },
      { name: "LOCAL DE LOS MUELLEROS" },
      { name: "MONTE DE SION" },
      { name: "MULTIUSO - EXTENSION UASD" },
      { name: "UCE" },
      { name: "AYUNTAMIENTO MUNICIPAL SAN PEDRO" },
      { name: "CENTRO DE BOMBEROS, GAUTIER" },
      { name: "SALON DE LA CULTURA AYUNTAMIENTO MUNICIPAL" }
    ]
  },
  {
    name: "SÁNCHEZ RAMIREZ",
    centers: [
      { name: "AYUNTAMIENTO DE QUITA SUEÑO" },
      { name: "BAJO TECHO" },
      { name: "CENTRO DE DIAGNOSTICO" },
      { name: "CENTRO DE PRIMER LA CUEVA" },
      { name: "CENTRO DE PRIMER NIVEL CABALLERO" },
      { name: "CENTRO DE PRIMER NIVEL CASTILLO" },
      { name: "CENTRO DE PRIMER NIVEL CHACUEY" },
      { name: "CENTRO DE PRIMER NIVEL COMEDERO ARRIBA" },
      { name: "CENTRO DE PRIMER NIVEL CRUZ DE ANGELINA" },
      { name: "CENTRO DE PRIMER NIVEL DUEY" },
      { name: "CENTRO DE PRIMER NIVEL EL LIMONCITO" },
      { name: "CENTRO DE PRIMER NIVEL EL PESCOZON" },
      { name: "CENTRO DE PRIMER NIVEL HERNANDO ALONZO" },
      { name: "CENTRO DE PRIMER NIVEL LA ALTAGRACIA" },
      { name: "CENTRO DE PRIMER NIVEL LA BIJA" },
      { name: "CENTRO DE PRIMER NIVEL LA CRUZ" },
      { name: "CENTRO DE PRIMER NIVEL LAS CANAS" },
      { name: "CENTRO DE PRIMER NIVEL SABALLO" },
      { name: "CENTRO DE PRIMER NIVEL SIERRA PRIETA" },
      { name: "CENTRO DE PRIMER NIVEL ZAMBRANA" },
      { name: "CLÍNICA NUESTRA SEÑORA DEL PILAR" },
      { name: "CLUB DE AMAS DE CASA PEDRO FRANCISCO BONO" },
      { name: "CLUB DEL COLEGIO MEDICO" },
      { name: "DISTRITO ESCOLAR 16-01" },
      { name: "GOBERNACION PROVINCIAL COTUI" },
      { name: "HOSPITAL DE VILLA LA MATA" },
      { name: "HOSPITAL DR. RAMON BAEZ" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "LOS COROZOS" },
      { name: "PARQUE DUARTE" },
      { name: "CENTRO DE PRIMER NIVEL PIÑA VIAJA" },
      { name: "CENTRO DE PRIMER NIVEL PLATANAL" },
      { name: "CLUB DE LEONES FANTINO " }
    ]
  },
  {
    name: "SANTIAGO",
    centers: [
      { name: "CENTRO DE LA CIUDAD (PARQUE)" },
      { name: "CIENFUEGOS (BAJO TECHO)" },
      { name: "CLÍNICA UNIÓN MÉDICA DEL NORTE" },
      { name: "CLUB CREATIVO:NAVARRETE" },
      { name: "CLUB HATO DEL YAQUE" },
      { name: "CLUB MAMBUICHE" },
      { name: "CORAASAN" },
      { name: "HOSPITAL IRENE FERNÁNDEZ JÁNICO" },
      { name: "HOSPITAL LUIS ESPAILLAT SABANA IGLESIA" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE" },
      { name: "LICEO EUGENIO DE JESUS MARCANO (TAMBORIL)" },
      { name: "UNIVERSIDAD NAPOLEON NUNEZ MOLINA (LICEY)" },
      { name: "INTELLISYS" }
    ]
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [
      { name: "AYUNTAMIENTO MUNICIPAL MONCIÓN" },
      { name: "ESCUELA ANA JOAQUIN HIDALGO" }
    ]
  },
  {
    name: "SANTO DOMINGO",
    centers: [
      { name: "CODECOD (CENTRO DE DESAROLLO)" },
      { name: "GACEBO DEL PARQUE MONTE ADENTRO" },
      { name: "HOSPITAL MUNICIPIAL DE BOCA CHICA" },
      { name: "MULTIUSO PANTOJA" },
      { name: "AYUNTAMIENTO SANTO DOMINGO ESTE" },
      { name: "CLUB DEPORTIVO SAN JOSE DE MENDOZA" },
      { name: "CLUB EL ROSAL" },
      { name: "CLUB PLAN SOCIAL DE LOS BILLETEROS" },
      { name: "CRUZ ROJA DOMINICANA FILIAR LA CALETA " },
      { name: "DIRECCION AREA DE SALUD II" },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "ESTACION BOMBEROS CIVILES NO.2" },
      { name: "HOSPITAL CIUDAD JUAN BOSCH" },
      { name: "HOSPITAL ELVIRA ECHAVARIA" },
      { name: "INTITUTO TECNICO SUPERIOR COMUNITARIO SAN LUIS" },
      { name: "JUMBO MEGACENTRO" },
      { name: "MULTIUSO DE INVIVIENDA" },
      { name: "MULTIUSO TAMARINDO" },
      { name: "PARROQUIA SAN AGUSTIN" },
      { name: "PARRROQUIA SANTO TOMAS VILLA NUEVA" },
      { name: "POLIDEPORTIVO GUERRA" },
      { name: "COSALUP" },
      { name: "AREA II DE SALUD" },
      { name: "CLUB MULTIUSOS EL CROM " },
      { name: "ESCUELA BETANIA" },
      { name: "ESCUELA LEONCIO MANZUETA" },
      { name: "ESCUELA SAN FELIPE" },
      { name: "HOGAR DE DÍA" },
      { name: "MULTIUSO LA VICTORIA" },
      { name: "PARROQUIA SANTA CRUZ" },
      { name: "VESTIR DE HOY" },
      { name: "BRIGADA DE APOYO Y SERVICIO ERD" },
      { name: "CENTRO EDUCATIVO MILITAR SAN MIGUEL ARCANGEL" },
      { name: "ESCUELA REPÚBLICA DE ECUADOR " },
      { name: "ESCUELA EMMA BALAGUER DE VALLEJO" },
      { name: "ESCUELA HARAS NACIONALES " },
      { name: "FUNDACION SIGLO XXI" },
      { name: "HOSPITAL MUNICIPAL HACIENDA ESTRELLA " },
      { name: "MULTIUSO DE GUARICANO " },
      { name: "FUNDACION EL ALMENDRO " },
      { name: "CENTRO COMUNAL LAS PALMAS" },
      { name: "CENTRO DE PRIMER NIVEL COSALUD" },
      { name: "CENTRO DE PRIMER NIVEL LAS CAOBAS" },
      { name: "MULTIUSOS HAINAMOSA" },
      { name: "CENTRO DE SALUD LA HORA DE DIOS" },
      { name: "CLUB BANCO DE RESERVAS" },
      { name: "FUNDACION PEDRO MARTINEZ" },
      { name: "HOSPITAL MARCELINO VELEZ SANTANA" },
      { name: "HOSPITAL MUNICIPAL DE ENGOMBE" },
      { name: "IGLESIA SAN PEDRO NOLASCO" },
      { name: "MULTIUSO SANTO SOCORRO" },
      { name: "MULTIUSO EL ABANICO" },
      {
        name: "PARROQUIA NUESTRA SEÑORA LA ALTAGRACIA/CENTRO DE PRIMER NIVEL DIAZ PIÑEYRO"
      },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "CENTRO DE PRIMER NIVEL COMUNAL EL CAFÉ/INFOTEP" },
      { name: "CENTRO DE PRIMER NIVELA DE LA MANO CON JESUS" },
      { name: "ESCUELA KILOMETRO 13/ ESCUELA NUEVA " },
      { name: "PARROQUIA ESPIRITU SANTO" },
      { name: "PARROQUIA SAGRADO CORAZON DE JESUS " },
      { name: "CENTRO DE PRIMER NIVELA ZONA F" },
      { name: "CENTRO DE PRIMER NIVEL PALAVE" },
      { name: "ESCUELA SALOME UREÑA" },
      { name: "ESCUELA CONRADO MIESES " },
      { name: "ESCUELA REPUBLICA DE JAMAICA " },
      { name: "CENTRO DE PRIMER NIVEL LA GUAYIGA" },
      { name: "AYUTAMIENTO DE PEDRO BRAND" }
    ]
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "CLINICA DR. MONTESINOS" },
      { name: "CLINICA MONTESINO" },
      { name: "CLUB DE LEONES" },
      { name: "CLUB DEL CERRO DE ESPERANZA" },
      { name: "CLUB QUISQUELLA" },
      { name: "CLUB ROTARIO" },
      { name: "COLEGIO MEDICO" },
      { name: "PARROQUIA MARÍA AUXILIADORA MAO" },
      { name: "UNIDAD DE ATENCION PRIMARIA CENTRO LAGUNA SALADA" }
    ]
  }
];

centros.sort((a, b) => (a.name < b.name ? -1 : 1));
