const centros2 = [
  {
    name: "DISTRITO NACIONAL  (DAS-V)",
    centers: [{ name: "CCN" }, { name: "COOPNAMA" }],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "BASE AÉREA SAN ISIDRO FARD" },
      { name: "DISTRITO 10-03 VILLA LIBERACIÓN" },
      { name: "LICEO KELVIN OBRERO (LOS FRAILES III)" },
      { name: "DISTRITO 10-05 BOCA CHICAE" },
    ],
  },
  {
    name: "SANTO DOMINGO NORTE (DAS-II)",
    centers: [
      { name: "LICEO FABIO MOTA" },
      { name: "ESCUELA REPUBLICA DE PANAMA" },
      { name: "IGLESIA MINISTERIO" },
    ],
  },
  {
    name: "SANTO DOMINGO NORTE (DAS-VI)",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO ESPECIALIZADO" },
      { name: "ASILO SOL Y LUNA" },
      { name: "ESCUELA ROSARIO EVANGELINA" },
      { name: "LABORATORIO AMADITA" },
      { name: "LABORATORIO REFERENCIA" },
    ],
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [{ name: "CENTRO DE DIAGNOSTICO BELLA VISTA" }],
  },
  {
    name: "SANTIAGO (DISTRITO-I)",
    centers: [
      { name: "CLUB SAMEJI." },
      { name: "FORTALEZA SAN LUIS" },
      { name: "TECHADO LOS CIRUELITOS" },
      { name: "PARQUE CENTRAL" },
      { name: "CLUB MAMBUCHE" },
      { name: "REGIONAL DE SALUD" },
      { name: "CLÍNICA SANTIAGO APÓSTOL" },
      { name: "ENSANCHE LIBERTAD (GUG)" },
      { name: "CIENFUEGOS (BAJO TECHO)" },
      { name: "MEDICA" },
      { name: "ZONA FRANCA PISANO" },
      { name: "TIPIQUITO LOS COCOS" },
      { name: "PLAZA CORAL" },
      { name: "DPS SANTIAGO I" },
      { name: "PARQUE VILLA GONZÁLEZ" },
      { name: "CENTRO TECNOLÓGICO COMUNITARIO" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO-III)",
    centers: [
      { name: "REGIONAL DE EDUCACIÓN IPISA 08-03" },
      { name: "DELIBERY,(ADULTOS MAYORES EN CAMA)" },
      { name: "CLUB SAMEJI" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [{ name: "ESCUELA VOCACIONAL" }, { name: "FORTALEZA 2 DE MAYO" }],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "DPS PUERTO PLATA" },
      { name: "YASICA" },
      { name: "IMBERT" },
      { name: "ALTAMIRA" },
      { name: "SAN FELIPE" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "INEMED" },
      { name: "CENTRO MÉDICO NACIONAL" },
      { name: "SIGLO 21" },
      { name: "CENTRO MEDICO MATERNO INFANTIL" },
      { name: "DIRECCIÓN REGIONAL NORDESTE, P.N." },
    ],
  },
  {
    name: "MARÍA TRINIDAD SÁNCHEZ",
    centers: [{ name: "HOSPITAL DR. CARLOS A ZAFRA" }, { name: "UNAP. NAGUA" }],
  },
  {
    name: "LA ROMANA",
    centers: [
      { name: "DISPENSARIO LUIS SUAREZ" },
      { name: "HOGAR DEL NIÑO" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "CENTRO DX CALETA" },
      { name: "CENTRO SAMARITANO" },
      { name: "CLINICA LOS MULOS" },
      { name: "K-14" },
      { name: "TOMAS DECIR" },
      { name: "UNAP" },
      { name: "DPS LA ROMANA" },
    ],
  },
  {
    name: "SÁNCHEZ",
    centers: [
      { name: "POLIDEPORTIVO SAMANA" },
      { name: "SANTA CLARA IGLESIA LA PROFESIA" },
      { name: "IGLESIA EVANGELICA DOMINICANA" },
      { name: "AYUNTAMIENTO MUNICIPAL,  SÁNCHEZ" },
      { name: "HOSPITAL Dr. ALBERTO GAUTREAUX, SANCHEZ." },
      { name: "POLIDEPORTIVO LAS TERRENAS" },
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "UCATEBA (SANTA CRUZ DE BARAHONA)DIST 02-03" },
      { name: "COOPERATIVA DE MAESTROS" },
      { name: "DIRECCIÓN REGIONAL SUR DE LA PN (SEDE)" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "DPS BAHORUCO" },
      { name: "LICEO SECUNDARIO MANUEL DE JESÚS GALVAN" },
    ],
  },
  {
    name: "PEDERNALES",
    centers: [
      { name: "HOSPITAL DR. ELIO FIALLO" },
      { name: "UNAP 3-4" },
      { name: "UNAP 5-6" },
      { name: "UNAP 7-8" },
      { name: "UNAP 9" },
    ],
  },
  {
    name: "AZUA",
    centers: [
      { name: "POLITÉCNICO AZUA" },
      { name: "LOS TRAMOJOS" },
      { name: "ESC. GUAYACANAL" },
      { name: "LA ALTAGRACIA" },
      { name: "CAÑADA LA PIEDRA" },
      { name: "BARRERA" },
      { name: "ESC. DE LOS CARTONES" },
      { name: "COL. LAS AMERICAS" },
      { name: "HATILLO" },
      { name: "ESC. DE LOS JOVILLOS" },
      { name: " DPS AZUA" },
    ],
  },
  {
    name: "ELÍAS PIÑA",
    centers: [{ name: "HOSPITAL ROSA DUARTE" }, { name: "CPN RINCONCITO" }],
  },
  {
    name: "SAN JUAN DE LA MAGUANA",
    centers: [
      { name: "CARDON" },
      { name: "CASINO SAN JUAN" },
      { name: "SALON DE CONFERENCIA DPS SAN JUAN" },
      { name: "PEDRO CORTO" },
      { name: "LOS COCOS" },
      { name: "ARROYO CANO" },
      { name: "BOHECHIO" },
      { name: "EL CERCADO" },
      { name: "DERRUMBADERO" },
      { name: "VALLEJUELO" },
    ],
  },
  {
    name: "ESPERANZA",
    centers: [
      { name: "COLEGIO MÉDICO" },
      { name: "CLUB DEL CERRO" },
      { name: "UNAP CENTRO" },
    ],
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [{ name: "LICEO SECUNDARIO LIBRADO EUGENIO BILLIARD" }],
  },
  {
    name: "DAJABON",
    centers: [{ name: "POLIDEPORTIVO AMBRIOSIO ESTEVEZ" }],
  },
  {
    name: "COTUI",
    centers: [
      { name: "CPN ZAMBRANA" },
      { name: "BAJO TECHO COTUI" },
      { name: "BAJO TECHO FANTINO" },
      { name: "CLUB 4 DE JULIO FANTINO" },
      { name: "CENTRO DIAGNÓSTICO FANTINO" },
      { name: "CENTRO DIAGNÓSTICO COTUI" },
      { name: "CPN LA BIJA" },
      { name: "GRAN ARENA" },
      { name: "COLEGIO MÉDICO" },
      { name: "CPN EL LIMÓN" },
      { name: "UTECO" },
      { name: "HOSPITAL RAMÓN BÁEZ" },
      { name: "HOSPITAL DE LA MATA" },
      { name: "HOSPITAL INMACULADA CONCEPCIÓN" },
      { name: "HOSPITAL DE CEVICOS" },
      { name: "HOSPITAL DE FANTINO" },
      { name: "CPN LA CRUZ COTUI" },
      { name: "CPN LA ALTAGRACIA COTUI" },
      { name: "CPN LIBERTAD" },
      { name: "CPN LA MATA" },
      { name: "DOMICILIARIO " },
      { name: "CPN LA CUEVA" },
      { name: "CPN LIMONCITO" },
      { name: "CPN EL PESCOZON" },
      { name: "CPN LA PLACETA" },
      { name: "CPN PEDRO FRANCISCO BONO" },
    ],
  },
].sort((a, b) => (a.name < b.name ? -1 : 1));
