const centros = [
  {
    name: "DISTRITO NACIONAL (DAS-IV)",
    centers: [
      { name: "HOSPITAL CECANOT" },
      { name: "CLÍNICA CRUZ JIMINIÁN" },
      { name: "DIRECCIÁN ÁREA DE SALID IV" },
      { name: "CLÍNICA RODRÍGUEZ SANTOS" },
      { name: "HOSPITAL DR.FRANCISCO E MOSCOSO PUELLO" },
      { name: "HOSPITAL FÉLIZ MARÍA GOICO" },
      { name: "CPN Valentín Buttén " },
      { name: "Fundación Escoba" },
      { name: "FUNSAZURZA" },
      { name: "Club Mauricio Báez" },
      { name: "CPN La Ciénaga" },
      { name: "Fundación JUDEGU" },
      { name: "Mercado Nuevo" },
      { name: "Club María Auxiliadora" },
      { name: "Club Rafael Leonidas Solano" },
      { name: "Fundación Cruz Jiminián" },
      { name: "CPN Puerto Isabela" },
      { name: "Club Rafael Barias" },
      { name: "CPN Padre Marcilla" },
      { name: "Fundación Activo 20-30" },
      { name: "CLUB RAFAEL BARIAS" },
      { name: "FUNDACIÓN JUDEGU" },
      { name: "CPN LA CIÉNAGA" },
      { name: "CLUB LOS PIONEROS" },
      { name: "CPN VALENTÍN BUTTÉN" },
      { name: "FUNDACIÓN ESCOBA" },
      { name: "CPN SAN PABLO" },
      { name: "CPN CARDENAL SANCHA" },
      { name: "CENTRO DIAGNÓSTICO BARNEY MORGAN" },
      { name: "CLUB MAURICIO BÁEZ" },
      { name: "CLUB LOS BOMBERITOS" },
      { name: "CPN PUERTO ISABELA" },
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-V)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD V" },
      { name: "HOGAR DE ANCIANOS SAN FRANCISCO DE ASIS" },
      { name: "CENTRO MÉDICO DEL CARIBE" },
      { name: "CENTRO MÉDICO DR. RICHARDSON CRUZ" },
      { name: "CENTRO MÉDICO ELOHIM" },
      { name: "CENTRO MÉDICO GAZCUE" },
      { name: "CENTRO MÉDICO MODERNO" },
      { name: "CENTRO MÉDICO REAL" },
      { name: "CENTRO MÉDICO UCE" },
      { name: "CLÍNICA ABREU" },
      { name: "CLÍNICA DOMINICO CUBANA" },
      { name: "CLÍNICA INDEPENDENCIA" },
      { name: "DISPENSARIO MÉDICO TEJADA Y FLORENTINO" },
      { name: "GINECOLOGÍA Y OBSTETRICIA" },
      { name: "HOSPITAL GENERAL DE LA POLICÍA" },
      { name: "HOSPITAL INFANTIL DR.ROBERT REID CABRAL" },
      { name: "Club San Carlos" },
      { name: "UNIBE" },
      { name: "Agora Mall" },
      { name: "Centro Olimpico" },
      { name: "Supermercado Nacional 27 de Febrero" },
      { name: "Multicentro Churchill" },
      { name: "UASD" },
      { name: "PUCMM" },
      { name: "Disp. Tejada y Florentino" },
      { name: "Juan Lambert" },
      { name: "Club Los Prados" },
      { name: "Club Naco" },
      { name: "Club Plaza Independencia" },
      { name: "Centro Esculapio" },
      { name: "Siervas de Maria  y Esperilla" },
      { name: "ADN" },
      { name: "Gerencia DNO" },
      { name: "Pensionados" },
      { name: "INAVI" },
      { name: "SRS METROPOLITANA" },
    ],
  },
  {
    name: "DISTRITO NACIONAL (DAS-VI)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD VI" },
      { name: "CENTRO MÉDICO VISTA DEL JARDIN" },
      { name: "HOSPITAL MATERNO INFANTIL SANTO SOCORRO" },
      { name: "HOSPITAL MUNICIPAL JACINTO IGNACIO MAÑÓN" },
      { name: "HOSPITAL SALVADOR B. GAUTIER" },
      { name: "UNIVERSIDAD PEDRO HENRIQUEZ UREÑA (UNPHU)" },
    ],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-II)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD II" },
      { name: "CENTRO MÉDICO ALMED" },
      { name: "CENTRO MÉDICO HISPÁNICO" },
      { name: "CENTRO MÉDICO INTEGRAL - I" },
      { name: "CENTRO MÉDICO INTEGRAL - III" },
      { name: "CENTRO MÉDICO UNIVERSAL" },
      { name: "CENTRO ORIENTAL DE DIABETES Y ENDOCRINOLOGÍA" },
      { name: "CENTRO POLICLÍNICO NACIONAL" },
      { name: "CENTRO PRIMER NIVEL (CPN), EL DIQUE" },
      { name: "CENTRO PRIMER NIVEL (CPN), ISABELITA" },
      { name: "CENTRO PRIMER NIVEL (CPN), LOS MAMEYES" },
      { name: "CENTRO PRIMER NIVEL (CPN), VILLA DUARTE" },
      { name: "CLÍNICA DRES. LEGER MATOS" },
      { name: "CLÍNICA SANTO DOMINGO ORIENTAL" },
      { name: "CENTRO SOTO GONZÁLEZ" },
      { name: "INSTITUTP SOCIAL COLECTIVO DE SALUD POPULAR (COPSALUD)" },
      { name: "CPN - VIERTNAM" },
      { name: "HOSPITAL DOCTOR DARIO CONTRERAS" },
      { name: "HOSPITAL MATERNO INFANTIL SAN LORENZO DE LOS MINA" },
      { name: "CENTRO MÉDICO MUNICIPAL DE RALMA" },
      { name: "HOSPITAL UNIVERSITARIO DOCTOR VÁSQUEZ" },
      { name: "INTEGRAL - I" },
      { name: "POLICLÍNICA ZONE - E" },
      { name: "CPNA EL DIQUE (2DA DOSIS)" },
      { name: "AREA II DE SALUD (2DA DOSIS)" },
      { name: "CPNA VIETNAM" },
      { name: "DISPENSARIO MEDICO SANTA MARIA REINA" },
      { name: "CLUB EL ROSAL" },
      { name: "NTRA SRA DE LA ALTAGRACIA" },
      { name: "AYUNTAMIENTO SDE" },
      { name: "ALDEA INFANTIL SOS" },
      { name: "CPNA ISABELITA" },
      { name: "CPNA SAN JOSE LA BARQUITA" },
      { name: "CPNA LOS MAMEYES" },
      { name: "CPNA LOS TRES BRAZOS" },
      { name: "COMEDOR ECONOMICO" },
      { name: "MINISTERIO REINO DEL CAMINO" },
      { name: "MULTIUSO HAMARAP" },
      { name: "PLAN SOCIAL DE LA PRESIDENCIA" },
      { name: "LABORATORIO CLINICO PATRIA RIVAS" },
      { name: "FUNDACION ARIS" },
      { name: "ALIANZA CRISTIANA Y MISIONERA" },
    ],
  },
  {
    name: "SANTO DOMINGO ESTE (DAS-I)",
    centers: [
      { name: "HOSPITAL DR. RAMÓN DE LARA, FARD" },
      { name: "DIRECCIÓN ÁREA DE SALUD I" },
      { name: "HOSPITAL MUNICIPAL ELVIRA ECHAVARRÍA DE GUERRA" },
      { name: "Parroquia Santo Tomas de Villanueva (El Almirante)." },
      { name: "Multiuso el Tamarindo (El Tamarindo)." },
      { name: "Multiuso Invivienda (Invivienda)." },
      { name: "Multiuso Frailes I (Frailes I)." },
      { name: "Multiuso de Guerra (Guerra)." },
      { name: "Centro CODECO (La Caleta)." },
      { name: "Club San José de Mendoza (Mendoza)." },
      { name: "CPNA Frailes III (Frailes III)." },
      { name: "Multiuso La Corporanea (Corporanea del Almirante)." },
      { name: "Gazebo del Parque Monte Adentro (Andrés Boca Chica)." },
      { name: "Instituto Tecnológico Superior Comunitario (ITSC) (San Luis)." },
    ],
  },
  {
    name: "SANTO DOMINGO NORTE (DAS-III)",
    centers: [
      { name: "CLÍNICA DR.UREÑA ARIAS" },
      { name: "HOSPITAL HACIENDA ESTRELLA" },
      { name: "HOSPITAL PEDIÁTRICO DR.HUGO MENDOZA" },
      { name: "DIRECCIÓN ÁREA DE SALUD III" },
      { name: "Club Vista Bella" },
      { name: "HOSPITAL NEY ARIAS LORA" },
      { name: "CPN La Nueva Barquita" },
      { name: "CPN Lotes Y Servicios" },
      { name: "CPN San Felipe" },
      { name: "CPN Villa Carmela " },
      { name: "Fundacosis XXI" },
      { name: "Fundamusa Salome Ureña" },
      { name: "Mamá Tingo" },
      { name: "Mi Tio y Yo" },
      { name: "Multiuso Crom" },
      { name: "Multiuso de La Victoria" },
      { name: "Multiuso Guaricano" },
      { name: "Multiuso Sabana Perdida" },
      { name: "Nueva Isabela" },
      { name: "Parroquia Santa Cruz" },
      { name: "Politecnico Bethania" },
      { name: "Sabana Perdida las Antillas" },
      { name: "Salón de Los Bomberos (Sector Privado)" },
      { name: "Sierra Prieta" },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS-VII)",
    centers: [
      { name: "DR.MARCELINO VELEZ SANTANA" },
      { name: "SUB CENTRO DR.INOCENCIO DIAZ PIÑEYRO" },
      { name: "CPN hato nuevo" },
      { name: "CPN Comunal el café /INFOTEP" },
      { name: "CPN pan y vino" },
      { name: "CPN comunal las palmas" },
      { name: "CPNA Las Caobas" },
      { name: "ONG La Hora de Dios" },
      { name: "Parroquia Espiritu Santo" },
      { name: "Multiuso santo socorro" },
      { name: "Multiuso Ivan Klang" },
      { name: "Centro comunitario la mina" },
      { name: "CPNA de la mano con Jesus" },
      { name: "IGLESIA BAUTISTA EL SENDERO, BIENVENIDO" },
      { name: "MULTIUSO PROGRESANDO EN VALORES" },
      { name: "PARROQUIA NUESTRA SENORA LA ALTAGRACIA " },
      { name: "SALON MULTIUSO EL ABANICO" },
      { name: "IGLESIA SAN PEDRO NOLASCO" },
      { name: "IGLESIA SAN FRANCISCO DE ASIS, CABALLONA" },
      { name: "IGLESIA PALAVE" },
      { name: "IGLESIA SAGRADO CORAZON DE JESUS, HATO NUEVO" },
      { name: "IGLESIA BAUTISTA PASTOR DE OVEJAS" },
      { name: "ASODIFIMO" },
      { name: "IGLESIA NUESTRA SEÑORA DE FATIMA" },
      { name: "COOPERATIVA DE HERRERA" },
      { name: "MISION ENMANUEL" },
      { name: "SANTO DOMINGO COUNTRY CLUB" },
      { name: "REHABILITACION LAS PALMAS " },
      { name: "COOPERATIVA DE MANOGUAYABO" },
      { name: "COLEGIO INFANTIL FREDDY, LA CIENEGA" },
      { name: "CLUB DEL BANCO DE RESERVAS" },
      { name: "IGLESIA EVANGELICA EL BUEN PASTOR" },
      { name: "CLUB DEPORTIVO COLIBRI-PALAVE" },
      { name: "ESCUELA ROSARIO EVANGELINA SOLANO" },
      { name: "CENTRO CRISTIANO SOCIEDAD LUCAS" },
    ],
  },
  {
    name: "SANTO DOMINGO OESTE (DAS-VIII)",
    centers: [
      { name: "DIRECCIÓN ÁREA DE SALUD VIII" },
      { name: "HOSPITAL DR.ELIAS SANTANA" },
      { name: "HOSPITAL MUNICIPAL LOS ALCARRIZOS II" },
      { name: "HOSPITAL DR.RODOLFO DE LA CRUZ LORA" },
      { name: "HOSPITAL GENERAL DR.VINICIO CALVENTI" },
      { name: "SUB CENTRO ALCARRIZO I" },
    ],
  },
  {
    name: "MONTE PLATA",
    centers: [
      { name: "CENTRO MÉDICO DR.MATEO ROSARIO" },
      { name: "HOSPITAL MUNICIPAL DE DR. PEDRO HEREDIA ROJAS" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MONTE PLATA" },
      { name: "Multiusos Monte Plata (de 68 años o más)" },
      { name: "Hospital Provincial Dr. Angel Contreras" },
      { name: "CPNA Gregorio Luperón (Antiguo hospital)" },
      { name: "DPS Monte Plata" },
      { name: "Dispensario Parroquial San Antonio de Padua" },
      { name: "Adultos mayores (convalecientes, casa a casa)" },
      { name: "Liceo Julio Abreu Cuello" },
    ],
  },
  {
    name: "SAN CRISTÓBAL",
    centers: [
      { name: "AMEDOSA-CLÍNICA SAN CRISTÓBAL" },
      { name: "CASA ACOGIDA DE ENVEJECIENTES NUESTRA SEÑORA DE LA ALTAGRACIA" },
      { name: "DIRECCÓN PROVINCIAL DE SALUD SAN CRISTÓBAL" },
      { name: "CPN CAMBITA GARABITO CRUCE" },
      { name: "HOSPITAL MUNICIPAL CAMBITA GARABITO" },
      { name: "HOSPITAL JUAN PABLO PINA" },
      { name: "LEPROCOMIO NUESTRA SEÑORA DE LAS MERCEDES" },
      { name: "HOSPITAL MUNICIPAL DE HAINA BALSEQUILLO" },
      { name: "HOSPITAL MUNICIPAL BAJOS DE HAINA" },
      { name: "HOSPITAL MUNICIPAL MARÍA PANIAGUA (BOBITA) DE NIGUA" },
      { name: "HOSPITAL MUNICIPAL DE PALENQUE" },
      { name: "HOSPITAL MUNICIPAL DE YAGUATE" },
      { name: "HOSPITAL MUNICIPAL VILLA ALTAGRACIA" },
      { name: "HOSPITAL NUESTRA SEÑORA DE LA ALTAGRACIA" },
      { name: "CENTRO DE SALUD HOSPITAL DR.RAFAEL J. MAÑÓN" },
      { name: "DISPENSARIO NTRA. SRA. DE LA PAZ" },
      { name: "CASINO SAN CRISTÓBAL" },
      { name: "PUESTO DPS SAN CRISTOBAL" },
      { name: "CEMECO" },
      { name: "AMEDOSA" },
    ],
  },
  {
    name: "PERAVIA",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD PERAVIA" },
      { name: "CENTRO GRUPO MÉDICO BANÍ" },
      { name: "CLÍNICA INSTITUTO REGIONAL MATERNO INFANTIL Y ESPECIALIDADES MÉDICAS (IRMIE)" },
      { name: "CENTRO MÉDICO DR.PAULINO DE NIZAO" },
      { name: "CENTRO MÉDICO REGIONAL AGUASVIVAS" },
      { name: "HOSPITAL MUNICIPAL VILLA FUNDACIÓN" },
      { name: "CLÍNICA PERAVIA" },
      { name: "DISPENSARIO MÉDICO BASE NAVAL" },
      { name: "HOSPITAL NUESTRA SEÑORA DE REGLA" },
    ],
  },
  {
    name: "SAN JOSÉ DE OCOA",
    centers: [
      { name: "CENTRO DE DIAGNÓSTICO BELLA VISTA" },
      { name: "CENTRO DE SALUD LAS FLORES" },
      { name: "CENTRO DE SALUD PUEBLO ABAJO" },
      { name: "CENTRO DE DIAGNÓSTICO Y ATENCIÓN PRIMARIA DE SAN LUIS" },
      { name: "CPN SAN RAFAEL" },
      { name: "CENTRO MÉDICO EL MANIEL" },
      { name: "CENTRO MÉDICO VELÁZQUEZ" },
      { name: "CLÍNICA ARIAS" },
      { name: "HOSPITAL MUNICIAL DR.GUARIONEZ ALCÁNTARA" },
      { name: "HOSPITAL SAN JOSÉ DE OCOA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN JOSÉ DE OCOA" },
      { name: "CPN NIZAO" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - I)",
    centers: [
      { name: "SEDE 9-1-1" },
      { name: "HOSPITAL PRESIDENTE ESTRELLA UREÑA" },
      { name: "CLÍNICA ARTURO LOGROÑO" },
      { name: "CENTRO MÉDICO SANTIAGO APOSTOL" },
      { name: "HOSPITAL PERIFÉRICO DE CIENFUEGOS" },
      { name: "HOSPITAL MUNICIAL DE NAVARRETE" },
      { name: "HOSPITAL MUNICIAL DE VILLA GONZÁLEZ DR.NATIER DÍAS" },
      { name: "HOSPITAL DR.SALVADOR B, GAUTIER, (INSTITUTO DOMINICANO DE SEGUROS SOCIALES)" },
      { name: "HOSPITAL ENSANCHE LIBERTAD" },
      { name: "HOSPITAL INFANTIL DR.ARTURO GRULLÓN" },
      { name: "HOSPITAL REGIONAL DE SALUD" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - I)" },
      { name: "PARQUE CENTRAL" },
      { name: "CLUB MAMBUICHE" },
      { name: "PLAZA CORAL" },
      { name: "TIPIQUITO LOS COCO" },
      { name: "CIENFUEGO (BAJO TECHO)" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - II)",
    centers: [
      { name: "CPN BELLA VISTA" },
      { name: "CPN LA OTRA BANDA" },
      { name: "CPN VILLA LIBERACIÓN" },
      { name: "CENTRO DIAGNÓSTICO LOS GUANDULES" },
      { name: "CENTRO DE SALUD MADRE FRANCES STREITEL" },
      { name: "CLÍNICA DR.GUZMÁN" },
      { name: "CLÍNICA JIMÉNEZ" },
      { name: "CLÍNICA PROFAMILIA ROSA CISNEROS" },
      { name: "CLÍNICA TOLENTINO ABREU" },
      { name: "CPN BARRIO NUEVO HERRADURA" },
      { name: "CPN BUEN PASTOR" },
      { name: "CPN LA JOYA" },
      { name: "CPN LAS CHARCAS" },
      { name: "CPN MAMA TINGO" },
      { name: "CPN VILLA BAO" },
      { name: "CPN VILLA TABACALERA" },
      { name: "CPN YAGUISTA DE PASTOR" },
      { name: "DEFENSA CIVIL" },
      { name: "HOGAR DE ANCIANOS SAN JOSÉ DE SAJOMA" },
      { name: "HOSPITAL INTEGRAL BELLA VISTA" },
      { name: "HOSPITAL MUNICIPAL HATO DEL YAQUE" },
      { name: "HOSPITAL MUNICIPAL DE SABANA IGLESIA" },
      { name: "HOSPITAL MUNICIAL DE SAN JOSÉ DE LAS MATAS" },
      { name: "IGLESIA ADVENTISTA DEL SÉPTIMO DÍA" },
      { name: "PROFAMILIA Y CENTRO DIAGNÓSTICO FAMILIAR DR.TERRERO" },
      { name: "PUESTO FIJO DE LA DAS II" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - II)" },
      { name: "Club Baracoa" },
      { name: "Club La Otra Banda" },
      { name: "UASD Recinto Stgo" },
      { name: "CPN Villa Liberacion " },
      { name: "CPN BN la Herradura" },
      { name: "CPN Mamatingo" },
      { name: "CPN Las Charcas" },
      { name: "CPN Yaguita de Pastor " },
      { name: "CPN Buen Pastor" },
      { name: "Consultorio Adventista" },
      { name: "CPN La Canela" },
      { name: "CPN Bella Vista" },
      { name: "HP Bella Vista" },
      { name: "CPN Yaguita de Pastor" },
      { name: "CPN La Canela " },
      { name: "CPN Platanal" },
      { name: "CPN Los Guandules" },
      { name: "HP Hato del Yaque" },
      { name: "Club Hato del Yaque" },
      { name: "CPN Villa Tabacalera" },
      { name: "CPN Villa Bao" },
      { name: "CPN Bejucal" },
      { name: "CPN Caimito" },
      { name: "CPN La Cidra" },
      { name: "CPN Don Juan" },
      { name: "CPN Pilones" },
      { name: "CPN Pinalito" },
      { name: "CPN Janey" },
      { name: "CPN Juncalito" },
      { name: "HM Sabana Iglesia" },
      { name: "HM Janico" },
      { name: "HM SAJOMA" },
      { name: "CPN Pedregal" },
      { name: "CPN La Cuesta" },
      { name: "CPN Inoa" },
      { name: "CPN Las Manaclas" },
      { name: "CPN Las Placets" },
      { name: "CPN Los Montones" },
      { name: "CPN Rincón de Piedra" },
      { name: "CPN El Rubio" },
    ],
  },
  {
    name: "SANTIAGO (DISTRITO - III)",
    centers: [
      { name: "ACERO ESTRELLA" },
      { name: "CENTRO CENCACE" },
      { name: "CENTRO DE ESPECIALIDADES DR.PAULINO REYES" },
      { name: "HOGAR GERIÁTRICO CANITAS DORADAS" },
      { name: "CENTRO GERIÁTRICO DOMINICANO" },
      { name: "CENTRO GERIÁTRICO DRA.MOREU" },
      { name: "CENTRO MATERNO INFANTIL Y ESPECIALIDADES" },
      { name: "CENTRO MÉDICO CIBAO - UTESA" },
      { name: "CENTRO UROLÓGICO DEL CIBAO" },
      { name: "CLÍNICA DOCTOR EDUARDO MARTÍNEZ" },
      { name: "CLÍNICA DR.BONILLA" },
      { name: "CLÍNICA GENARO VALDEZ UTESA" },
      { name: "CONSULTORIO AEROPUERTO INTERNACIONAL SANTIAGO" },
      { name: "DISPENSARIO MÉDICO UAPA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD (DPS - III)" },
      { name: "FUNDACIÓN SOLIDARIA DEL DIVINO NIÑO DE JESUS INC." },
      { name: "HOGAR DE ANCIANOS ELISEO ÁLVAREZ" },
      { name: "HOGAR DE ANCIANOS LAS TRES HERMANAS" },
      { name: "CENTRO MÉDICO PREVENTIVO SALUD Y VIDA (CENSAVID)" },
      { name: "HOSPITAL MUNICIPAL DE TAMBORIL DR.JORGE ARMANDO 'ICO'" },
      { name: "HOSPITAL JORGE BLANCO" },
      { name: "HOSPITAL JOSÉ MARÍA CABRAL Y BÁEZ" },
      { name: "HOSPITAL JUAN 23 MONTE ADENTRO" },
      { name: "HOSPITAL OFTALMOLÓGICO" },
      { name: "INSTITUTO DERMATOLÓGICO Y CIRUJÍA DEL PIEL DR.HUMBERTO BOGAERT DÍAZ" },
      { name: "INSTITUTO ONCOLÓGICO REGIONAL DEL CIBAO" },
      { name: "CENTRO MÉDICO LOS VETERANOS" },
      { name: "CENTRO MÉDICO NEOCLINIC" },
      { name: "HOSPITAL SAN VICENTE DE PAUL" },
      { name: "CPN La Ceibita" },
      { name: "Club Villa Olga" },
      { name: "CPN Hoya Del Caimito" },
      { name: "UTESA" },
      { name: "Club de los periodistas" },
      { name: "Club Hermanos patiño" },
      { name: "Hemmi" },
      { name: "Centro de Acopio PUCMM" },
      { name: "Club Puñal" },
      { name: "CPN Hato Mayor" },
      { name: "Club de Los Periodistas" },
      { name: "Distrito 08-08" },
      { name: "Ecuela de Guayabal" },
      { name: "ONCOSER" },
    ],
  },
  {
    name: "ESPAILLAT",
    centers: [
      { name: "HOGAR PARA ANCIANOS DESVALIDOS LA SANTÍSIMA TRINIDAD" },
      { name: "CENTRO DE DIAGNÓSTICO AVANZADO LOS LÓPEZ (CDA)" },
      { name: "CPN CEIBA DE MADERA" },
      { name: "CPN JUAN LOPEZ" },
      { name: "CLÍNICA ALTAGRACIA" },
      { name: "CENTRO MÉDICO GUADALUPE" },
      { name: "COLEGIO MÉDICO DOMINICANO FILIAL MOCA (CMD)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD ESPAILLAT" },
      { name: "HOSPITAL DR.TORIBIO BENCOSME" },
      { name: "CENTRO MÉDICO HOSPIMED" },
      { name: "HOSPITAL CARLOS MARÍA ROJAS BADÍA" },
      { name: "HOSPITAL MUNICIPAL JAMAO AL NORTE" },
      { name: "HOSPITAL MUNICIPAL JOSÉ CONTRERAS" },
      { name: "HOSPITAL MUNICIPAL MANUEL DE LUNA" },
      { name: "HOSPITAL MUNICIPAL DR. RAFAEL GUTIERREZ SÁNCHEZ" },
      { name: "HOSPITAL DR.ROTIBIO BENCOSME (HOSTOBEN)" },
      { name: "INSTITUTO DE ESPECIALIDADES MÉDICAS GREGORIO HERNÁNDEZ" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL Y ESPECIALIDADES DR.MÉNDEZ" },
      { name: "CPN LAS FLORES" },
      { name: "CPN LA ISLETA" },
      { name: "CPN BOCA FERREA" },
      { name: "CPN ALGARROBO" },
      { name: "CPN LAS LAGUNAS" },
      { name: "CPN LA MANZANA" },
      { name: "CPN LA GUAMA" },
      { name: "CPN GUAUCI" },
      { name: "CPN QUEBRADA HONDA" },
      { name: "CPN ZAFARRAYA" },
      { name: "CPN EL COROZO" },
      { name: "CPN NUEVO PUERTO RICO" },
      { name: "CPN LOS LÓPEZ" },
      { name: "CPN SANTA ROSA" },
      { name: "CPN LAS GUAZUMAS" },
      { name: "CPN TIERRA DURA" },
      { name: "CPN EL HIGUERITO" },
      { name: "CPN BONAGUA" },
      { name: "CPN MONTE DE LA JAGUA" },
      { name: "CPN ORTEGA" },
      { name: "CPN REPARADERO" },
      { name: "CDX CARLOS MARIA ROJAS BADIA" },
      { name: "CPN JOBA ARRIBA" },
      { name: "CPN LA YAGUA" },
      { name: "CPN VERAGUA" },
      { name: "CPN BATEY GINEBRA" },
      { name: "CPN VILLA PROGRESO" },
      { name: "CPN LOS BRAZOS" },
      { name: "CPN EL CAIMITO" },
      { name: "CPN PALMA HERRADA" },
      { name: "CPN SAL SI PUEDES" },
      { name: "CPN LOS PANCHOS" },
      { name: "CPN BARRIO VIEJO PUERTO RICO" },
      { name: "CPN BARRIO MANUEL RODRIGUEZ" },
      { name: "CPN LA ERMITA" },
      { name: "CPN SAN FRANCISCO ARRIBA" },
      { name: "CPN CANCA LA REINA" },
      { name: "CPN SAN VICTOR" },
      { name: "CPN CUERO DURO" },
      { name: "CPN PUESTO GRANDE" },
      { name: "CPN VILLA CAFETALERA" },
      { name: "PUESTO FIJO DPS" },
      { name: "GERENCIA DE AREA" },
      { name: "SALON DE ACT. BARRIO VILLA ESTELA" },
      { name: "CLUB SAN SEBASTIAN" },
      { name: "CLUB CASINO RENACIMIENTO" },
      { name: "LOGIA PERSEVERANCIA" },
      { name: "DISTRITO 06-01 JOSE CONTRERAS" },
      { name: "DISTRITO 06-06 MOCA" },
      { name: "DISTRITO 06-07 GASPAR HERNANDEZ" },
      { name: "DISTRITO 06-08 JAMAO AL NORTE" },
      { name: "DISTRITO 06-09 SAN VICTOR" },
    ],
  },
  {
    name: "PUERTO PLATA",
    centers: [
      { name: "HOGAR DE ANCIANOS SAN ANTONIO MARÍA CLARET" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA DE SALUD (CAPS) BASE AÉREA PUERTO PLATA" },
      { name: "CENTRO MÉDICO BOURNIGAL" },
      { name: "CENTRO MÉDICO CABARETE" },
      { name: "CENTRO MÉDICO DE ESPECIALIDADES UTESA" },
      { name: "CENTRO SANITARIO DR.FRANCISCO GONZÁLEZ HARDY" },
      { name: "CLÍNICA BRUGAL" },
      { name: "HOSPITAL DR. RAFAEL CANTISANO ARIAS" },
      { name: "HOSPITAL GREGORIO LUPERÓN" },
      { name: "HOSPITAL MUNICIPAL ALTAMIRA" },
      { name: "HOSPITAL MUNICIPAL DE VILLA ISABELA" },
      { name: "HOSPITAL PABLO MORROBEL JIMÉNEZ" },
      { name: "HOSPITAL PROVINCIAL DOCENTE RICARDO LIMARDO" },
      { name: "PADRE LAS CASAS (CASA CLUB)" },
      { name: "POLICLÍNICAS DE VILLA LIBERACIÓN Y CHARAMICO" },
      { name: "CENTRO COMUNAL Y VOCACIONAL " },
      { name: "CLUB DE PADRE GRANERO" },
      { name: "CPN BARRANCON" },
      { name: "CPN DOLORES DE LA CRUZ" },
      { name: "CPN EL JAVILLAR" },
      { name: "CPN GREGORIO LUPERON" },
      { name: "CPN JOSUE" },
      { name: "CPN LLANOS DE PEREZ" },
      { name: "CPN MAIMON " },
      { name: "DIRECCIÓN PROVINCIAL SALUD PUERTO PLATA" },
      { name: "CPN MAMA MALTA " },
      { name: "CPN MUÑOZ" },
      { name: "CPN NAVAS" },
      { name: "CPN PALMAR GRANDE" },
      { name: "CPN RANCHITO DE LOS VARGAS " },
      { name: "CPN RIO GRANDE" },
      { name: "CPN SAN MARCOS" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD DE PUERTO PLATA" },
      { name: "IGLESIA EL SHADDAY" },
      { name: "IGLESIA FAMILIAR" },
      { name: "IGLESIA GENESIS" },
      { name: "LA CANCHA DE PADRE GRANERO " },
      { name: "LIGA DEL ATLANTICO " },
      { name: "MULTIUSO DE SOSUA " },
      { name: "PARQUE REGALADO " },
      { name: "PLAY DE LA FORTALEZA " },
      { name: "PLAY DE PADRE LAS CASAS " },
      { name: "PLAY DE TATO " },
      { name: "PLAY DE VILLA PROGRESO " },
      { name: "POLIDEPORTIVO DE PUERTO PLATA " },
      { name: "SABANA GRANDE" },
      { name: "TEMPLO EL SHADDAY" },
    ],
  },
  {
    name: "DUARTE",
    centers: [
      { name: "CENTRO DE CIRUGÍA PLÁSTICA AVANZADA DEL CIBAO (CIPLACI)" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL DEL NORDESTE" },
      { name: "CENTRO MÉDICO NACIONAL SAN FRANCISCO" },
      { name: "CENTRO MÉDICO SIGLO 21" },
      { name: "CPN VENTURA GRULLÓN" },
      { name: "HOSPITAL SAN VICENTE DE PAUL" },
      { name: "INSTITUTO DE ESPECIALIDADES MÉDICAS DEL NORDESTE, INEMED" },
      { name: "CPN LOMA DE LA JOYA" },
      { name: "CENTRO DE AISLAMIENTO Y CUIDADOS INTENSIVOS GUIZA" },
      { name: "CPN PROVINCIA DUARTE" },
      { name: "HOGAR DE ANCIANOS AMÉRICA ESPERANZA, SAN FCO DE MACORIS" },
      { name: "HOSPITAL FEDERICO LEOPOLDO LAVANDIER" },
      { name: "HOSPITAL MUNICIPAL DE CASTILLO" },
      { name: "HOSPITAL MUNICIPAL DR.FELIPE J. ACHÉCAR" },
      { name: "HOSPITAL MUNICIPAL DR.MARIO FDEZ MENA, CENOVI" },
      { name: "HOSPITAL PÚBLICO ALICIA DE LEGENDRE" },
      { name: "HOSPITAL PÚBLICO ETANAILDA BRITO, LAS GUARANAS" },
      { name: "DISPENSARIO RECINTO UASD" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD DUARTE" },
      { name: "UNIVERSIDAD NORDESTANA" },
      { name: "Getsemani" },
      { name: "Arenoso (El Aguacate)" },
      { name: "Villas Rivas (Barraquito)" },
      { name: "Villa Rivas (Multiusos )" },
      { name: "Castillo Urbano (Centro Comunal)" },
      { name: "Castillo Rural (Rincon Hondo)" },
      { name: "Hostos (Sabana Grande)" },
      { name: "Pimentel (Caobete)" },
      { name: "Pimentel (San Felipe Arriba)" },
      { name: "Pimentel (Arena 57)" },
      { name: "La Peña (Club Miguel Gelabert)" },
      { name: "La Enea (club la Enea)" },
      { name: "Ciudad Ganadera (Vacunacion a los Profesores)" },
      { name: "Pueblo Nuevo (Club ayuda Mutua)" },
      { name: "Capilla La Altagracia" },
      { name: "Parroquia San Pablo Apóstol (Los Rieles)" },
      { name: "Los Jardines 1era Etapa (Centro Comunal)" },
      { name: "Vista al Valle (Club Juan Bautista)" },
      { name: "Los Espinolas (Club Juan A. Espinolas)" },
      { name: "UCNE" },
      { name: "Naranjo Dulce" },
      { name: "Genimo (Centro Comunal de Genimo)" },
      { name: "DPS-Duarte" },
      { name: "La Cruz de Cenovi (Club Anacaona)" },
    ],
  },
  {
    name: "MARÍA TRINIDAD SÁNCHEZ",
    centers: [
      { name: "CENTRO MÉDICO DR.PÉREZ" },
      { name: "CENTRO MÉDICO ESPAILLAT UBIERA" },
      { name: "CENTRO DE ESPECIALIDADES MÉDICAS COSTA NORTE" },
      { name: "CENTRO DE ESPECIALIDADES MÉDICAS NAGUA (CEMNA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MARÍA TRINIDAD SÁNCHEZ" },
      { name: "HOGAR ASILO DE ANCIANOS LOS DISCÍPULOS Y MISIONEROS DEL AMOR Y LA PAZ" },
      { name: "HOSPITAL MUNICIPAL DESIDERIO ACOSTA" },
      { name: "HOSPITAL DR.CARLOS A ZAFRA" },
      { name: "HOSPITAL DR.LUIS RAMÓN BONILLA" },
      { name: "HOSPITAL MATERNO INFANTIL MATANCITAS" },
      { name: "HOSPITAL MUNICIPAL EL FACTOR" },
      { name: "HOSPITAL MUNICIPAL DR.VIRGILIO A. GARCÍA" },
      { name: "HOSPITAL ANTONIO YAPOR HEDED" },
      { name: "POLICLÍNICO LA UNIÓN" },
    ],
  },
  {
    name: "BAHORUCO",
    centers: [
      { name: "CENTRO MINUCIPAL LOS RIOS" },
      { name: "CENTRO MUNICIPAL TAMAYO" },
      { name: "HOSPITAL GIL ROLDÁN" },
      { name: "HOSPITAL JULIA SANTANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BAHORUCO" },
      { name: "HOSPITAL SAN BARTOLOMÉ" },
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "AYUNTAMIENTO MONSERRATE " },
      { name: "ESCUELA MENA ARRIBA" },
      { name: "ESCUELA MENA ABAJO" },
      { name: "AYUNTAMIENTO UVILLA" },
      { name: "TECHADO DE TAMAYO" },
      { name: "AYUNTAMIENTO SANTANA" },
      { name: "DPS BAHORUCO" },
      { name: "MULTIUSO NEYBA 01" },
      { name: "MULTIUSO NEIBA 02" },
      { name: "TECHADO DE JARAGUA" },
      { name: "ESCUELA. FE Y ALEGRIA" },
      { name: "CENTRO COMUNAL GALVAN" },
      { name: "ESCUELA. LAS TEJAS" },
      { name: "CPN LAS SABILAS" },
      { name: "CLUB LAS VIÑAS" },
    ],
  },
  {
    name: "SAMANÁ",
    centers: [
      { name: "CLÍNICA ESPECIALIZADA INTERNACIONAL LAS TERRENAS" },
      { name: "HOSPITAL LIC. PABLO PAULINO, LAS TERRENAS" },
      { name: "HOSPITAL NATIVIDAD ALCALÁ EL LIMÓN" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD SAMANÁ" },
      { name: "HOSPITAL PROVINCIAL DR. LEOPOLDO POU, SANTA BARBARA" }
    ]
  },
  {
    name: "HERMANAS MIRABAL",
    centers: [
      { name: "CENTRO MÉDICO DE ESPECIALIDADES VILLA TAPIA (CEMEVIT)" },
      { name: "CENTRO DIAGNOSTICO VILLA TAPIA" },
      { name: "CENTRO MÉDICO DR. RAFAEL GRULLÓN" },
      { name: "CENTRO MÉDICO MATERNO INFANTIL DR. ROMÁN BRACHE" },
      { name: "HOSPITAL DR. ROMAN BAUTISTA BRACHE" },
      { name: "DIRECIÓN PROVINCIAL DE SALUD HERMANAS MIRABAL" },
    ]
  },
  {
    name: "INDEPENDENCIA",
    centers: [
      { name: "CENTRO DE ATENCION PRIMARIA (UNAP)" },
      { name: "CENTRO DIAGNÓSTICO JIMANÍ" },
      { name: "CPN EL LIMON" },
      { name: "CPN JIMANÍ" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD INDEPENDENCIA" },
      { name: "HOSPITAL PROVINCIAL GENERAL MELENCIANO" },
      { name: "HOSPITAL DR. JOSÉ PÉREZ" },
      { name: "HOSPITAL LOS PINOS DEL EDEN" },
      { name: "HOSPITAL MUNICIPAL DE JIMANÍ" },
      { name: "HOSPITAL MUNICIPAL DUVERGÉ" },
      { name: "CPN JIMANI VIEJO" },
      { name: "CPN JIMANI PUEBLO" },
      { name: "CPN BOCA DE CACHON" },
      { name: "CPN TIERRA NUEVA" },
      { name: "CPN LAS BAITOAS" },
      { name: "CPN VENGAN A VER" },
      { name: "CPN PUESTO ESCONDIDO" },
      { name: "CPN SAN JOSE" },
      { name: "CPN LAS MERCEDES" },
      { name: "CPN SAN ISIDRO" },
      { name: "CPN PLACER BONITO" },
      { name: "CPN COLONIA MIXTA" },
      { name: "CPN MELLA " },
      { name: "CPN ANGOSTURA" },
      { name: "CPN CRISTOBAL" },
      { name: "CPN BATEY -8" },
      { name: "CPN BARTOLOME" },
      { name: "CPN LOS PINOS DEL EDEN" },
      { name: "HOSP. MUNIC. LA DESCUBIERTA" },
      { name: "CPN LA DESCUBIERTA" },
      { name: "CPN POSTRER RIO" },
      { name: "CPN EL GUAYABAL" },
      { name: "CPN LOS BOLOS" },
    ]
  },
  {
    name: "SAN PEDRO DE MACORÍS",
    centers: [
      { name: "CENTRO MÉDICO DE LEÓN" },
      { name: "CENTRO MÉDICO ESPECIALIZADO MACORIS" },
      { name: "CENTRO MÉDICO UCE SAN PEDRO DE MACORÍS" },
      { name: "CLÍNICA DR. FRANKLIN PEÑA" },
      { name: "HOSPITAL DR. JAIME OLIVER PINO" },
      { name: "HOSPITAL PEDRO MARÍA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN PEDRO DE MACORÍS" },
      { name: "HOSPITAL REGIONAL DR. ANTONIO MUSA" },
    ]
  },
  {
    name: "HATO MAYOR",
    centers: [
      { name: "ASILO DE ANCIANOS ROMERLIA SALAS DE BARCELÓ" },
      { name: "SEDE 9-1-1" },
      { name: "CENTRO DE REHABILITACIÓN DE HATO MAYOR" },
      { name: "DIRECCION PROVINCIAL DE SALUD HATO MAYOR" },
      { name: "HATO MAYOR DEL REY" },
      { name: "HOSPITAL ELUPINA CORDERO" },
      { name: "HOSPITAL LEOPOLDO MARTÍNEZ" },
      { name: "HOSPITAL MUNICIPAL EL VALLE" },
      { name: "LABORATORIO ALBUERME" },
      { name: "LABORATORIO ODONTOLÓGICOS LOCALES" },
      { name: "LABORATORIO PATRIA RIVAS" },
      { name: "LABORATORIO PUELLO" },
      { name: "LABORATORIO VASQUEZ" },
      { name: "LOCAL LA LOGIA" },
      { name: "HOSPITAL MUNICIPAL SRTA. ELUPINA CORDERO SABANA DE LA MAR" },
    ]
  },
  {
    name: "LA ALTAGRACIA",
    centers: [
      { name: "CENTRO MÉDICO DR. BALTAZAR Y ASOCIADOS, SRL" },
      { name: "CENTRO MÉDICO PUNTA CANA" },
      { name: "CENTRO MEDICO QUIRÚRGICO" },
      { name: "CLÍNICA DOCTOR GIL" },
      { name: "CENTRO MÉDICO DE ORTOPEDIA Y ESPECIALIDADES DR. QUEVEDO" },
      { name: "CLÍNICA DOCTOR VIRGILIO CEDANO" },
      { name: "CLÍNICA DR. PEROZO SRL" },
      { name: "GRUPO MÉDICO LIBERTAD" },
      { name: "HOSPITAL GENERAL Y DE ESPECIALIDADES NUESTRA SEÑORA DE LA ALTAGRACIA (HGENSA)" },
      { name: "HOSPITAL DRA. EVANGELINA RODRIGUEZ" },
      { name: "HOSPITAL IMG BAVARO" },
      { name: "HOSPITAL LAGUNAS DE NISIBON" },
      { name: "HOSPITAL MATERNO INFANTIL" },
      { name: "HOSPITAL NUESTRA SRA. DE LA ALTAGRACIA" },
      { name: "HOSPITEN" },
      { name: "MEDICALL BAVARO" },
      { name: "SERVICIO REGIONAL DE SALUD (SRS)" },
      { name: "SERVIMED LABORATORO" },
      { name: "UNAP ZONA URBANA" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD LA ALTAGRACIA" },
      { name: "UNAP ZONAS RURALES" },
      { name: "Multiuso" },
      { name: "Polideportivo" },
      { name: "UNAP San Francisco" },
      { name: "UNAP Otra Banda" },
      { name: "Aeropuerto Punta Cana" },
      { name: "Bayahibe" },
      { name: "Boca de Yuma" },
      { name: "Cap Cana" },
      { name: "UNAP Pepe Rosario" },
    ]
  },
  {
    name: "SAN JUAN",
    centers: [
      { name: "ASOCIACIÓN AYUDA MUTUA" },
      { name: "AYUNTAMIENTO PROVINCIAL" },
      { name: "CENTRO TECNOLÓGICO" },
      { name: "COLEGIO DOMINICANO DE INGENIEROS, ARQUITECTOS Y AGRIMENSORES (CODIA)" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD SAN JUAN" },
      { name: "HOSPITAL DR. FEDERICO AYBAR" },
      { name: "HOSPITAL MUNICIPAL DE BOHECHIO" },
      { name: "HOSPITAL MUNICIPAL DE VALLEJUELO" },
      { name: "HOSPITAL MUNICIPAL EL CERCADO" },
      { name: "HOSPITAL MUNICIPAL JUAN HERRERA" },
      { name: "HOSPITAL MUNICIPAL MATAS DE FARFAN" },
      { name: "HOSPITAL REGIONAL DOCENTE DR. ALEJANDRO CABRAL" },
      { name: "IGLESIA ESPÍRITU SANTOS" },
      { name: "POLIDEPORTIVO DE SAN JUAN" },
      { name: "SEDE  9-1-1" },
    ]
  },
  {
    name: "AZUA",
    centers: [
      { name: "DIRECCIÓN PROVINCIAL DE SALUD AZUA" },
      { name: "HOSPITAL MUNICIPAL DE PERALTA" },
      { name: "HOSPITAL MUNICIPAL GUAYABAL" },
      { name: "HOSPITAL MUNICIPAL NUESTRA SEÑORA DEL CARMEN" },
      { name: "HOSPITAL PADRES LAS CASA" },
      { name: "HOSPITAL TAIWAN" },
      { name: "UNIVERSIDAD UTESUR" },
      { name: "CENTRO COMUNAL BOSQUE SECO BARRIO LA COLONIA" },
      { name: "UNAP LAS LOMA" },
      { name: "CPN LOS JOVILLOS" },
      { name: "UNAP CUCHILLA" },
      { name: "UNAP TABARA ARRIBA" },
      { name: "UNAP LAS LOMAS" },
      { name: "ANSONIA" },
      { name: "UNAP EL HIGUERO" },
      { name: "UNAP ESTEBANIA" },
      { name: "UNAP VILLA CORAZON" },
    ]
  },
  {
    name: "ELÍAS PIÑA",
    centers: [
      { name: "CENTRO MÉDICO DRA CABRERA" },
      { name: "HOSPITAL BANICA" },
      { name: "HOSPITAL MUNICIPAL HONDO VALLE" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD EL ELÍAS PIÑA" },
    ]
  },
  {
    name: "VALVERDE",
    centers: [
      { name: "ASILO DE ANCIANOS DE MAO" },
      { name: "CASA CLUB COLEGIO MEDICO MAO" },
      { name: "CENTRO MÉDICO CEMENOR, S,R,L" },
      { name: "CLÍNICA INMANOR" },
      { name: "CLÍNICA DR. MONTESINOS" },
      { name: "CLINICA PERPETUO SOCORRO" },
      { name: "CLUB DE LEONES MAO" },
      { name: "COLEGIO MÉDICO DOMINICANO (CMD)" },
      { name: "HOSPITAL DR. JOSÉ FAUSTO OVALLES" },
      { name: "HOSPITAL MATERNO INFALTIL JOSE FRANCISCO PEÑA GOME" },
      { name: "HOSPITAL MUNICIPAL LAGUNA SALADA" },
      { name: "HOSPITAL REGIONAL  ING. LUIS L. BOGAERT" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD VALVERDE" },
      { name: "SEDE 911" },
    ]
  },
  {
    name: "SANTIAGO RODRÍGUEZ",
    centers: [
      { name: "CLÍNICA GRAN PODER DE DIOS" },
      { name: "HOSPITAL DE MONCIÓN" },
      { name: "HOSPITAL MUNICIPAL VILLA LOS ALMACIGOS" },
      { name: "HOSPITAL PROVINCIAL GENERAL SANTIAGO RODRÍGUEZ" },
    ]
  },
  {
    name: "MONTECRISTI",
    centers: [
      { name: "AYUNTAMIENTO CANA CHAPETON" },
      { name: "CENTRO INTEGRAL ODONTOLÓGICO Y ORTODONCIA" },
      { name: "CLÍNICA GRUPO MÉDICO CARLO CARLOS J.FINLAY" },
      { name: "CLÍNICA DENTAL DR. LUIS PIMETEL" },
      { name: "CLÍNICA DENTAL DR. MATIRDE GONZALEZ" },
      { name: "CLÍNICA DRA. SUERO" },
      { name: "CLÍNICA ODONTOLOGICA NERSON ISIDOR" },
      { name: "CLÍNICA SAN ANTONIO" },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD MONTECRISTI" },
      { name: "HATILLO PALMA E EL CLUB" },
      { name: "HOSPITAL DE LAS MATAS DE SANTA CRUZ" },
      { name: "HOSPITAL JULIO ALVAREZ ACOSTA" },
      { name: "HOSPITAL MUNICIPAL DE CASTAÑUELA" },
      { name: "HOSPITAL MUNICIPAL GUAYUBIN " },
      { name: "HOSPITAL MUNICIPAL PEPILLO SALCEDO" },
      { name: "HOSPITAL MUNICIPAL VILLA VASQUES" },
      { name: "HOSPITAL PÚBLICO PADRE FANTINO" },
      { name: "LABORATORIO DENTAL ROMULO LORENZO" },
      { name: "MANZANILLO EN EL MULTIUSO" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SAN FERNANDO (UNAP)" },
      { name: "CENTRO DE ATENCIÓN PRIMARIA SANTA MARIA (UNAP)" },
      { name: "AYUNTAMIENTO VILLA ELISA" },
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "UNAP VILLA ELISA " },
      { name: "UNAP EL PAPALLO" },
      { name: "GUAYUBIN POLIDEPORTIVO/ SUSTITUCION PARQUE" },
      { name: "CANA Chapetón AYUNTAMIENTO DISTRITAL" },
      { name: "VILLA ELISA AYUNTAMIENTO" },
      { name: "ORFANATO ENMANUEL " },
      { name: "UNAP CERRO GORDO" },
      { name: "UNAP HATO DEL MEDIO" },
      { name: "UNAP PILOTO" },
      { name: "CENTRO COMUNAL ARROYO CAÑA" },
      { name: "UNAP VILLA SINDA " },
      { name: "UNAP LOS DERRAMADEROS" },
      { name: "UNAP COPEY DE GUAYUBIN" },
      { name: "UNAP MARTIN García" },
      { name: "CLUB EL POCITO" },
      { name: "UNAP EL POCITO" },
    ]
  },
  {
    name: "DAJABON",
    centers: [
      { name: "CLÍNICA ROSA BENITA" },
      { name: "HOGAR DE ANCIANOS EN VILLA ALEGRE" },
      { name: "HOSPITAL MUNICIPAL RESTAURACIÓN" },
      { name: "HOSPITAL RAMON ADRIANO VILLALOBOS" },
      { name: "DIRECCION PROVINCIAL DE SALUD DAJABON" },
      { name: "HOSPITAL RAMON MATÍAS MELLA" },
      { name: "Cancha Cub Cultural Liberacion Juvenil" },
      { name: "Centro de Clavellina" },
      { name: "Centro de Madre Amor y Paz" },
      { name: "Centro de Madre Barrio NORTE" },
      { name: "Centro de Madre Cayuco" },
      { name: "Centro de Madre Cristo Resucitado" },
      { name: "Centro de Madre Hermana Mirabal" },
      { name: "Centro de Madre La Altagracia" },
      { name: "Centro de Madre La Esperanza" },
      { name: "Centro de Madre Plaza Beller" },
      { name: "Centro de Madre Sagrado Corazon de Jesus" },
      { name: "Centro de Madre Villa Alegre" },
      { name: "Centro de Madres Cristo Resucitado" },
      { name: "Centro Madre Unión y Paz" },
      { name: "Club Rafael Socias" },
      { name: "La Rikillona" },
      { name: "LOYOLA" },
      { name: "Poli Deportivo Ambrosio Estévez" },
      { name: "C/Presidente Enrique Frente a la Policía" },
      { name: "C/P. Lo Loyola" },
      { name: "Centro Comunal Cayuco" },
      { name: "Club El Rodeo y Club Los Compos" },
      { name: "Centro comunal de Sangre Linda" },
      { name: "ADEPA" },
      { name: "Multi Uso Rivera del Masacre" },
      { name: "Centro Comunal Aguacate" },
      { name: "Centro Comunal el Cruce" },
      { name: "Casa de la Cultura" },
      { name: "Centro de Madre Luperón" },
    ]
  },
  {
    name: "MONSEÑOR NOUEL",
    centers: [
      { name: "CENTRO DE CIRUGÍA Y ESPECILIDADES MEDICAS MAIMON" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS MONSEÑOR NOUEL" },
      { name: "CENTRO MÉDICO ZONA PROSPERIDAD" },
      { name: "CLINICA CAROLINA DE JESUS" },
      { name: "CLINICA SAN ANTONIO DE PADUA" },
      { name: "CONSULTORIO NUESTRA SRA. DE FATIMA" },
      { name: "DIRECCION PROVINCIAL DE SALUD MONSEÑOR NOUEL" },
      { name: "EPIDEMIOLOGO PROVINCIAL DE SALUD" },
      { name: "HOGAR DE ANCIANOS SAN ANTONIO" },
      { name: "HOSPITAL DR. PEDRO EMILIO DE MARCHENA" },
      { name: "HOSPITAL DR. JOSE A. COLUMNA" },
      { name: "HOSPITAL MARCHENA NUEVO" },
      { name: "HOSPITAL MUNICIPAL DE MAIMON" },
      { name: "HOSPITAL MUNICIPAL DE PIEDRA BLANCA" },
      { name: "CENTRO MEDICO PLAN DIENTE SANO" },
      { name: "CENTRO ZONA PROSPERIDAD" },
      { name: "UNAP SAN Pedro y San Pablo" },
      { name: "UNAP Sabana del Puerto" },
      { name: "UNAP Juma" },
      { name: "UNAP de Los Quemados" },
      { name: "Máximo Gómez" },
      { name: "UNAP Juan Adrián" },
      { name: "Dispensario de Fátima" },
      { name: "UNAP Jayaco" },
      { name: "Las Amapolas" },
      { name: "Arroyo Toro" },
      { name: "UNAP Caribe" },
      { name: "Polibon" },
      { name: "UNAP Los Arroces" },
      { name: "UNAP Rincón de Yuboa" },
      { name: "Distrito Escolar 16-05" },
      { name: "UNAP Sonador" },
      { name: "Centro Psicológico" },
      { name: "Las Liras" },
    ]
  },
  {
    name: "LA VEGA",
    centers: [
      { name: "CENTRO MEDICO CEMEVE" },
      { name: "CENTRO DIAGNOSTICO Y DE ATENCION PRIMARIA LA VEGA" },
      { name: "CENTRO MEDICO PADRE FANTINO, S.R.L." },
      { name: "CLINICA 5TO. CENTENARIO" },
      { name: "CLINICA BAEZ SOTO SRL" },
      { name: "CLINICA LA CONCEPCION" },
      { name: "DIRECCIOB PROVINCIAL DE SALUD LA VEGA" },
      { name: "HOSPITAL DRA. ARMIDA GARCIA" },
      { name: "HOSPITAL JIMA ABAJO" },
      { name: "HOSPITAL JUAN ANTONIO CASTILLO (CUTUPU)" },
      { name: "HOSPITAL PROFESOR JUAN BOSCH" },
      { name: "HOSPITAL REGIONAL UNIVERSITARIO DR. LUIS ML. MORILLO KING" },
      { name: "POLICLINICO LA VEGA, S.A" },
      { name: "REGIONAL DE SALUD 8" },
    ]
  },
  {
    name: "SÁNCHEZ RAMÍREZ",
    centers: [
      { name: "CENTRO MEDICO AMK DENTAL" },
      { name: "CENTRO DE ESPECIALIDADES MEDICAS" },
      { name: "CENTRO DE EUDIRIS SOTO" },
      { name: "CENTRO DIAGNOSTICO COTUI" },
      { name: "CENTRO DIAGNOSTICO DE FANTINO" },
      { name: "CENTRO DIAGNOSTICO VILLA LA MATA" },
      { name: "CENTRO MEDICO NUÑEZ HERNANDEZ" },
      { name: "CLINICA GUADALUPE" },
      { name: "CLINICA NUESTRA SRA. DEL PILAR" },
      { name: "CPN SANCHEZ RAMIREZ" },
      { name: "DIRECCION DE AREA DE SALUD SÁNCHEZ RAMÍREZ" },
      { name: "DIRECCION PROVINCIA DE SALUD SANCHEZ RAMIREZ" },
      { name: "HOGAR DE ANCIANOS CLUB DE LEONES INMACULADA CONCEPCIÓN" },
      { name: "HOGAR DE DIA VILLA LA MATA" },
      { name: "HOSPITAL CEVICO" },
      { name: "HOSPITAL INMACULADA CONCEPCION" },
      { name: "HOSPITAL MUNICIPAL FANTINO (SIGFREDO ALBA)" },
      { name: "HOSPITAL RAMÓN BÁEZ" },
      { name: "DIRECCION PROVINCIAL DE SALUD " },
      { name: "CENTRO MEDICO ODNONTOCLINIC" },
      { name: "CENTRO MEDICO ORAL IMPLANT RD" },
      { name: "Centro Tecnologico del Limon" },
      { name: "Polideportivo Samana" },
      { name: "SEDE  9-1-1 SÁNCHEZ RAMÍREZ" },
      { name: "Cruce de Honduras (Edificio blanco)" },
      { name: "Centro Comunal Rancho Español" },
      { name: "Daniel wilmore" },
      { name: "Teson" },
      { name: "Juana Vicenta" },
      { name: "VILLA CLARA. iglesia evangelica" },
      { name: "Batey de hormiga" },
      { name: "Iglesia Catolica El Rincon" },
      { name: "Junta de Vecino Los Cacaos" },
      { name: "CATEY JUNTA DE VECINOS." },
      { name: "LOMETA" },
      { name: "LA MAJAGUA UNAP" },
      { name: "Sindicato de portuaria" },
      { name: "Fabrica de hielo la pascuala" },
      { name: "Centro Comunal Los Corrales" },
      { name: "Ayuntamiento" },
      { name: "CRUZ ROJA" },
      { name: "AYUNTAMIENTO" },
      { name: "NARANJITO.  Iglesia catolica" },
      { name: "LOS PUENTES club de madres" },
      { name: "Polideportivo" },
    ]
  },
  {
    name: "San Francisco De Macoris",
    centers: [
      { name: "Centro del Jaya" },
      { name: "Rehabilitacion" },
      { name: "Yun Peralta" },
      { name: "Serenidad " },
      { name: "Club 27 de Febrero " },
      { name: "Club de los Profesores" },
      { name: "Getsemani" },
      { name: "Club Olegario Tenares (Vista al Valle)" },
      { name: "Ciudad Ganadera" },
      { name: "Cancha San Martin" },
      { name: "Profamilia" },
      { name: "Centro Comunal Pablo VI" },
      { name: "DPS Duarte" },
      { name: "Casa Senatorial" },
      { name: "Club de Mayorista" },
      { name: "Centro Comunal San Juan Bautista" },
      { name: "Club Cristo Rey" },
      { name: "Capilla La Altagracia" },
      { name: "Los Espinolas" },
      { name: "Hermanas Mirabal" },
      { name: "Santa Ana" },
      { name: "Regional de Salud" },
    ]
  },
  {
    name: "Aguayo",
    centers: [
      { name: "Centro Comunal de Aguayo" }
    ],
  },
  {
    name: "Arenoso",
    centers: [
      { name: "Multiuso Bajo Techo Arenoso" },
    ],
  },
  {
    name: "Castillo",
    centers: [
      { name: "Centro Comunal de Castillo" }
    ],
  },
  {
    name: "Cenovi",
    centers: [
      { name: "Centro Comunal Salome Ureña (Cenovi)" }
    ],
  },
  {
    name: "Hostos",
    centers: [
      { name: "Centro Comunal de Hostos " }
    ],
  },
  {
    name: "Hoyo de Jaya",
    centers: [
      { name: "Casa Curial (Hoyo de Jaya)" }
    ],
  },
  {
    name: "La Peña",
    centers: [
      { name: "Club Miguel Gelaber" }
    ],
  },
  {
    name: "Las Guaranas",
    centers: [
      { name: "Club Blue" }
    ],
  },
  {
    name: "Pimentel",
    centers: [
      { name: "Arena 57" }
    ],
  },
  {
    name: "Villa Rivas",
    centers: [
      { name: "Multiuso Bajo Techo Villa Rivas" },
    ],
  },
  {
    name: "Santa Barbara",
    centers: [
      { name: "Polideportivo" },
      { name: "Centro Tecnologico del Limon" },
      { name: "Centro Comunal Los Robalos" },
      { name: "Cruce de Honduras (Edificio blanco)" },
      { name: "Centro Comunal Rancho Español" },
      { name: "FABRICA DE HIELO LA PASCUALA" },
      { name: "CRUCE DE TEZON" },
      { name: "AYUNTAMIENTO LAS GALERAS" },
      { name: "JUNTA DE VECINO DANIEL WILLMORE" },
      { name: "Iglesia Catolica" },
      { name: "Sindicato de portuaria" },
      { name: "Junta de vecinos Los Cacaos" },
      { name: "Local Cooperativa vieja" }
    ],
  },
  {
    name: "Las Terrenas",
    centers: [
      { name: "Centro Comunal" },
      { name: "Iglesia Catolica" },
      { name: "CLUB DE MADRES LOS PUENTES" },
      { name: "Polideportivo " }
    ],
  },
  {
    name: "Sanchez",
    centers: [
      { name: "CPN La Lometa" },
      { name: "Centro Comunal, Batey Hormiga" },
      { name: "MAJAGUA ADENTRO" },
      { name: "Iglesia Catolica Las Garitas" },
      { name: "Centro Comunal Los Corrales" },
      { name: "Ayuntamiento Municipal" },
    ],
  },
  {
    name: "Salcedo",
    centers: [
      { name: "UNAP ANA MERCEDES RODRIGUEZ" },
      { name: "HOSPITAL DR. PASACASIO TORIBIO PIANTINI" },
      { name: "LICEO EMILIANO TEJERA" },
      { name: "CLUB DE MONTE ADENTRO" },
      { name: "ESCUELA JAIME MOLINA MOTA" },
      { name: "CASA DE LA TERCERA EDAD" },
      { name: "UNAP EL RANCHO" },
      { name: "LICEO DANIELA SARMIENTO" },
      { name: "ESCUELA JAYABO ADENTRO" },
      { name: "BRIGADA MOVIL ADULTO MAYORES" },
      { name: "UNAP MIREYA LANTIGUA" },
      { name: "CENTRO COMUNAL CONUCO" },
      { name: "BRIGADA MOVIL" },
    ],
  },
  {
    name: "Tenares",
    centers: [
      { name: "CENTRO DIAGNOSTICO TENARES" },
      { name: "POLIDEPORTIVO TENARES" },
      { name: "CENTRO COMUNITARIO PASO HONDO ADULTOS DE 70 AÑOS" },
      { name: "CENTRO COMUNITARIO LA JAGUITA TENARES ADULTOS DE 70 AÑOS Y MAS" },
      { name: "UNAP EULALIA PEÑA PERSONAL" },
      { name: "ESCUELA IRMA JORGE" },
      { name: "BRIGADA MOVIL ESCUELA LOMA DE AGUA Y CLUB ARROYO SECO" },
      { name: "HOSPITAL ANGEL CONCEPCION LAJARA" },
      { name: "LICEO JULIAN JAVIER" },
      { name: "BRIGADA MOVIL" },
      { name: "UNAP EL COROZAL" },
      { name: "CLUB LOS POMOS" },
    ],
  },
  {
    name: "Villa Tapia",
    centers: [
      { name: "CENTRO DIAGNOSTICO " },
      { name: "ESCUELA FEDERICO AUGUSTO GONZALEZ" },
      { name: "ESCUELA AMINTA VALERIO" },
      { name: "HOGAR DE ANCIANO PADRE NOEL" },
      { name: "ESCUELA FEDERICO GONZALES" },
      { name: "CLUB SAN ANTONIO LOS LIMONES" },
    ],
  },
  {
    name: "Tamayo",
    centers: [
      { name: "AYUNTAMIENTO DE TAMAYO" },
      { name: "TECHADO DE TAMAYO" },
      { name: "MONSERRATE" }
    ],
  },
  {
    name: "Neyba",
    centers: [
      { name: "MULTIUSO NEYBA" },
      { name: "DPS BAHORUCO" },
      { name: "EL MANGUITO" }
    ],
  },
  {
    name: "Los Rios",
    centers: [
      { name: "CLUB LAS VIÑAS" },
    ],
  },
  {
    name: "Galvan",
    centers: [
      { name: "ESC. LAS TEJAS" },
      { name: "CENTRO COMUNAL GALVAN" },
    ],
  },
  {
    name: "Villa Jaragua",
    centers: [
      { name: "TECHADO DE JARAGUA" },
      { name: "ESC. FE Y ALEGRIA" },
    ],
  },
  {
    name: "Santa Cruz",
    centers: [
      { name: "Iglesia Resureccion y vida" },
      { name: "Iglesia Buenas Nuevas" },
      { name: "Iglesia de Dios Pentecostal M.I" },
      { name: "CMD Filiar Barahona" }
    ],
  },
  {
    name: "Distrito Municipal de Villa Central",
    centers: [
      { name: "Club Juan Pablo Duarte" }
    ],
  },
  {
    name: "Vicente Noble",
    centers: [
      { name: "Club Cultural Vicente Noble" }
    ],
  },
  {
    name: "Cabral",
    centers: [
      { name: "Polideportivo/Multiusos Cabral" },
      { name: "Club Comunitario Las Viñas" }
    ],
  },
  {
    name: "Polo",
    centers: [
      { name: "Club Municipal de Polo" }
    ],
  },
  {
    name: "El Cachón",
    centers: [
      { name: "Club el Cachon" }
    ],
  },
  {
    name: "Enriquillo",
    centers: [
      { name: "Ayuntamiento de Enriquillo" }
    ],
  },
  {
    name: "Paraiso",
    centers: [
      { name: "Ayuntamiento de Paraiso" }
    ],
  },
  {
    name: "La Cienaga",
    centers: [
      { name: "Centro Comunitario de La Cienaga" }
    ],
  },
  {
    name: "Provincia de Barahona",
    centers: [
      { name: "Todas las unidades de Atencion Primaria  de la Provincia de Barahona, que son 40." }
    ],
  },
  {
    name: "BARAHONA",
    centers: [
      { name: "CENTRO DE ATENCIÓN LA CIENEGA (UNAP)" },
      { name: "CENTRO OLÍMPICO" },
      { name: "CENTRO REGIONAL MAGNOLIA" },
      { name: "HOSPITAL MUNICIPAL DR. JAIME SÁNCHEZ" },
      { name: "HOSPITAL DE REHABILITACIÓN (ASOCIACIÓN DOMINICANA DE REHABILITACIÓN)" },
      { name: "INSTITUTO DERMATÓLOGICO HUMBERTO BOGAERT UNIDAD BARAHONA" },
      { name: "HOSPITAL JAIME SANCHEZ" },
      { name: "HOSPITAL MINICIPAL DE POLO" },
      { name: "HOSPITAL MUNICIPAL DE CABRAL" },
      { name: "HOSPITAL MUNICIPAL DE ENRIQUILLO" },
      { name: "HOSPITAL MUNICIPAL DE PARAISO" },
      { name: "HOSPITAL MUNICIPAL DE SALINAS" },
      { name: "HOSPITAL MUNICIPAL DE VICENTE NOBLE" },
      { name: "HOSPITAL REGIONAL JAIME MOTA", },
      { name: "DIRECCIÓN PROVINCIAL DE SALUD BARAHONAL" },
      { name: "SERVICIO NACIONAL DE SALUD" }
    ],
  },
  {
    name: "Jimani",
    centers: [
      { name: "CPN Jimani Viejo" },
      { name: "CPN Jimani Pueblo" },
      { name: "CPN El Limon" },
      { name: "CPN Boca De Cachon" },
      { name: "CPN Tierra Nueva" }
    ],
  },
  {
    name: "Duverge",
    centers: [
      { name: "CPN Las Baitoas" },
      { name: "CPN Vengan a Ver" },
      { name: "CPN Puesto Escondido" },
      { name: "CPN San Jose" },
      { name: "CPN Las Mercedes" },
      { name: "CPN San Isidro" },
      { name: "CPN Placer Bonito" }
    ],
  },
  {
    name: "Mella",
    centers: [
      { name: "CPN Colonia Mixta" },
      { name: "CPN Mella " }
    ],
  },
  {
    name: "Angostura",
    centers: [
      { name: "CPN Angostura" }
    ],
  },
  {
    name: "Cristobal",
    centers: [
      { name: "CPN Cristobal" },
      { name: "CPN Batey -8" }
    ],
  },
  {
    name: "La Descubierta",
    centers: [
      { name: "CPN Bartolome" },
      { name: "CPN Los Pinos Del Eden" },
    ],
  },
  {
    name: "Postrer Rio",
    centers: [
      { name: "CPN Postrer Rio" },
      { name: "CPN El Guayabal" },
      { name: "CPN Los Bolos" }
    ],
  },
  {
    name: "SAN PEDRO",
    centers: [
      { name: "Club de Periodista" },
      { name: "Centro Comunal Barrio Lindo" },
      { name: "PARROQUIA NUESTRA SEÑORA DE LOS ANGELES" },
      { name: "PARROQUIA VIRGEN DEL CARMEN" },
      { name: "IGLESIA ENMANUEL SEGUNDA" },
      { name: "IGLESIA ENMANUEL TERCERA" },
      { name: "IGLESIA CIRCULO DE ORACION" },
      { name: "UCE" },
      { name: "CAPILLA SAGRADO CORAZON DE JESUS" },
      { name: "AYUNTAMIENTO MUNICIPAL" },
      { name: "GOBERNACION PROVINCIAL" },
      { name: "CLUB DE LEONES" },
      { name: "CENTRO COMERCIAL CUMAYASA" },
      { name: "UNAP PORVENIR" },
      { name: "CENTRO COMUNAL BATEY SOCO" },
      { name: "UNAP EL BRISAL" },
      { name: "UNAP EVANGELINA RODRIGUEZ" },
      { name: "UNAP JAGUAL" },
      { name: "UNAP CABEZA DE TORO" },
      { name: "UNAP HONDURAS" },
      { name: "UNAP DON JUAN" },
      { name: "UNAP DANDO  LA MANO AL POBRE" },
      { name: "IGLESIA ASAMBLEA DE DIOS" },
      { name: "UNAP" },
      { name: "IGLESIA DE DIOS" },
      { name: "LOS MONTONES" },
      { name: "MULTIUSO" },
    ],
  },
  {
    name: "Los Llanos",
    centers: [
      { name: "Club 26 de febrero" },
    ],
  },
  {
    name: "Quisqueya",
    centers: [
      { name: "Multiuso" },
    ],
  },
  {
    name: "Ramon Santana",
    centers: [
      { name: "Salon Ayuntaniento" },
    ],
  },
  {
    name: "Consuelo",
    centers: [
      { name: "Multiuso" },
    ],
  },
  {
    name: "Guayacanes",
    centers: [
      { name: "Iglesia de Dios" },
      { name: "Multiusu Honduras" },
      { name: "Iglesia Catolica" },
      { name: "Iglesia Asamblea De Dios" },
      { name: "Multiusu, Punta Pescadora" },
    ],
  },
  {
    name: "La Romana",
    centers: [
      { name: "Domiciliar DPS" },
      { name: "Policia Nacional" },
      { name: "Unap Isla Saona" },
      { name: "Centro de Diagnostico Caleta" },
      { name: "Unap Paulina Jimenez" },
      { name: "Fuerza Armada" },
      { name: "Gobernacion" },
      { name: "Hogar del Niño" },
      { name: "Unap Caleta" },
      { name: "Hospital Aristides Fiallo Cabral" },
      { name: "Hospital Francisco A. Gonzalvo" },
      { name: "Unap Tomas desir" },
      { name: "Dispensario Médico Dr. Luis J. Suarez" },
      { name: "Gerencia de Área" },
      { name: "Unap Los Bomberos" },
      { name: "Dispensario  Padre Cavaloto" },
      { name: "Centro Médico Dr. Rosario" },
      { name: "DPS -La Romana" },
      { name: "CESAC" },
      { name: "Multiuso Calasanz San Eduardo" },
      { name: "CEMER" },
      { name: "Colegio Medico Filial la Romana" },
      { name: "Centro Medico Oriental" },
      { name: "911 La Romana" },
      { name: "Iglesia Sanata Rosa de Lima" },
      { name: "Iglesia San Pablo" },
      { name: "Iglesia San Antonio de Padua" },
      { name: "Asamblea de Dios Camino de Vida" },
      { name: "Asamblea de Dios Casa Sobre la Roca" },
      { name: "Asamblea de Dios Emanuel Dios Con Nosotros" },
      { name: "Asamblea de Dios 5ta" },
      { name: "Asamblea de Dios Nueva Vida Central" },
      { name: "Asamblea de Dios la Rosa Salon Maranatha" },
      { name: "Centro Diagnostico Caleta" },
      { name: "Policlinica Duarte" },
    ],
  },
  {
    name: "Villa Hermosa",
    centers: [
      { name: "Policlinica Los Mulos" },
      { name: "Unap Km10 de Cumayasa" },
      { name: "Unap Villa Hermosa 4" },
      { name: "Unap Km14 de Cumayasa" },
      { name: "Villa  Hermosa 1-2" },
      { name: "Unap Cucama" },
      { name: "Km 10" },
    ],
  },
  {
    name: "Guaymte",
    centers: [
      { name: "Guaymate" },
    ],
  },
  {
    name: "HIGUEY",
    centers: [
      { name: "MULTIUSO #1" },
      { name: "POLIDEPORTIVO" },
      { name: "UNAP LA OTRA BANDA" },
      { name: "UNAP SAN FRANCISCO" },
      { name: "UNAP MAMÁ TINGÓ" },
      { name: "SERVICIO NACIONAL DE SALUD" },
      { name: "UNAP HATO DE MANA" },
      { name: "UNAP EL BONAO" },
    ],
  },
  {
    name: "SAN RAFAEL DEL YUMA",
    centers: [
      { name: "UNAP BAYAHIBE" },
      { name: "UNAP LOS NEGROS" },
    ],
  },
  {
    name: "Hato Mayor del Rey",
    centers: [
      { name: "Unap Guayabo Dulce" },
      { name: "Unap Jalonga" },
      { name: "Unap Los Hatillos" },
      { name: "Unap Villa Canto" },
      { name: "Unap Villa Ortega" },
      { name: "Unap La China" },
      { name: "Unap Villa Navarro" },
      { name: "Unap Ondina" },
      { name: "Unap Barrio Lindo" },
      { name: "Unap Gualey" },
      { name: "Unap La Javilla" },
      { name: "Unap Punta de Garza" },
      { name: "Unap Puerto Rico" },
      { name: "Unap Las Guamas" },
      { name: "Unap KM15" },
      { name: "Unap Yerba Buena" },
      { name: "Unap La Sierra" },
      { name: "Unap Morquecho" },
      { name: "Unap Pringamosa" },
      { name: "El mamón" },
    ],
  },
  {
    name: "Sabana de la Mar",
    centers: [
      { name: "Unap Magua" },
      { name: "Unap Las Yaguita" },
      { name: "Unap Las Cañitas" },
      { name: "Escuela Caño Hondo" },
    ],
  },
  {
    name: "El Valle",
    centers: [
      { name: "Hospital El Valle" },
    ],
  },
  {
    name: "EL SEIBO",
    centers: [
      { name: "DPS" },
      { name: "911" },
      { name: "COLEGIO EL ROSARIO" },
      { name: "CENTRO CAMPESINO" },
      { name: "CTC" },
      { name: "POLITECNICO FEZ Y ALEGRIA" },
      { name: "POLITECNICO SEGIO A BERA" },
      { name: "ESCUELA VILLA GUERRERO" },
      { name: "CASA CLUB GINANDIANA" },
      { name: "CENTRO COMUNAL V.G." },
      { name: "VICENTILLO" },
      { name: "CENTRO COM.VILA G." },
      { name: "PEDRO SANCHEZ" },
      { name: "LA HIGUERRA" },
      { name: "IGLESIA BEJAMIN" },
      { name: "EL CERCADO" },
      { name: "EL CUEY" },
      { name: "CLUB DOMINO" },
      { name: "CENTRO C.GINANDIAN" },
      { name: "CENTRO MEDICO DR. CHAIN" },
      { name: "BOCA DEL RIO" },
      { name: "CENTRO PARROQUIAL" },
      { name: "DISTRITO EDUCATIVO" },
      { name: "EL ASFALTO" },
      { name: "ESTANCIA DE ENVEGECIENTES" },
      { name: "LOS FRANCESES" },
    ],
  },
  {
    name: "MICHES",
    centers: [
      { name: "CTC" },
      { name: "EL ASFALTO" },
      { name: "BOCA DEL RIO" },
      { name: "LOS FRANCESES" },
      { name: "CENTRO PARROQUIAL" },
    ],
  },
  {
    name: "Pedernales",
    centers: [
      { name: "CPN 3-4" },
      { name: "CPN 5-6" },
      { name: "CPN 7-8" },
      { name: "UNAP 9" },
    ],
  },
  {
    name: "SABANA YEGUA",
    centers: [
      { name: "UNAP SABANA YEGUA" },
    ],
  },
  {
    name: "LAS YAYAS AZUA",
    centers: [
      { name: "CPN LAS YAYASS 1" },
      { name: "UNAP YAYAS ARRIBA" },
      { name: "CPN MAGUEYAL" },
      { name: "CPN VILLARPANDO" },
      { name: "UNAP HATO NUEVO " },
      { name: "VIAJAMA" },
    ],
  },
  {
    name: "PADRE LAS CASAS",
    centers: [
      { name: "CPN SANTA ANA PLC" },
      { name: "UNAP. LAS LAGUNAS" },
      { name: "LICEO JOSE FCO BOBADILLA" },
    ],
  },
  {
    name: "PUEBLO VIEJO",
    centers: [
      { name: "CPN PUEBLO VIEJO" },
    ],
  },
  {
    name: "PERALTA",
    centers: [
      { name: "LOS JOBOS 2" },
      { name: "UNAP CARRIZAL" },
    ],
  },
  {
    name: "GUAYUBIN",
    centers: [
      { name: "CLUB CULTURAL HATILLO PALMA" },
      { name: "UNAP VILLA ELISA" },
      { name: "UNAP EL PAPALLO" },
      { name: "GUAYUBIN POLIDEPORTIVO/ SUSTITUCION PARQUE" },
      { name: "CANA Chapetón AYUNTAMIENTO DISTRITAL" },
      { name: "VILLA ELISA AYUNTAMIENTO" },
      { name: "ORFANATO ENMANUEL" },
      { name: "UNAP CERRO GORDO" },
      { name: "UNAP HATO DEL MEDIO" },
      { name: "UNAP PILOTO" },
      { name: "CENTRO COMUNAL ARROYO CAÑA" },
      { name: "BRIGADA MOVIL ARROYO CAÑA" },
      { name: "BRIGADA MOVIL DOÑA ANTONIA" },
      { name: "BRIGADA MOVIL LA GUAJACA" },
      { name: "UNAP VILLA SINDA" },
      { name: "UNAP LOS DERRAMADEROS" },
      { name: "UNAP COPEY DE GUAYUBIN" },
      { name: "BRIGADA MOVIL COPEY DE GUAYUBIN" },
      { name: "BRIGADA MOVIL HATILLO PALMA" },
      { name: "BRIGADA MOVIL GUAYUBIN" },
      { name: "BRIGADA MOVIL GUAYUBINCITO" },
      { name: "UNAP MARTIN García" },
      { name: "CLUB EL POCITO" },
      { name: "UNAP EL POCITO" },
      { name: "PUESTO MOVIL VILLA LOBO ADENTRO" },
    ],
  },
  {
    name: "Cotui",
    centers: [
      { name: "AMK DENTAL" },
      { name: "AYUNTAMIENTO DE QUITA SUEÑO" },
      { name: "BAJO TECHO" },
      { name: "CPN CABALLERO" },
      { name: "CLUB DE AMAS DE CASA PEDRO FRANCISCO BONO" },
      { name: "CLUB DE BOXEO HICACO" },
      { name: "CPN COMEDERO ARRIBA" },
      { name: "CPN ALTAGRACIA DE COTUI" },
      { name: "CPN ATALAYA" },
      { name: "CPN BARRAQUITO" },
      { name: "CPN CASTILLO" },
      { name: "CPN CHACUEY" },
      { name: "CPN CLUB ROTARIO" },
      { name: "CPN DOS PALMAS" },
      { name: "CPN DUEY" },
      { name: "CPN EL LIMÓN" },
      { name: "CPN HOGAR DE ANCIANOS COTUI" },
      { name: "CPN LA ALTAGRACIA" },
      { name: "CPN LA CRUZ" },
      { name: "CPN LA ESTANCIA" },
      { name: "CPN LA PLACETA" },
      { name: "CPN LAS CAOBAS" },
      { name: "CPN LIBERTAD" },
      { name: "CPN LOS BARRAQUITOS" },
      { name: "CPN PEDRO FRANCISCO BONO" },
      { name: "CPN PLATANAL" },
      { name: "CPN PUEBLO NUEVO" },
      { name: "CPN QUITA SUEÑO" },
      { name: "CPN SABALLO" },
      { name: "CPN ZAMBRANA" },
      { name: "DIRECCION DE AREA DE SALUD" },
      { name: "DOMICILIARIO" },
      { name: "DPS SANCHEZ RAMIREZ" },
      { name: "ESCUELA LABORAL LA ESTANCIA" },
      { name: "GRAN ARENA" },
      { name: "IAD" },
      { name: "LA GRAN ARENA" },
      { name: "LABORATORIO REFERENCIA" },
      { name: "REHABILITACION" },
      { name: "SALON COMUNAL BARRIO LA CRUZ" },
      { name: "UASD INFOTEP PLAZA ARTESANAL" },
      { name: "UTECO" },
    ],
  },
  {
    name: "Fantino",
    centers: [
      { name: "BAJO TECHO" },
      { name: "CLUB 4 DE JULIO" },
      { name: "CPN ALTAGRACIA DE FANTINO" },
      { name: "CPN BARRIO LINDO" },
      { name: "CPN COMEDERO ABAJO" },
      { name: "CPN EL BAQUETAZO" },
      { name: "CPN EL LIMONCITO" },
      { name: "CPN LA ALTAGRACIA DE FANTINO" },
      { name: "CPN PIÑA VIEJA" },
      { name: "CPN SIERRA PRIETA" },
    ],
  },
  {
    name: "Cevicos",
    centers: [
      { name: "CPN ARENOSO" },
      { name: "CPN BATERO" },
      { name: "CPN LA CUEVA" },
      { name: "SALON PARROQUIAL DE CEVICOS" },
    ],
  },
  {
    name: "La Mata",
    centers: [
      { name: "CPN CRUZ DE ANGELINA" },
      { name: "CPN EL PESCOZON" },
      { name: "CPN HERNANDO ALONZO" },
      { name: "CPN LA BIJA" },
      { name: "CPN LA SOLEDAD " },
      { name: "CPN LAS CANAS" },
      { name: "CPN LOS CASTELLANOS" },
      { name: "CPN VILLA LA MATA" },
      { name: "LOS COROZOS" },
    ],
  },
  {
    name: "NAGUA",
    centers: [
      { name: "UASD VIEJA" },
      { name: "CPN. Matancita" },
      { name: "CPN LOS YAYALES" },
      { name: "CPN ARROYO AL MEDIO" },
      { name: "CPN EL YAYAL" },
      { name: "CPN EL GUAYABO" },
      { name: "CPN LAS CORCOBAS" },
      { name: "CPN LAS GORDAS" },
      { name: "CENTRO COMUNITARIO MATA BONITA" },
      { name: "UASD NUEVA" },
      { name: "POLIDEPORTIVO NAGUA" },
      { name: "PARROQUIA SANTISIMA TRINIDAD" },
      { name: "UAPA" },
      { name: "AYUNTAMIENTO DE NAGUA" },
    ],
  },
  {
    name: "EL Factor",
    centers: [
      { name: "CASA DE FORMACION SAGRADA FAMILIA" },
      { name: "CPN EL PAPAYO" },
      { name: "CPN LOS LIMONES" },
      { name: "CPN LA FACTORIA" },
      { name: "CPN LA PICHINGA" },
      { name: "AYUNTAMIENTO DEL POZO" },
    ],
  },
  {
    name: "RIO SAN JUAN",
    centers: [
      { name: "CPN COPEYITO" },
      { name: "CPN BEJUCO ALAMBRE" },
      { name: "CPN BOBITA" },
      { name: "POLIDEPORTIVO RIO SAN JUAN" },
    ],
  },
  {
    name: "CABRERA",
    centers: [
      { name: "CPN PAYITA" },
      { name: "CPN BAOBA DEL PIÑAL" },
      { name: "CPN SAN RAFAEL" },
      { name: "CPN LA CAPILLA" },
      { name: "CPN LA ENTRADA" },
      { name: "CPN LOMA ALTA" },
      { name: "CPN ABREU" },
    ],
  },
  {
    name: "LOS ALCARRIZOS",
    centers: [
      { name: "LICEO JUAN BOSCH DISTRITO 15-01" },
      { name: "PLAZA PRESIDENTE PEÑA GOMEZ" },
      { name: "IGLESIA NTRA. SRA. DE LA ALTAGRACIA," },
      { name: "IGLESIA JEREMIAS" },
      { name: "LOCAL JUNTA DE VECINOS BARRIO LA TORRE LEBRON" },
      { name: "MULTIUSO PALMAREJO" },
      { name: "CPN CRISTO OBRERO" },
    ],
  },
  {
    name: "PEDRO BRAND",
    centers: [
      { name: "CPN LA CUABA" },
      { name: "CANCHA ESCUELA FRANCISCO DEL ROSARIO SANCHEZ" },
      { name: "CPN LA GUAYIGA" },
      { name: "CPN EL PEDREGAL" },
    ],
  },
  {
    name: "Palenque",
    centers: [
      { name: "CPN JUAN BARON" },
    ],
  },
  {
    name: "Villa Altagracia",
    centers: [
      { name: "CPN LA CUCHILLA" },
      { name: "CPN EL CAOBAL" },
    ],
  },
  {
    name: "Cambita",
    centers: [
      { name: "CPN MAMA TINGO" },
    ],
  },
  {
    name: "NIGUA",
    centers: [
      { name: "CPN MIRA CIELO" },
      { name: "CPN LA CANELA" },
      { name: "CPN LOS BOTAOS" },
    ],
  },
  {
    name: "VILLA GONZALES",
    centers: [
      { name: "PARQUE VILLA GONZALES" },
    ],
  },
  {
    name: "NAVARRETE",
    centers: [
      { name: "CENTRO TECNOLOGICO COMUNITARIO" },
    ],
  },
  {
    name: "SAJOMA",
    centers: [
      { name: "CPN El Rubio" },
    ],
  },
  {
    name: "Puñal",
    centers: [
      { name: "Club Puñal" },
      { name: "CPN Guayabal" },
    ],
  },
  {
    name: "MOCA",
    centers: [
      { name: "CPN LAS FLORES" },
      { name: "CPN LA ISLETA" },
      { name: "CPN BOCA FERREA" },
      { name: "CPN ALGARROBO" },
      { name: "CPN LAS LAGUNAS" },
      { name: "CPN LA MANZANA" },
      { name: "CPN JUAN LOPEZ" },
      { name: "CPN LA GUAMA" },
      { name: "CPN GUAUCI" },
      { name: "CPN QUEBRADA HONDA" },
      { name: "CPN ZAFARRAYA" },
      { name: "CPN EL COROZO" },
      { name: "CPN NUEVO PUERTO RICO" },
      { name: "CPN LOS LÓPEZ" },
      { name: "CPN SANTA ROSA" },
      { name: "CPN LAS GUAZUMAS" },
      { name: "CPN TIERRA DURA" },
      { name: "CPN EL HIGUERITO" },
      { name: "CPN BONAGUA" },
      { name: "CPN MONTE DE LA JAGUA" },
      { name: "CPN ORTEGA" },
      { name: "CPN REPARADERO" },
      { name: "CDX CARLOS MARIA ROJAS BADIA" },
      { name: "CPN PALMA HERRADA" },
      { name: "CPN SAL SI PUEDES" },
      { name: "CPN LOS PANCHOS" },
      { name: "CPN BARRIO VIEJO PUERTO RICO" },
      { name: "CPN BARRIO MANUEL RODRIGUEZ" },
      { name: "CPN LA ERMITA" },
      { name: "CPN SAN FRANCISCO ARRIBA" },
      { name: "CPN CANCA LA REINA" },
      { name: "CPN CEIBA DE MADERA" },
      { name: "CPN SAN VICTOR" },
      { name: "CPN CUERO DURO" },
      { name: "CPN PUESTO GRANDE" },
      { name: "CPN VILLA CAFETALERA" },
      { name: "PUESTO FIJO DPS" },
      { name: "JOSE HORACIO RODRIGUEZ" },
      { name: "IGLESIA ADVENTISTA ROSA DE SARON" },
      { name: "POLIDEPORTIVO DE MOCA" },
      { name: "CANCHA MUNICIPAL" },
      { name: "SALON DE ACT. BARRIO VILLA ESTELA" },
      { name: "CLUB NARCISO BENCOSME JUAN LOPEZ" },
      { name: "CLUB AMA DE CASA SANTA TERESA DE JESUS" },
      { name: "CLUB UNION Y PROGRESO LAS LAGUNAS" },
      { name: "CLUB SAN SEBASTIAN" },
      { name: "LOGIA PERSEVERANCIA" },
    ],
  },
  {
    name: "GASPAR HERNANDEZ",
    centers: [
      { name: "CPN JOBA ARRIBA" },
      { name: "CPN LA YAGUA" },
      { name: "CPN VERAGUA" },
      { name: "CPN BATEY GINEBRA" },
      { name: "CLUB LIBERTAD GASPAR HDEZ" },
    ],
  },
  {
    name: "JAMAO AL NORTE",
    centers: [
      { name: "CPN LOS BRAZOS" },
    ],
  },
  {
    name: "CARRETERA MOCA-JAMAO",
    centers: [
      { name: "CPN EL CAIMITO" },
    ],
  },
  {
    name: "CAYETANO GERMOSEN",
    centers: [
      { name: "CLUB CASINO RENACIMIENTO" },
    ],
  },
  {
    name: "SAN JUAN DE LA MAGUANA",
    centers: [
      { name: "Salón De Conferencia De La DPS" },
      { name: "CASINO SAN JUAN" },
      { name: "CODIA" },
      { name: "POLIDEPORTIVO. LOS TRANSFORMADORES" },
      { name: "IGLESIA ESPIRITU SANTOS" },
      { name: "CENTRO TEGNOLOGICO" },
      { name: "ESCUELA ENRIQUILLO" },
      { name: "VILLA LIBERACION" },
      { name: "GUANITO" },
      { name: "CPN SABANA ALTA" },
      { name: "CPN LOS BANCOS" },
      { name: "CPN SABANETA" },
      { name: "CPN HATO NUEVO" },
      { name: "CPN LAS MAGUANA" },
      { name: "CPN EL ROSARIO" },
      { name: "CPN LA JAGUA" },
      { name: "LOS TRANSFORMADORES II" },
      { name: "CPN CARDON" },
      { name: "CPN LAS ZANJAS" },
      { name: "CPN EL CACHEO" },
      { name: "CPN EL BATEY" },
      { name: "CPN LAS CHARCAS DE GARABITO" },
      { name: "CPN MOGOLLON" },
      { name: "CPN PEDRO CORTO" },
    ],
  },
  {
    name: "LAS MATAS DE FARFAN",
    centers: [
      { name: "AYUNTAMIENTO. L.M.F" },
      { name: "ASC. AYUDA MUTUA. L.M.F" },
    ],
  },
  {
    name: "JUAN HERRERA",
    centers: [
      { name: "CPN JUAN HERRERA" },
      { name: "CPN JINOVA" },
    ],
  },
  {
    name: "VALLEJUELO",
    centers: [
      { name: "CPN VALLEJUELO" },
      { name: "CPN JORGILLO" },
      { name: "CPN CAPULIN" },
    ],
  },
  {
    name: "EL CERCADO",
    centers: [
      { name: "CPN BATISTA" },
      { name: "CPN EL JOBITO" },
      { name: "CPN DERRUMBADERO" },
      { name: "CPN LA NAVAJA" },
      { name: "CPN VALLECITO" },
      { name: "CPN LA COLONIA" },
    ],
  },
  {
    name: "BOHECHIO",
    centers: [
      { name: "CPN BOHECHIO" },
      { name: "CPN ARROYO CANO" },
      { name: "CPN BUENA VISTA DE YAQUE" },
      { name: "CPN LA GUAMA" },
    ],
  },
  {
    name: "Comendador",
    centers: [
      { name: "CPN Macasía" },
      { name: "CPN La Gallera" },
      { name: "CPN Sabana Larga" },
      { name: "CPN Rinconcito" },
      { name: "CPN Guayabo" },
      { name: "CPN Pinzon" },
      { name: "CPN Las Delicias" },
      { name: "CPN Potrozo" },
      { name: "CPN Hato Viejo" },
      { name: "Techado de Basket" },
      { name: "CTC" }
    ]
  },
  {
    name: "Banica",
    centers: [
      { name: "CPN Sabana Cruz" },
      { name: "CPN Higuierito" },
      { name: "Polideportivo" },
      { name: "CPN de Sabana Mula" }
    ]
  },
  {
    name: "Hondo Valle",
    centers: [
      { name: "CPN Rancho La Guardia" },
      { name: "Polideportivo de Hondo Valle" }
    ]
  },
  {
    name: "El llano",
    centers: [
      { name: "CPN el Llano" },
      { name: "CPN Guanito" },
      { name: "Polideportivo del Llano" },
      { name: "CPN Rosa La Piedra" }
    ]
  },
  {
    name: "Pedro Santana",
    centers: [
      { name: "CTC Pedro Santana" },
      { name: "CPN Las Palmas" },
      { name: "CPN Pedro Santana" }
    ]
  },
  {
    name: "Juan Santiago",
    centers: [
      { name: "CPN Juan Santiago" }
    ]
  },
  {
    name: "El Pino",
    centers: [
      { name: "Centro Comunal Manuel Bueno" },
      { name: "Centro Tecnologico" },
      { name: "Club Los Compos" },
      { name: "Club Nuevo Horizonte El Pino" },
      { name: "Unap El Pino" }
    ]
  },
  {
    name: "Loma de Cabrera",
    centers: [
      { name: "Casa de la Cultura" },
      { name: "Centro comunal Capotillo" },
      { name: "Centro Comunal El Cajuil" },
      { name: "Centro Comunal el Cruce" },
      { name: "Centro Comunal Hipolito Billini" },
      { name: "Centro comunal La Peñita" },
      { name: "Centro Comunal Santiago de la Cruz" },
      { name: "Centro de Madre Unidas para Luchar" },
      { name: "Iglesia Demofilo Cruz" },
      { name: "Poli Deportivo La Ceiba" }
    ]
  },
  {
    name: "Partido",
    centers: [
      { name: "ADEPA" },
      { name: "Centro Comunal de Aminilla" },
      { name: "Centro Comunal La Culata" },
      { name: "Centro Comunal Sangre Linda" },
      { name: "Centro Comunal Vaca Gorda" },
      { name: "Centro de Madre Los Indios" },
      { name: "Club El Coral" },
      { name: "Club Tabacuey" },
      { name: "El Multi Uso Partido" },
      { name: "Multi Uso de la Esuela Antonio Medina" }
    ]
  },
  {
    name: "Restauracion",
    centers: [
      { name: "Centro Comunal Las Rosas" },
      { name: "Centro Comunal Los Cerezos" },
      { name: "Centro Comunal Trinitaria" },
      { name: "Centro de Madre Mariano Cestero" },
      { name: "Centro de Madres Amantes del Progreso" },
      { name: "Centro Tecnologico Comunitario" },
      { name: "Club Fronterizo" }
    ]
  },
  {
    name: "Sabaneta",
    centers: [
      { name: "Ajesaro" },
      { name: "Polideportivo" },
      { name: "Cancha Germán Castro" },
      { name: "Dirección de Salud Santiago Rodríguez" }
    ]
  },
  {
    name: "Monción",
    centers: [
      { name: "Ayuntamiento Monción" },
      { name: "Ayuntamiento Sabaneta" }
    ]
  },
  {
    name: "Villa Los Almácigos",
    centers: [
      { name: "Ayuntamiento Almácigos" },
      { name: "Escuela Dr. Carlos González" }
    ]
  },
  {
    name: "Yamasá",
    centers: [
      { name: "Hospital Municipal de Yamasa" },
      { name: "Centro Medico Concepcion y Diaz" }
    ]
  },
  {
    name: "Sabana Grande de Boya",
    centers: [
      { name: "Hospita Dr. Pedro Heredia Rojas, Sabana Grande de Boya" },
      { name: "Multiusos Sabana Grande de Boya (de 68 años o más)" }
    ]
  },
  {
    name: "Bayaguana",
    centers: [
      { name: "Hospital Santo Cristo de los Milagros" },
    ]
  },
  {
    name: "Peralvillo",
    centers: [
      { name: "Centro medico Humbeto Garcia" },
    ]
  }
].sort((a, b) => (a.name < b.name ? -1 : 1));
